import { parseOwnedActivationAggregate, type OwnedActivationAggregate } from "../../../investigation/continuity/OwnedInvestigationContinuity.ts";

export interface AdmitManifoldArtifactRequest { readonly projectionId:string; readonly expectedOperationalHeadId:string|null; readonly selectedRelationshipDeclarationIds:readonly string[]; readonly idempotencyKey:string }
export interface AdmissionEffects { readonly canon:"NONE"; readonly manifold:"REVISION_APPENDED"; readonly rex:"NONE"; readonly tavily:"NONE"; readonly webDiscovery:"NONE"; readonly candidateEvidence:"NONE"; readonly researchInbox:"NONE"; readonly confidence:"NONE"; readonly billing:"NONE" }
export interface ManifoldArtifactAdmissionReceipt { readonly receiptId:string; readonly investigationId:string; readonly projectionId:string; readonly verifiedOutputHash:string; readonly admittedArtifactNodeId:string; readonly selectedRelationshipDeclarationIds:readonly string[]; readonly createdRelationshipIds:readonly string[]; readonly previousOperationalRevisionId:string|null; readonly resultingOperationalRevisionId:string; readonly admittedAt:string; readonly effects:AdmissionEffects }
export interface AdmitManifoldArtifactResponse { readonly receipt:ManifoldArtifactAdmissionReceipt; readonly replayed:boolean; readonly authoritativeCurrentHead:string; readonly activation:OwnedActivationAggregate }
export class ManifoldArtifactAdmissionError extends Error { readonly code:string;readonly staleHead:boolean;constructor(code:string,message:string,staleHead=false){super(message);this.name="ManifoldArtifactAdmissionError";this.code=code;this.staleHead=staleHead} }

const record=(value:unknown,path:string):Record<string,unknown>=>{if(value===null||typeof value!=="object"||Array.isArray(value))throw new Error(path);return value as Record<string,unknown>};
const exact=(value:Record<string,unknown>,keys:readonly string[],path:string)=>{if(Object.keys(value).length!==keys.length||Object.keys(value).some(key=>!keys.includes(key)))throw new Error(path)};
const id=(value:unknown,path:string)=>{if(typeof value!=="string"||!value.trim()||value!==value.trim()||value.length>300)throw new Error(path);return value};
const hash=(value:unknown,path:string)=>{const result=id(value,path);if(!/^sha256:[0-9a-f]{64}$/.test(result))throw new Error(path);return result};
const ids=(value:unknown,path:string)=>{if(!Array.isArray(value))throw new Error(path);const result=value.map((item,index)=>id(item,`${path}.${index}`));if(new Set(result).size!==result.length)throw new Error(path);return Object.freeze(result)};
function decode(raw:unknown,investigationId:string,request:AdmitManifoldArtifactRequest):AdmitManifoldArtifactResponse{
 const root=record(raw,"admission");exact(root,["receipt","replayed","authoritativeCurrentHead","activation"],"admission");if(typeof root.replayed!=="boolean")throw new Error("admission.replayed");
 const receipt=record(root.receipt,"receipt");exact(receipt,["receiptId","investigationId","projectionId","verifiedOutputHash","admittedArtifactNodeId","selectedRelationshipDeclarationIds","createdRelationshipIds","previousOperationalRevisionId","resultingOperationalRevisionId","admittedAt","effects"],"receipt");
 const effects=record(receipt.effects,"effects");exact(effects,["canon","manifold","rex","tavily","webDiscovery","candidateEvidence","researchInbox","confidence","billing"],"effects");if(effects.canon!=="NONE"||effects.manifold!=="REVISION_APPENDED"||effects.rex!=="NONE"||effects.tavily!=="NONE"||effects.webDiscovery!=="NONE"||effects.candidateEvidence!=="NONE"||effects.researchInbox!=="NONE"||effects.confidence!=="NONE"||effects.billing!=="NONE")throw new Error("effects");
 const selected=ids(receipt.selectedRelationshipDeclarationIds,"selected");const created=ids(receipt.createdRelationshipIds,"created");const result=id(receipt.resultingOperationalRevisionId,"resultingRevision");const head=id(root.authoritativeCurrentHead,"head");const activation=parseOwnedActivationAggregate(root.activation,investigationId);
 if(receipt.investigationId!==investigationId||receipt.projectionId!==request.projectionId||selected.length!==request.selectedRelationshipDeclarationIds.length||selected.some((item,index)=>item!==[...request.selectedRelationshipDeclarationIds].sort()[index])||created.length!==selected.length||result!==head||activation.operationalRevisionHead?.revisionId!==head||receipt.previousOperationalRevisionId!==request.expectedOperationalHeadId)throw new Error("admission identity mismatch");
 if(!(receipt.previousOperationalRevisionId===null||typeof receipt.previousOperationalRevisionId==="string")||typeof receipt.admittedAt!=="string"||!Number.isFinite(Date.parse(receipt.admittedAt)))throw new Error("receipt lineage");
 return Object.freeze({receipt:Object.freeze({receiptId:id(receipt.receiptId,"receiptId"),investigationId,projectionId:request.projectionId,verifiedOutputHash:hash(receipt.verifiedOutputHash,"verifiedOutputHash"),admittedArtifactNodeId:id(receipt.admittedArtifactNodeId,"nodeId"),selectedRelationshipDeclarationIds:selected,createdRelationshipIds:created,previousOperationalRevisionId:receipt.previousOperationalRevisionId as string|null,resultingOperationalRevisionId:result,admittedAt:receipt.admittedAt,effects:effects as unknown as AdmissionEffects}),replayed:root.replayed,authoritativeCurrentHead:head,activation});
}
function csrf(){const match=document.cookie.split(";").map(x=>x.trim()).find(x=>x.startsWith("isees_csrf="));return match?decodeURIComponent(match.slice("isees_csrf=".length)):undefined}
export function createManifoldArtifactAdmissionClient(options:{baseUrl?:string;fetch?:typeof fetch}={}){const transport=options.fetch??fetch,base=(options.baseUrl??"").replace(/\/$/,"");return Object.freeze({async admit(investigationId:string,request:AdmitManifoldArtifactRequest,signal?:AbortSignal){const token=csrf();if(!token)throw new ManifoldArtifactAdmissionError("AUTHENTICATION_REQUIRED","A secure authenticated account session is required.");let response:Response;try{response=await transport(`${base}/api/v1/investigations/${encodeURIComponent(investigationId)}/manifold-artifact-admissions`,{method:"POST",credentials:"include",redirect:"error",signal,headers:{"Content-Type":"application/json","X-ISEES-CSRF":token},body:JSON.stringify(request)})}catch{throw new ManifoldArtifactAdmissionError("NETWORK_FAILURE","Admission could not reach the investigation authority.")}const body:unknown=await response.json().catch(()=>null);if(!response.ok){const error=(body as {error?:{code?:unknown;message?:unknown}})?.error;const code=typeof error?.code==="string"?error.code:"ADMISSION_FAILED";throw new ManifoldArtifactAdmissionError(code,code.includes("REVISION")||response.status===409?"The investigation changed. Refresh and review before confirming again.":typeof error?.message==="string"?error.message:"Admission failed safely.",code.includes("REVISION")||response.status===409)}try{return decode(body,investigationId,request)}catch{throw new ManifoldArtifactAdmissionError("MALFORMED_RESPONSE","The admission response failed strict authority validation.")}}})}
export type ManifoldArtifactAdmissionClient=ReturnType<typeof createManifoldArtifactAdmissionClient>;
