import { PROJECTION_FORMATS, PROJECTION_STATES, type AuthorRevision } from "../../contracts/StudioV1Contract.ts";
import { validateAuthorRevision, validateSnapshot } from "../../contracts/StudioCanonicalSerialization.ts";
import type { FrozenResearchSourceSnapshot } from "../../contracts/StudioV1Contract.ts";
import type { ArtifactDiscoveryList, ArtifactHead, ProjectionStatusList, RevisionDetail, RevisionList, SaveResult } from "./StudioV1AuthorApiTypes.ts";

const object = (value: unknown, path: string): Record<string, unknown> => { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error(path); return value as Record<string, unknown>; };
const exact = (value: Record<string, unknown>, keys: readonly string[], path: string) => { if (Object.keys(value).length !== keys.length || Object.keys(value).some(key => !keys.includes(key))) throw new Error(path); };
const id = (value: unknown, path: string): string => { if (typeof value !== "string" || !value.trim() || value.length > 300 || Array.from(value).some(char => char.charCodeAt(0) < 32)) throw new Error(path); return value; };
const integer = (value: unknown, path: string) => { if (!Number.isSafeInteger(value) || Number(value) < 1) throw new Error(path); return Number(value); };
const hash = (value: unknown, path: string) => { if (typeof value !== "string" || !/^sha256:[0-9a-f]{64}$/.test(value)) throw new Error(path); return value; };
const timestamp = (value: unknown, path: string) => { if (typeof value !== "string" || !/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(value) || Number.isNaN(Date.parse(value))) throw new Error(path); return value; };
const nullable = <T>(value: unknown, decode: (v: unknown, p: string) => T, path: string): T | null => value === null ? null : decode(value, path);
const array = (value: unknown, path: string) => { if (!Array.isArray(value)) throw new Error(path); return value; };
const freeze = <T>(value: T): T => Object.freeze(value);

export function decodeSaveResult(raw: unknown): SaveResult { const x=object(raw,"save"); exact(x,["artifactId","revisionId","revisionNumber","projectionIds","replayed"],"save"); if(typeof x.replayed!=="boolean")throw new Error("save.replayed"); return freeze({artifactId:id(x.artifactId,"save.artifactId"),revisionId:id(x.revisionId,"save.revisionId"),revisionNumber:integer(x.revisionNumber,"save.revisionNumber"),projectionIds:freeze(array(x.projectionIds,"save.projectionIds").map((v,i)=>id(v,`save.projectionIds.${i}`))),replayed:x.replayed}); }
export function decodeArtifactHead(raw: unknown): ArtifactHead { const x=object(raw,"artifact"); exact(x,["artifactId","currentRevisionId","currentRevisionNumber","contentHash","savedAt"],"artifact"); const allNull=x.currentRevisionId===null&&x.currentRevisionNumber===null&&x.contentHash===null&&x.savedAt===null; const allSet=x.currentRevisionId!==null&&x.currentRevisionNumber!==null&&x.contentHash!==null&&x.savedAt!==null; if(!allNull&&!allSet)throw new Error("artifact.head"); return freeze({artifactId:id(x.artifactId,"artifact.artifactId"),currentRevisionId:nullable(x.currentRevisionId,id,"artifact.currentRevisionId"),currentRevisionNumber:nullable(x.currentRevisionNumber,integer,"artifact.currentRevisionNumber"),contentHash:nullable(x.contentHash,hash,"artifact.contentHash"),savedAt:nullable(x.savedAt,timestamp,"artifact.savedAt")}); }
export function decodeArtifactDiscovery(raw:unknown):ArtifactDiscoveryList{const root=object(raw,"discovery");exact(root,["items"],"discovery");const items=array(root.items,"discovery.items").map((rawItem,index)=>{const path=`discovery.items.${index}`,x=object(rawItem,path);exact(x,["artifactId","investigationId","ownerPrincipalId","profile","lifecycleClassification","createdAt","currentRevisionId","currentRevisionNumber","contentHash","savedAt"],path);const allNull=x.currentRevisionId===null&&x.currentRevisionNumber===null&&x.contentHash===null&&x.savedAt===null,allSet=x.currentRevisionId!==null&&x.currentRevisionNumber!==null&&x.contentHash!==null&&x.savedAt!==null;if(!allNull&&!allSet)throw new Error(`${path}.head`);return freeze({artifactId:id(x.artifactId,`${path}.artifactId`),investigationId:id(x.investigationId,`${path}.investigationId`),ownerPrincipalId:id(x.ownerPrincipalId,`${path}.ownerPrincipalId`),profile:id(x.profile,`${path}.profile`),lifecycleClassification:id(x.lifecycleClassification,`${path}.lifecycleClassification`),createdAt:timestamp(x.createdAt,`${path}.createdAt`),currentRevisionId:nullable(x.currentRevisionId,id,`${path}.currentRevisionId`),currentRevisionNumber:nullable(x.currentRevisionNumber,integer,`${path}.currentRevisionNumber`),contentHash:nullable(x.contentHash,hash,`${path}.contentHash`),savedAt:nullable(x.savedAt,timestamp,`${path}.savedAt`)})});return freeze({items:freeze(items)});}
const metadata=(raw:unknown,path:string)=>{const x=object(raw,path);exact(x,["revisionId","revisionNumber","parentRevisionId","contentHash","savedAt","sourceSnapshots"],path);const refs=array(x.sourceSnapshots,`${path}.sourceSnapshots`).map((v,i)=>{const r=object(v,`${path}.sourceSnapshots.${i}`);exact(r,["snapshotId","snapshotHash"],`${path}.sourceSnapshots.${i}`);return freeze({snapshotId:id(r.snapshotId,"snapshotId"),snapshotHash:hash(r.snapshotHash,"snapshotHash")})});return freeze({revisionId:id(x.revisionId,"revisionId"),revisionNumber:integer(x.revisionNumber,"revisionNumber"),parentRevisionId:nullable(x.parentRevisionId,id,"parentRevisionId"),contentHash:hash(x.contentHash,"contentHash"),savedAt:timestamp(x.savedAt,"savedAt"),sourceSnapshots:freeze(refs)});};
export function decodeRevisionList(raw:unknown):RevisionList{const x=object(raw,"revisions");exact(x,["artifactId","items"],"revisions");return freeze({artifactId:id(x.artifactId,"revisions.artifactId"),items:freeze(array(x.items,"revisions.items").map((v,i)=>metadata(v,`revisions.items.${i}`)))});}
export function decodeRevisionDetail(raw:unknown):RevisionDetail{const x=object(raw,"revisionDetail");exact(x,["artifactId","revision"],"revisionDetail");const wire=object(x.revision,"revisionDetail.revision");const normalized=wire.parentRevisionId===null?Object.fromEntries(Object.entries(wire).filter(([key])=>key!=="parentRevisionId")):wire;validateAuthorRevision(normalized);return freeze({artifactId:id(x.artifactId,"revisionDetail.artifactId"),revision:freeze(normalized as unknown as AuthorRevision)});}
export function decodeSourceSnapshot(raw:unknown):FrozenResearchSourceSnapshot{validateSnapshot(raw);return freeze(raw);}
export function decodeProjectionStatuses(raw:unknown):ProjectionStatusList{const x=object(raw,"projections");exact(x,["artifactId","revisionId","items"],"projections");const items=array(x.items,"projections.items").map((v,i)=>{const p=object(v,`projections.items.${i}`);exact(p,["projectionId","format","parentRevisionId","state","failureCategory","outputHash"],`projections.items.${i}`);if(!PROJECTION_FORMATS.includes(p.format as never)||!PROJECTION_STATES.includes(p.state as never))throw new Error("projection enum");return freeze({projectionId:id(p.projectionId,"projectionId"),format:p.format as typeof PROJECTION_FORMATS[number],parentRevisionId:id(p.parentRevisionId,"parentRevisionId"),state:p.state as typeof PROJECTION_STATES[number],failureCategory:nullable(p.failureCategory,id,"failureCategory"),outputHash:nullable(p.outputHash,hash,"outputHash")});});return freeze({artifactId:id(x.artifactId,"artifactId"),revisionId:id(x.revisionId,"revisionId"),items:freeze(items)});}
export function decodeSafeError(raw:unknown):{code:string;message:string}{const root=object(raw,"errorEnvelope");exact(root,["error"],"errorEnvelope");const error=object(root.error,"error");const keys=error.requestId===undefined?["code","message"]:["code","message","requestId"];exact(error,keys,"error");if(error.requestId!==undefined)id(error.requestId,"requestId");return {code:id(error.code,"code"),message:id(error.message,"message")};}
