import { resolveApiBaseUrl } from "../../../api/ApiOrigin.ts";
import { canonicalSerialize, canonicalSha256, validateAuthorRevision, validateSnapshot } from "../../contracts/StudioCanonicalSerialization.ts";
import { PROJECTION_FORMATS } from "../../contracts/StudioV1Contract.ts";
import { decodeArtifactDiscovery, decodeArtifactHead, decodeProjectionStatuses, decodeRevisionDetail, decodeRevisionList, decodeSafeError, decodeSaveResult } from "./StudioV1AuthorDecoders.ts";
import { StudioV1AuthorClientError, type SaveAuthorRequest, type StudioV1AuthorOperation } from "./StudioV1AuthorApiTypes.ts";
import type { ArtifactDiscoveryList, ArtifactHead, ProjectionStatusList, RevisionDetail, RevisionList, SaveResult, StudioV1AuthorErrorCode } from "./StudioV1AuthorApiTypes.ts";

export interface StudioV1AuthorClientOptions { readonly baseUrl?: string; readonly resolveBaseUrl?: () => string; readonly fetch?: typeof fetch; readonly readCsrfToken?: () => string | undefined }
export interface StudioV1AuthorApiClient {
 createArtifact(i:string,r:SaveAuthorRequest,s?:AbortSignal):Promise<SaveResult>; saveRevision(i:string,a:string,r:SaveAuthorRequest,s?:AbortSignal):Promise<SaveResult>;
 discoverArtifacts?(i:string,s?:AbortSignal):Promise<ArtifactDiscoveryList>;
 getArtifact(i:string,a:string,s?:AbortSignal):Promise<ArtifactHead>; listRevisions(i:string,a:string,s?:AbortSignal):Promise<RevisionList>;
 getRevision(i:string,a:string,r:string,s?:AbortSignal):Promise<RevisionDetail>; listProjectionStatuses(i:string,a:string,r:string,s?:AbortSignal):Promise<ProjectionStatusList>;
}
const MAX=65_536;
const browserCsrf=()=>{if(typeof document==="undefined")return undefined;const p=document.cookie.split(";").map(x=>x.trim()).find(x=>x.startsWith("isees_csrf="));if(!p)return undefined;try{return decodeURIComponent(p.slice(11))||undefined}catch{return undefined}};
const segment=(v:string,n:string,o:StudioV1AuthorOperation)=>{if(typeof v!=="string"||!v.trim()||v!==v.trim()||v.length>300||/[\\/]|\.\./.test(v))throw new StudioV1AuthorClientError("CONTRACT_INVALID",`${n} is invalid.`,o);return encodeURIComponent(v)};
const safe=(v:string)=>v.replace(/[\r\n\t]+/g," ").replace(/[<>]/g,"").slice(0,240)||"The Studio V1 request failed.";
const mapped=(c:string,s:number):StudioV1AuthorErrorCode=>({UNAUTHENTICATED:"UNAUTHENTICATED",CSRF_REJECTED:"CSRF_REJECTED",INVESTIGATION_NOT_FOUND:"INVESTIGATION_NOT_FOUND",STUDIO_V1_ARTIFACT_NOT_FOUND:"ARTIFACT_NOT_FOUND",STUDIO_V1_REVISION_NOT_FOUND:"REVISION_NOT_FOUND",STUDIO_V1_UNAVAILABLE:"STUDIO_V1_UNAVAILABLE",INVALID_STUDIO_V1_CONTRACT:"CONTRACT_INVALID",EXPECTED_HEAD_REQUIRED:"CONTRACT_INVALID",ROUTE_PAYLOAD_MISMATCH:"ROUTE_PAYLOAD_MISMATCH",STUDIO_V1_HASH_MISMATCH:"HASH_MISMATCH",STUDIO_V1_CONTENT_HASH_MISMATCH:"HASH_MISMATCH",STUDIO_V1_SNAPSHOT_HASH_MISMATCH:"HASH_MISMATCH",STUDIO_V1_REVISION_CONFLICT:"EXPECTED_HEAD_CONFLICT",IDEMPOTENCY_KEY_REUSE:"IDEMPOTENCY_KEY_REUSE",STUDIO_V1_PERSISTENCE_UNAVAILABLE:"PERSISTENCE_UNAVAILABLE",STUDIO_V1_INTERNAL_FAILURE:"SAFE_INTERNAL_FAILURE"}[c] as StudioV1AuthorErrorCode|undefined)??(s>=500?"SAFE_INTERNAL_FAILURE":"CONTRACT_INVALID");
async function json(r:Response){const declared=Number(r.headers.get("content-length"));if(Number.isFinite(declared)&&declared>MAX)throw 0;const reader=r.body?.getReader();if(!reader){const t=await r.text();if(t.length>MAX)throw 0;return JSON.parse(t)}const chunks:Uint8Array[]=[];let n=0;for(;;){const {done,value}=await reader.read();if(done)break;if(value){n+=value.length;if(n>MAX){await reader.cancel();throw 0}chunks.push(value)}}const bytes=new Uint8Array(n);let at=0;for(const c of chunks){bytes.set(c,at);at+=c.length}return JSON.parse(new TextDecoder("utf-8",{fatal:true}).decode(bytes))}
function body(r:SaveAuthorRequest,i:string,a:string|undefined,o:StudioV1AuthorOperation){try{if(r.artifact.investigationId!==i||(a!==undefined&&r.artifact.artifactId!==a)||r.revision.artifactId!==r.artifact.artifactId)throw new StudioV1AuthorClientError("ROUTE_PAYLOAD_MISMATCH","Request identity does not match the route.",o);if(!r.idempotencyKey||r.idempotencyKey.length>200)throw 0;validateAuthorRevision({...r.revision,authorPrincipalId:"transport-authenticated-principal"});if((r.revision.revisionNumber===1)!==(r.expectedHeadRevisionId===undefined)||r.artifact.currentSavedRevisionId!==r.expectedHeadRevisionId||r.artifact.workingDraft.basedOnRevisionId!==r.expectedHeadRevisionId)throw 0;if(r.revision.contentHash!==canonicalSha256(r.revision.semanticContent))throw new StudioV1AuthorClientError("HASH_MISMATCH","The content hash is invalid.",o);r.snapshots.forEach(x=>{validateSnapshot(x);if(x.investigationId!==i)throw new StudioV1AuthorClientError("ROUTE_PAYLOAD_MISMATCH","Request identity does not match the route.",o)});r.projections.forEach(x=>{if(!PROJECTION_FORMATS.includes(x.format)||!/^sha256:[0-9a-f]{64}$/.test(x.configurationHash))throw 0});return canonicalSerialize(r)}catch(e){if(e instanceof StudioV1AuthorClientError)throw e;throw new StudioV1AuthorClientError("CONTRACT_INVALID","The Studio V1 request contract is invalid.",o)}}
export function createStudioV1AuthorApiClient(options:StudioV1AuthorClientOptions={}):StudioV1AuthorApiClient{
 const fetcher=options.fetch??((input,init)=>fetch(input,init)),base=resolveApiBaseUrl(options.baseUrl??options.resolveBaseUrl?.()),csrf=options.readCsrfToken??browserCsrf;
 const call=async<T>(o:StudioV1AuthorOperation,p:string,d:(x:unknown)=>T,init:RequestInit):Promise<T>=>{let r:Response;try{r=await fetcher(`${base}${p}`,{...init,credentials:"include",redirect:"error"})}catch(e){if(init.signal?.aborted||(e instanceof DOMException&&e.name==="AbortError"))throw new StudioV1AuthorClientError("ABORTED","The Studio V1 request was cancelled.",o);throw new StudioV1AuthorClientError("NETWORK_FAILURE","The Studio V1 service could not be reached.",o,{retryable:init.method==="GET"})}let x:unknown;try{x=await json(r)}catch{throw new StudioV1AuthorClientError("MALFORMED_RESPONSE","The Studio V1 service returned an invalid response.",o,{status:r.status,retryable:init.method==="GET"&&r.status>=500})}if(!r.ok){try{const e=decodeSafeError(x),code=mapped(e.code,r.status);throw new StudioV1AuthorClientError(code,safe(e.message),o,{status:r.status,retryable:init.method==="GET"&&r.status>=500,conflict:code==="EXPECTED_HEAD_CONFLICT"||code==="IDEMPOTENCY_KEY_REUSE"})}catch(e){if(e instanceof StudioV1AuthorClientError)throw e;throw new StudioV1AuthorClientError("SAFE_INTERNAL_FAILURE","The Studio V1 request failed.",o,{status:r.status,retryable:init.method==="GET"&&r.status>=500})}}try{return d(x)}catch(e){const decodeFailure=o==="discoverArtifacts"?"DISCOVERY_DECODE_FAILED":o==="getRevision"?(e instanceof Error&&e.message==="contentHash mismatch"?"CONTENT_HASH_MISMATCH":"REVISION_DECODE_FAILED"):undefined;throw new StudioV1AuthorClientError("MALFORMED_RESPONSE","The Studio V1 service returned an invalid response.",o,{status:r.status,decodeFailure})}};
 const prefix=(i:string,o:StudioV1AuthorOperation)=>`/api/v1/investigations/${segment(i,"investigationId",o)}/studio-v1/artifacts`;
 const mutate=(o:"createArtifact"|"saveRevision",p:string,r:SaveAuthorRequest,i:string,a?:string,s?:AbortSignal)=>{const token=csrf();if(!token)throw new StudioV1AuthorClientError("CSRF_REJECTED","The secure session could not be verified.",o,{status:403});return call(o,p,decodeSaveResult,{method:"POST",headers:{"Content-Type":"application/json","X-ISEES-CSRF":token},body:body(r,i,a,o),signal:s})};
 const client:StudioV1AuthorApiClient={createArtifact:(i,r,s)=>mutate("createArtifact",prefix(i,"createArtifact"),r,i,undefined,s),saveRevision:(i,a,r,s)=>mutate("saveRevision",`${prefix(i,"saveRevision")}/${segment(a,"artifactId","saveRevision")}/revisions`,r,i,a,s),discoverArtifacts:(i,s)=>call("discoverArtifacts",prefix(i,"discoverArtifacts"),decodeArtifactDiscovery,{method:"GET",signal:s}),getArtifact:(i,a,s)=>call("getArtifact",`${prefix(i,"getArtifact")}/${segment(a,"artifactId","getArtifact")}`,decodeArtifactHead,{method:"GET",signal:s}),listRevisions:(i,a,s)=>call("listRevisions",`${prefix(i,"listRevisions")}/${segment(a,"artifactId","listRevisions")}/revisions`,decodeRevisionList,{method:"GET",signal:s}),getRevision:(i,a,r,s)=>call("getRevision",`${prefix(i,"getRevision")}/${segment(a,"artifactId","getRevision")}/revisions/${segment(r,"revisionId","getRevision")}`,decodeRevisionDetail,{method:"GET",signal:s}),listProjectionStatuses:(i,a,r,s)=>call("listProjectionStatuses",`${prefix(i,"listProjectionStatuses")}/${segment(a,"artifactId","listProjectionStatuses")}/revisions/${segment(r,"revisionId","listProjectionStatuses")}/projections`,decodeProjectionStatuses,{method:"GET",signal:s})};return Object.freeze(client);
}
