import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const read = (path: string): Promise<string> => readFile(resolve(root, path), "utf8");
const [manifestText, html, popup, extraction, consent, readme] = await Promise.all([read("manifest.json"), read("popup.html"), read("src/popup.ts"), read("src/extraction.ts"), read("src/consent.ts"), read("README.md")]);
const manifest = JSON.parse(manifestText) as Record<string, unknown>;
assert.equal(manifest.manifest_version, 3);
assert.equal(manifest.name, "iSEES Capture");
assert.deepEqual(manifest.permissions, ["activeTab", "scripting", "downloads", "storage"]);
assert.equal("host_permissions" in manifest, false);
const csp = (manifest.content_security_policy as { extension_pages: string }).extension_pages;
assert.match(csp, /script-src 'self'/); assert.match(csp, /connect-src 'none'/); assert.doesNotMatch(csp, /https?:|unsafe-eval|unsafe-inline/);
assert.match(html, /iSEES Capture/); assert.match(html, /External Source Capture/); assert.match(html, /creates a source package for later inspection and import into iSEES/);
assert.match(html, /id="agreement-check" type="checkbox"/); assert.match(html, /id="agree-button"[^>]*disabled/); assert.match(html, /Agree and enable iSEES Capture/);
assert.match(html, /Withdraw agreement/); assert.match(html, /id="capture-check" type="checkbox"/); assert.match(html, /Create iSEES Source Capsule/);
assert.match(html, /aria-live="polite"/); assert.match(html, /for="rights"/); assert.match(html, /for="privacy"/); assert.match(html, /for="researcher-note"/);
assert.match(consent, /version: AGREEMENT_VERSION, agreedAt:/); assert.match(consent, /Object\.keys\(record\)\.length === 2/); assert.match(consent, /storage\.local\.remove/);
assert.ok(popup.indexOf("readAgreement()") < popup.indexOf("chrome.tabs.query"), "agreement gate precedes tab access");
assert.ok(popup.indexOf('addEventListener("click"') < popup.indexOf("chrome.scripting.executeScript"), "inspection is click-triggered");
assert.ok(popup.indexOf('addEventListener("submit"') < popup.indexOf('uuid("capsule")'), "confirmed submit path owns identity generation");
assert.ok(popup.indexOf("extractActiveSelection") < popup.indexOf("exportSourceCapsule(frozenAttempt)"), "preview precedes exporter");
assert.match(popup, /import \{ exportSourceCapsule \}/); assert.doesNotMatch(popup, /createSourceCapsuleV1|capsuleHashBasis/);
assert.match(popup, /const exportedBytes = artifact\.utf8Bytes\(\)/); assert.match(popup, /new Blob\(\[exactBuffer\]/); assert.match(popup, /filename: artifact\.filename/); assert.match(popup, /conflictAction: "uniquify"/); assert.match(popup, /finally \{ URL\.revokeObjectURL/);
assert.match(popup, /has not been imported into iSEES/); assert.doesNotMatch(popup + extraction + consent, /fetch\(|XMLHttpRequest|WebSocket|sendBeacon|localStorage|sessionStorage|document\.cookie|chrome\.history/);
assert.match(extraction, /getSelection\(\)/); assert.match(extraction, /selection\?\.toString\(\)/); assert.match(extraction, /EMPTY_SELECTION/); assert.doesNotMatch(extraction, /outerHTML|innerHTML|querySelectorAll|querySelector[^\n]*(?:input|form|password)|\.value\b/);
assert.ok(extraction.indexOf('meta[property="og:site_name"]') < extraction.indexOf('meta[name="application-name"]'));
assert.ok(extraction.indexOf('meta[name="author"]') < extraction.indexOf('meta[property="article:author"]'));
assert.ok(extraction.indexOf('meta[property="article:published_time"]') < extraction.indexOf('meta[itemprop="datePublished"]'));
assert.match(popup, /researcherNotes: note \?/); assert.doesNotMatch(consent, /exactText|passage|pageTitle|finalUrl|researcher|email|name/);
assert.match(readme, /Browser acceptance|browser acceptance/i); assert.match(readme, /screenshots, full-page capture/);
for (const forbidden of ["ResearchInbox", "CandidateKnowledge", "SystemCanon", "/api/", "http://", "https://"]) assert.equal(popup.includes(forbidden), false, `forbidden authority/network token: ${forbidden}`);
console.log("VerifyIseesCaptureExtension: PASS (32 extension shell controls verified)");
