import { ARTIFACT_PROFILES, ASSISTANCE_MODES, CITATION_STYLES, GOVERNED_CONCLUSIONS, PROJECTION_FORMATS, PROJECTION_STATES, SEMANTIC_NODE_TYPES, type AiDraftProposal, type AuthorRevision, type ChildProjection, type FrozenResearchSourceSnapshot, type InferencePackage, type SemanticDocument, type SensitiveSourceDirectives } from "./StudioV1Contract.ts";

export class StudioV1ValidationError extends Error {}
const object = (v: unknown): v is Record<string, unknown> => typeof v === "object" && v !== null && !Array.isArray(v);
const exact = (v: Record<string, unknown>, allowed: readonly string[], name: string) => { const unknown = Object.keys(v).filter(k => !allowed.includes(k)); if (unknown.length) throw new StudioV1ValidationError(`${name} unknown field: ${unknown[0]}`); };
const req = (v: Record<string, unknown>, key: string): unknown => { if (!(key in v)) throw new StudioV1ValidationError(`missing ${key}`); return v[key]; };
const text = (v: unknown, name: string): string => { if (typeof v !== "string" || !v.trim()) throw new StudioV1ValidationError(`${name} must be non-blank`); return v; };
const list = (v: unknown, name: string): unknown[] => { if (!Array.isArray(v)) throw new StudioV1ValidationError(`${name} must be an array`); return v; };
const unique = (values: readonly string[], name: string) => { if (new Set(values).size !== values.length) throw new StudioV1ValidationError(`duplicate ${name}`); };
const utc = (v: unknown, name: string) => { const s = text(v, name); if (!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(s) || Number.isNaN(Date.parse(s))) throw new StudioV1ValidationError(`${name} must be canonical UTC`); };
const sha = (v: unknown, name: string) => { if (typeof v !== "string" || !/^sha256:[0-9a-f]{64}$/.test(v)) throw new StudioV1ValidationError(`${name} must be SHA-256`); };
const enumValue = (v: unknown, values: readonly string[], name: string) => { if (typeof v !== "string" || !values.includes(v)) throw new StudioV1ValidationError(`unsupported ${name}`); };
const rejectUnsupportedConfidence = (v: unknown): void => { if (Array.isArray(v)) v.forEach(rejectUnsupportedConfidence); else if (object(v)) for (const [k, child] of Object.entries(v)) { if (["probability", "confidence", "confidenceValue", "bayesianProbability"].includes(k)) throw new StudioV1ValidationError(`unsupported ${k}`); rejectUnsupportedConfidence(child); } };

export function canonicalSerialize(value: unknown): string {
  if (value === null || typeof value === "boolean" || typeof value === "string") return JSON.stringify(value);
  if (typeof value === "number" && Number.isFinite(value)) return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(canonicalSerialize).join(",")}]`;
  if (object(value)) return `{${Object.keys(value).sort().map(k => `${JSON.stringify(k)}:${canonicalSerialize(value[k])}`).join(",")}}`;
  throw new StudioV1ValidationError("canonical JSON supports only finite JSON values");
}
// Small synchronous SHA-256 keeps the domain contract usable in browser and Node
// without adding a dependency. Input is always the canonical UTF-8 JSON above.
function sha256(textValue: string): string {
  const bytes = new TextEncoder().encode(textValue); const bitLength = bytes.length * 8;
  const paddedLength = Math.ceil((bytes.length + 9) / 64) * 64; const data = new Uint8Array(paddedLength); data.set(bytes); data[bytes.length] = 0x80;
  const view = new DataView(data.buffer); view.setUint32(paddedLength - 4, bitLength >>> 0); view.setUint32(paddedLength - 8, Math.floor(bitLength / 0x100000000));
  const h = new Uint32Array([0x6a09e667,0xbb67ae85,0x3c6ef372,0xa54ff53a,0x510e527f,0x9b05688c,0x1f83d9ab,0x5be0cd19]);
  const k = new Uint32Array([0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2]);
  const rotr=(x:number,n:number)=>(x>>>n)|(x<<(32-n)); const w=new Uint32Array(64);
  for(let offset=0;offset<data.length;offset+=64){for(let i=0;i<16;i++)w[i]=view.getUint32(offset+i*4);for(let i=16;i<64;i++){const s0=rotr(w[i-15],7)^rotr(w[i-15],18)^(w[i-15]>>>3);const s1=rotr(w[i-2],17)^rotr(w[i-2],19)^(w[i-2]>>>10);w[i]=(w[i-16]+s0+w[i-7]+s1)>>>0;}let [a,b,c,d,e,f,g,hh]=h;for(let i=0;i<64;i++){const s1=rotr(e,6)^rotr(e,11)^rotr(e,25);const ch=(e&f)^(~e&g);const t1=(hh+s1+ch+k[i]+w[i])>>>0;const s0=rotr(a,2)^rotr(a,13)^rotr(a,22);const maj=(a&b)^(a&c)^(b&c);const t2=(s0+maj)>>>0;hh=g;g=f;f=e;e=(d+t1)>>>0;d=c;c=b;b=a;a=(t1+t2)>>>0;}[a,b,c,d,e,f,g,hh].forEach((x,i)=>h[i]=(h[i]+x)>>>0);}
  return [...h].map(x=>x.toString(16).padStart(8,"0")).join("");
}
export const canonicalSha256 = (value: unknown): string => `sha256:${sha256(canonicalSerialize(value))}`;

function validateCitation(raw: unknown): void { if (!object(raw)) throw new StudioV1ValidationError("citation must be object"); exact(raw,["citationId","authors","institutionalAuthor","title","container","publisher","publicationDate","accessedDate","volume","issue","edition","pagesOrLocator","doi","url","isbn","reportOrAccessionId","sourceSnapshotId","completeness","missingRequiredFields"],"citation"); ["citationId","title","sourceSnapshotId"].forEach(k=>text(req(raw,k),k)); const missing=list(req(raw,"missingRequiredFields"),"missingRequiredFields").map(x=>text(x,"missing field")); unique(missing,"missing fields"); if (raw.completeness === "COMPLETE" && missing.length) throw new StudioV1ValidationError("complete citation cannot have missing required fields"); if (raw.completeness === "INCOMPLETE" && !missing.length) throw new StudioV1ValidationError("incomplete citation must identify missing fields"); if (!['COMPLETE','INCOMPLETE'].includes(String(raw.completeness))) throw new StudioV1ValidationError("invalid citation completeness"); if (!(Array.isArray(raw.authors) && raw.authors.length) && !raw.institutionalAuthor) throw new StudioV1ValidationError("citation requires authors or institutional author"); }
export function validateSemanticDocument(raw: unknown): asserts raw is SemanticDocument { if (!object(raw)) throw new StudioV1ValidationError("document must be object"); exact(raw,["documentId","schemaVersion","title","nodeOrder","nodes","citations","citationStyle"],"document"); text(req(raw,"documentId"),"documentId"); text(req(raw,"title"),"title"); if(raw.schemaVersion!=="studio-author-semantic/v1") throw new StudioV1ValidationError("schemaVersion"); const nodes=list(req(raw,"nodes"),"nodes"); const ids=nodes.map((n,i)=>{if(!object(n))throw new StudioV1ValidationError("node"); text(n.id,`node ${i} id`); enumValue(n.type,SEMANTIC_NODE_TYPES,"node type"); return String(n.id)}); unique(ids,"semantic IDs"); const order=list(req(raw,"nodeOrder"),"nodeOrder").map(x=>text(x,"nodeOrder identity")); unique(order,"node order identities"); if(order.length!==ids.length||order.some((id,i)=>id!==ids[i])) throw new StudioV1ValidationError("nodeOrder must exactly match node serialization order"); list(req(raw,"citations"),"citations").forEach(validateCitation); if(!object(raw.citationStyle)){throw new StudioV1ValidationError("citationStyle")}; exact(raw.citationStyle,["style","styleVersion","locale"],"citationStyle"); enumValue(raw.citationStyle.style,CITATION_STYLES,"citation style"); text(raw.citationStyle.styleVersion,"styleVersion"); text(raw.citationStyle.locale,"locale"); rejectUnsupportedConfidence(raw); }
export function validateAuthorRevision(raw: unknown): asserts raw is AuthorRevision { if(!object(raw))throw new StudioV1ValidationError("revision"); exact(raw,["artifactId","revisionId","revisionNumber","parentRevisionId","semanticContent","contentHash","sourceSnapshots","profile","profileVersion","createdAt","authorPrincipalId","immutableStatus"],"revision"); ["artifactId","revisionId","profileVersion","authorPrincipalId"].forEach(k=>text(req(raw,k),k)); enumValue(raw.profile,ARTIFACT_PROFILES,"profile"); utc(raw.createdAt,"createdAt"); if(!Number.isInteger(raw.revisionNumber)||Number(raw.revisionNumber)<1)throw new StudioV1ValidationError("revisionNumber"); if(raw.revisionNumber===1&&raw.parentRevisionId!==undefined)throw new StudioV1ValidationError("first revision cannot have parent"); if(Number(raw.revisionNumber)>1&&!raw.parentRevisionId)throw new StudioV1ValidationError("later revision requires parent"); if(raw.immutableStatus!=="IMMUTABLE_SAVED_REVISION")throw new StudioV1ValidationError("revision must be immutable"); validateSemanticDocument(raw.semanticContent); sha(raw.contentHash,"contentHash"); if(raw.contentHash!==canonicalSha256(raw.semanticContent))throw new StudioV1ValidationError("contentHash mismatch"); const snapshots=list(raw.sourceSnapshots,"sourceSnapshots").map(x=>{if(!object(x))throw new StudioV1ValidationError("snapshot reference"); exact(x,["snapshotId","snapshotHash"],"snapshot reference"); sha(x.snapshotHash,"snapshotHash"); return text(x.snapshotId,"snapshotId")}); unique(snapshots,"snapshot references"); }
export function validateSnapshot(raw: unknown): asserts raw is FrozenResearchSourceSnapshot { if(!object(raw))throw new StudioV1ValidationError("snapshot"); exact(raw,["snapshotId","investigationId","capturedAt","selectionScope","selectedAnchorIds","inboxMembershipBasis","sources","snapshotHash","immutableStatus"],"snapshot"); text(raw.snapshotId,"snapshotId");text(raw.investigationId,"investigationId");utc(raw.capturedAt,"capturedAt"); const ids=list(raw.selectedAnchorIds,"selectedAnchorIds").map(x=>text(x,"anchorId")); unique(ids,"selected anchors"); const sources=list(raw.sources,"sources"); const sourceIds=sources.map(x=>{if(!object(x))throw new StudioV1ValidationError("source"); return text(x.anchorId,"source anchorId")}); unique(sourceIds,"snapshot sources"); if(raw.selectionScope==="ENTIRE_RESEARCH_INBOX"&&raw.inboxMembershipBasis!=="COMPLETE_ELIGIBLE_INBOX_INDEPENDENT_OF_UI")throw new StudioV1ValidationError("entire Inbox must be UI-independent"); if(raw.selectionScope==="EXPLICIT_SELECTION"&&raw.inboxMembershipBasis!=="EXPLICIT_STABLE_IDENTITIES")throw new StudioV1ValidationError("selection basis"); if(ids.length!==sourceIds.length||ids.some((id,i)=>id!==sourceIds[i]))throw new StudioV1ValidationError("selected anchors must match frozen source order"); if(raw.immutableStatus!=="FROZEN")throw new StudioV1ValidationError("snapshot must be frozen"); sha(raw.snapshotHash,"snapshotHash"); const domain={...raw}; delete domain.snapshotHash; if(raw.snapshotHash!==canonicalSha256(domain))throw new StudioV1ValidationError("snapshotHash mismatch"); }
export function effectiveSensitivity(policies: readonly SensitiveSourceDirectives[]): SensitiveSourceDirectives { if(!policies.length) throw new StudioV1ValidationError("sensitivity policy required"); return {includeInAnalysis:policies.every(p=>p.includeInAnalysis)&&!policies.some(p=>p.excludeFromAiProcessing),includeInArtifact:policies.every(p=>p.includeInArtifact),citePublicly:policies.every(p=>p.citePublicly)&&!policies.some(p=>p.restrictedAppendix),anonymize:policies.some(p=>p.anonymize),restrictedAppendix:policies.some(p=>p.restrictedAppendix),excludeFromAiProcessing:policies.some(p=>p.excludeFromAiProcessing)}; }
export function validateProposal(raw: unknown, currentRevisionId?: string, currentContentHash?: string): asserts raw is AiDraftProposal { if(!object(raw))throw new StudioV1ValidationError("proposal"); exact(raw,["proposalId","artifactId","baseRevisionId","baseContentHash","sourceSnapshots","assistanceMode","providerProvenance","units","authorityState","staleBase","unsupportedClaimFindings","incompleteCitationFindings"],"proposal"); ["proposalId","artifactId","baseRevisionId"].forEach(k=>text(raw[k],k));sha(raw.baseContentHash,"baseContentHash");enumValue(raw.assistanceMode,ASSISTANCE_MODES,"assistance mode");if(raw.authorityState!=="UNAPPLIED_PROPOSAL")throw new StudioV1ValidationError("proposal cannot be authority"); const units=list(raw.units,"units"); unique(units.map(x=>object(x)?text(x.proposalUnitId,"proposalUnitId"):""),"proposal units"); if(units.some(x=>!object(x)||x.state!=="UNAPPLIED"))throw new StudioV1ValidationError("proposal units must remain unapplied"); const stale=currentRevisionId!==undefined&&(raw.baseRevisionId!==currentRevisionId||raw.baseContentHash!==currentContentHash); if(stale&&(!object(raw.staleBase)||raw.staleBase.rejected!==true))throw new StudioV1ValidationError("stale proposal must be rejected"); }
export function validateProjection(raw: unknown, parentContentHash: string): asserts raw is ChildProjection { if(!object(raw))throw new StudioV1ValidationError("projection"); exact(raw,["projectionId","parentArtifactId","parentRevisionId","parentContentHash","format","state","templateProfileVersion","rendererVersion","configurationHash","outputHash","priorSuccessfulProjectionId","failure","publication"],"projection"); ["projectionId","parentArtifactId","parentRevisionId","templateProfileVersion","rendererVersion"].forEach(k=>text(raw[k],k)); sha(raw.parentContentHash,"parentContentHash");sha(raw.configurationHash,"configurationHash");enumValue(raw.format,PROJECTION_FORMATS,"projection format");enumValue(raw.state,PROJECTION_STATES,"projection state");if(raw.parentContentHash!==parentContentHash)throw new StudioV1ValidationError("projection parent hash mismatch");if(["CURRENT","PUBLISHED","RETRACTED"].includes(String(raw.state))&&!raw.outputHash)throw new StudioV1ValidationError("successful projection requires output hash");if(raw.outputHash)sha(raw.outputHash,"outputHash");if(raw.state==="FAILED"&&(!raw.failure||!raw.priorSuccessfulProjectionId))throw new StudioV1ValidationError("failed projection must preserve prior success"); }
const LEGAL_PROJECTION_TRANSITIONS: Readonly<Record<string, readonly string[]>> = {NOT_GENERATED:["QUEUED"],QUEUED:["REBUILDING","FAILED"],REBUILDING:["CURRENT","FAILED"],CURRENT:["STALE","SUPERSEDED","PUBLISHED"],STALE:["QUEUED","SUPERSEDED"],FAILED:["QUEUED","SUPERSEDED"],SUPERSEDED:[],PUBLISHED:["RETRACTED","SUPERSEDED"],RETRACTED:[]};
export function validateProjectionTransition(from: ChildProjection["state"], to: ChildProjection["state"]): void { if(!LEGAL_PROJECTION_TRANSITIONS[from]?.includes(to))throw new StudioV1ValidationError(`illegal projection transition ${from} -> ${to}`); }
export function validateInference(raw: unknown): asserts raw is InferencePackage { rejectUnsupportedConfidence(raw); if(!object(raw))throw new StudioV1ValidationError("inference"); exact(raw,["inferenceSessionId","inferencePackageId","invocationOwner","intentionCapabilities","intentionResults","h0","alternatives","observations","mathematicalWarrants","assumptions","supportingEvidence","counterevidence","alternativeExplanations","predictions","falsifiers","unresolvedUncertainties","outputClassification","proposalState","governedConclusion"],"inference"); if(raw.invocationOwner!=="STUDIO")throw new StudioV1ValidationError("Inference Box is STUDIO-only"); const results=list(raw.intentionResults,"intentionResults"); if(results.some(x=>!object(x)||x.completionStatus!=="COMPLETED"||x.immutableStatus!=="IMMUTABLE"||x.access!=="READ_ONLY"))throw new StudioV1ValidationError("INTENTION input must be completed immutable read-only"); if(!object(raw.intentionCapabilities)||Object.values(raw.intentionCapabilities).some(x=>x!=="PROHIBITED"))throw new StudioV1ValidationError("INTENTION capabilities prohibited"); const observations=list(raw.observations,"observations");if(observations.some(x=>!object(x)||x.epistemicClass!=="DETERMINISTIC_MEASUREMENT"))throw new StudioV1ValidationError("measurement boundary"); const interpretations=[raw.h0,...list(raw.alternatives,"alternatives"),...list(raw.mathematicalWarrants,"warrants"),...list(raw.counterevidence,"counterevidence")];if(interpretations.some(x=>!object(x)||x.epistemicClass!=="ABDUCTIVE"))throw new StudioV1ValidationError("abductive boundary"); const alts=list(raw.alternatives,"alternatives");if(!alts.some(x=>object(x)&&x.hypothesisId==="H1a")||!alts.some(x=>object(x)&&x.hypothesisId==="H1b"))throw new StudioV1ValidationError("H1a and H1b required"); const conclusion=raw.governedConclusion;if(!object(conclusion))throw new StudioV1ValidationError("governed conclusion");enumValue(conclusion.conclusion,GOVERNED_CONCLUSIONS,"conclusion"); ["evidenceScope","assumptions","unresolvedAlternatives"].forEach(k=>{if(!list(conclusion[k],k).length)throw new StudioV1ValidationError(`${k} required`)});if(conclusion.conclusion==="H0_REJECTED_UNDER_DECLARED_TEST"&&!conclusion.declaredTest)throw new StudioV1ValidationError("H0 rejection requires declared test"); }
