import type { CorpusEvent } from "../../corpus/corpusTypes";
import type { Investigation } from "../investigationTypes";
import { materializeInitialOperationalRevision, resolveCurrentOperationalRevision } from "../revision/OperationalGraphRevision";
import type { KnowledgeObject } from "../../knowledge/model/KnowledgeObject";
import { createCanonicalInvestigationFromCorpusEvent } from "../../federation/services/importInvestigation";
import type { FederationRepository } from "../../federation/adapters/FederationAdapter";
import { materializeOwnedActivation, parseOwnedActivationAggregate, type MaterializedOwnedActivation } from "./OwnedInvestigationContinuity";
import { resolveApiBaseUrl } from "../../api/ApiOrigin";

export class CanonImportError extends Error { readonly code:string; constructor(code:string,message:string){super(message);this.code=code} }
const csrf=()=>document.cookie.split(";").map(x=>x.trim()).find(x=>x.startsWith("isees_csrf="))?.slice(11);
export async function importCanonEventIntoOwnedInvestigation(input:{investigation:Investigation;event:CorpusEvent;repository:FederationRepository;knowledge:readonly KnowledgeObject[];expectedAggregateRevision:number;idempotencyKey:string;transport?:typeof fetch}):Promise<{activation:MaterializedOwnedActivation;duplicate:boolean;replayed:boolean;aggregateRevision:number}>{
  const local=createCanonicalInvestigationFromCorpusEvent(input.repository,input.event);const operational=materializeInitialOperationalRevision(local,input.knowledge,{recordedAt:local.updatedAt});const graph=resolveCurrentOperationalRevision(operational).manifold.graph;const focused=graph.nodes.filter(node=>node.type==="EVENT"&&(node.id===input.event.canonical_event.event_id||node.metadata?.sourceId===input.event.canonical_event.event_id));if(focused.length!==1)throw new CanonImportError("CANON_INVALID","Canonical event does not resolve exactly once.");
  const payload={investigationId:input.investigation.id,eventId:input.event.canonical_event.event_id,eventTitle:input.event.canonical_event.event_name,expectedAggregateRevision:input.expectedAggregateRevision,idempotencyKey:input.idempotencyKey,workspace:{sourceWorkspaceId:`workspace:${input.investigation.id}`,nodes:graph.nodes.map(node=>({id:node.id,kind:node===focused[0]?"CANONICAL_EVENT":"NOTE",canonicalEventId:node===focused[0]?input.event.canonical_event.event_id:null,title:node.label})),edges:graph.edges.map(edge=>({id:edge.id,sourceId:edge.source,targetId:edge.target,kind:"RELATED"}))},viewState:{activeMode:"OVERVIEW",focusedEventId:input.event.canonical_event.event_id,activeLayers:[],temporalContext:null,investigativeScale:null}};
  const token=csrf();if(!token)throw new CanonImportError("AUTHENTICATION_REQUIRED","The secure account session is unavailable.");const response=await(input.transport??fetch)(`${resolveApiBaseUrl()}/api/v1/investigations/${encodeURIComponent(input.investigation.id)}/canon-events`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json","X-ISEES-CSRF":decodeURIComponent(token)},body:JSON.stringify(payload)});const body:unknown=await response.json().catch(()=>null);if(!response.ok){const code=(body as {error?:{code?:string}})?.error?.code??"IMPORT_FAILED";throw new CanonImportError(code,code==="REVISION_CONFLICT"?"The Investigation changed. Refresh before importing.":"The Canon event could not be imported safely.")};const result=body as {investigationId:string;aggregateRevision:number;duplicate:boolean;replayed:boolean;activation:unknown};if(result.investigationId!==input.investigation.id)throw new CanonImportError("IDENTITY_MISMATCH","Import response identity does not match the active Investigation.");return Object.freeze({activation:materializeOwnedActivation(parseOwnedActivationAggregate(result.activation,input.investigation.id)),duplicate:result.duplicate,replayed:result.replayed,aggregateRevision:result.aggregateRevision});
}
