from __future__ import annotations

from typing import Any, Protocol


class NativeCaseDraftRepository(Protocol):
    def create(self, *, principal_id: str, command: dict[str, Any]) -> tuple[dict[str, Any], bool]: ...
    def get(self, *, principal_id: str, candidate_id: str) -> dict[str, Any] | None: ...
    def list(self, *, principal_id: str) -> list[dict[str, Any]]: ...
    def update(self, *, principal_id: str, candidate_id: str,
               command: dict[str, Any]) -> tuple[dict[str, Any] | None, bool]: ...
