from __future__ import annotations

from typing import Any, Protocol


class CandidateEvidenceRepository(Protocol):
    def create(self, *, command: dict[str, Any], principal_id: str, origin: str) -> tuple[dict[str, Any], bool]: ...
    def list(self, *, investigation_id: str, principal_id: str, limit: int, cursor: str | None) -> tuple[list[dict[str, Any]], str | None]: ...
    def get(self, *, investigation_id: str, candidate_id: str, principal_id: str) -> dict[str, Any] | None: ...
    def transition(self, *, investigation_id: str, candidate_id: str, principal_id: str, command: dict[str, Any]) -> tuple[dict[str, Any], bool]: ...
