from __future__ import annotations

ARTIFACT_PROFILES = ("INVESTIGATION_REPORT", "EXECUTIVE_BRIEF", "SCIENTIFIC_PAPER", "INTENTION_HYPOTHESIS_ASSESSMENT")
CITATION_STYLES = ("APA", "CHICAGO", "IEEE")
SEMANTIC_NODE_TYPES = ("HEADING", "SECTION", "PARAGRAPH", "CLAIM", "QUOTATION", "CITATION_REFERENCE", "FOOTNOTE", "EQUATION", "FIGURE", "TABLE", "APPENDIX", "RESEARCHER_NOTE")
PROJECTION_FORMATS = ("PDF", "DOCX", "HTML", "LATEX", "BIBLIOGRAPHY_MANIFEST", "SOURCE_PROVENANCE_MANIFEST")
PROJECTION_STATES = ("NOT_GENERATED", "QUEUED", "REBUILDING", "CURRENT", "STALE", "FAILED", "SUPERSEDED", "PUBLISHED", "RETRACTED")
ASSISTANCE_MODES = ("BUILD_OUTLINE", "DRAFT_SELECTED_SECTIONS", "DRAFT_COMPLETE_ARTIFACT", "REVIEW_SCHOLARLY_INTEGRITY")
GOVERNED_CONCLUSIONS = ("CONSISTENT_WITH", "INSUFFICIENT_EVIDENCE", "NOT_DISTINGUISHABLE", "H0_WEAKENED", "H0_REJECTED_UNDER_DECLARED_TEST", "H1_VIABLE", "FURTHER_INVESTIGATION_REQUIRED")
PROHIBITED_STUDIO_MUTATIONS = ("SYSTEM_CANON", "INVESTIGATION_EVIDENCE", "DETERMINISTIC_RESULTS", "RESEARCH_INBOX", "SOURCE_SYSTEMS", "INTENTION")

# Wire ordering is significant only where explicitly modeled: nodeOrder is identical
# to nodes order; selectedAnchorIds is identical to frozen sources order. Other lists
# preserve author-declared order. Sets are never serialized.
