import { KnowledgeObjectType } from "../../knowledge/model/KnowledgeObjectTypes";
import { IntentionAvailability, IntentionEpistemicClassification, type IntentionEpistemicClassification as EpistemicClassification } from "../contracts/IntentionAvailability";
import { IntentionEquationId } from "../contracts/IntentionEquationRegistry";
import { IntentionValidationStatus } from "../contracts/IntentionHypothesis";
import type { IntentionMetricDerivation } from "../contracts/IntentionMetricDerivation";
import type { IntentionProjection, IntentionProjectionInput } from "./IntentionProjectionTypes";

const lexical = (a: string, b: string) => a < b ? -1 : a > b ? 1 : 0;
export function canonicalIntentionSerialize(value: unknown): string { const stable = (v: unknown): unknown => Array.isArray(v) ? v.map(stable) : v && typeof v === "object" ? Object.fromEntries(Object.entries(v as Record<string, unknown>).sort(([a],[b]) => lexical(a,b)).map(([k,c]) => [k, stable(c)])) : v; return JSON.stringify(stable(value)); }
function hash(value: unknown): string { const text = canonicalIntentionSerialize(value); let h = 2166136261; for (let i=0;i<text.length;i+=1) { h ^= text.charCodeAt(i); h = Math.imul(h, 16777619); } return (h >>> 0).toString(16).padStart(8,"0"); }
function freeze<T>(value: T): T { if (value && typeof value === "object" && !Object.isFrozen(value)) { Object.values(value as Record<string, unknown>).forEach(freeze); Object.freeze(value); } return value; }
const ids = (values: readonly string[]) => [...new Set(values)].sort(lexical);
function fail(message: string): never { throw new Error(`INTENTION projection rejected input: ${message}`); }
function sourceResidual(object: IntentionProjectionInput["knowledgeObjects"][number]): number | undefined { const payload = object.payload as { canonicalEvent?: { manifold_analysis?: { topology?: { topology_state?: { residual_instability?: unknown } } } } } | undefined; const value = payload?.canonicalEvent?.manifold_analysis?.topology?.topology_state?.residual_instability; return typeof value === "number" && Number.isFinite(value) ? value : undefined; }

export function resolveIntentionProjection(input: IntentionProjectionInput): IntentionProjection {
  const investigation = input.investigation; if (!investigation?.id.trim()) fail("active Investigation is required.");
  const revision = input.currentRevision; if (!revision || revision.id !== investigation.currentRevisionId || !investigation.revisions.some(item => item.id === revision.id)) fail("exact current operational revision is required.");
  const focus = input.focusedEventId; if (!focus?.trim() || focus !== investigation.workspace.focused_event_id) fail("exact focused EVENT is required.");
  if (!input.model.id.trim() || !input.model.version.trim() || !input.model.configurationId.trim()) fail("model, version, and configuration identities are required.");
  const execution = input.resolveExecution; if (execution && execution.provenance.investigationId !== investigation.id) fail("Resolve execution belongs to another Investigation.");
  const selectedCandidate = input.selectedCandidate;
  if (!!selectedCandidate !== !!execution) fail("selected candidate and Resolve execution must be supplied together.");
  let authoritativeCandidate: typeof selectedCandidate = undefined;
  if (selectedCandidate && execution) {
    const matches = execution.candidateEvaluations.evaluations.filter(e => e.identity.evaluationId === selectedCandidate.identity.evaluationId && e.identity.candidateId === selectedCandidate.identity.candidateId);
    if (matches.length !== 1) fail("selected candidate must resolve exactly once within the matching Resolve execution.");
    authoritativeCandidate = matches[0]!;
    if (authoritativeCandidate.identity.evaluationId !== selectedCandidate.identity.evaluationId || authoritativeCandidate.identity.candidateId !== selectedCandidate.identity.candidateId || authoritativeCandidate.identity.leftKnowledgeObjectId !== selectedCandidate.identity.leftKnowledgeObjectId || authoritativeCandidate.identity.rightKnowledgeObjectId !== selectedCandidate.identity.rightKnowledgeObjectId) fail("selected candidate pair identity is incoherent with its Resolve execution evaluation.");
  }
  const knowledge = [...input.knowledgeObjects].sort((a,b) => lexical(a.identity.id,b.identity.id));
  const focused = knowledge.filter(o => o.type === KnowledgeObjectType.EVENT && o.provenance.sourceId === focus); if (focused.length !== 1) fail("focused EVENT Knowledge must resolve exactly once.");
  const sourceKnowledgeIds = ids(authoritativeCandidate ? [authoritativeCandidate.identity.leftKnowledgeObjectId, authoritativeCandidate.identity.rightKnowledgeObjectId] : [focused[0]!.identity.id]);
  if (sourceKnowledgeIds.some(id => !knowledge.some(o => o.identity.id === id))) fail("candidate Knowledge lineage is incomplete.");
  const sourceRelationshipIds = ids(knowledge.filter(o => sourceKnowledgeIds.includes(o.identity.id)).flatMap(o => o.relationships.map(r => r.id)));
  const identityBasis = { investigationId: investigation.id, revisionId: revision.id, resolveExecutionId: execution?.executionId, candidateId: authoritativeCandidate?.identity.candidateId, evaluationId: authoritativeCandidate?.identity.evaluationId, modelId: input.model.id, modelVersion: input.model.version, configurationId: input.model.configurationId, configurationValues: ids(input.model.unorderedConfigurationValues ?? []) };
  const executionId = `intention-execution:${hash(identityBasis)}`; const projectionId = `intention-projection:${hash({ ...identityBasis, focus })}`;
  const nodes = sourceKnowledgeIds.map(sourceId => { const object = knowledge.find(o => o.identity.id === sourceId)!; const canonicalEventId = object.provenance.sourceId; return { id: `intention-node:${hash({ projectionId, sourceId })}`, owner: "INTENTION" as const, sourceKnowledgeId: sourceId, canonicalEventId, role: canonicalEventId === focus ? "FOCUSED_EVENT" as const : "COMPARE_EVENT" as const, metricDerivationIds: [] as string[] }; });
  const derivations: IntentionMetricDerivation[] = [];
  const make = (nodeId: string, metricId: string, metricName: string, symbol: string, equationId: string, availability: "AVAILABLE"|"UNAVAILABLE"|"THEORETICAL", value: number|undefined, reason: string|undefined, sourcePath: string, epistemic: EpistemicClassification = IntentionEpistemicClassification.COMPUTATIONAL_PROJECTION): IntentionMetricDerivation => ({ id: `intention-derivation:${hash({ executionId,nodeId,metricId })}`, metricId, metricName, symbol, ...(value === undefined ? {} : { value, displayValue: String(value) }), units: "unitless", availability, epistemicClassification: epistemic, equationId, inputs: availability === "AVAILABLE" ? [{ id: metricId, symbol, value: value!, sourcePath, sourceKnowledgeIds, sourceRelationshipIds, availability: IntentionAvailability.AVAILABLE }] : [], assumptions: [], unavailableInputs: availability === "AVAILABLE" ? [] : [metricId], sourceKnowledgeIds, sourceRelationshipIds, investigationId: investigation.id, operationalRevisionId: revision.id, ...(execution ? { resolveExecutionId: execution.executionId } : {}), intentionExecutionId: executionId, modelId: input.model.id, modelVersion: input.model.version, configurationId: input.model.configurationId, projectedNodeId: nodeId, ...(reason ? { reason } : {}) });
  for (const node of nodes) { const object = knowledge.find(o => o.identity.id === node.sourceKnowledgeId)!; const residual = sourceResidual(object); derivations.push(make(node.id,"source-residual-instability","Corpus topology residual instability","Rᵢ(source)",IntentionEquationId.SOURCE_RESIDUAL_INSTABILITY,residual === undefined ? "UNAVAILABLE":"AVAILABLE",residual,residual === undefined ? "Canonical source residual_instability is unavailable." : undefined,"payload.canonicalEvent.manifold_analysis.topology.topology_state.residual_instability",IntentionEpistemicClassification.CANONICAL_SOURCE_MATERIAL)); derivations.push(make(node.id,"attractor-detection","Attractor detection","A",IntentionEquationId.ATTRACTOR_DETECTION,"THEORETICAL",undefined,"No repository-authoritative attractor definition or test exists.","none",IntentionEpistemicClassification.THEORETICAL_DESCRIPTOR)); }
  const links = authoritativeCandidate ? [{ id: `intention-link:${hash({ projectionId, candidateId: authoritativeCandidate.identity.candidateId })}`, owner: "INTENTION" as const, sourceNodeId: nodes.find(n => n.sourceKnowledgeId === authoritativeCandidate.identity.leftKnowledgeObjectId)!.id, targetNodeId: nodes.find(n => n.sourceKnowledgeId === authoritativeCandidate.identity.rightKnowledgeObjectId)!.id, kind: "DESCRIPTIVE_RESOLVE_COMPARISON" as const, metricDerivationIds: [] as string[] }] : [];
  if (authoritativeCandidate && links[0]) derivations.push(make(links[0].sourceNodeId,"resolve-aggregate-similarity","Resolve aggregate similarity","Sᵣ",IntentionEquationId.RESOLVE_AGGREGATE_SIMILARITY,"AVAILABLE",authoritativeCandidate.explanation.aggregate.aggregateSimilarity,undefined,"resolveExecution.candidateEvaluations.evaluations[].explanation.aggregate.aggregateSimilarity"));
  nodes.forEach(node => node.metricDerivationIds.push(...derivations.filter(d => d.projectedNodeId === node.id).map(d => d.id))); if (links[0]) links[0].metricDerivationIds.push(...derivations.filter(d => d.metricId === "resolve-aggregate-similarity").map(d => d.id));
  const lineage = { investigationId: investigation.id, operationalRevisionId: revision.id, focusedEventId: focus, ...(execution ? { resolveExecutionId: execution.executionId } : {}), ...(authoritativeCandidate ? { candidateId: authoritativeCandidate.identity.candidateId, evaluationId: authoritativeCandidate.identity.evaluationId } : {}), sourceKnowledgeIds, sourceRelationshipIds, modelId: input.model.id, modelVersion: input.model.version, configurationId: input.model.configurationId };
  const hypothesis = { id: `intention-hypothesis:${hash({ executionId, kind:"organizing-structure" })}`, statement: "An organizing structure may account for descriptive patterns.", nullCandidate: { id: `intention-null:${hash({ executionId, kind:"no-organizing-structure" })}`, statement: "The descriptive patterns do not require an organizing structure." }, assumptions: [], requiredInputs: ["authoritative INTENTION model", "authoritative null model", "test definition"], availability: IntentionAvailability.THEORETICAL, falsificationConditions: [], validationStatus: IntentionValidationStatus.NOT_TESTED, reason: "No repository-authoritative inferential test exists." };
  const base = { id: projectionId, executionId, availability: IntentionAvailability.AVAILABLE, epistemicClassification: IntentionEpistemicClassification.COMPUTATIONAL_PROJECTION, nodes, links, derivations, lineage, hypotheses: [hypothesis], validationStatus: IntentionValidationStatus.NOT_TESTED };
  const result = { ...base, canonicalRepresentation: canonicalIntentionSerialize(base) }; return freeze(result);
}
