import { INTENTION_EQUATION_REGISTRY } from "../contracts/IntentionEquationRegistry";
import type { IntentionProjection } from "./IntentionProjectionTypes";
const availability = new Set(["AVAILABLE","UNAVAILABLE","THEORETICAL"]); const required = (v: string, label: string) => { if (!v?.trim()) throw new Error(`${label} is required.`); };
export function validateIntentionProjection(value: IntentionProjection): void {
  [value.id,value.executionId,value.lineage.investigationId,value.lineage.operationalRevisionId,value.lineage.modelId,value.lineage.modelVersion,value.lineage.configurationId].forEach((v,i) => required(v,`identity ${i}`));
  const nodeIds = new Set<string>(); value.nodes.forEach(node => { required(node.id,"projected node ID"); if (node.owner !== "INTENTION" || nodeIds.has(node.id)) throw new Error("Invalid or duplicate projected node ownership/identity."); nodeIds.add(node.id); });
  const linkIds = new Set<string>(); value.links.forEach(link => { if (link.owner !== "INTENTION" || linkIds.has(link.id) || !nodeIds.has(link.sourceNodeId) || !nodeIds.has(link.targetNodeId)) throw new Error("Invalid projected link."); linkIds.add(link.id); });
  const derivationIds = new Set<string>(); const equations = new Set(INTENTION_EQUATION_REGISTRY.map(e => e.id));
  value.derivations.forEach(d => { if (derivationIds.has(d.id) || !nodeIds.has(d.projectedNodeId)) throw new Error("Duplicate derivation or mismatched node ownership."); derivationIds.add(d.id); if (!availability.has(d.availability) || !equations.has(d.equationId)) throw new Error("Invalid availability or unknown equation."); if (d.value !== undefined && !Number.isFinite(d.value)) throw new Error("Metric values must be finite."); if (d.availability === "AVAILABLE" && (d.value === undefined || d.inputs.length === 0)) throw new Error("AVAILABLE derivation requires a value and inputs."); if (d.availability !== "AVAILABLE" && !d.reason?.trim()) throw new Error("UNAVAILABLE/THEORETICAL derivation requires a reason."); if (d.investigationId !== value.lineage.investigationId || d.operationalRevisionId !== value.lineage.operationalRevisionId || d.modelId !== value.lineage.modelId || d.modelVersion !== value.lineage.modelVersion || d.configurationId !== value.lineage.configurationId) throw new Error("Inconsistent derivation lineage."); });
  INTENTION_EQUATION_REGISTRY.forEach(e => { if (e.executable !== false || /=>|function\s*\(|eval\s*\(|new Function/.test(e.displayExpression)) throw new Error("Executable content masquerades as a display equation."); });
}
