import { createContext,useContext } from "react";
import type { StudioV1SaveState } from "../v1/runtime/StudioV1SaveOrchestrator.ts";
import type { RevisionDetail, RevisionList } from "../v1/api/StudioV1AuthorApiTypes.ts";
import type { AdmitManifoldArtifactResponse, ManifoldArtifactAdmissionReceipt } from "../v1/api/ManifoldArtifactAdmissionApi.ts";
import type { ManifoldArtifactManifest } from "../contracts/StudioV1Contract.ts";
export type ManifoldAdmissionResult=AdmitManifoldArtifactResponse|Readonly<{receipt:ManifoldArtifactAdmissionReceipt;replayed:boolean;authoritativeCurrentHead:string}>;
export interface StudioSaveActionContextValue{readonly state:StudioV1SaveState;readonly admission:{readonly authenticated:boolean;readonly guest:boolean;readonly eligible:boolean;readonly investigationId?:string;readonly operationalHeadId:string|null;readonly eligibleNodeIds:readonly string[];readonly pending:boolean;readonly stale:boolean;readonly message:string;readonly result?:ManifoldAdmissionResult};save():Promise<void>;retry():Promise<void>;reloadHead():Promise<void>;keepLocalDraft():void;listRevisions():Promise<RevisionList|undefined>;loadRevision(id:string):Promise<RevisionDetail|undefined>;clearRevisionPreview():void;inspectProjections():Promise<unknown>;materializeManifoldArtifact():Promise<unknown>;inspectManifoldArtifact():Promise<unknown>;downloadManifoldArtifact():Promise<unknown>;closeManifoldInspector():void;admitManifoldArtifact(projectionId:string,selected:readonly string[],idempotencyKey:string,manifest:ManifoldArtifactManifest,outputHash:string):Promise<boolean>;refreshAdmissionAuthority():Promise<void>;viewAdmittedArtifact():void}
export const StudioSaveActionContext=createContext<StudioSaveActionContextValue|undefined>(undefined);
export function useStudioSaveAction(){const value=useContext(StudioSaveActionContext);if(!value)throw new Error("Studio save action requires StudioSaveActionProvider.");return value}
