import { useEffect,useMemo,useState,type ReactNode } from "react";
import { useAuthorDocumentRuntime } from "../../author/runtime/AuthorDocumentRuntimeContext.tsx";
import { useOperatorIdentity } from "../../identity/runtime/OperatorIdentityRuntimeContext.tsx";
import { createStudioV1AuthorApiClient,type StudioV1AuthorApiClient } from "../v1/api/StudioV1AuthorApiClient.ts";
import { StudioV1SaveOrchestrator } from "../v1/runtime/StudioV1SaveOrchestrator.ts";
import { StudioSaveActionContext } from "./StudioSaveActionContext.ts";
import { createManifoldArtifactAdmissionClient, ManifoldArtifactAdmissionError, type ManifoldArtifactAdmissionClient } from "../v1/api/ManifoldArtifactAdmissionApi.ts";
import { materializeOwnedActivation, parseOwnedActivationAggregate } from "../../investigation/continuity/OwnedInvestigationContinuity.ts";
import { useWorkspaceRuntime } from "../../workspace/runtime/WorkspaceRuntimeContext.tsx";
import { WorkspaceMode } from "../../workspace/runtime/WorkspaceRuntimeTypes.ts";
import type { ManifoldArtifactManifest } from "../contracts/StudioV1Contract.ts";
import type { ManifoldAdmissionResult } from "./StudioSaveActionContext.ts";
export function StudioSaveActionProvider({children,client,admissionClient}:{readonly children:ReactNode;readonly client?:StudioV1AuthorApiClient;readonly admissionClient?:ManifoldArtifactAdmissionClient}){
 const runtime=useAuthorDocumentRuntime();const identity=useOperatorIdentity();const [owner]=useState(()=>new StudioV1SaveOrchestrator(client??createStudioV1AuthorApiClient()));const[,render]=useState(0);
 const workspace=useWorkspaceRuntime();const [admissionApi]=useState(()=>admissionClient??createManifoldArtifactAdmissionClient());const [admissionState,setAdmissionState]=useState<{pending:boolean;stale:boolean;message:string;result?:ManifoldAdmissionResult}>({pending:false,stale:false,message:""});
 const authenticated=identity.status==="READY"&&identity.identity?.kind==="ACCOUNT";const guest=identity.status==="READY"&&identity.identity?.kind==="GUEST"&&identity.persistence==="SESSION";const principalId=authenticated?identity.identity?.operatorId:undefined;const investigationId=runtime.getActiveInvestigationId();
 useEffect(()=>owner.subscribe(()=>render(v=>v+1)),[owner]);
 useEffect(()=>{const observe=()=>owner.observe(runtime.getActiveDocument(),runtime.isDirty(),runtime.getActiveInvestigationId());observe();return runtime.subscribe(observe)},[owner,runtime]);
 useEffect(()=>{void owner.discover(runtime,authenticated?investigationId:undefined,principalId)},[authenticated,investigationId,owner,principalId,runtime]);
 useEffect(()=>()=>owner.dispose(),[owner]);
 const active=workspace.getActiveInvestigation(),head=active?.currentRevisionId??null,eligibleNodeIds=active?.revisions.find(item=>item.id===head)?.manifold.graph.nodes.map(node=>node.id)??[];const guestEligible=guest&&workspace.canAdmitGuestManifoldArtifact(investigationId);
 const refreshAdmissionAuthority=async()=>{if(!investigationId)return;const response=await fetch(`/api/v1/investigations/${encodeURIComponent(investigationId)}/activation`,{credentials:"include"});const raw:unknown=await response.json();const activation=materializeOwnedActivation(parseOwnedActivationAggregate(raw,investigationId));workspace.refreshAdoptedOwnedInvestigation(activation);setAdmissionState(value=>({...value,stale:false,message:"Investigation refreshed. Review the proposals and confirm again."}))};
 const admit=async(projectionId:string,selected:readonly string[],idempotencyKey:string,manifest:ManifoldArtifactManifest,outputHash:string)=>{if((!authenticated&&!guestEligible)||!investigationId)return false;setAdmissionState(value=>({...value,pending:true,message:"Admission pending…"}));try{let result:ManifoldAdmissionResult;if(guestEligible){const local=workspace.admitGuestManifoldArtifact({investigationId,projectionId,expectedOperationalHeadId:head,selectedRelationshipDeclarationIds:[...selected].sort(),idempotencyKey,manifest,outputHash,admittedAt:new Date().toISOString()});result={receipt:local.receipt,replayed:local.replayed,authoritativeCurrentHead:local.receipt.resultingOperationalRevisionId}}else{const remote=await admissionApi.admit(investigationId,{projectionId,expectedOperationalHeadId:head,selectedRelationshipDeclarationIds:[...selected].sort(),idempotencyKey});const activation=materializeOwnedActivation(remote.activation);workspace.refreshAdoptedOwnedInvestigation(activation);result=remote}workspace.clearStudioManifoldArtifactReview();workspace.navigateToMode(WorkspaceMode.MANIFOLD);workspace.setSelection({kind:"NODE",nodeId:result.receipt.admittedArtifactNodeId});setAdmissionState({pending:false,stale:false,result,message:`Admitted 1 node and ${result.receipt.createdRelationshipIds.length} edge${result.receipt.createdRelationshipIds.length===1?"":"s"} in ${result.receipt.resultingOperationalRevisionId}.`});return true}catch(error){const stale=error instanceof ManifoldArtifactAdmissionError&&error.staleHead;setAdmissionState(value=>({...value,pending:false,stale,message:error instanceof Error?error.message:"Admission failed safely."}));return false}};
 const state=owner.getState();const value=useMemo(()=>({state,admission:{authenticated,guest:guestEligible,eligible:authenticated||guestEligible,investigationId,operationalHeadId:head,eligibleNodeIds,pending:admissionState.pending,stale:admissionState.stale,message:admissionState.message,result:admissionState.result},save:()=>owner.save(runtime,authenticated),retry:()=>owner.save(runtime,authenticated),reloadHead:()=>owner.reloadHead(runtime),keepLocalDraft:()=>owner.keepLocalDraft(),listRevisions:()=>owner.listRevisions(),loadRevision:(id:string)=>owner.loadRevision(id),clearRevisionPreview:()=>owner.clearRevisionPreview(),inspectProjections:()=>owner.inspectProjections(),materializeManifoldArtifact:()=>owner.materializeManifoldArtifact(),inspectManifoldArtifact:()=>owner.inspectManifoldArtifact(),downloadManifoldArtifact:()=>owner.downloadManifoldArtifact(),closeManifoldInspector:()=>owner.closeManifoldInspector(),admitManifoldArtifact:admit,refreshAdmissionAuthority,viewAdmittedArtifact:()=>{const nodeId=admissionState.result?.receipt.admittedArtifactNodeId;if(!nodeId)return;workspace.navigateToMode(WorkspaceMode.MANIFOLD);workspace.setSelection({kind:"NODE",nodeId})}}),[admissionState,authenticated,eligibleNodeIds,guestEligible,head,investigationId,owner,runtime,state,workspace]);return <StudioSaveActionContext.Provider value={value}>{children}</StudioSaveActionContext.Provider>
}
