import type { ArtifactIdentity, AuthorRevision, FrozenResearchSourceSnapshot, SemanticDocument } from "../contracts/StudioV1Contract.ts";
import { canonicalSerialize, canonicalSha256, manifoldArtifactOutputHash, renderManifoldArtifactManifest } from "../contracts/StudioCanonicalSerialization.ts";
import type { AssembledStudioDraftingContext, StudioManifoldArtifactDraft } from "./StudioDraftingTypes.ts";

/** Adapts session-local drafting inputs to the canonical Studio V1 renderer inputs. */
export async function projectStudioManifoldArtifact(assembled: AssembledStudioDraftingContext): Promise<StudioManifoldArtifactDraft> {
  const context=assembled.context,artifactId=context.baseIdentity.artifactId??`local:${context.documentId}`,revisionId=context.baseIdentity.artifactVersionId??`local-r${context.baseIdentity.documentRuntimeRevision}`,revisionNumber=context.baseIdentity.artifactRevision??Math.max(1,context.baseIdentity.documentRuntimeRevision),principalId="local-studio-preview";
  const semanticContent:SemanticDocument={documentId:context.documentId,schemaVersion:"studio-author-semantic/v1",title:"Local Studio MANIFOLD_ARTIFACT preview",nodeOrder:context.researcherNotes.map(value=>value.nodeId),nodes:context.researcherNotes.map(value=>({id:value.nodeId,type:"RESEARCHER_NOTE",text:value.text})),citations:[],citationStyle:{style:"APA",styleVersion:"studio-v1-apa/1",locale:"en-US"},manifoldDeclarations:[]};
  const snapshots:FrozenResearchSourceSnapshot[]=context.sources.map(source=>{const content=canonicalSerialize(source.capturedRepresentation),representation={representationId:`${source.anchorId}:representation`,mediaType:source.captureMediaType,schemaVersion:source.captureSchemaVersion,content,contentHash:canonicalSha256(content)};const domain={snapshotId:source.anchorId,investigationId:context.investigationId,capturedAt:new Date(source.collectedAt).toISOString(),selectionScope:"EXPLICIT_SELECTION" as const,selectedAnchorIds:[source.anchorId],inboxMembershipBasis:"EXPLICIT_STABLE_IDENTITIES" as const,sources:[{anchorId:source.anchorId,classification:source.classification==="CANONICAL"?"CANONICAL" as const:"CANDIDATE" as const,availability:"AVAILABLE" as const,provenance:`${source.sourceWorkspace}:${source.sourceKind}:${source.sourceIdentity}`,sensitivity:{includeInAnalysis:true,includeInArtifact:true,citePublicly:false,anonymize:false,restrictedAppendix:false,excludeFromAiProcessing:true},representations:[representation]}],immutableStatus:"FROZEN" as const};return{...domain,snapshotHash:canonicalSha256(domain)};});
  const artifact:ArtifactIdentity={artifactId,investigationId:context.investigationId,authorPrincipalId:principalId,profile:"INVESTIGATION_REPORT",profileCapability:"ADMITTED_UNVERIFIED",lifecycleClassification:"AUTHOR_REVISION",createdAt:"1970-01-01T00:00:00.000Z",workingDraft:{state:"UNSAVED"}};
  const revision:AuthorRevision={artifactId,revisionId,revisionNumber,...(revisionNumber>1?{parentRevisionId:`local-parent-r${revisionNumber-1}`}:{ }),semanticContent,contentHash:canonicalSha256(semanticContent),sourceSnapshots:snapshots.map(value=>({snapshotId:value.snapshotId,snapshotHash:value.snapshotHash})),profile:"INVESTIGATION_REPORT",profileVersion:"investigation-report/v1",createdAt:"1970-01-01T00:00:00.000Z",authorPrincipalId:principalId,immutableStatus:"IMMUTABLE_SAVED_REVISION"};
  const projection=renderManifoldArtifactManifest(artifact,revision,snapshots,context.investigationId);
  return Object.freeze({kind:"MANIFOLD_ARTIFACT_DRAFT",schemaVersion:"studio-manifold-artifact-draft/v1",authorityState:"UNAPPLIED_LOCAL_PROJECTION",contextManifest:{...context,contextHash:assembled.contextHash,proposalEffect:"CREATES_UNAPPLIED_LOCAL_PROJECTION_ONLY" as const},projection,outputHash:manifoldArtifactOutputHash(projection)});
}

export function serializeStudioManifoldArtifact(value: StudioManifoldArtifactDraft): string { return canonicalSerialize(value.projection); }
