import { createEntityDossierRevision, createGovernedEntityDossier, entityDossierSha256 } from "./EntityDossierCanonicalization.ts";
import { ENTITY_DOSSIER_SCHEMA_VERSION, type EntityDossierFact, type EntityDossierFactSourceLink, type EntityDossierRelationshipFact, type EntityDossierRevision, type EntityDossierSourceRecord, type GovernedEntityDossier, type GovernedEntityDossierRegistryEntry } from "./EntityDossierTypes.ts";
import { USS_PRINCETON_OFFICIAL_SOURCE_EXTRACTS as SOURCES, USS_PRINCETON_SOURCE_RETRIEVED_AT as RETRIEVED_AT, type UssPrincetonOfficialSourceKey } from "./sources/uss-princeton/manifest.ts";
import { NIMITZ_TIC_TAC_EVENT_DOSSIER_REVISION_1, NIMITZ_TIC_TAC_EVENT_GOVERNED_DOSSIER, NIMITZ_TIC_TAC_EVENT_ID } from "./fixtures/nimitzTicTacEventDossier.ts";

const ENTITY_ID="system:entity:uss-princeton", DOSSIER_ID=`dossier:${ENTITY_ID}`, EVENT_ID="E-TICTAC-2004", UNKNOWN_TIME="1970-01-01T00:00:00.000Z";
const R1_ID=`dossier-revision:${ENTITY_ID}:1`, R2_ID=`dossier-revision:${ENTITY_ID}:2`, CANON_SOURCE_ID=`source:system-canon:${EVENT_ID}:revision:1`;
const canonSnapshot={source:"SYSTEM_CANON",sourceKind:"CANONICAL_FACILITY",sourceRevision:1,sourceTime:UNKNOWN_TIME,eventId:EVENT_ID,canonicalKnowledgeObjectId:ENTITY_ID,canonicalType:"ENTITY",facilityName:"USS Princeton",facilityType:"AEGIS RADAR",distance:"0km",inboundRelationship:{sourceId:`system:event:${EVENT_ID}`,relationshipType:"OBSERVED_AT",targetId:ENTITY_ID}} as const;

const oldFact=(factId:string,predicate:string,value:EntityDossierFact["value"]):EntityDossierFact=>({factId,subjectEntityId:ENTITY_ID,predicate,value,temporalQualification:{kind:"UNSPECIFIED",effectiveTime:UNKNOWN_TIME},geographicQualification:{state:"UNAVAILABLE"},derivation:"DIRECT_SOURCE",epistemicClassification:"OBSERVED",reviewStatus:"ACCEPTED",canonEffect:"GLOBAL_BASE",uncertainty:[],limitationIds:["limitation:system-canon-only"]});
const oldFacts=[oldFact("fact:uss-princeton:canonical-type","canonical_type",{valueType:"STRING",value:"ENTITY"}),oldFact("fact:uss-princeton:facility-type","facility_type",{valueType:"STRING",value:"AEGIS RADAR"}),oldFact("fact:uss-princeton:system-canon-distance","system_canon_distance",{valueType:"STRING",value:"0km"}),oldFact("fact:uss-princeton:source-revision","source_revision",{valueType:"INTEGER",value:1})] as const;
const eventFactId=`fact:uss-princeton:observed-at:${EVENT_ID}`;
const oldLinks:readonly EntityDossierFactSourceLink[]=[...oldFacts.map(f=>f.factId),eventFactId].map(factId=>({sourceLinkId:`link:${factId}:system-canon`,factId,sourceRecordId:CANON_SOURCE_ID,relationship:"SUPPORTS"}));

// I3A authority: do not add optional operational fields here. Its hash is a locked regression value.
const revision1=createEntityDossierRevision({dossierRevisionId:R1_ID,dossierId:DOSSIER_ID,revisionNumber:1,schemaVersion:ENTITY_DOSSIER_SCHEMA_VERSION,entityIdentity:{canonicalEntityId:ENTITY_ID,displayName:"USS Princeton",aliases:[],canonicalKnowledgeObjectId:ENTITY_ID,canonicalType:"ENTITY",entityType:"ENTITY",entitySubtype:"CANONICAL_FACILITY",identifiers:[]},scope:"GLOBAL_BASE",facts:oldFacts,relationshipFacts:[{factId:eventFactId,subjectEntityId:ENTITY_ID,relationshipType:"OBSERVED_AT",objectEntityId:`system:event:${EVENT_ID}`,direction:"INBOUND",temporalQualification:{kind:"DURING_EVENT",eventId:EVENT_ID,effectiveTime:UNKNOWN_TIME},geographicQualification:{state:"UNAVAILABLE"},derivation:"DIRECT_SOURCE",epistemicClassification:"OBSERVED",reviewStatus:"ACCEPTED",canonEffect:"GLOBAL_BASE",uncertainty:[],limitationIds:["limitation:system-canon-only"]}],sourceRecords:[{sourceRecordId:CANON_SOURCE_ID,authority:"System Canon",publisher:"System Canon",repositoryIdentity:`SYSTEM_CANON/${EVENT_ID}`,retrievalState:"NOT_APPLICABLE_LOCAL_CANON",retrievedAt:UNKNOWN_TIME,effectiveTime:UNKNOWN_TIME,snapshotIdentity:`SYSTEM_CANON/${EVENT_ID}/revision/1`,contentHash:entityDossierSha256(canonSnapshot),accessState:"LOCAL_CANON",retentionState:"SOURCE_CONTROLLED"}],sourceLinks:oldLinks,fieldAvailability:[{field:"aliases",state:"UNAVAILABLE"},{field:"carrierStrikeGroupMembership",state:"UNAVAILABLE"},{field:"commissioningHistory",state:"UNAVAILABLE"},{field:"crewOperationalHistory",state:"UNAVAILABLE"},{field:"encounterNarrative",state:"UNAVAILABLE"},{field:"geographicPosition",state:"UNAVAILABLE"},{field:"hullNumber",state:"UNAVAILABLE"},{field:"parentCommand",state:"UNAVAILABLE"},{field:"platformSpecification",state:"UNAVAILABLE"},{field:"shipClass",state:"UNAVAILABLE"},{field:"systemsCapabilities",state:"UNAVAILABLE"}],limitations:[{limitationId:"limitation:system-canon-only",code:"SYSTEM_CANON_FIELDS_ONLY"}],immutableState:"IMMUTABLE"});

const sourceRecord=(key:UssPrincetonOfficialSourceKey,sourceType:NonNullable<EntityDossierSourceRecord["sourceType"]>):EntityDossierSourceRecord=>{const s=SOURCES[key];return {sourceRecordId:s.sourceRecordId,authority:s.authority,publisher:s.publisher,locator:s.canonicalUrl,retrievalState:"RETRIEVED",retrievedAt:RETRIEVED_AT,...(s.publicationTime===undefined?{}:{publicationTime:s.publicationTime}),snapshotIdentity:`${s.sourceRecordId}/retained-factual-record/v1`,contentHash:entityDossierSha256(s.retainedFacts),accessState:"PUBLIC",retentionState:"SOURCE_CONTROLLED",sourceTitle:s.sourceTitle,sourceType,sourceRevisionLabel:s.sourceRevisionLabel,mediaType:"application/vnd.isees.retained-factual-record+json",authoritativeScope:s.authoritativeScope,lastVerifiedAt:RETRIEVED_AT,freshnessPolicy:"STABLE_REFERENCE"};};
const fact=(id:string,category:NonNullable<EntityDossierFact["category"]>,predicate:string,label:string,value:EntityDossierFact["value"],applicability:NonNullable<EntityDossierFact["applicability"]>,temporal:EntityDossierFact["temporalQualification"]={kind:"UNSPECIFIED",effectiveTime:UNKNOWN_TIME}):EntityDossierFact=>({factId:`fact:uss-princeton:r2:${id}`,subjectEntityId:ENTITY_ID,category,predicate,displayLabel:label,value,scope:"GLOBAL_BASE",applicability,temporalQualification:temporal,geographicQualification:{state:"UNAVAILABLE"},derivation:"DIRECT_SOURCE",epistemicClassification:"ESTABLISHED",reviewStatus:"ACCEPTED",canonEffect:"GLOBAL_BASE",conflictState:"NONE",uncertainty:[],limitationIds:["limitation:official-sources-only"],governingDossierRevisionId:R2_ID});
const facts=[
 fact("official-name","IDENTITY","official_name","Official name",{valueType:"STRING",value:"USS Princeton"},"SHIP_SPECIFIC"),
 fact("hull-number","IDENTIFIER","hull_number","Hull number",{valueType:"IDENTIFIER",scheme:"US_NAVY_HULL_CLASSIFICATION",value:"CG 59"},"SHIP_SPECIFIC"),
 fact("entity-category","CLASSIFICATION","entity_category","Entity category",{valueType:"STRING",value:"PLATFORM"},"SHIP_SPECIFIC"),
 fact("platform-category","CLASSIFICATION","platform_category","Platform category",{valueType:"STRING",value:"NAVAL_VESSEL"},"SHIP_SPECIFIC"),
 fact("vessel-type","CLASSIFICATION","vessel_type","Vessel type",{valueType:"STRING",value:"GUIDED_MISSILE_CRUISER"},"SHIP_SPECIFIC"),
 fact("ship-class","CLASSIFICATION","ship_class","Ship class",{valueType:"STRING",value:"TICONDEROGA_CLASS"},"SHIP_SPECIFIC"),
 fact("operator","ORGANIZATION","operator","Operator",{valueType:"STRING",value:"UNITED_STATES_NAVY"},"SHIP_SPECIFIC"),
 fact("builder","LIFECYCLE","builder","Builder",{valueType:"STRING",value:"INGALLS_SHIPBUILDING"},"SHIP_SPECIFIC"),
 fact("commissioned","LIFECYCLE","commissioned_date","Commissioned",{valueType:"DATE",value:"1989-02-11T00:00:00.000Z",precision:"DAY"},"SHIP_SPECIFIC",{kind:"AT_TIME",effectiveTime:"1989-02-11T00:00:00.000Z"}),
 fact("class-length","SPECIFICATION","class_length","Class length",{valueType:"NUMBER",value:567,unit:"feet"},"CLASS_LEVEL"),
 fact("class-beam","SPECIFICATION","class_beam","Class beam",{valueType:"NUMBER",value:55,unit:"feet"},"CLASS_LEVEL"),
 fact("class-displacement","SPECIFICATION","class_full_load_displacement","Class full-load displacement",{valueType:"NUMBER",value:9600,unit:"long tons"},"CLASS_LEVEL"),
 fact("class-speed","SPECIFICATION","class_speed","Class speed",{valueType:"STRING",value:"30+ knots"},"CLASS_LEVEL"),
 fact("class-propulsion","SPECIFICATION","class_propulsion","Class propulsion",{valueType:"STRING",value:"4 GE LM2500 gas turbine engines; 2 shafts; 80,000 total shaft horsepower"},"CLASS_LEVEL"),
 fact("aegis-system","SYSTEM","combat_system","Combat system",{valueType:"STRING",value:"AEGIS_COMBAT_SYSTEM"},"SHIP_SPECIFIC"),
 fact("spy-1b","SENSOR","radar_system","Radar system",{valueType:"STRING",value:"SPY-1B"},"SHIP_SPECIFIC"),
 fact("aegis-role","CAPABILITY","aegis_system_role","Aegis system role",{valueType:"STRING",value:"INTEGRATED_DETECT_IDENTIFY_ENGAGE_ARCHITECTURE"},"SYSTEM_LEVEL"),
 fact("mission-roles","CAPABILITY","documented_mission_roles","Documented mission roles",{valueType:"STRING",value:"ANTI_AIR; ANTISUBMARINE; SURFACE_STRIKE"},"SHIP_SPECIFIC"),
 fact("official-command-page","EXTERNAL_REFERENCE","official_reference","Official command page",{valueType:"URL_REFERENCE",value:SOURCES.commandAbout.canonicalUrl,url:SOURCES.commandAbout.canonicalUrl,displayName:SOURCES.commandAbout.sourceTitle},"SHIP_SPECIFIC"),
 fact("official-history-holdings","EXTERNAL_REFERENCE","official_history_reference","Official history holdings",{valueType:"URL_REFERENCE",value:SOURCES.nhhcHoldings.canonicalUrl,url:SOURCES.nhhcHoldings.canonicalUrl,displayName:"NHHC Princeton (CG-59) holdings"},"SHIP_SPECIFIC"),
] as const;
const keys:Record<string,readonly UssPrincetonOfficialSourceKey[]>={"official-name":["commandAbout"],"hull-number":["commandAbout","cruiserFactFile"],"entity-category":["commandAbout","cruiserFactFile"],"platform-category":["commandAbout","cruiserFactFile"],"vessel-type":["commandAbout","cruiserFactFile"],"ship-class":["commandAbout","cruiserFactFile"],operator:["commandAbout"],builder:["cruiserFactFile"],commissioned:["commandAbout"],"class-length":["cruiserFactFile"],"class-beam":["cruiserFactFile"],"class-displacement":["cruiserFactFile"],"class-speed":["cruiserFactFile"],"class-propulsion":["cruiserFactFile"],"aegis-system":["commandAbout","aegisSystem"],"spy-1b":["commandAbout"],"aegis-role":["aegisSystem"],"mission-roles":["commandAbout","cruiserFactFile"],"official-command-page":["commandAbout"],"official-history-holdings":["nhhcHoldings"]};
const links:EntityDossierFactSourceLink[]=facts.flatMap(f=>{const short=f.factId.split(":").at(-1)!;return keys[short].map(key=>{const s=SOURCES[key];return {sourceLinkId:`link:${f.factId}:${key}`,factId:f.factId,sourceRecordId:s.sourceRecordId,relationship:"SUPPORTS",citationLocator:s.citationLocator,extractedFragmentHash:entityDossierSha256(s.retainedFacts),governingDossierRevisionId:R2_ID};});});
const eventRelationship:EntityDossierRelationshipFact={factId:eventFactId,subjectEntityId:ENTITY_ID,category:"EVENT_ROLE",relationshipType:"OBSERVED_AT",displayLabel:"System Canon event relationship",objectEntityId:`system:event:${EVENT_ID}`,direction:"INBOUND",scope:"GLOBAL_BASE",applicability:"SHIP_SPECIFIC",temporalQualification:{kind:"DURING_EVENT",eventId:EVENT_ID,effectiveTime:UNKNOWN_TIME},geographicQualification:{state:"UNAVAILABLE"},derivation:"DIRECT_SOURCE",epistemicClassification:"OBSERVED",reviewStatus:"ACCEPTED",canonEffect:"GLOBAL_BASE",conflictState:"NONE",uncertainty:[{code:"SYSTEM_CANON_RELATIONSHIP_ONLY",detail:"No encounter narrative or sensor-performance claim is established by this relationship."}],limitationIds:["limitation:system-canon-event-edge-only"],governingDossierRevisionId:R2_ID};
const canonSource:EntityDossierSourceRecord={sourceRecordId:CANON_SOURCE_ID,authority:"System Canon",publisher:"System Canon",repositoryIdentity:`SYSTEM_CANON/${EVENT_ID}`,retrievalState:"NOT_APPLICABLE_LOCAL_CANON",retrievedAt:UNKNOWN_TIME,effectiveTime:UNKNOWN_TIME,snapshotIdentity:`SYSTEM_CANON/${EVENT_ID}/revision/1`,contentHash:entityDossierSha256(canonSnapshot),accessState:"LOCAL_CANON",retentionState:"SOURCE_CONTROLLED",sourceTitle:`System Canon ${EVENT_ID} revision 1`,sourceType:"LOCAL_CANON",sourceRevisionLabel:"System Canon revision 1",mediaType:"application/vnd.isees.system-canon+json",authoritativeScope:["Existing canonical graph identity and OBSERVED_AT relationship only"],freshnessPolicy:"STABLE_REFERENCE"};
links.push({sourceLinkId:`link:${eventFactId}:system-canon:r2`,factId:eventFactId,sourceRecordId:CANON_SOURCE_ID,relationship:"SUPPORTS",citationLocator:"canonical facility inboundRelationship",extractedFragmentHash:entityDossierSha256(canonSnapshot.inboundRelationship),governingDossierRevisionId:R2_ID});
const revision2=createEntityDossierRevision({dossierRevisionId:R2_ID,dossierId:DOSSIER_ID,revisionNumber:2,parentRevisionId:R1_ID,schemaVersion:ENTITY_DOSSIER_SCHEMA_VERSION,entityIdentity:{canonicalEntityId:ENTITY_ID,displayName:"USS Princeton",aliases:["USS Princeton (CG 59)","USS Princeton (CG-59)"],canonicalKnowledgeObjectId:ENTITY_ID,canonicalType:"ENTITY",entityType:"PLATFORM",entitySubtype:"NAVAL_VESSEL",identifiers:[{identifierId:"identifier:uss-princeton:us-navy-hull",scheme:"US_NAVY_HULL_CLASSIFICATION",value:"CG 59"}]},scope:"GLOBAL_BASE",facts,relationshipFacts:[eventRelationship],sourceRecords:[canonSource,sourceRecord("commandAbout","OFFICIAL_ENTITY_PAGE"),sourceRecord("cruiserFactFile","OFFICIAL_FACT_FILE"),sourceRecord("aegisSystem","OFFICIAL_FACT_FILE"),sourceRecord("nhhcHoldings","OFFICIAL_HISTORY")],sourceLinks:links,fieldAvailability:[{field:"carrierStrikeGroupMembershipCurrent",state:"NOT_ESTABLISHED"},{field:"currentCommandAssignment",state:"NOT_RESEARCHED"},{field:"currentContactDetails",state:"NOT_RESEARCHED"},{field:"currentDeployability",state:"NOT_ESTABLISHED"},{field:"decommissionedDate",state:"NOT_ESTABLISHED"},{field:"documentedLimitations",state:"NO_LIMITATION_DOCUMENTED"},{field:"encounterNarrativeNovember2004",state:"NOT_ESTABLISHED"},{field:"encounterRadarTracksNovember2004",state:"NOT_ESTABLISHED"},{field:"encounterSensorPerformanceNovember2004",state:"NOT_ESTABLISHED"},{field:"laidDownDate",state:"NOT_RESEARCHED"},{field:"launchedDate",state:"NOT_RESEARCHED"},{field:"researcherConfidenceScore",state:"UNAVAILABLE"},{field:"specificCrewActionsNovember2004",state:"NOT_ESTABLISHED"}],limitations:[{limitationId:"limitation:official-sources-only",code:"ONLY_REVIEWED_OFFICIAL_SOURCE_FACTS_ADMITTED"},{limitationId:"limitation:system-canon-event-edge-only",code:"EVENT_RELATIONSHIP_DOES_NOT_ESTABLISH_ENCOUNTER_NARRATIVE"}],immutableState:"IMMUTABLE"});

export const USS_PRINCETON_DOSSIER_REVISION_1=revision1;
export const USS_PRINCETON_DOSSIER_REVISION_2=revision2;
export const USS_PRINCETON_GOVERNED_ENTITY_DOSSIER=createGovernedEntityDossier({dossierId:DOSSIER_ID,schemaVersion:ENTITY_DOSSIER_SCHEMA_VERSION,canonicalEntityId:ENTITY_ID,scope:"GLOBAL_BASE",revisions:[revision1,revision2]});
export const USS_PRINCETON_PINNED_HEAD_REVISION_ID=R2_ID;
export const SYSTEM_CANON_ENTITY_DOSSIER_REGISTRY:Readonly<Record<string,GovernedEntityDossierRegistryEntry>>=Object.freeze({
 [ENTITY_ID]:Object.freeze({canonicalEntityId:ENTITY_ID,dossier:USS_PRINCETON_GOVERNED_ENTITY_DOSSIER,pinnedHeadRevisionId:R2_ID}),
 [NIMITZ_TIC_TAC_EVENT_ID]:Object.freeze({canonicalEntityId:NIMITZ_TIC_TAC_EVENT_ID,dossier:NIMITZ_TIC_TAC_EVENT_GOVERNED_DOSSIER,pinnedHeadRevisionId:NIMITZ_TIC_TAC_EVENT_DOSSIER_REVISION_1.dossierRevisionId}),
});
// I3C-A deliberately does not advance operational graph references. This
// compatibility view keeps the existing I3B singleton projection pinned to R1;
// I3C-B will adopt the explicit registry head through an authorized builder edit.
const OPERATIONAL_GRAPH_COMPATIBILITY_DOSSIER=createGovernedEntityDossier({dossierId:DOSSIER_ID,schemaVersion:ENTITY_DOSSIER_SCHEMA_VERSION,canonicalEntityId:ENTITY_ID,scope:"GLOBAL_BASE",revisions:[revision1]});
export function resolveSystemCanonEntityDossier(id:string):GovernedEntityDossier|undefined{return id===ENTITY_ID?OPERATIONAL_GRAPH_COMPATIBILITY_DOSSIER:SYSTEM_CANON_ENTITY_DOSSIER_REGISTRY[id]?.dossier;}
export function resolveSystemCanonEntityDossierRevision(id:string,revisionId:string):EntityDossierRevision|undefined{return revisionId.toLowerCase().includes("latest")?undefined:SYSTEM_CANON_ENTITY_DOSSIER_REGISTRY[id]?.dossier.revisions.find(r=>r.dossierRevisionId===revisionId);}
export function resolvePinnedSystemCanonEntityDossierRevision(id:string):EntityDossierRevision|undefined{const entry=SYSTEM_CANON_ENTITY_DOSSIER_REGISTRY[id];return entry===undefined?undefined:resolveSystemCanonEntityDossierRevision(id,entry.pinnedHeadRevisionId);}
