import { useId } from "react";

export function FrontierManifoldExplainer(){const id=useId().replace(/:/g,"");const title=`frontier-title-${id}`,desc=`frontier-desc-${id}`,arrow=`frontier-arrow-${id}`;return <figure className="frontier-diagram" aria-labelledby={title}><figcaption><strong>Begin at the edge of what is known.</strong><span>Diagrammatic explanation — not live investigation output.</span></figcaption><svg viewBox="0 0 360 520" role="img" aria-labelledby={`${title} ${desc}`} focusable="false"><title id={title}>Frontier Agent governed research expansion and return</title><desc id={desc}>A selected Manifold node or edge anchors a dashed outward Research Vector. A free proposal passes through explicit researcher authorization before Tavily discovery. Candidate Evidence stays outside the canonical Manifold, passes through researcher accept or reject review, and reaches deterministic Manifold recomputation only after governed acceptance.</desc><defs><marker id={arrow} viewBox="0 0 8 8" refX="7" refY="4" markerWidth="7" markerHeight="7" orient="auto"><path d="M0 0 8 4 0 8Z"/></marker></defs>
<g className="frontier-diagram__manifold"><text x="16" y="24">1 · CURRENT MANIFOLD</text><path d="M26 75 80 48 126 83 86 126 35 111Z M80 48 86 126 M26 75 126 83"/><circle cx="26" cy="75" r="6"/><circle className="frontier-diagram__selected" cx="80" cy="48" r="10"/><circle cx="126" cy="83" r="6"/><circle cx="86" cy="126" r="6"/><text x="16" y="148">Selected node or edge supplies context and scope</text></g>
<path className="frontier-diagram__vector" d="M92 48C160 26 211 45 254 76" markerEnd={`url(#${arrow})`}/><text x="156" y="38">2 · RESEARCH VECTOR</text>
<g className="frontier-diagram__box frontier-diagram__proposal"><rect x="198" y="68" width="146" height="56" rx="7"/><text x="271" y="90" textAnchor="middle">3 · FRONTIER PROPOSAL</text><text x="271" y="108" textAnchor="middle">Proposal creation is free</text></g>
<path className="frontier-diagram__path" d="M271 124V157" markerEnd={`url(#${arrow})`}/><g className="frontier-diagram__gate"><path d="M196 164H346M196 176H346"/><text x="271" y="198" textAnchor="middle">4 · RESEARCHER AUTHORIZATION GATE</text><text x="271" y="214" textAnchor="middle">No execution before explicit authorization</text></g>
<path className="frontier-diagram__path" d="M271 219V246" markerEnd={`url(#${arrow})`}/><g className="frontier-diagram__box frontier-diagram__tavily"><rect x="198" y="250" width="146" height="48" rx="7"/><text x="271" y="270" textAnchor="middle">5 · TAVILY DISCOVERY</text><text x="271" y="286" textAnchor="middle">approved live sources</text></g>
<path className="frontier-diagram__path" d="M271 298V329" markerEnd={`url(#${arrow})`}/><g className="frontier-diagram__box frontier-diagram__candidate"><rect x="175" y="333" width="169" height="58" rx="7"/><text x="259" y="354" textAnchor="middle">6 · CANDIDATE EVIDENCE</text><text x="259" y="372" textAnchor="middle">outside canonical membership</text></g>
<path className="frontier-diagram__path" d="M175 362H143" markerEnd={`url(#${arrow})`}/><g className="frontier-diagram__gate"><path d="M126 324V403M136 324V403"/><text x="116" y="420" textAnchor="middle">7 · ACCEPT / REJECT</text></g><path className="frontier-diagram__accepted" d="M126 382C91 419 75 438 75 461" markerEnd={`url(#${arrow})`}/><g className="frontier-diagram__box frontier-diagram__recompute"><rect x="16" y="465" width="208" height="42" rx="7"/><text x="120" y="483" textAnchor="middle">8 · DETERMINISTIC RECOMPUTATION</text><text x="120" y="499" textAnchor="middle">only after governed acceptance</text></g></svg><ul><li>Proposal creation is free.</li><li>No research executes before explicit authorization.</li><li>Candidate Evidence remains outside the canonical Manifold.</li><li>Recompute only after governed acceptance.</li></ul></figure>}

export function FrontierAgentExplanation(){return <article className="frontier-explainer"><h3>Begin at the edge of what is known.</h3><p>A Frontier Agent begins at a selected node with missing intelligence, a selected edge requiring validation, a contradiction, an unresolved similarity, a hypothesis, or an evidence gap. The selected node or edge supplies context and scope; the agent proposes a bounded research vector.</p><p>Proposal creation is free. It states the question, relevance, providers, searches, expected evidence, capabilities, limitations, maximum cost, and stop conditions. The researcher approves, modifies, rejects, or postpones it. No paid discovery begins before authorization.</p><p>REX conducts approved research. Tavily discovers live sources. Results return as Candidate Evidence outside the canonical Manifold. The researcher governs acceptance or rejection; deterministic recomputation occurs only after governed acceptance.</p><FrontierManifoldExplainer/><section className="frontier-explainer__prohibitions"><h4>Frontier Agents cannot independently</h4><ul><li>modify the Manifold;</li><li>promote Candidate Evidence;</li><li>add material to the Research Inbox;</li><li>resolve uncertainty as fact or change conclusions;</li><li>begin additional paid work; or</li><li>decide what evidence means.</li></ul></section><blockquote>The Manifold reveals the frontier. Frontier Agents propose the search. REX conducts the investigation. Tavily discovers the sources. The researcher governs what becomes knowledge.</blockquote><p className="frontier-explainer__cta">Select what you do not understand. Send a Frontier Agent beyond the known record. Bring the evidence back under your control.</p><p><strong>Present runtime:</strong> Frontier Agents do not execute; proposal and Authorization Envelope persistence do not exist.</p></article>}
