import { resolveApiBaseUrl } from "../api/ApiOrigin.ts";

export type RexTargetKind = "NODE" | "EDGE";
export type RexAssignmentLifecycle = "SLEEPING"|"ELIGIBLE"|"EXECUTING"|"SUSPENDED"|"EXPIRED"|"REVOKED"|"BUDGET_EXHAUSTED";
export interface RexAssignment { readonly assignmentId:string; readonly investigationId:string; readonly targetId:string; readonly targetKind:RexTargetKind; readonly lifecycle:RexAssignmentLifecycle; readonly currentRevisionId:string; readonly manifoldRevisionId:string; readonly manifoldRevisionHash:string; readonly createdAt:string; readonly updatedAt:string; readonly idempotencyDisposition:"CREATED"|"REPLAYED" }
export interface RexPreparation { readonly executionId:string; readonly jobId:string|null; readonly disposition:"EXECUTABLE"|"SUPPRESSED_DUPLICATE"; readonly semanticDuplicateStatus:"UNIQUE"|"SUPPRESSED"; readonly originalExecutionId:string|null; readonly authorizationDisposition:"ALLOW"; readonly estimatedMicros:number; readonly reservedMicros:number; readonly executionStatus:string }
export interface RexReceipt { readonly executionId:string; readonly jobId:string; readonly assignmentId:string; readonly assignmentRevisionId:string; readonly manifoldRevisionId:string; readonly manifoldRevisionHash:string; readonly sourceAdapterIdentity:string; readonly sourceAdapterVersion:string; readonly normalizerIdentity:string; readonly normalizerVersion:string; readonly candidateBundleId:string; readonly candidateContentHash:string; readonly sourceContentHash:string; readonly aiAssistanceStatus:"NONE"|"ASSISTED"; readonly providerIdentity:string; readonly modelIdentity:string; readonly estimatedMicros:number; readonly reservedMicros:number; readonly actualMicros:number; readonly chargedMicros:number; readonly releasedMicros:number; readonly terminalExecutionStatus:"COMPLETED"; readonly completedAt:string; readonly contentHash:string }
export interface RexFieldLineage { readonly candidateField:string; readonly sourceField:string; readonly exactValue:string; readonly normalizationRule:string }
export interface RexCandidateLineage { readonly candidateId:string; readonly sourceLocator:string; readonly sourceVersion:string; readonly fields:readonly RexFieldLineage[] }
export interface RexCandidateNode { readonly candidateId:string; readonly kind:string; readonly label:string; readonly claim:string; readonly candidateContentHash:string }
export interface RexCandidateEdge { readonly candidateId:string; readonly kind:string; readonly label:string; readonly sourceCandidateId:string; readonly targetCandidateId:string; readonly proposedRelationship:string; readonly candidateContentHash:string }
export interface RexCandidateBundle { readonly candidateBundleId:string; readonly investigationId:string; readonly assignmentRevisionId:string; readonly executionId:string; readonly manifoldRevisionId:string; readonly manifoldRevisionHash:string; readonly sourceLocator:string; readonly sourceVersion:string; readonly sourceClassification:string; readonly adapterIdentity:string; readonly adapterVersion:string; readonly normalizerIdentity:string; readonly normalizerVersion:string; readonly sourceContentHash:string; readonly candidateContentHash:string; readonly candidateClassification:"CANDIDATE_KNOWLEDGE"; readonly reviewStatus:"RESEARCHER_REVIEW_REQUIRED"; readonly canonEffect:"NONE"; readonly aiAssistanceStatus:"NONE"|"ASSISTED"; readonly providerIdentity:string; readonly modelIdentity:string; readonly modelClass:string; readonly nodes:readonly RexCandidateNode[]; readonly edges:readonly RexCandidateEdge[]; readonly fieldLineage:readonly RexCandidateLineage[] }
export interface RexCompletedDiscovery { readonly selectedSource:Readonly<{kind:RexTargetKind;identity:string}>; readonly assignmentId:string; readonly receipt:RexReceipt; readonly bundle:RexCandidateBundle }
export interface RexExpansionPlan { readonly plannerVersion:string; readonly profile:Readonly<{id:string;version:string}>; readonly objectivePacks:readonly Readonly<{id:string;version:string}>[]; readonly queryGuidance:readonly string[]; readonly governedContext:readonly string[]; readonly limits:readonly string[]; readonly stopRules:readonly string[] }
export interface RexExpansionProposal { readonly proposalId:string; readonly investigationId:string; readonly principalId:string; readonly selectedObject:Readonly<{kind:RexTargetKind;id:string}>; readonly revision:Readonly<{id:string;hash:string}>; readonly researcherQuestion:string; readonly researcherNotes:string|null; readonly plan:RexExpansionPlan; readonly proposedQueryPlan:readonly string[]; readonly limits:readonly string[]; readonly stopRules:readonly string[]; readonly inspectionWork:readonly string[]; readonly status:"PROPOSAL_ONLY"; readonly createdAt:string; readonly costEnvelope:Readonly<{status:"PLANNING_ONLY";providerComponent:"UNAVAILABLE";iseesMargin:"UNAVAILABLE";maximumCustomerPrice:"UNAVAILABLE";customerCharge:string}>; readonly effects:Readonly<Record<string,"NONE">>; readonly idempotencyDisposition?:"CREATED"|"REPLAYED" }
export interface RexExpansionProposalRequest { readonly targetId:string; readonly targetKind:RexTargetKind; readonly operationalRevisionId:string; readonly operationalRevisionHash:string; readonly researcherQuestion:string; readonly researcherNotes:string|null }

export class RexClientError extends Error { readonly code:string; readonly status?:number; constructor(code:string, message:string, status?:number) { super(message); this.name="RexClientError"; this.code=code; this.status=status; } }
type Fetch = typeof fetch;
type RecordValue = Record<string,unknown>;
const isRecord=(value:unknown):value is RecordValue=>value!==null&&typeof value==="object"&&!Array.isArray(value);
const record=(value:unknown):RecordValue=>{if(!isRecord(value))throw new Error();return value};
const text=(value:unknown):string=>{if(typeof value!=="string"||!value.trim())throw new Error();return value};
const number=(value:unknown):number=>{if(typeof value!=="number"||!Number.isFinite(value))throw new Error();return value};
const one=<T extends string>(value:unknown, values:readonly T[]):T=>{const v=text(value);for(const allowed of values)if(v===allowed)return allowed;throw new Error()};
const iso=(value:unknown):string=>{const v=text(value);if(!Number.isFinite(Date.parse(v)))throw new Error();return v};
const hash=(value:unknown):string=>{const v=text(value);if(!/^sha256:[0-9a-f]{64}$/.test(v))throw new Error();return v};
const exact=(value:RecordValue,keys:readonly string[]):void=>{const actual=Object.keys(value);if(actual.length!==keys.length||actual.some(key=>!keys.includes(key)))throw new Error()};

function assignment(value:unknown):RexAssignment { const v=record(value); exact(v,["assignmentId","investigationId","targetId","targetKind","lifecycle","currentRevisionId","createdAt","updatedAt","idempotencyDisposition","manifoldRevisionId","manifoldRevisionHash"]); return Object.freeze({assignmentId:text(v.assignmentId),investigationId:text(v.investigationId),targetId:text(v.targetId),targetKind:one(v.targetKind,["NODE","EDGE"]),lifecycle:one(v.lifecycle,["SLEEPING","ELIGIBLE","EXECUTING","SUSPENDED","EXPIRED","REVOKED","BUDGET_EXHAUSTED"]),currentRevisionId:text(v.currentRevisionId),manifoldRevisionId:text(v.manifoldRevisionId),manifoldRevisionHash:hash(v.manifoldRevisionHash),createdAt:iso(v.createdAt),updatedAt:iso(v.updatedAt),idempotencyDisposition:one(v.idempotencyDisposition,["CREATED","REPLAYED"])}); }
function preparation(value:unknown):RexPreparation { const v=record(value), job=v.jobId===null?null:text(v.jobId), original=v.originalExecutionId===null?null:text(v.originalExecutionId); return Object.freeze({executionId:text(v.executionId),jobId:job,disposition:one(v.disposition,["EXECUTABLE","SUPPRESSED_DUPLICATE"]),semanticDuplicateStatus:one(v.semanticDuplicateStatus,["UNIQUE","SUPPRESSED"]),originalExecutionId:original,authorizationDisposition:one(v.authorizationDisposition,["ALLOW"]),estimatedMicros:number(v.estimatedMicros),reservedMicros:number(v.reservedMicros),executionStatus:text(v.executionStatus)}); }
function receiptValue(value:unknown):RexReceipt { const v=record(value); return Object.freeze({executionId:text(v.executionId),jobId:text(v.jobId),assignmentId:text(v.assignmentId),assignmentRevisionId:text(v.assignmentRevisionId),manifoldRevisionId:text(v.manifoldRevisionId),manifoldRevisionHash:hash(v.manifoldRevisionHash),sourceAdapterIdentity:text(v.sourceAdapterIdentity),sourceAdapterVersion:text(v.sourceAdapterVersion),normalizerIdentity:text(v.normalizerIdentity),normalizerVersion:text(v.normalizerVersion),candidateBundleId:text(v.candidateBundleId),candidateContentHash:hash(v.candidateContentHash),sourceContentHash:hash(v.sourceContentHash),aiAssistanceStatus:one(v.aiAssistanceStatus,["NONE","ASSISTED"]),providerIdentity:text(v.providerIdentity),modelIdentity:text(v.modelIdentity),estimatedMicros:number(v.estimatedMicros),reservedMicros:number(v.reservedMicros),actualMicros:number(v.actualMicros),chargedMicros:number(v.chargedMicros),releasedMicros:number(v.releasedMicros),terminalExecutionStatus:one(v.terminalExecutionStatus,["COMPLETED"]),completedAt:iso(v.completedAt),contentHash:hash(v.contentHash)}); }
function bundle(value:unknown):RexCandidateBundle { const v=record(value); if(!Array.isArray(v.nodes)||!Array.isArray(v.edges)||!Array.isArray(v.fieldLineage))throw new Error(); const nodes=v.nodes.map(raw=>{const n=record(raw);return Object.freeze({candidateId:text(n.candidateId),kind:text(n.kind),label:text(n.label),claim:text(n.claim),candidateContentHash:hash(n.candidateContentHash)})}); const edges=v.edges.map(raw=>{const e=record(raw);return Object.freeze({candidateId:text(e.candidateId),kind:text(e.kind),label:text(e.label),sourceCandidateId:text(e.sourceCandidateId),targetCandidateId:text(e.targetCandidateId),proposedRelationship:text(e.proposedRelationship),candidateContentHash:hash(e.candidateContentHash)})}); const fieldLineage=v.fieldLineage.map(raw=>{const l=record(raw);if(!Array.isArray(l.fields))throw new Error();return Object.freeze({candidateId:text(l.candidateId),sourceLocator:text(l.sourceLocator),sourceVersion:text(l.sourceVersion),fields:Object.freeze(l.fields.map(rawField=>{const f=record(rawField);return Object.freeze({candidateField:text(f.candidateField),sourceField:text(f.sourceField),exactValue:text(f.exactValue),normalizationRule:text(f.normalizationRule)})}))})}); return Object.freeze({candidateBundleId:text(v.candidateBundleId),investigationId:text(v.investigationId),assignmentRevisionId:text(v.assignmentRevisionId),executionId:text(v.executionId),manifoldRevisionId:text(v.manifoldRevisionId),manifoldRevisionHash:hash(v.manifoldRevisionHash),sourceLocator:text(v.sourceLocator),sourceVersion:text(v.sourceVersion),sourceClassification:text(v.sourceClassification),adapterIdentity:text(v.adapterIdentity),adapterVersion:text(v.adapterVersion),normalizerIdentity:text(v.normalizerIdentity),normalizerVersion:text(v.normalizerVersion),sourceContentHash:hash(v.sourceContentHash),candidateContentHash:hash(v.candidateContentHash),candidateClassification:one(v.candidateClassification,["CANDIDATE_KNOWLEDGE"]),reviewStatus:one(v.reviewStatus,["RESEARCHER_REVIEW_REQUIRED"]),canonEffect:one(v.canonEffect,["NONE"]),aiAssistanceStatus:one(v.aiAssistanceStatus,["NONE","ASSISTED"]),providerIdentity:text(v.providerIdentity),modelIdentity:text(v.modelIdentity),modelClass:text(v.modelClass),nodes:Object.freeze(nodes),edges:Object.freeze(edges),fieldLineage:Object.freeze(fieldLineage)}); }
function completedDiscoveries(value:unknown):readonly RexCompletedDiscovery[] { const v=record(value); if(!Array.isArray(v.discoveries))throw new Error(); return Object.freeze(v.discoveries.map(raw=>{const d=record(raw),selected=record(d.selectedSource);return Object.freeze({selectedSource:Object.freeze({kind:one(selected.kind,["NODE","EDGE"]),identity:text(selected.identity)}),assignmentId:text(d.assignmentId),receipt:receiptValue(d.receipt),bundle:bundle(d.bundle)})})); }
function proposal(value:unknown):RexExpansionProposal { const v=record(value),selected=record(v.selectedObject),revision=record(v.revision),cost=record(v.costEnvelope),effects=record(v.effects),rawPlan=record(v.plan),profile=record(rawPlan.profile); const strings=(x:unknown)=>{if(!Array.isArray(x)||x.some(item=>typeof item!=="string"||!item.trim()))throw new Error();return Object.freeze([...x])}; if(Object.values(effects).some(x=>x!=="NONE")||!Array.isArray(rawPlan.objectivePacks))throw new Error(); const plan=Object.freeze({plannerVersion:text(rawPlan.plannerVersion),profile:Object.freeze({id:text(profile.id),version:text(profile.version)}),objectivePacks:Object.freeze(rawPlan.objectivePacks.map(item=>{const pack=record(item);return Object.freeze({id:text(pack.id),version:text(pack.version)})})),queryGuidance:strings(rawPlan.queryGuidance),governedContext:strings(rawPlan.governedContext),limits:strings(rawPlan.limits),stopRules:strings(rawPlan.stopRules)}); return Object.freeze({proposalId:text(v.proposalId),investigationId:text(v.investigationId),principalId:text(v.principalId),selectedObject:Object.freeze({kind:one(selected.kind,["NODE","EDGE"]),id:text(selected.id)}),revision:Object.freeze({id:text(revision.id),hash:hash(revision.hash)}),researcherQuestion:text(v.researcherQuestion),researcherNotes:v.researcherNotes===null?null:String(v.researcherNotes),plan,proposedQueryPlan:strings(v.proposedQueryPlan),limits:strings(v.limits),stopRules:strings(v.stopRules),inspectionWork:strings(v.inspectionWork),status:one(v.status,["PROPOSAL_ONLY"]),createdAt:iso(v.createdAt),costEnvelope:Object.freeze({status:one(cost.status,["PLANNING_ONLY"]),providerComponent:one(cost.providerComponent,["UNAVAILABLE"]),iseesMargin:one(cost.iseesMargin,["UNAVAILABLE"]),maximumCustomerPrice:one(cost.maximumCustomerPrice,["UNAVAILABLE"]),customerCharge:text(cost.customerCharge)}),effects:Object.freeze(Object.fromEntries(Object.entries(effects).map(([k])=>[k,"NONE" as const]))),...(v.idempotencyDisposition===undefined?{}:{idempotencyDisposition:one(v.idempotencyDisposition,["CREATED","REPLAYED"])})}); }

function csrf(source:()=>string):string { const pair=source().split(";").map(x=>x.trim()).find(x=>x.startsWith("isees_csrf=")); if(!pair)throw new RexClientError("CSRF_TOKEN_MISSING","The secure researcher session could not be verified.",403); try{const value=decodeURIComponent(pair.slice("isees_csrf=".length));if(!value)throw 0;return value}catch{throw new RexClientError("CSRF_TOKEN_INVALID","The secure researcher session could not be verified.",403)} }
export interface RexApi { createProposal(investigationId:string,request:RexExpansionProposalRequest,signal?:AbortSignal):Promise<RexExpansionProposal>; getProposal(investigationId:string,proposalId:string,signal?:AbortSignal):Promise<RexExpansionProposal>; createAssignment(investigationId:string,targetId:string,targetKind:RexTargetKind,signal?:AbortSignal):Promise<RexAssignment>; prepare(investigationId:string,assignment:RexAssignment,signal?:AbortSignal):Promise<RexPreparation>; execute(investigationId:string,jobId:string,signal?:AbortSignal):Promise<RexReceipt>; getReceipt(investigationId:string,executionId:string,signal?:AbortSignal):Promise<RexReceipt>; getBundle(investigationId:string,bundleId:string,signal?:AbortSignal):Promise<RexCandidateBundle>; listCompletedDiscoveries(investigationId:string,signal?:AbortSignal):Promise<readonly RexCompletedDiscovery[]> }
export function createRexApi(options:{fetch?:Fetch;baseUrl?:string;cookieSource?:()=>string}={}):RexApi { const transport=options.fetch??fetch, base=resolveApiBaseUrl(options.baseUrl), cookies=options.cookieSource??(()=>document.cookie); const call=async<T>(path:string,decode:(x:unknown)=>T,init:RequestInit):Promise<T>=>{let response:Response;try{response=await transport(`${base}${path}`,{...init,credentials:"include",redirect:"error"})}catch{throw new RexClientError("NETWORK_FAILURE","The REX repository could not be reached.")};let body:unknown;try{body=await response.json()}catch{throw new RexClientError("MALFORMED_RESPONSE","REX returned an invalid response.",response.status)}if(!response.ok){const e=record(body).error;try{const detail=record(e);throw new RexClientError(text(detail.code),text(detail.message),response.status)}catch(error){if(error instanceof RexClientError)throw error;throw new RexClientError("REX_REQUEST_FAILED","REX could not complete the governed request.",response.status)}}try{return decode(body)}catch{throw new RexClientError("MALFORMED_RESPONSE","REX returned an invalid response.",response.status)}}; const path=(i:string,s:string)=>`/api/v1/investigations/${encodeURIComponent(i)}/rex${s}`; const post=<T>(i:string,s:string,decode:(x:unknown)=>T,payload?:unknown,signal?:AbortSignal)=>call(path(i,s),decode,{method:"POST",headers:{"Content-Type":"application/json","X-ISEES-CSRF":csrf(cookies)},...(payload===undefined?{}:{body:JSON.stringify(payload)}),signal}); return Object.freeze({createProposal:(i:string,r:RexExpansionProposalRequest,s?:AbortSignal)=>post(i,"/proposals",proposal,r,s),getProposal:(i:string,p:string,s?:AbortSignal)=>call(path(i,`/proposals/${encodeURIComponent(p)}`),proposal,{method:"GET",signal:s}),createAssignment:(i:string,t:string,k:RexTargetKind,s?:AbortSignal)=>post(i,"/assignments",assignment,{targetId:t,targetKind:k,objective:`Search outward from selected ${k.toLocaleLowerCase()} ${t} using the governed local fixture.`},s),prepare:(i:string,a:RexAssignment,s?:AbortSignal)=>post(i,"/execution-preparations",preparation,{assignmentId:a.assignmentId,manifoldRevisionId:a.manifoldRevisionId,manifoldRevisionHash:a.manifoldRevisionHash},s),execute:async(i:string,j:string,s?:AbortSignal)=>{const envelope=await post(i,`/jobs/${encodeURIComponent(j)}/executions`,record,undefined,s);return receiptValue(envelope.receipt)},getReceipt:(i:string,e:string,s?:AbortSignal)=>call(path(i,`/executions/${encodeURIComponent(e)}/receipt`),receiptValue,{method:"GET",signal:s}),getBundle:(i:string,b:string,s?:AbortSignal)=>call(path(i,`/candidate-bundles/${encodeURIComponent(b)}`),bundle,{method:"GET",signal:s}),listCompletedDiscoveries:(i:string,s?:AbortSignal)=>call(path(i,"/completed-discoveries"),completedDiscoveries,{method:"GET",signal:s})}); }
