import { useRef, useState } from "react";
import { useOperatorIdentity } from "../identity/runtime/OperatorIdentityRuntimeContext.tsx";
import { resolveCoherentInvestigationSelection } from "../intelligence/selection/InvestigationSelectionCoherence.ts";
import { useKnowledgeObjects } from "../knowledge/runtime/KnowledgeObjectRuntimeContext.tsx";
import { useResearchBridge } from "../research/ResearchBridgeContext.tsx";
import type { RexResearchDiscoveryAnchor } from "../research/researchBridgeTypes.ts";
import { useWorkspaceRuntime } from "../workspace/runtime/WorkspaceRuntimeContext.tsx";
import { createRexApi, RexClientError, type RexApi, type RexTargetKind } from "./RexApi.ts";
import { publishRexDiscoveriesAtomically } from "./RexResearchInboxProjection.ts";

export type RexProgress="READY"|"PREPARING"|"EXECUTING"|"COMPLETED"|"FAILED";
const safeFailure=(error:unknown):string=>{const code=error instanceof RexClientError?error.code:"REX_REQUEST_FAILED"; const messages:Record<string,string>={AUTHENTICATION_REQUIRED:"Authentication is required for REX discovery.",INVESTIGATION_NOT_FOUND:"This investigation is not owned or is unavailable.",REX_NOT_FOUND:"The governed REX execution is unavailable or already terminal.",REX_AUTHORIZATION_DENIED:"REX authorization was denied.",REX_BUDGET_EXCEEDED:"The governed REX budget is unavailable.",REX_CIRCUIT_BREAKER_OPEN:"REX is paused by a circuit breaker.",SOURCE_ADAPTER_FAILED:"The local fixture execution failed safely.",CANDIDATE_NORMALIZATION_FAILED:"The local fixture result could not be normalized safely.",NETWORK_FAILURE:"The REX repository is unavailable.",REX_REPOSITORY_UNAVAILABLE:"The REX repository is unavailable."};return messages[code]??"REX could not complete the governed request. Existing Research Inbox entries were preserved."};

export function RexExploreControl({api=createRexApi()}:{readonly api?:RexApi}) {
  const workspace=useWorkspaceRuntime(), identity=useOperatorIdentity(), knowledge=useKnowledgeObjects(), research=useResearchBridge();
  const investigation=workspace.getActiveInvestigation();
  const selection=resolveCoherentInvestigationSelection(investigation,knowledge,workspace.getSelection());
  const target=selection?.kind==="NODE"?{kind:"NODE" as RexTargetKind,identity:selection.nodeId}:selection?.kind==="EDGE"?{kind:"EDGE" as RexTargetKind,identity:selection.edgeId}:undefined;
  const authenticated=identity.identity?.kind==="ACCOUNT"&&identity.persistence==="PERSISTENT";
  const owned=authenticated&&investigation?.createdBy==="AUTHENTICATED_RESEARCHER";
  const governed=Boolean(investigation?.currentRevisionId&&target);
  const [progress,setProgress]=useState<RexProgress>("READY"),[message,setMessage]=useState("Ready for explicit governed discovery."),[summary,setSummary]=useState<string>(),[completedTarget,setCompletedTarget]=useState<string>();
  const running=useRef(false);
  const unavailable=!authenticated?"REX discovery requires a saved researcher investigation.":!owned?"REX requires an authenticated investigation owned by the current researcher.":!governed?"Select a governed MANIFOLD node or edge to explore.":undefined;
  const targetKey=investigation&&target?`${investigation.id}:${target.kind}:${target.identity}`:undefined;
  const restored=Boolean(target&&investigation&&research.getDesk().entries.some(entry=>{if(entry.anchor.sourceWorkspace!=="REX"||!("rexDiscovery" in entry.anchor))return false;const discovery=(entry.anchor as RexResearchDiscoveryAnchor).rexDiscovery;return discovery.investigationId===investigation.id&&discovery.selectedSource.kind===target.kind&&discovery.selectedSource.identity===target.identity}));
  const effectiveProgress:RexProgress=restored||(progress==="COMPLETED"&&completedTarget===targetKey)?"COMPLETED":progress==="PREPARING"||progress==="EXECUTING"?progress:"READY";
  const effectiveMessage=restored?"COMPLETED · Governed discoveries are already present in Research Inbox.":effectiveProgress==="READY"?"Ready for explicit governed discovery.":message;
  async function explore(){if(running.current||unavailable||!investigation||!target)return;running.current=true;const capturedRevision=investigation.currentRevisionId,capturedTarget=target,capturedTargetKey=`${investigation.id}:${target.kind}:${target.identity}`;setProgress("PREPARING");setMessage("PREPARING · Creating or retrieving the governed assignment.");setSummary(undefined);try{const assignment=await api.createAssignment(investigation.id,target.identity,target.kind);setMessage("PREPARING · Applying eligibility, authorization, duplicate, circuit-breaker, and zero-cost budget gates.");const prepared=await api.prepare(investigation.id,assignment);let receipt;if(prepared.disposition==="SUPPRESSED_DUPLICATE"){setMessage("PREPARING · Governed duplicate found; retrieving the original completed result.");receipt=await api.getReceipt(investigation.id,prepared.originalExecutionId??prepared.executionId)}else{if(!prepared.jobId)throw new RexClientError("REX_NOT_FOUND","The governed job is unavailable.");setProgress("EXECUTING");setMessage("EXECUTING · Running the durable local zero-cost fixture job.");receipt=await api.execute(investigation.id,prepared.jobId)}const bundle=await api.getBundle(investigation.id,receipt.candidateBundleId);const currentInvestigation=workspace.getActiveInvestigation(),currentSelection=resolveCoherentInvestigationSelection(currentInvestigation,knowledge,workspace.getSelection());const currentTarget=currentSelection?.kind==="NODE"?currentSelection.nodeId:currentSelection?.kind==="EDGE"?currentSelection.edgeId:undefined;if(currentInvestigation?.id!==investigation.id||currentInvestigation.currentRevisionId!==capturedRevision||currentTarget!==capturedTarget.identity)throw new RexClientError("STALE_SELECTION","The selection changed before REX publication completed.");const publication=publishRexDiscoveriesAtomically(research,{investigationId:investigation.id,selectedSource:capturedTarget,assignmentId:receipt.assignmentId,receipt,bundle});setCompletedTarget(capturedTargetKey);setProgress("COMPLETED");setMessage(publication.added===0?"COMPLETED · These governed discoveries are already present in Research Inbox.":"COMPLETED · Added to Research Inbox.");setSummary(`${bundle.nodes.length} candidate node${bundle.nodes.length===1?"":"s"} · ${bundle.edges.length} candidate edge${bundle.edges.length===1?"":"s"} · Source ${bundle.sourceClassification} · AI assistance ${bundle.aiAssistanceStatus} · zero-cost fixture · Receipt ${receipt.contentHash.slice(7,19)}`)}catch(error){setProgress("FAILED");setMessage(safeFailure(error))}finally{running.current=false}}
  return <section className="selection-intelligence__section rex-explore" aria-label="REX discovery"><h2 className="selection-intelligence__section-title">REX Discovery</h2><p>Search outward from this selected node or edge. Results remain Candidate Knowledge and require researcher review.</p><button type="button" disabled={Boolean(unavailable)||running.current} onClick={()=>void explore()}>Explore with REX</button><div className={`rex-explore__status rex-explore__status--${effectiveProgress.toLocaleLowerCase()}`} role="status" aria-live="polite"><strong>{effectiveProgress}</strong><span>{unavailable??effectiveMessage}</span>{summary&&!restored&&<span>{summary}</span>}{effectiveProgress==="COMPLETED"&&<span>Candidate Knowledge · Researcher Review Required · Canon Effect: None</span>}</div></section>;
}
