import { RESEARCH_ANCHOR_SCHEMA_VERSION, type RexResearchDiscoveryAnchor } from "../research/researchBridgeTypes.ts";
import { migrateResearchAnchor, researchAnchorId } from "../research/ResearchAnchorContract.ts";
import type { ResearchBridgeRuntime } from "../research/ResearchBridgeRuntime.ts";
import type { RexCandidateBundle, RexReceipt, RexTargetKind } from "./RexApi.ts";

export interface RexPublicationInput { readonly investigationId:string; readonly selectedSource:Readonly<{kind:RexTargetKind;identity:string}>; readonly assignmentId:string; readonly receipt:RexReceipt; readonly bundle:RexCandidateBundle }
export function createRexDiscoveryAnchors(input:RexPublicationInput):readonly RexResearchDiscoveryAnchor[] {
  const {bundle,receipt}=input;
  if(bundle.investigationId!==input.investigationId||bundle.executionId!==receipt.executionId||bundle.candidateBundleId!==receipt.candidateBundleId||bundle.assignmentRevisionId!==receipt.assignmentRevisionId||bundle.sourceContentHash!==receipt.sourceContentHash||bundle.candidateContentHash!==receipt.candidateContentHash)throw new Error("REX result lineage does not match its governed receipt.");
  const candidates=[...bundle.nodes.map(node=>({candidateId:node.candidateId,candidateKind:"NODE" as const,candidateLabel:node.label,candidateContentHash:node.candidateContentHash})),...bundle.edges.map(edge=>({candidateId:edge.candidateId,candidateKind:"EDGE" as const,candidateLabel:edge.label,candidateContentHash:edge.candidateContentHash,proposedRelationship:edge.proposedRelationship,proposedEndpoints:{sourceCandidateId:edge.sourceCandidateId,targetCandidateId:edge.targetCandidateId}}))];
  return Object.freeze(candidates.map(candidate=>{
    const lineage=bundle.fieldLineage.find(item=>item.candidateId===candidate.candidateId);
    if(!lineage||lineage.fields.length===0)throw new Error("REX candidate field lineage is incomplete.");
    const anchorId=researchAnchorId(input.investigationId,"EVIDENCE_RECORD",bundle.candidateBundleId,candidate.candidateId,receipt.contentHash);
    const rexDiscovery=Object.freeze({investigationId:input.investigationId,selectedSource:input.selectedSource,assignmentId:input.assignmentId,assignmentRevisionId:receipt.assignmentRevisionId,executionId:receipt.executionId,receiptContentHash:receipt.contentHash,candidateBundleId:bundle.candidateBundleId,candidateId:candidate.candidateId,candidateKind:candidate.candidateKind,candidateLabel:candidate.candidateLabel,...("proposedRelationship" in candidate?{proposedRelationship:candidate.proposedRelationship,proposedEndpoints:candidate.proposedEndpoints}:{}),sourceLocator:bundle.sourceLocator,sourceVersion:bundle.sourceVersion,sourceClassification:bundle.sourceClassification,sourceContentHash:bundle.sourceContentHash,candidateContentHash:candidate.candidateContentHash,fieldLineage:lineage.fields,epistemicClassification:bundle.candidateClassification,reviewStatus:bundle.reviewStatus,canonEffect:bundle.canonEffect,aiAssistanceStatus:bundle.aiAssistanceStatus,providerIdentity:bundle.providerIdentity,modelIdentity:bundle.modelIdentity,adapterIdentity:bundle.adapterIdentity,adapterVersion:bundle.adapterVersion,normalizerIdentity:bundle.normalizerIdentity,normalizerVersion:bundle.normalizerVersion,createdAt:receipt.completedAt,completedAt:receipt.completedAt});
    return migrateResearchAnchor(Object.freeze({schemaVersion:RESEARCH_ANCHOR_SCHEMA_VERSION,kind:"EVIDENCE_RECORD",anchorId,investigationId:input.investigationId,sourceWorkspace:"REX",sourceIdentity:`${candidate.candidateKind}:${candidate.candidateId}`,collectedAt:new Date(receipt.completedAt),createdAt:new Date(receipt.completedAt),classification:"UNDETERMINED",sourceRevisionId:bundle.manifoldRevisionId,sourceExecutionId:receipt.executionId,sourceProjectionId:bundle.candidateBundleId,display:Object.freeze({title:`Candidate ${candidate.candidateKind.toLocaleLowerCase()}: ${candidate.candidateLabel}`,summary:"Candidate Knowledge · Researcher Review Required · Canon Effect: None"}),insertability:Object.freeze({state:"INSPECTION_ONLY",reason:"REX discoveries require researcher review and do not create accepted relationships."}),capturedRepresentation:Object.freeze({schemaVersion:"rex-research-anchor/v1",mediaType:"application/json",value:rexDiscovery}),pinned:false,evidence:Object.freeze({identity:candidate.candidateId,representation:rexDiscovery}),rexDiscovery})) as RexResearchDiscoveryAnchor;
  }));
}
export function publishRexDiscoveriesAtomically(runtime:ResearchBridgeRuntime,input:RexPublicationInput){const anchors=createRexDiscoveryAnchors(input);const result=runtime.createAnchorsAtomically(anchors);return Object.freeze({...result,anchors});}
