import { useEffect, useMemo, useState } from "react";
import { useAuthorDocument, useAuthorDocumentRevision } from "../../author/runtime/AuthorDocumentRuntimeContext";
import type { AuthorNode } from "../../author/model/AuthorNodeTypes";
import { useOperatorIdentity } from "../../identity/runtime/OperatorIdentityRuntimeContext";
import { researchBridgeRuntime } from "../../research/ResearchBridgeRuntime";
import { useActiveInvestigation } from "../../workspace/runtime/WorkspaceRuntimeContext";
import { studioApi } from "../api/StudioApi";
import { STUDIO_ARTIFACT_DESIGNS } from "../drafting/StudioArtifactDesigns";
import { StudioDraftingRuntime } from "../drafting/StudioDraftingRuntime";
import { STUDIO_DRAFTING_LIMITS } from "../drafting/StudioDraftingTypes";
import "./StudioDraftingPanel.css";

function noteText(node: AuthorNode): string | undefined { const value = node as unknown as { text?: unknown; citation?: unknown }; return typeof value.text === "string" ? value.text : typeof value.citation === "string" ? value.citation : undefined; }
const concise = (value: string) => value.length > 180 ? `${value.slice(0, 177)}…` : value;

export default function StudioDraftingPanel() {
  const investigation = useActiveInvestigation(); const operator = useOperatorIdentity(); const document = useAuthorDocument(); const documentRevision = useAuthorDocumentRevision();
  const [runtime] = useState(() => new StudioDraftingRuntime(studioApi));
  const [, render] = useState(0); const [researchRevision, setResearchRevision] = useState(researchBridgeRuntime.getRevision());
  useEffect(() => runtime.subscribe(() => render(value => value + 1)), [runtime]);
  useEffect(() => researchBridgeRuntime.subscribe(() => setResearchRevision(researchBridgeRuntime.getRevision())), []);
  const projection = useMemo(() => { void researchRevision; return researchBridgeRuntime.projectInvestigation({ investigationId: investigation?.id, pinnedFirst: false }); }, [investigation?.id, researchRevision]);
  const scope = useMemo(() => investigation && operator.identity ? { investigationId: investigation.id, principalId: operator.identity.operatorId } : undefined, [investigation, operator.identity]);
  useEffect(() => { runtime.updateEnvironment({ scope, document, documentRuntimeRevision: documentRevision, researchRevision, researchProjection: projection }); }, [runtime, scope, document, documentRevision, researchRevision, projection]);
  const state = runtime.getState();
  const eligible = projection.entries.filter(({ anchor }) => anchor.insertability.state === "INSERTABLE" && anchor.classification !== "UNDETERMINED");
  const ineligible = projection.entries.filter(({ anchor }) => anchor.insertability.state !== "INSERTABLE" || anchor.classification === "UNDETERMINED");
  const notes = (document?.nodes ?? []).map((node, order) => ({ node, order, text: noteText(node) })).filter(item => item.node.type !== "REFERENCE" && item.text !== undefined);
  const selectedSourceCount = state.sourceSelectionMode === "ALL" ? eligible.length : state.selectedSourceAnchorIds.length;
  const manifest = state.assembled;

  return <aside className="studio-drafting" aria-label="Artifact Drafting">
    <header className="studio-drafting__header"><div><span>STUDIO / PREPARATION</span><h2>Artifact Drafting</h2></div><strong className={`studio-drafting__status studio-drafting__status--${state.status.toLowerCase()}`}>{state.status.replaceAll("_", " ")}</strong></header>
    <p className="studio-drafting__message" role={["GENERATION_FAILED", "STALE"].includes(state.status) ? "alert" : "status"} aria-live="polite">{state.message}</p>
    <section className="studio-drafting__card"><h3>1. Research sources</h3><p>Drafting selection is transient and does not change the Research Inbox.</p>
      <fieldset className="studio-drafting__modes"><legend>Source-selection mode</legend><label><input type="radio" name="draft-source-mode" checked={state.sourceSelectionMode === "SUBSET"} onChange={() => runtime.setSourceSelectionMode("SUBSET")} /> SUBSET <small>include only checked eligible sources</small></label><label><input type="radio" name="draft-source-mode" checked={state.sourceSelectionMode === "ALL"} onChange={() => runtime.setSourceSelectionMode("ALL")} /> ALL <small>include every eligible source in the full Investigation projection, independent of Inbox filters</small></label></fieldset>
      <div className="studio-drafting__counts"><span>{eligible.length} eligible</span><span>{selectedSourceCount} selected</span><span>{ineligible.length} excluded</span></div>
      {state.sourceSelectionMode === "SUBSET" && <div className="studio-drafting__bulk"><button type="button" onClick={() => runtime.selectAllEligibleSources()}>Select eligible sources</button><button type="button" onClick={() => runtime.clearSelectedSources()}>Clear selected sources</button></div>}
      <div className="studio-drafting__choice-list">{projection.entries.map(({ anchor }) => { const isEligible = anchor.insertability.state === "INSERTABLE" && anchor.classification !== "UNDETERMINED"; const reason = anchor.classification === "UNDETERMINED" ? "Classification is UNDETERMINED." : anchor.insertability.state === "INSPECTION_ONLY" ? anchor.insertability.reason : undefined; return <label key={anchor.anchorId} className={!isEligible ? "is-ineligible" : ""}><input type="checkbox" disabled={!isEligible || state.sourceSelectionMode === "ALL"} checked={isEligible && (state.sourceSelectionMode === "ALL" || state.selectedSourceAnchorIds.includes(anchor.anchorId))} onChange={event => runtime.setSourceSelected(anchor.anchorId, event.target.checked)} /><span><strong>{anchor.display.title}</strong><small>{anchor.sourceWorkspace} · {anchor.kind.replaceAll("_", " ")} · {anchor.classification.replaceAll("_", " ")}</small><em>{anchor.sourceIdentity}</em>{reason && <b>Excluded: {reason}</b>}</span></label>; })}</div>
    </section>
    <section className="studio-drafting__card"><h3>2. Researcher notes</h3><p>Selected prose guides drafting; it is not evidence. References are never listed here.</p>{!document ? <p className="studio-drafting__blocker">No active .author document. Create or restore a draft in the author editor.</p> : <><div className="studio-drafting__counts"><span>{state.selectedResearcherNoteNodeIds.length} selected</span><span>{notes.length} eligible</span></div><div className="studio-drafting__choice-list">{notes.map(({ node, order, text }) => <label key={node.id}><input type="checkbox" checked={state.selectedResearcherNoteNodeIds.includes(node.id)} onChange={event => runtime.setNoteSelected(node.id, event.target.checked)} /><span><strong>{node.type.replaceAll("_", " ")}{"section" in node && typeof node.section === "string" ? ` · ${node.section}` : ""}</strong><small>Document position {order + 1}</small><em title={text}>{concise(text!)}</em></span></label>)}</div></>}</section>
    <section className="studio-drafting__card"><h3>3. Artifact design</h3><label className="studio-drafting__field">Predefined design<select value={`${state.design.designId}@${state.design.designVersion}`} onChange={event => { const design = STUDIO_ARTIFACT_DESIGNS.find(item => `${item.designId}@${item.designVersion}` === event.target.value); if (design) runtime.setDesign(design); }}>{STUDIO_ARTIFACT_DESIGNS.map(design => <option key={design.designId} value={`${design.designId}@${design.designVersion}`}>{design.label} · v{design.designVersion}</option>)}</select></label><p>{state.design.purpose}</p><ol>{state.design.sectionPlan.map(section => <li key={section}>{section}</li>)}</ol><p><strong>Guidance:</strong> {state.design.draftingGuidance}</p><p><strong>Provenance:</strong> {state.design.provenanceExpectations}</p></section>
    <section className="studio-drafting__card"><h3>4. Drafting instructions</h3><label className="studio-drafting__field">Researcher instructions <small>Guides composition; never treated as evidence.</small><textarea value={state.draftingInstruction} aria-invalid={state.draftingInstruction.length > STUDIO_DRAFTING_LIMITS.maxInstructionChars} onChange={event => runtime.setDraftingInstruction(event.target.value)} /></label><div className="studio-drafting__counter">{state.draftingInstruction.length} / {STUDIO_DRAFTING_LIMITS.maxInstructionChars} characters</div></section>
    <section className="studio-drafting__card"><h3>5. Exact context manifest</h3><dl className="studio-drafting__manifest"><dt>Investigation</dt><dd>{investigation?.id ?? "Unavailable"}</dd><dt>Active document</dt><dd>{document?.identity.id ?? "Unavailable"}</dd><dt>Captured revision</dt><dd>{manifest?.context.baseIdentity.documentRuntimeRevision ?? documentRevision}</dd><dt>Selection mode</dt><dd>{manifest?.context.sourceSelectionMode ?? state.sourceSelectionMode}</dd><dt>Sources</dt><dd>{manifest ? `${manifest.context.sources.length} selected / ${eligible.length} eligible / ${manifest.context.excludedSources.length} excluded` : `${selectedSourceCount} selected / ${eligible.length} eligible / ${ineligible.length} excluded`}</dd><dt>Researcher notes</dt><dd>{manifest?.context.researcherNotes.length ?? state.selectedResearcherNoteNodeIds.length}</dd><dt>Design</dt><dd>{state.design.label} · v{state.design.designVersion}</dd><dt>Context hash</dt><dd className="studio-drafting__hash">{manifest?.contextHash ?? "Pending valid deterministic context"}</dd><dt>Instructions</dt><dd>{state.draftingInstruction ? `Present · ${state.draftingInstruction.length} characters` : "Missing · blocker"}</dd><dt>Proposal effect</dt><dd>Generated content remains an UNAPPLIED DRAFT and cannot change the document.</dd></dl><p className={manifest ? "studio-drafting__ready" : "studio-drafting__blocker"}>{manifest ? "Validation passed; no blockers." : state.message}</p>
      <div className="studio-drafting__actions"><button type="button" className="is-primary" disabled={!manifest || state.status === "GENERATING"} onClick={() => void runtime.generate()}>{state.proposal || state.preservedProposal ? "Regenerate" : "Generate Draft"}</button>{state.status === "GENERATING" && <button type="button" onClick={() => runtime.cancel()}>Cancel generation</button>}</div>
    </section>
    {(state.proposal || state.preservedProposal) && <section className="studio-drafting__card studio-drafting__proposal"><header><div><span>UNAPPLIED DRAFT</span><h3>{state.design.label}</h3></div><strong>{state.status.replaceAll("_", " ")}</strong></header>{(() => { const proposal = state.proposal ?? state.preservedProposal!; return <><dl className="studio-drafting__manifest"><dt>Proposal</dt><dd>{proposal.proposalId}</dd><dt>Provider / model</dt><dd>{proposal.providerId || "Not supplied"} / {proposal.modelId || "Not supplied"}</dd><dt>Context hash</dt><dd className="studio-drafting__hash">{proposal.contextHash}</dd><dt>Base document</dt><dd>{proposal.documentId} · r{proposal.baseIdentity.documentRuntimeRevision}</dd><dt>Generated</dt><dd>{new Date(proposal.generatedAt).toLocaleString()}</dd></dl><div className="studio-drafting__blocks">{proposal.blocks.map(block => <article key={block.blockId}><small>{block.blockType}{block.section ? ` · ${block.section}` : ""}</small><p>{block.text}</p><div>{block.sourceReferences.length ? block.sourceReferences.map(reference => <span key={`${reference.anchorId}:${reference.relationship}`}>{reference.relationship}: {reference.anchorId}</span>) : <span>No source references declared</span>}</div></article>)}</div>{(["warnings", "uncertaintyDisclosures", "contradictionDisclosures", "unsupportedClaimDisclosures"] as const).map(key => <div className="studio-drafting__disclosures" key={key}><h4>{key.replace(/([A-Z])/g, " $1")}</h4>{proposal[key].length ? <ul>{proposal[key].map((item, index) => <li key={`${key}:${index}`}>{item}</li>)}</ul> : <p>None declared.</p>}</div>)}</>; })()}<p className="studio-drafting__boundary">This proposal has not changed the .author document.</p><div className="studio-drafting__actions"><button type="button" className="is-primary" disabled={!manifest || state.status === "GENERATING"} onClick={() => void runtime.generate()}>Regenerate</button><button type="button" className="is-danger" onClick={() => runtime.discard()}>Discard unapplied draft</button></div></section>}
  </aside>;
}
