import { useEffect, useMemo, useRef, useState } from "react";
import type { ManifoldArtifactManifest, ManifoldDeclaration } from "../contracts/StudioV1Contract.ts";
import { useStudioSaveAction } from "../runtime/StudioSaveActionContext.ts";
import { MANIFOLD_DECLARATION_LABELS, summarizeManifoldArtifact } from "./StudioManifoldArtifactSemantics.ts";

const Fields=({items}:{items:readonly [string,string|number][]})=><dl className="studio-manifest__facts">{items.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>;
type Proposal=Extract<ManifoldDeclaration,{declarationType:"PROPOSED_RELATIONSHIP"}>;
const endpoint=(proposal:Proposal,side:"subject"|"object")=>`${proposal[side].kind}:${proposal[side].identity}`;
export function StudioManifoldArtifactInspector({manifest,projectionId,outputHash,onClose}:{readonly manifest:ManifoldArtifactManifest;readonly projectionId:string;readonly outputHash:string;readonly onClose:()=>void}){
 const dialog=useRef<HTMLDivElement>(null),confirm=useRef<HTMLDivElement>(null),status=useRef<HTMLParagraphElement>(null);const actions=useStudioSaveAction();
 const [selected,setSelected]=useState<readonly string[]>([]),[confirming,setConfirming]=useState(false),[commandKey,setCommandKey]=useState<string>();
 useEffect(()=>{dialog.current?.focus();const key=(event:KeyboardEvent)=>{if(event.key==="Escape"){if(confirming)setConfirming(false);else onClose()}};document.addEventListener("keydown",key);return()=>document.removeEventListener("keydown",key)},[confirming,onClose]);
 useEffect(()=>{if(confirming)confirm.current?.focus()},[confirming]);useEffect(()=>{if(actions.admission.message)status.current?.focus()},[actions.admission.message]);
 const summary=summarizeManifoldArtifact(manifest),counts=summary.declarations,proposals=manifest.declarations.filter((item):item is Proposal=>item.declarationType==="PROPOSED_RELATIONSHIP"),eligibleIds=useMemo(()=>new Set(actions.admission.eligibleNodeIds),[actions.admission.eligibleNodeIds]);
 const eligibility=(proposal:Proposal)=>{const invalid=[proposal.subject,proposal.object].find(ref=>!(ref.kind==="ARTIFACT"&&ref.identity==="$ADMITTED_ARTIFACT")&&!eligibleIds.has(ref.identity));return invalid?`Endpoint ${invalid.kind}:${invalid.identity} is unresolved in the current operational head.`:undefined};
 const toggle=(id:string,checked:boolean)=>setSelected(value=>checked?[...value,id]:value.filter(item=>item!==id));
 const begin=()=>{setCommandKey(globalThis.crypto?.randomUUID?.()??`admission-${Date.now()}-${projectionId}`);setConfirming(true)};
 const submit=async()=>{const key=commandKey!;setConfirming(false);await actions.admitManifoldArtifact(projectionId,selected,key,manifest,outputHash)};
 const admitted=actions.admission.result?.receipt.projectionId===projectionId?actions.admission.result:undefined;
 return <div className="studio-manifest__backdrop"><div ref={dialog} className="studio-manifest" role="dialog" aria-modal="true" aria-labelledby="studio-manifest-title" tabIndex={-1}>
  <header><div><span>READ-ONLY · CONTRACT VALIDATED</span><h2 id="studio-manifest-title">MANIFOLD ARTIFACT manifest</h2></div><button type="button" className="studio-inspector__button" onClick={onClose}>Close</button></header>
  <p className="studio-manifest__boundary">{admitted?"Admitted to Manifold":"Projected · Not admitted to Manifold"}. No prose parsing or AI interpretation occurred.</p>
  <section><h3>Identity</h3><Fields items={[["Target investigation",actions.admission.investigationId??manifest.source.investigationId],["Current operational head",actions.admission.operationalHeadId??"No operational revision"],["Kind",manifest.kind],["Schema version",manifest.schemaVersion],["Projection ID",projectionId],["Source artifact ID",manifest.source.artifactId],["Source document ID",manifest.source.documentId],["Source revision",`${manifest.source.revisionId} · revision ${manifest.source.revisionNumber}`],["Source content hash",manifest.source.contentHash],["Output hash",outputHash]]}/></section>
  <section><h3>Proposed relationships</h3>{proposals.length===0?<p>No proposed relationships. Admission will add only the artifact node.</p>:<ul className="studio-manifest__proposals">{proposals.map(proposal=>{const reason=eligibility(proposal);return <li key={proposal.declarationId}><label><input type="checkbox" checked={selected.includes(proposal.declarationId)} disabled={Boolean(reason)||actions.admission.pending||Boolean(admitted)} onChange={event=>toggle(proposal.declarationId,event.currentTarget.checked)}/><span><strong>{proposal.predicate}</strong> · {endpoint(proposal,"subject")} → {endpoint(proposal,"object")}<br/><code>{proposal.declarationId}</code> · {proposal.proposalState} / qualified declaration</span></label>{reason&&<p className="studio-inspector__disabled-reason">{reason}</p>}</li>})}</ul>}<p>Unselected proposals remain declarations in the artifact and do not become Manifold edges.</p></section>
  {!actions.admission.eligible&&!admitted&&<section><h3>Admission unavailable</h3><p>Projection admission requires an unambiguous active owned or disposable guest investigation.</p></section>}
  {actions.admission.eligible&&!admitted&&<section><button type="button" className="studio-inspector__button studio-inspector__button--primary" disabled={actions.admission.pending||actions.admission.stale||proposals.some(proposal=>Boolean(eligibility(proposal)))} onClick={begin}>ADMIT &amp; RECOMPUTE</button>{proposals.some(proposal=>Boolean(eligibility(proposal)))&&<p className="studio-inspector__disabled-reason">Admission is unavailable because every proposed relationship must resolve against the active operational head.</p>}{actions.admission.stale&&actions.admission.authenticated&&<button type="button" className="studio-inspector__button" onClick={()=>void actions.refreshAdmissionAuthority()}>REFRESH AND REVIEW</button>}</section>}
  {confirming&&<div className="studio-manifest__confirmation" role="alertdialog" aria-modal="true" aria-labelledby="admission-confirm-title" ref={confirm} tabIndex={-1}><h3 id="admission-confirm-title">Confirm admission and recomputation</h3><Fields items={[["Artifact identity",manifest.source.artifactId],["Projection identity",projectionId],["Active investigation",actions.admission.investigationId??"Unavailable"],["Proposed node types","ARTIFACT × 1"],["Proposed edge types",selected.length?proposals.filter(item=>selected.includes(item.declarationId)).map(item=>item.predicate).sort().join(", "):"None selected"],["Proposed edge count",selected.length],["Provenance / source-anchor count",summary.sourceAnchors],["Validation status","PASS · schema, integrity, lineage, active head, and endpoints"],["Expected canonical effect",`One immutable graph revision; 1 node and ${selected.length} edge${selected.length===1?"":"s"}`]]}/>{actions.admission.guest&&<p><strong>Guest working copy only ? Library canon will not be changed ? Nothing will be saved.</strong></p>}<p>Admission will mutate and deterministically recompute the active investigation Manifold.</p>{selected.length?<ul>{[...selected].sort().map(id=><li key={id}><code>{id}</code></li>)}</ul>:<p>No relationship declarations are selected.</p>}<p>No declaration is automatically promoted to truth. Tavily, REX, web discovery, Candidate Evidence, AI drafting, external APIs, Research Inbox publication, and billing will not run.</p><button type="button" className="studio-inspector__button studio-inspector__button--primary" disabled={actions.admission.pending} onClick={()=>void submit()}>CONFIRM ADMIT &amp; RECOMPUTE</button><button type="button" className="studio-inspector__button" disabled={actions.admission.pending} onClick={()=>{setConfirming(false);dialog.current?.focus()}}>Cancel</button></div>}
  <p ref={status} role="status" aria-live="polite" tabIndex={-1}>{actions.admission.message}</p>
  {admitted&&<section><h3>Admission receipt</h3><Fields items={[["Receipt identity",admitted.receipt.receiptId],["Admitted node identity",admitted.receipt.admittedArtifactNodeId],["Resulting operational revision",admitted.receipt.resultingOperationalRevisionId],["Created relationship count",admitted.receipt.createdRelationshipIds.length],["Replay status",admitted.replayed?"REPLAYED":"ORIGINAL COMMIT"]]}/><button type="button" className="studio-inspector__button studio-inspector__button--primary" onClick={actions.viewAdmittedArtifact}>VIEW IN MANIFOLD</button></section>}
  <section><h3>Contents</h3><Fields items={[["Frozen snapshot count",summary.frozenSnapshots],["Research Inbox / source-anchor count",summary.sourceAnchors],["Source Knowledge reference count",summary.sourceKnowledge],["Evidence / citation reference count",summary.evidenceAndCitations],["Accepted relationship-reference count",summary.acceptedRelationships],["Normalized provenance count",summary.normalizedProvenance],["Total declaration count",summary.totalDeclarations]]}/></section>
  <section><h3>Declaration breakdown</h3><Fields items={Object.entries(MANIFOLD_DECLARATION_LABELS).map(([type,label])=>[label,counts[type]??0])}/></section>
  <section><h3>Authority</h3><Fields items={[["Canon Effect",manifest.canonEffect],["REX execution","NONE"],["Tavily execution","NONE"]]}/></section>
 </div></div>
}
