/* eslint-disable react-refresh/only-export-components -- verifier-facing pure presentation helpers intentionally share this owner. */
import { useEffect, useId, useLayoutEffect, useRef, useState, type CSSProperties, type KeyboardEvent, type ReactNode, type Ref } from "react";
import { createPortal } from "react-dom";
import { assessContextualRelevance, type IntelligenceContextFacts } from "./ContextualRelevance";
import type { EvaluatedMathematicalSnapshot } from "./EquationDocumentationTypes";
import { evaluateIntelligenceDensity, type DensityCandidate } from "./IntelligenceDensityPolicy";
import type { IntelligenceRegistry } from "./IntelligenceRegistry";
import type { IntelligenceDefinition } from "./MetricIntelligenceTypes";
import type { MetricMathematicsRegistryEntry } from "./MetricMathematicsRegistry";
import type { VisibleMathematics } from "./MetricExplanationContract";

export interface ContextualIntelligenceBinding { readonly registry: IntelligenceRegistry; readonly definitionId: string; readonly context: IntelligenceContextFacts; readonly competingCandidates?: readonly DensityCandidate[]; }
export interface ContextualIntelligenceContent { readonly definition: string; readonly interpretation?: string; readonly notice: string; readonly inclusionRules?: readonly string[]; readonly exclusionRules?: readonly string[]; readonly provenance?: readonly string[]; readonly sourceReferences?: readonly string[]; readonly briefingTemplateValues?: Readonly<Record<string, string>>; readonly epistemicClassification: string; readonly evaluatedSnapshot?: EvaluatedMathematicalSnapshot; readonly mathematics?: MetricMathematicsRegistryEntry; readonly visibleMathematics?: VisibleMathematics; }
interface Props { readonly binding: ContextualIntelligenceBinding; readonly content: ContextualIntelligenceContent; readonly children?: ReactNode; readonly badge?: ReactNode; readonly actions?: ReactNode; }

const REGISTERED_TEMPLATE_TOKEN = /\{([A-Za-z][A-Za-z0-9]*)\}/g;

export function evaluateBriefingTemplate(template: string, values: Readonly<Record<string, string>> = {}): string {
  const evaluated = template.replace(REGISTERED_TEMPLATE_TOKEN, (token, name: string) => {
    if (!Object.prototype.hasOwnProperty.call(values, name)) throw new Error(`Missing registered briefing template value: ${token}`);
    return values[name];
  });
  if (REGISTERED_TEMPLATE_TOKEN.test(evaluated)) throw new Error(`Unresolved registered briefing template token in: ${evaluated}`);
  return evaluated;
}

export function deduplicateDisplayedSourceReferences(sourceReferences: readonly string[]): readonly string[] {
  return [...new Set(sourceReferences)];
}

export function ContextualIntelligenceTrigger({ binding, content, children, badge, actions }: Props) {
  const definition = binding.registry.getDefinition(binding.definitionId);
  if (!definition) return null;
  const assessment = assessContextualRelevance(definition, binding.context);
  const candidates = [...(binding.competingCandidates ?? []), { surfaceId: binding.context.surfaceId, assessment }];
  const decision = evaluateIntelligenceDensity(candidates).find(item => item.surfaceId === binding.context.surfaceId && item.definitionId === definition.definitionId);
  if (!decision || (decision.visibility !== "PRIMARY" && decision.visibility !== "SECONDARY")) return null;
  const mathematics = content.mathematics ?? (definition.mathematicsAuthorityIdentity ? binding.registry.getMathematics(definition.mathematicsAuthorityIdentity) : undefined);
  return <RegisteredTrigger definition={definition} content={mathematics ? {...content, mathematics} : content} badge={badge} actions={actions}>{children}</RegisteredTrigger>;
}

function RegisteredTrigger({ definition, content, children, badge, actions }: Omit<Props, "binding"> & { definition: IntelligenceDefinition }) {
  const id = useId().replace(/:/g, ""); const trigger = useRef<HTMLButtonElement>(null); const briefing = useRef<HTMLDivElement>(null); const dialog = useRef<HTMLDivElement>(null);
  const openTimer = useRef<number | undefined>(undefined); const closeTimer = useRef<number | undefined>(undefined); const [briefingOpen,setBriefingOpen]=useState(false); const [deepDiveOpen,setDeepDiveOpen]=useState(false); const [position,setPosition]=useState<CSSProperties>();
  const clearTimers=()=>{if(openTimer.current)clearTimeout(openTimer.current);if(closeTimer.current)clearTimeout(closeTimer.current);};
  const openBriefingLater=()=>{clearTimers();openTimer.current=window.setTimeout(()=>setBriefingOpen(true),350);};
  const closeBriefingLater=()=>{clearTimers();closeTimer.current=window.setTimeout(()=>setBriefingOpen(false),120);};
  const openDeepDive=()=>{clearTimers();setBriefingOpen(false);setDeepDiveOpen(true);};
  const closeDeepDive=()=>{setDeepDiveOpen(false);window.setTimeout(()=>trigger.current?.focus(),0);};
  const onKeyDown=(event:KeyboardEvent<HTMLButtonElement>)=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();openDeepDive();}else if(event.key==="Escape"){event.preventDefault();setBriefingOpen(false);}};
  useEffect(()=>()=>clearTimers(),[]);
  useLayoutEffect(()=>{if(!briefingOpen)return;const place=()=>{const anchor=trigger.current?.getBoundingClientRect(),tip=briefing.current?.getBoundingClientRect();if(!anchor||!tip)return;const margin=8,gap=8,left=Math.min(Math.max(margin,anchor.left),Math.max(margin,window.innerWidth-tip.width-margin));const top=anchor.bottom+gap+tip.height+margin<=window.innerHeight?anchor.bottom+gap:anchor.top-tip.height-gap;setPosition({left,top:Math.max(margin,top)});};place();window.addEventListener("resize",place);window.addEventListener("scroll",place,true);return()=>{window.removeEventListener("resize",place);window.removeEventListener("scroll",place,true);};},[briefingOpen]);
  useEffect(()=>{if(!deepDiveOpen)return;dialog.current?.focus();const key=(event:globalThis.KeyboardEvent)=>{if(event.key==="Escape"){event.preventDefault();closeDeepDive();return;}if(event.key==="Tab"&&dialog.current){const nodes=[...dialog.current.querySelectorAll<HTMLElement>('button,[href],input,select,textarea,[tabindex]:not([tabindex="-1"])')];if(!nodes.length)return;const first=nodes[0]!,last=nodes[nodes.length-1]!;if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key);},[deepDiveOpen]);
  const kind=definition.intelligenceKind==="METRIC"?"metric":"term";
  return <span className="contextual-intelligence"><button ref={trigger} type="button" className="contextual-intelligence__trigger" aria-label={`Explain ${kind}: ${definition.label}`} aria-describedby={briefingOpen?`${id}-briefing`:undefined} aria-haspopup="dialog" onPointerEnter={openBriefingLater} onPointerLeave={closeBriefingLater} onFocus={()=>setBriefingOpen(true)} onBlur={event=>{if(!briefing.current?.contains(event.relatedTarget as Node))setBriefingOpen(false);}} onClick={openDeepDive} onKeyDown={onKeyDown}>{children}<span className="contextual-intelligence__glyph" aria-hidden="true">i</span></button>{badge}{briefingOpen&&createPortal(<ContextualIntelligenceBriefing ref={briefing} id={`${id}-briefing`} definition={definition} content={content} style={position} onPointerEnter={clearTimers} onPointerLeave={closeBriefingLater}/>,document.body)}{deepDiveOpen&&createPortal(<div className="contextual-intelligence__backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)closeDeepDive();}}><ContextualIntelligenceDeepDive ref={dialog} id={id} definition={definition} content={content} actions={actions} onClose={closeDeepDive}/></div>,document.body)}</span>;
}

export function ContextualIntelligenceBriefing({id,definition,content,style,onPointerEnter,onPointerLeave,ref}:{id:string;definition:IntelligenceDefinition;content:ContextualIntelligenceContent;style?:CSSProperties;onPointerEnter:()=>void;onPointerLeave:()=>void;ref:Ref<HTMLDivElement>}){const conciseBriefing=evaluateBriefingTemplate(definition.briefing.conciseTemplate,content.briefingTemplateValues);return <div ref={ref} id={id} role="tooltip" className="contextual-intelligence__briefing" style={style} onPointerEnter={onPointerEnter} onPointerLeave={onPointerLeave}><strong>{definition.label}</strong><p>{conciseBriefing}</p><p><b>Why here:</b> {definition.whyItMatters[0]}</p><p><b>Notice:</b> {content.notice}</p><span>{content.epistemicClassification}</span></div>;}

export function ContextualIntelligenceDeepDive({id,definition,content,actions,onClose,ref}:{id:string;definition:IntelligenceDefinition;content:ContextualIntelligenceContent;actions?:ReactNode;onClose:()=>void;ref:Ref<HTMLDivElement>}){const displayedSourceReferences=content.sourceReferences?deduplicateDisplayedSourceReferences(content.sourceReferences):undefined;const math=content.mathematics;return <div ref={ref} role="dialog" aria-modal="true" aria-labelledby={`${id}-title`} tabIndex={-1} className="contextual-intelligence__dialog"><header><div><span>{definition.intelligenceKind} INTELLIGENCE</span><h2 id={`${id}-title`}>{definition.label}</h2>{math&&<p className="contextual-intelligence__badges"><b>{math.authorityClassification}</b><b>{math.equationStatus}</b></p>}</div><button type="button" className="contextual-intelligence__instrument-button contextual-intelligence__close-button" onClick={onClose} aria-label={`Close ${definition.label} intelligence`}>Close</button></header><div className="contextual-intelligence__body"><section><h3>Meaning</h3>{math&&<><h4>Research question</h4><p>{math.researchQuestion}</p></>}<p>{content.definition}</p>{content.interpretation&&<><h4>Interpretation</h4><p>{content.interpretation}</p></>}<h4>Why it matters</h4>{definition.whyItMatters.map(x=><p key={x}>{x}</p>)}<h4>What to notice</h4><p>{content.notice}</p></section>{math?<RegisteredMathematics entry={math} visible={content.visibleMathematics}/>:<MathematicalDeepDiveSection definition={definition} snapshot={content.evaluatedSnapshot}/>}<section><h3>Philosophy and limits</h3>{math&&<p className="contextual-intelligence__philosophy">{math.philosophyOfUse}</p>}<ul>{math?.epistemicBoundaries.map(x=><li key={x}>{x}</li>)??content.exclusionRules?.map(x=><li key={x}>{x}</li>)}</ul></section><section><h3>Authority and provenance</h3><dl><dt>Registry identity</dt><dd>{math?.identity??"Not registered"}</dd><dt>Authority</dt><dd>{math?.authorityClassification??content.epistemicClassification}</dd><dt>Equation status</dt><dd>{math?.equationStatus??definition.mathematicalDocumentationStatus.status}</dd><dt>Semantic producer</dt><dd>{definition.semanticProducer.id}@{definition.semanticProducer.version}</dd><dt>Evaluator</dt><dd>{math?`${math.evaluatorIdentity}@${math.evaluatorVersion}`:definition.intelligenceKind==="METRIC"?`${definition.evaluatorLineage.implementationReference}@${definition.evaluatorLineage.version}`:"Not applicable"}</dd><dt>Canon effect</dt><dd>{definition.canonEffect}</dd><dt>Operational graph effect</dt><dd>{definition.operationalGraphEffect}</dd><dt>Verification provenance</dt><dd>{(content.provenance??definition.provenanceRequirements).join(" · ")}</dd>{displayedSourceReferences&&<><dt>Source references</dt><dd>{displayedSourceReferences.join(" · ")}</dd></>}</dl></section></div>{actions&&<footer>{actions}</footer>}</div>;}

function RegisteredMathematics({entry,visible}:{entry:MetricMathematicsRegistryEntry;visible?:VisibleMathematics}){const trace=visible?.equationStatus==="IMPLEMENTATION_EQUATION"?visible.trace:undefined;return <><section className="contextual-intelligence__math"><h3>Mathematical model</h3>{entry.authoritativeEquation?<><p><b>{entry.characteristics.includes("NOTATION_ONLY")?"Canon-authorized notation only":"Executable implementation equation; not Canon-authorized mathematics"}</b></p><div className="contextual-intelligence__equation" aria-label={entry.authoritativeEquation.plainText}>{entry.authoritativeEquation.notation}</div><p>{entry.authoritativeEquation.plainText}</p><table><thead><tr><th>Symbol</th><th>Meaning</th><th>Domain</th><th>Unit</th></tr></thead><tbody>{entry.authoritativeEquation.symbols.map(x=><tr key={x.symbol}><td>{x.symbol}</td><td>{x.meaning}</td><td>{x.acceptedDomain}</td><td>{x.unit}</td></tr>)}</tbody></table></>:entry.equationStatus==="UNAVAILABLE"?<p className="contextual-intelligence__unavailable">Mathematics unavailable: {entry.documentationAvailability.reason}</p>:<p>No governing equation is claimed. The registered deterministic procedure is authoritative for this implementation behavior.</p>}</section>{trace&&<section><h3>This result</h3><div className="contextual-intelligence__equation">{trace.substitution}</div><div className="contextual-intelligence__table-wrap"><table><thead><tr><th>Dimension</th><th>Status</th><th>Similarity</th><th>Weight</th><th>Weighted contribution / reason</th></tr></thead><tbody>{trace.dimensions.map(x=><tr key={x.dimension}><td>{x.dimension}</td><td>{x.availability}</td><td>{x.similarity??"—"}</td><td>{x.configuredWeight??"—"}</td><td>{x.weightedContribution??x.unavailableReason}</td></tr>)}</tbody></table></div><dl><dt>Numerator</dt><dd>{trace.numerator}</dd><dt>Participating-weight denominator</dt><dd>{trace.denominator}</dd><dt>Exact result</dt><dd>{trace.exactResult}</dd><dt>Displayed result</dt><dd className="contextual-intelligence__result">{trace.displayedResult}</dd><dt>Formatting</dt><dd>{trace.formattingRule}</dd></dl></section>}{entry.deterministicProcedure&&<details><summary>How the deterministic procedure works</summary><ol>{entry.deterministicProcedure.steps.map(x=><li key={x.stepIdentity}>{x.description}</li>)}</ol>{[...entry.deterministicProcedure.exclusionRules,...entry.deterministicProcedure.missingDataBehavior,...entry.deterministicProcedure.sourceCopyBehavior,...entry.deterministicProcedure.presentationFormatting].map(x=><p key={x}>{x}</p>)}</details>}</>}

export function MathematicalDeepDiveSection({definition,snapshot}:{definition:IntelligenceDefinition;snapshot?:EvaluatedMathematicalSnapshot}){const equation=definition.mathematicalDocumentation;if(!equation)return <section className="contextual-intelligence__math"><h3>Mathematical documentation</h3><p className="contextual-intelligence__unavailable">Formal mathematical documentation is not yet available for this metric.</p><dl><dt>Status</dt><dd>{definition.mathematicalDocumentationStatus.status}</dd><dt>Registered reason</dt><dd>{definition.mathematicalDocumentationStatus.reason??"Not applicable to this intelligence item."}</dd>{definition.intelligenceKind==="METRIC"&&<><dt>Evaluator provenance</dt><dd>{definition.evaluatorLineage.implementationReference}@{definition.evaluatorLineage.version}</dd></>}</dl></section>;return <section className="contextual-intelligence__math"><h3>Governing equation</h3><h4>{equation.equationName}</h4><div className="contextual-intelligence__equation">{equation.notation}</div><p>{equation.plainText}</p>{snapshot&&<><h3>Evaluated substitution</h3><div className="contextual-intelligence__equation">{snapshot.formattedSubstitutedExpression}</div><ol>{snapshot.inputSubstitutions.map(x=><li key={`${x.order}-${x.symbol}`}><b>{x.symbol}</b> = {x.formattedValue} {x.unit}</li>)}</ol><h3>Evaluated result</h3><div className="contextual-intelligence__result">{snapshot.formattedDisplayedValue} <small>exact: {snapshot.exactEvaluatedValue}</small></div></>}<h3>Symbols and domains</h3><table><thead><tr><th>Symbol</th><th>Meaning</th><th>Domain</th><th>Unit</th></tr></thead><tbody>{equation.symbols.map(x=><tr key={x.symbol}><td>{x.symbol}</td><td>{x.meaning}</td><td>{x.acceptedDomain}</td><td>{x.unit}</td></tr>)}</tbody></table><Detail label="Accepted domains" values={equation.acceptedDomains}/><Detail label="Units" values={equation.units}/><Detail label="Assumptions" values={equation.assumptions}/><Detail label="Availability rules" values={equation.availabilityRules}/><Detail label="Normalization" values={[equation.normalizationMethod]}/><Detail label="Thresholds" values={equation.thresholds}/><dl><dt>Governing source</dt><dd>{equation.governingSource}</dd><dt>Citation</dt><dd>{equation.citationText}</dd><dt>Verification status</dt><dd>{equation.verificationStatus}</dd><dt>Evaluator</dt><dd>{equation.evaluatorImplementationReference}@{equation.evaluatorVersion}</dd><dt>Related equations</dt><dd>{equation.relatedEquationIds.join(" · ")||"None registered"}</dd></dl></section>;}
const Detail=({label,values}:{label:string;values:readonly string[]})=><div><h4>{label}</h4><p>{values.join(" · ")||"None registered"}</p></div>;
