import type { ComparePairProjectionReady } from "../compare/projection/ComparePairProjectionTypes.ts";
import type { IntentionMetricDerivation } from "../intention/contracts/IntentionMetricDerivation.ts";
import type { CanonicalFeatureDimension } from "../resolve/features/CanonicalKnowledgeFeatureTypes.ts";
import type { ResolveCandidateDimensionIntelligence, ResolveCandidateIntelligence } from "../resolve/intelligence/ResolveCandidateIntelligenceTypes.ts";
import type { LayersExperimentalPairProjection, LayersLayerContribution } from "../layers/projection/LayersExperimentalPairProjectionTypes.ts";
import { createEvaluatedMathematicalSnapshot, type EquationDocumentation } from "./EquationDocumentationTypes.ts";
import type { GovernedMetricExplanation, MetricDefinition } from "./MetricIntelligenceTypes.ts";
import { projectResolveAggregateTrace } from "./MetricCalculationTrace.ts";

const dimensions = ["NARRATIVE", "OBSERVABILITY", "INFRASTRUCTURE", "TOPOLOGY", "GEOGRAPHY"] as const;
const unavailableEquation = "Governing equation unavailable";
const mathematicsIdentity=(id:string):string|undefined=>id==="resolve.aggregate-similarity"?"resolve.aggregate-correspondence":id.startsWith("resolve.dimension.")?id.replace(/-similarity$/,"-correspondence"):id==="intention.source-residual-instability"?"intention.source-residual-copy":id==="layers.score-delta"?"layers.delta-classification":id==="layers.weighted-contribution"?"layers.weighted-contribution":undefined;
const base = (id:string,label:string):MetricDefinition => ({definitionId:id,definitionVersion:"1.0.0",label,intelligenceKind:"METRIC",semanticProducer:{id:"resolve.canonical-similarity",version:"1.0.0"},eligibleContexts:["MANIFOLD","COMPARE","NARRATIVE","INTENTION"],briefing:{templateId:`metric-briefing/${id}`,version:"1.0.0",conciseTemplate:"{displayValue}. Higher means greater deterministic correspondence; it identifies where closer investigation may be useful."},whyItMatters:["This deterministic correspondence helps compare structures without asserting probability, causation, proof, truth, or an accepted relationship."],inclusionClassification:"INTERPRETIVE",provenanceRequirements:["candidateId","evaluationId","ordered Knowledge endpoints","authoritative evaluator output"],mathematicalDocumentationStatus:{status:"DEFERRED_UNAVAILABLE",reason:unavailableEquation},...(mathematicsIdentity(id)?{mathematicsAuthorityIdentity:mathematicsIdentity(id)}:{}),collectionEligible:false,epistemicEffect:"DERIVED_NON_CANONICAL",canonEffect:"NONE",operationalGraphEffect:"NONE",evaluatorLineage:{implementationReference:"resolve/similarity/CanonicalKnowledgeSimilarity",version:"1.0.0"}});

export const RESOLVE_AGGREGATE_DEFINITION = Object.freeze(base("resolve.aggregate-similarity","Aggregate correspondence"));
export const RESOLVE_DIMENSION_DEFINITIONS = Object.freeze(Object.fromEntries(dimensions.map(d=>[d,Object.freeze(base(`resolve.dimension.${d.toLowerCase()}-similarity`,`${d[0]}${d.slice(1).toLowerCase()} correspondence`))])) as Record<typeof dimensions[number],MetricDefinition>);
export const INTENTION_SOURCE_RESIDUAL_DEFINITION = Object.freeze({...base("intention.source-residual-instability","Corpus topology residual instability"),semanticProducer:{id:"intention.projection",version:"1.0.0"},eligibleContexts:["INTENTION"],evaluatorLineage:{implementationReference:"IntentionProjectionResolver.sourceResidual",version:"1.0.0"}});
const layerDefinition=(id:string,label:string)=>Object.freeze({...base(id,label),semanticProducer:{id:"layers.experimental-pair-projection",version:"2.0.0"},eligibleContexts:["LAYERS"],evaluatorLineage:{implementationReference:"layers/projection/LayersExperimentalPairProjection",version:"2.0.0"}});
export const LAYERS_METRIC_DEFINITIONS=Object.freeze({baseline:layerDefinition("layers.baseline-score","Baseline score"),delta:layerDefinition("layers.score-delta","Experimental score delta"),similarity:layerDefinition("layers.contribution-similarity","Layer contribution similarity"),configuredWeight:layerDefinition("layers.configured-weight","Configured layer weight"),participatingWeight:layerDefinition("layers.participating-weight","Participating normalized weight"),weightedContribution:layerDefinition("layers.weighted-contribution","Weighted layer contribution")});
export const GOVERNED_METRIC_DEFINITIONS = Object.freeze([RESOLVE_AGGREGATE_DEFINITION,...dimensions.map(d=>RESOLVE_DIMENSION_DEFINITIONS[d]),INTENTION_SOURCE_RESIDUAL_DEFINITION,...Object.values(LAYERS_METRIC_DEFINITIONS)]);

const pct=(value:number)=>`${(value*100).toFixed(1)}%`;
const pairIdentity=(projection:ComparePairProjectionReady)=>`${projection.leftKnowledgeObjectId}↔${projection.rightKnowledgeObjectId}`;
const common=(projection:ComparePairProjectionReady, definitionId:string, surfaceId:string, activeMode:string, value:number, definition:string, notice:string):GovernedMetricExplanation=>({definitionId,semanticIdentity:`resolve:${projection.evaluationId}:${definitionId}`,surfaceId,activeMode,displayValue:pct(value),exactValue:String(value),definition,interpretation:`The authoritative Resolve evaluator produced ${pct(value)} for ${pairIdentity(projection)}. Higher values mean more similarity on the registered basis, not greater likelihood.`,notice,provenance:[`candidate ${projection.candidateId}`,`evaluation ${projection.evaluationId}`,`ordered endpoints ${pairIdentity(projection)}`,...projection.similarityRationale],sourceReferences:[projection.leftKnowledgeObjectId,projection.rightKnowledgeObjectId],limitations:["Similarity is not probability, confidence, causation, proof, or truth.","The candidate remains non-canonical and no relationship is accepted.",unavailableEquation],unavailableInputs:projection.evidence.unavailableDimensions.map(value=>`${value}: UNAVAILABLE`)});

export function resolveAggregateMetricExplanation(projection:ComparePairProjectionReady,surfaceId:string,activeMode:string):GovernedMetricExplanation {
  const value=projection.aggregate.aggregateSimilarity;
  return {...common(projection,RESOLVE_AGGREGATE_DEFINITION.definitionId,surfaceId,activeMode,value,"The configured-weight aggregate of the available canonical dimension similarities.",`${projection.aggregate.participatingDimensionCount}/${projection.aggregate.totalDimensionCount} dimensions participated. Configured weights and unavailable dimensions remain visible in the dimension results.`),mathematicsAuthorityIdentity:"resolve.aggregate-correspondence",mathematicalExplanation:{equationStatus:"IMPLEMENTATION_EQUATION",notationOnly:false,trace:projectResolveAggregateTrace(projection)}};
}
export function resolveDimensionMetricExplanation(projection:ComparePairProjectionReady,item:ResolveCandidateDimensionIntelligence,surfaceId:string,activeMode:string):GovernedMetricExplanation|undefined {
  if(item.source.availability!=="AVAILABLE") return undefined;
  const definition=RESOLVE_DIMENSION_DEFINITIONS[item.dimension as CanonicalFeatureDimension];
  return {...common(projection,definition.definitionId,surfaceId,activeMode,item.source.similarity,`Deterministic ${item.dimension.toLowerCase()} similarity between the ordered canonical feature profiles.`,`Configured weight: ${item.source.weight}. This dimension participated in the aggregate.`),provenance:[`configured weight ${item.source.weight}`,...common(projection,definition.definitionId,surfaceId,activeMode,item.source.similarity,"","").provenance],mathematicsAuthorityIdentity:definition.mathematicsAuthorityIdentity,mathematicalExplanation:{equationStatus:"PROCEDURE_ONLY",notationOnly:false}};
}
export function resolveCandidateAggregateMetricExplanation(candidate:ResolveCandidateIntelligence,surfaceId:string,activeMode:string):GovernedMetricExplanation { const x=candidate.explanation; const projection={...candidate.identity,candidateId:candidate.identity.candidateId,evaluationId:candidate.identity.evaluationId,aggregate:x.aggregate,dimensions:x.dimensions,evidence:x.evidence,similarityRationale:x.similarityRationale,leftKnowledgeObjectId:candidate.identity.leftKnowledgeObjectId,rightKnowledgeObjectId:candidate.identity.rightKnowledgeObjectId} as ComparePairProjectionReady; return resolveAggregateMetricExplanation(projection,surfaceId,activeMode); }
export function resolveCandidateDimensionMetricExplanation(candidate:ResolveCandidateIntelligence,item:ResolveCandidateDimensionIntelligence,surfaceId:string,activeMode:string):GovernedMetricExplanation|undefined { const x=candidate.explanation; const projection={...candidate.identity,candidateId:candidate.identity.candidateId,evaluationId:candidate.identity.evaluationId,aggregate:x.aggregate,dimensions:x.dimensions,evidence:x.evidence,similarityRationale:x.similarityRationale,leftKnowledgeObjectId:candidate.identity.leftKnowledgeObjectId,rightKnowledgeObjectId:candidate.identity.rightKnowledgeObjectId} as ComparePairProjectionReady; return resolveDimensionMetricExplanation(projection,item,surfaceId,activeMode); }
export function layersMetricExplanation(projection:LayersExperimentalPairProjection,kind:keyof typeof LAYERS_METRIC_DEFINITIONS,value:number,displayValue:string,surfaceId:string,contribution?:LayersLayerContribution):GovernedMetricExplanation { const definition=LAYERS_METRIC_DEFINITIONS[kind]; const sourceReferences=projection.evaluatorInput.endpoints.flatMap(endpoint=>endpoint.components.flatMap(component=>component.availability==="AVAILABLE"?component.lineage.sources.map(source=>source.sourceIdentity):[])); return {definitionId:definition.definitionId,semanticIdentity:`layers:${projection.executionId}:${contribution?.layerId??"relationship"}:${kind}`,surfaceId,activeMode:"LAYERS",displayValue,exactValue:String(value),definition:`${definition.label} retained from the immutable LayersExperimentalPairProjection.`,interpretation:`The projection produced ${displayValue}; its meaning is limited to this deterministic, non-canonical experiment.`,notice:`Event-space manifold construction: ${projection.provenance.governingEquation}. ${contribution?`Evaluator ${contribution.evaluatorKey??"UNAVAILABLE"}@${contribution.evaluatorVersion??"UNAVAILABLE"}.`:""}`,provenance:[`execution ${projection.executionId}`,`input projection ${projection.evaluatorInput.inputProjectionId}`,`pair ${projection.pairId}`,`configured weight ${contribution?.canonicalWeight??"UNAVAILABLE"}`,`participating weight ${contribution?.participatingWeight??"UNAVAILABLE"}`,`normalization ${contribution?.normalization?`${contribution.normalization.normalizationKey}@${contribution.normalization.normalizationVersion}`:"UNAVAILABLE"}`],sourceReferences,limitations:["This experimental result does not mutate Canon or prove a relationship.","Unavailable inputs remain unavailable and are never replaced with zero."],unavailableInputs:projection.unavailableInputs.map(input=>`${input.code}: UNAVAILABLE — ${input.description}`)}; }

export function intentionMetricExplanation(value:IntentionMetricDerivation,surfaceId:string):GovernedMetricExplanation|undefined {
  if(value.availability!=="AVAILABLE"||value.value===undefined)return undefined;
  const equation=intentionEquationDocumentation(value);
  const displayValue=value.displayValue??String(value.value); const units=value.units??"unitless";
  return {definitionId:value.metricId==="resolve-aggregate-similarity"?RESOLVE_AGGREGATE_DEFINITION.definitionId:`intention.${value.metricId}`,semanticIdentity:value.metricId==="resolve-aggregate-similarity"&&value.resolveExecutionId?`resolve:${value.resolveExecutionId}:${RESOLVE_AGGREGATE_DEFINITION.definitionId}`:value.id,surfaceId,activeMode:"INTENTION",displayValue,exactValue:String(value.value),definition:`${value.metricName}, retained from its authoritative INTENTION derivation.`,interpretation:`The displayed value is ${displayValue} ${units}.`,notice:"Inspect the equation, substitutions, availability, model, execution, and source lineage before using this projection.",provenance:[`derivation ${value.id}`,`model ${value.modelId}@${value.modelVersion}`,`INTENTION execution ${value.intentionExecutionId}`,`revision ${value.operationalRevisionId}`],sourceReferences:[...value.sourceKnowledgeIds,...value.sourceRelationshipIds],limitations:["A computational projection does not prove intent, causation, or an accepted relationship."],unavailableInputs:value.unavailableInputs.map(input=>`${input}: UNAVAILABLE`),...(equation?{evaluatedSnapshot:createEvaluatedMathematicalSnapshot({equationReference:{equationId:equation.equationId,semanticVersion:equation.semanticVersion},inputSubstitutions:value.inputs.map((input,index)=>({order:index,symbol:input.symbol,exactValue:String(input.value),formattedValue:String(input.value),unit:units,provenance:[input.sourcePath,...input.sourceKnowledgeIds,...input.sourceRelationshipIds]})),formattedSubstitutedExpression:value.inputs.map(input=>`${input.symbol}=${input.value}`).join(", "),exactEvaluatedValue:String(value.value),formattedDisplayedValue:displayValue,activeInvestigationId:value.investigationId,operationalRevisionId:value.operationalRevisionId,evaluationIdentity:value.id,inputProvenance:[...value.sourceKnowledgeIds,...value.sourceRelationshipIds],unavailableInputDisclosures:value.unavailableInputs,assumptionsActuallyApplied:value.assumptions})}: {})};
}
function intentionEquationDocumentation(value:IntentionMetricDerivation):EquationDocumentation|undefined { void value; return undefined; }
