import { ContextualIntelligenceTrigger } from "./ContextualIntelligencePresentation";
import { METRIC_INTELLIGENCE_REGISTRY, TOPOLOGY_SIMILARITY_DEFINITION } from "./TopologySimilarityMetricIntelligence";
import type { MetricSignificanceBriefing } from "./MetricIntelligenceTypes";
import "./MetricIntelligence.css";

export interface MetricIntelligenceTriggerProps { readonly briefing:MetricSignificanceBriefing; readonly collected:boolean; readonly onCollect:()=>void; }
export function MetricIntelligenceTrigger({briefing,collected,onCollect}:MetricIntelligenceTriggerProps){
  const collectOnce=()=>{if(!collected)onCollect();};
  return <ContextualIntelligenceTrigger binding={{registry:METRIC_INTELLIGENCE_REGISTRY,definitionId:TOPOLOGY_SIMILARITY_DEFINITION.definitionId,context:{activeMode:"LAYERS",surfaceId:"layers:experimental-topology-similarity",focusedSubject:briefing.source.endpoints[0].subjectIdentity,comparedSubject:briefing.source.endpoints[1].subjectIdentity,activeLayers:["TOPOLOGY"],availability:"AVAILABLE",anomalyOrContradiction:false,alreadyRepresentedNearby:false,valueTraits:{materiallyNonObvious:true,weightedNormalizedUncertainOrAssumed:true,directlyConnectsSubjects:true}}}} content={{definition:"A deterministic comparison of two frozen Resolve topology states, expressed as the registered evaluator output.",interpretation:briefing.whyItMatters,notice:briefing.researchQuestion,exclusionRules:briefing.limitations,provenance:[briefing.deterministicBasisSummary],sourceReferences:briefing.source.endpoints.flatMap(endpoint=>endpoint.components.flatMap(component=>component.sourceReferences)),briefingTemplateValues:{displayValue:briefing.displayValue},epistemicClassification:briefing.epistemicClassification}} badge={collected?<span className="contextual-intelligence__saved" aria-label="Collected in Research Inbox">SAVED</span>:undefined} actions={<button type="button" className="contextual-intelligence__instrument-button contextual-intelligence__research-button" onClick={collectOnce} disabled={collected}>{collected?"Added to Research Inbox":"Add to Research Inbox"}</button>}><span onDoubleClick={event=>{event.preventDefault();event.stopPropagation();collectOnce();}}>{briefing.displayValue}</span></ContextualIntelligenceTrigger>;
}
