import { ContextualIntelligenceTrigger } from "./ContextualIntelligencePresentation";
import { METRIC_INTELLIGENCE_REGISTRY, TOPOLOGY_SIMILARITY_DEFINITION } from "./TopologySimilarityMetricIntelligence";
import type { GovernedMetricExplanation, MetricSignificanceBriefing } from "./MetricIntelligenceTypes";
import { METRIC_MATHEMATICS_REGISTRY } from "./MetricMathematicsRegistry";
import "./MetricIntelligence.css";

export type MetricIntelligenceTriggerProps = { readonly briefing:MetricSignificanceBriefing; readonly collected:boolean; readonly onCollect:()=>void; readonly metric?:never } | { readonly metric:GovernedMetricExplanation; readonly briefing?:never; readonly collected?:never; readonly onCollect?:never };
export function MetricIntelligenceTrigger(props:MetricIntelligenceTriggerProps){
  if(props.metric){const metric=props.metric;if(!METRIC_INTELLIGENCE_REGISTRY.getDefinition(metric.definitionId))return null;const mathematics=metric.mathematicsAuthorityIdentity?METRIC_MATHEMATICS_REGISTRY.get(metric.mathematicsAuthorityIdentity):undefined;return <ContextualIntelligenceTrigger binding={{registry:METRIC_INTELLIGENCE_REGISTRY,definitionId:metric.definitionId,context:{activeMode:metric.activeMode,surfaceId:metric.surfaceId,activeLayers:[],availability:"AVAILABLE",anomalyOrContradiction:false,alreadyRepresentedNearby:false,valueTraits:{materiallyNonObvious:true,weightedNormalizedUncertainOrAssumed:true,directlyConnectsSubjects:true}}}} content={{definition:metric.definition,interpretation:metric.interpretation,notice:metric.notice,exclusionRules:metric.limitations,provenance:[...metric.provenance,`semantic identity ${metric.semanticIdentity}`,`exact value ${metric.exactValue}`,...metric.unavailableInputs],sourceReferences:metric.sourceReferences,briefingTemplateValues:{displayValue:metric.displayValue},epistemicClassification:"DETERMINISTIC / DERIVED / NON-CANONICAL",evaluatedSnapshot:metric.evaluatedSnapshot,mathematics,visibleMathematics:metric.mathematicalExplanation,tooltipSummary:metric.notice}}><span>{metric.displayValue}</span>{metric.mathematicalRole&&<span className="contextual-intelligence__metric-facts"><span>{metric.mathematicalRole}</span>{metric.configuredWeight&&<span>Configured weight: {metric.configuredWeight}</span>}{metric.rawWeightedProduct&&<span>Raw weighted product: {metric.rawWeightedProduct}</span>}{metric.normalizedAggregateContribution&&<span>Normalized aggregate contribution: {metric.normalizedAggregateContribution}</span>}</span>}</ContextualIntelligenceTrigger>}
  const {briefing,collected,onCollect}=props;
  const collectOnce=()=>{if(!collected)onCollect();};
  const s=briefing.source;const weighting=s.rawWeightedProduct!==undefined&&s.normalizedAggregateContribution!==undefined?{configuredWeight:String(s.canonicalConfiguredWeight),rawWeightedProduct:String(s.rawWeightedProduct),participatingWeight:String(s.participatingNormalizedWeight),normalizedAggregateContribution:String(s.normalizedAggregateContribution)}:undefined;
  return <ContextualIntelligenceTrigger binding={{registry:METRIC_INTELLIGENCE_REGISTRY,definitionId:TOPOLOGY_SIMILARITY_DEFINITION.definitionId,context:{activeMode:"LAYERS",surfaceId:"layers:experimental-topology-similarity",focusedSubject:s.endpoints[0].subjectIdentity,comparedSubject:s.endpoints[1].subjectIdentity,activeLayers:["TOPOLOGY"],availability:"AVAILABLE",anomalyOrContradiction:false,alreadyRepresentedNearby:false,valueTraits:{materiallyNonObvious:true,weightedNormalizedUncertainOrAssumed:true,directlyConnectsSubjects:true}}}} content={{definition:"A deterministic comparison of two frozen Resolve topology states, expressed as the registered evaluator output.",interpretation:briefing.whyItMatters,notice:briefing.researchQuestion,tooltipSummary:`Configured weight: ${s.canonicalConfiguredWeight}. Normalized aggregate contribution: ${s.normalizedAggregateContribution??"unavailable"}.`,exclusionRules:briefing.limitations,provenance:[briefing.deterministicBasisSummary,`execution ${s.executionId}`,`input projection ${s.inputProjectionId}`,`endpoint snapshots ${s.endpoints[0].snapshotId} · ${s.endpoints[1].snapshotId}`],sourceReferences:s.endpoints.flatMap(endpoint=>endpoint.components.flatMap(component=>component.sourceReferences)),briefingTemplateValues:{displayValue:briefing.displayValue},epistemicClassification:briefing.epistemicClassification,mathematics:METRIC_MATHEMATICS_REGISTRY.get("resolve.dimension.topology-correspondence"),visibleMathematics:{equationStatus:"PROCEDURE_ONLY",notationOnly:false,dimensionTrace:s.calculationTrace,weighting,finalScore:String(s.value)}}} badge={collected?<span className="contextual-intelligence__saved" aria-label="Collected in Research Inbox">SAVED</span>:undefined} actions={<button type="button" className="contextual-intelligence__instrument-button contextual-intelligence__research-button" onClick={collectOnce} disabled={collected}>{collected?"Added to Research Inbox":"Add to Research Inbox"}</button>}><span onDoubleClick={event=>{event.preventDefault();event.stopPropagation();collectOnce();}}>{briefing.displayValue}</span></ContextualIntelligenceTrigger>;
}
