import { DEFAULT_CANONICAL_SIMILARITY_WEIGHTS } from "../resolve/similarity/CanonicalKnowledgeSimilarityTypes.ts";
import { createDeterministicProcedure, DETERMINISTIC_PROCEDURE_SCHEMA_VERSION, type DeterministicProcedure } from "./DeterministicProcedureTypes.ts";
import type { EquationDocumentation } from "./EquationDocumentationTypes.ts";
import { assertValidAuthorityStatus, AuthorityClassification, EquationStatus, type MathematicsCharacteristic } from "./MetricMathematicsAuthorityTypes.ts";

export const METRIC_MATHEMATICS_REGISTRY_SCHEMA_VERSION = "metric-mathematics-registry/v1" as const;
export const ISEES_MATHEMATICS_PHILOSOPHY = "iSEES does not use mathematics to declare what is true. It uses deterministic mathematics to expose structure, measure correspondence, and identify where disciplined human investigation may be useful." as const;
export const ISEES_EPISTEMIC_BOUNDARIES = Object.freeze([
  "Similarity is not identity.", "Correspondence is not probability.", "Association is not causation.",
  "A derived score is not proof or truth.", "Candidate generation is not relationship acceptance.",
  "Unavailable evidence is not zero.", "Researcher action owns acceptance and publication.",
  "AI may explain results but must not alter deterministic calculations.",
  "Every result is bounded by its inputs, evaluator, configuration, version, and provenance.",
]);

export interface MetricMathematicsRegistryEntry {
  readonly identity: string;
  readonly schemaVersion: typeof METRIC_MATHEMATICS_REGISTRY_SCHEMA_VERSION;
  readonly semanticVersion: string;
  readonly displayName: string;
  readonly authorityClassification: AuthorityClassification;
  readonly equationStatus: EquationStatus;
  readonly characteristics: readonly MathematicsCharacteristic[];
  readonly researchQuestion: string;
  readonly plainLanguageDefinition: string;
  readonly philosophyOfUse: typeof ISEES_MATHEMATICS_PHILOSOPHY;
  readonly epistemicBoundaries: readonly string[];
  readonly owner: string;
  readonly evaluatorIdentity: string;
  readonly evaluatorVersion: string;
  readonly authoritativeEquation?: EquationDocumentation;
  readonly deterministicProcedure?: DeterministicProcedure;
  readonly relatedMathematics: readonly Readonly<{ identity: string; relationship: string }>[];
  readonly documentationAvailability: Readonly<{ status: "AVAILABLE" | "UNAVAILABLE"; reason?: string }>;
}

const symbols = (items: readonly (readonly [string,string,string,string])[]) => items.map(([symbol,meaning,acceptedDomain,unit]) => ({symbol,meaning,acceptedDomain,unit}));
const equation = (id:string,name:string,notation:string,plainText:string,refs:readonly string[], defs:ReturnType<typeof symbols>, source:string, evaluator:string, related:readonly string[]=[]):EquationDocumentation => Object.freeze({equationId:id,equationName:name,semanticVersion:"1.0.0",governingSource:source,notation,plainText,referencedSymbols:refs,symbols:defs,acceptedDomains:defs.map(x=>x.acceptedDomain),units:[...new Set(defs.map(x=>x.unit))],assumptions:[],availabilityRules:[],normalizationMethod:"As stated in notation and procedure documentation.",thresholds:[],evaluatorImplementationReference:evaluator,evaluatorVersion:"1.0.0",relatedEquationIds:related,verificationStatus:"VERIFIED",citationText:source,provenanceRequirements:["input identity","owner version"]});

const procedure = (identity:string, evaluatorIdentity:string, steps:readonly string[], options:Partial<Pick<DeterministicProcedure,"inclusionRules"|"exclusionRules"|"missingDataBehavior"|"sourceCopyBehavior"|"presentationFormatting"|"provenanceReferences">>={}):DeterministicProcedure => createDeterministicProcedure({schemaVersion:DETERMINISTIC_PROCEDURE_SCHEMA_VERSION,procedureIdentity:identity,procedureVersion:"1.0.0",evaluatorIdentity,evaluatorVersion:"1.0.0",inputs:[],outputs:[],steps:steps.map((description,order)=>({order,stepIdentity:`${identity}:step:${order}`,operation:description.startsWith("Branch")?"BRANCH":description.startsWith("Copy")?"COPY_SOURCE":description.startsWith("Format")?"FORMAT_PRESENTATION":"TRANSFORM",description,inputIdentities:[],outputIdentities:[],branchCases:[]})),inclusionRules:options.inclusionRules??[],exclusionRules:options.exclusionRules??[],missingDataBehavior:options.missingDataBehavior??[],sourceCopyBehavior:options.sourceCopyBehavior??[],presentationFormatting:options.presentationFormatting??[],provenanceReferences:options.provenanceReferences??[evaluatorIdentity]});

const manifoldEquation=equation("manifold.event-space-construction","Event-space manifold construction","M = g(L,T,S)","The deterministic construction operator g constructs the general event-space manifold M from active layers L, temporal context T, and investigative scale or scope S.",["M","g","L","T","S"],symbols([["M","General event-space manifold","deterministic investigation representation","manifold"],["g","Invariant deterministic event-space manifold construction operator","deterministic construction operator","function"],["L","General active-layer configuration","governed active layers","configuration"],["T","General temporal context","governed temporal context","context"],["S","General investigative scale or scope","governed scale or scope","scope"]]),"SC-001 canonical reduction; SC-003 evidence-conditioning clarification","resolve/engine/CanonicalManifold");
const evidenceConditionedManifoldEquation=equation("manifold.evidence-conditioned-instantiation","Evidence-conditioned manifold instantiation","M_E = g(L_E,T_E,S_E)","The same deterministic construction operator g constructs manifold M_E from the layer configuration L_E, temporal context T_E, and investigative scale or scope S_E established under governed evidence context E; E conditions those instantiated terms and is not a fourth argument to g.",["M_E","g","L_E","T_E","S_E","E"],symbols([["M_E","Event-space manifold instantiated under governed evidence context E","deterministic investigation representation","manifold"],["g","Invariant deterministic event-space manifold construction operator","deterministic construction operator","function"],["L_E","Layer configuration selected, populated, or resolved under E","governed active layers","configuration"],["T_E","Temporal context established under E","governed temporal context","context"],["S_E","Investigative scale or scope established under E","governed scale or scope","scope"],["E","Governed evidence context conditioning the instantiated terms; not a direct argument to g","governed evidence context","context"]]),"SC-003 evidence-conditioning clarification","resolve/engine/CanonicalManifold",["manifold.event-space-construction"]);
const aggregateEquation=equation("resolve.aggregate-correspondence","Resolve aggregate correspondence","S(A,B) = (Σ[d∈D_available] w_d s_d) / (Σ[d∈D_available] w_d)","The available dimension similarities are combined by their configured weights and renormalized over participating dimensions.",["S(A,B)","D_available","w_d","s_d"],symbols([["S(A,B)","Aggregate correspondence for A and B","[0,1] when available","ratio"],["D_available","Dimensions with mutually available inputs","subset of configured dimensions","set"],["w_d","Configured weight for dimension d","non-negative finite number","weight"],["s_d","Similarity for dimension d","[0,1]","ratio"]]),"Verified executable behavior; not Canon-authorized","resolve/similarity/CanonicalKnowledgeSimilarity.computeAggregateSimilarity");

const common = {schemaVersion:METRIC_MATHEMATICS_REGISTRY_SCHEMA_VERSION,semanticVersion:"1.0.0",philosophyOfUse:ISEES_MATHEMATICS_PHILOSOPHY,epistemicBoundaries:ISEES_EPISTEMIC_BOUNDARIES} as const;
const entry=(value:Omit<MetricMathematicsRegistryEntry,keyof typeof common>):MetricMathematicsRegistryEntry=>Object.freeze({...common,...value,characteristics:Object.freeze([...value.characteristics]),relatedMathematics:Object.freeze([...value.relatedMathematics]),epistemicBoundaries:ISEES_EPISTEMIC_BOUNDARIES});
const related=(identity:string,relationship:string)=>Object.freeze({identity,relationship});
const exec=(identity:string,displayName:string,definition:string,evaluatorIdentity:string,proc:DeterministicProcedure,relation:readonly ReturnType<typeof related>[]=[]):MetricMathematicsRegistryEntry=>entry({identity,displayName,authorityClassification:AuthorityClassification.EXECUTABLE_BUT_NOT_CANONIZED,equationStatus:EquationStatus.PROCEDURE_ONLY,characteristics:["ALGORITHMIC_PROCEDURE"],researchQuestion:`What deterministic ${displayName.toLowerCase()} does the current implementation report?`,plainLanguageDefinition:definition,owner:evaluatorIdentity,evaluatorIdentity,evaluatorVersion:"1.0.0",deterministicProcedure:proc,relatedMathematics:relation,documentationAvailability:{status:"AVAILABLE"}});
const deferred=(identity:string,displayName:string,definition:string,owner:string):MetricMathematicsRegistryEntry=>entry({identity,displayName,authorityClassification:AuthorityClassification.DEFERRED_UNAVAILABLE,equationStatus:EquationStatus.UNAVAILABLE,characteristics:[],researchQuestion:`What authorized deterministic mathematics, if any, governs ${displayName.toLowerCase()}?`,plainLanguageDefinition:definition,owner,evaluatorIdentity:"UNAVAILABLE",evaluatorVersion:"UNAVAILABLE",relatedMathematics:[],documentationAvailability:{status:"UNAVAILABLE",reason:"No repository-authoritative deterministic mathematical documentation is currently available."}});

const jaccard=(id:string,owner:string)=>procedure(id,owner,["Normalize each supplied string and remove duplicates.","Branch: when both normalized sets are empty, return 1.","Count members shared by both sets and members in their union.","Divide intersection size by union size and clamp the result to [0,1]."],{missingDataBehavior:["Mutual availability is checked before this procedure; unavailable evidence does not become an empty set or zero."]});

const entries: readonly MetricMathematicsRegistryEntry[] = [
  entry({identity:"manifold.event-space-construction",displayName:"Event-space manifold construction",authorityClassification:AuthorityClassification.CANON_AUTHORIZED,equationStatus:EquationStatus.AUTHORIZED_EQUATION,characteristics:["NOTATION_ONLY"],researchQuestion:"How is the event-space manifold constructed from governed investigation state?",plainLanguageDefinition:"A deterministic projection constructs the event-space manifold from active layers, temporal context, and investigative scale or scope; it is not a metric evaluator.",owner:"System Canon / Resolve manifold",evaluatorIdentity:"resolve/engine/CanonicalManifold",evaluatorVersion:"1.0.0",authoritativeEquation:manifoldEquation,relatedMathematics:[],documentationAvailability:{status:"AVAILABLE"}}),
  entry({identity:"manifold.evidence-conditioned-instantiation",displayName:"Evidence-conditioned manifold instantiation",authorityClassification:AuthorityClassification.CANON_AUTHORIZED,equationStatus:EquationStatus.AUTHORIZED_EQUATION,characteristics:["NOTATION_ONLY"],researchQuestion:"How does governed evidence context condition a particular event-space manifold?",plainLanguageDefinition:"The governed evidence context selects, populates, or resolves the instantiated layer, temporal, and scope terms used by the invariant construction operator; it is not a similarity, correspondence, scoring, probability, confidence, causation, proof, truth, or INTENTION inference equation.",owner:"System Canon / Resolve manifold",evaluatorIdentity:"resolve/engine/CanonicalManifold",evaluatorVersion:"1.0.0",authoritativeEquation:evidenceConditionedManifoldEquation,relatedMathematics:[related("manifold.event-space-construction","Evidence-conditioned instantiation of the general construction law")],documentationAvailability:{status:"AVAILABLE"}}),
  entry({identity:"resolve.aggregate-correspondence",displayName:"Resolve aggregate correspondence",authorityClassification:AuthorityClassification.EXECUTABLE_BUT_NOT_CANONIZED,equationStatus:EquationStatus.IMPLEMENTATION_EQUATION,characteristics:["ALGORITHMIC_PROCEDURE"],researchQuestion:"How strongly do the available configured dimensions correspond across two cases?",plainLanguageDefinition:"A configured-weight mean over only the dimensions whose inputs are mutually available.",owner:"Resolve canonical similarity evaluator",evaluatorIdentity:"resolve/similarity/CanonicalKnowledgeSimilarity.computeAggregateSimilarity",evaluatorVersion:"1.0.0",authoritativeEquation:aggregateEquation,deterministicProcedure:procedure("resolve.aggregate-correspondence","resolve/similarity/CanonicalKnowledgeSimilarity.computeAggregateSimilarity",["Select only dimensions whose comparison result is AVAILABLE.","Multiply each available similarity by its configured weight.","Sum weighted values and participating weights.","Branch: if no dimensions participate or participating weight is not positive, return UNAVAILABLE.","Divide the weighted sum by participating weight and clamp to [0,1].","Format presentation by multiplying the exact ratio by 100 and applying one-decimal percent formatting."],{exclusionRules:["Unavailable dimensions do not participate and are not treated as zero."],missingDataBehavior:["No participants or non-positive participating weight produces UNAVAILABLE."],presentationFormatting:["Exact ratio × 100, one decimal place, percent suffix."]}),relatedMathematics:[related("resolve.dimension.*","Supplies participating dimension values")],documentationAvailability:{status:"AVAILABLE"}}),
  exec("resolve.dimension.narrative-correspondence","Narrative correspondence","Jaccard correspondence between normalized narrative-trait sets.","resolve/similarity/CanonicalKnowledgeSimilarity.compareNarrative",jaccard("resolve.dimension.narrative-correspondence","resolve/similarity/CanonicalKnowledgeSimilarity.compareNarrative"),[related("resolve.aggregate-correspondence","May participate with configured weight 0.30")]),
  exec("resolve.dimension.observability-correspondence","Observability correspondence","Mean of clamped confidence-distance and normalized duration-distance similarities when all four source inputs are available.","resolve/similarity/CanonicalKnowledgeSimilarity.compareObservability",procedure("resolve.dimension.observability-correspondence","resolve/similarity/CanonicalKnowledgeSimilarity.compareObservability",["Require confidence and duration for both endpoints.","Transform confidence distance to max(0, 1 - absolute distance).","Transform duration distance to max(0, 1 - absolute distance / 100).","Take the arithmetic mean of the two similarities."],{missingDataBehavior:["If any required value is unavailable, the dimension is UNAVAILABLE; missing values do not become zero."]}),[related("resolve.aggregate-correspondence","May participate with configured weight 0.20")]),
  exec("resolve.dimension.infrastructure-correspondence","Infrastructure correspondence","Jaccard correspondence between normalized facility-type sets.","resolve/similarity/CanonicalKnowledgeSimilarity.compareInfrastructure",jaccard("resolve.dimension.infrastructure-correspondence","resolve/similarity/CanonicalKnowledgeSimilarity.compareInfrastructure"),[related("resolve.aggregate-correspondence","May participate with configured weight 0.15")]),
  exec("resolve.dimension.topology-correspondence","Topology correspondence","Arithmetic mean of four clamped component-distance similarities in fixed topology-vector order.","resolve/similarity/CanonicalKnowledgeSimilarity.compareTopology",procedure("resolve.dimension.topology-correspondence","resolve/similarity/CanonicalKnowledgeSimilarity.compareTopology",["Require both four-component topology-state vectors.","For each aligned component, compute 1 minus the absolute distance and clamp to [0,1].","Take the arithmetic mean in contradiction-density, residual-instability, entanglement-score, cluster-fragmentation order."],{missingDataBehavior:["If either topology state is unavailable, the dimension is UNAVAILABLE."]}),[related("resolve.aggregate-correspondence","May participate with configured weight 0.25")]),
  exec("resolve.dimension.geography-correspondence","Geography correspondence","Exact normalized state equality: one for equal states and zero for different states.","resolve/similarity/CanonicalKnowledgeSimilarity.compareGeography",procedure("resolve.dimension.geography-correspondence","resolve/similarity/CanonicalKnowledgeSimilarity.compareGeography",["Normalize each optional geographic state string.","Branch: if either normalized state is unavailable, return UNAVAILABLE.","Compare normalized states for equality; return 1 when equal and 0 otherwise."],{missingDataBehavior:["Missing state produces UNAVAILABLE, not zero."]}),[related("resolve.aggregate-correspondence","May participate with configured weight 0.10")]),
  exec("layers.selected-score-normalization","LAYERS selected-score normalization","Renormalizes selected available layer contributions by their total participating configured weight.","layers/projection/LayersExperimentalPairProjection.compute",procedure("layers.selected-score-normalization","layers/projection/LayersExperimentalPairProjection.compute",["Select mapped selected layers with AVAILABLE evaluator results.","Sum their configured weights.","Branch: if participating weight is zero, return UNAVAILABLE.","Divide weighted sum by participating weight."],{exclusionRules:["Unmapped or unavailable selected layers do not participate."],missingDataBehavior:["Zero participating weight produces UNAVAILABLE."]}),[related("resolve.aggregate-correspondence","Uses the same available-weight renormalization behavior")]),
  exec("layers.weighted-contribution","LAYERS weighted contribution","The available layer similarity multiplied by its configured weight, then divided by total participating weight for the displayed contribution ledger.","layers/projection/LayersExperimentalPairProjection.compute",procedure("layers.weighted-contribution","layers/projection/LayersExperimentalPairProjection.compute",["Multiply an available layer similarity by its configured weight.","Divide by total participating configured weight.","Branch: unavailable layers retain zero non-participating contribution and an explicit reason."],{missingDataBehavior:["Unavailable layers are excluded from participation; the reason remains visible."]})),
  exec("layers.delta-classification","LAYERS delta classification","Classifies baseline and experimental availability and score ordering as formed, dissolved, strengthened, weakened, unchanged, or unavailable.","layers/projection/LayersExperimentalPairProjection.projectLayersExperimentalPair",procedure("layers.delta-classification","layers/projection/LayersExperimentalPairProjection.projectLayersExperimentalPair",["Branch: unavailable baseline and available experiment is FORMED; both unavailable is UNAVAILABLE.","Branch: available baseline and unavailable experiment is DISSOLVED.","Branch: with both available, compare scores for STRENGTHENED, WEAKENED, or UNCHANGED.","When both scores are available, subtract baseline from experimental for signed delta."],{missingDataBehavior:["A signed delta exists only when both scores are available."]})),
  entry({identity:"intention.source-residual-copy",displayName:"INTENTION source residual copy",authorityClassification:AuthorityClassification.SOURCE_SUPPLIED,equationStatus:EquationStatus.SOURCE_COPY,characteristics:["ALGORITHMIC_PROCEDURE"],researchQuestion:"What residual-instability value does the canonical source supply?",plainLanguageDefinition:"A lossless source-field copy, explicitly not a residual computed by an INTENTION model.",owner:"IntentionProjectionResolver",evaluatorIdentity:"IntentionProjectionResolver.sourceResidual",evaluatorVersion:"1.0.0",deterministicProcedure:procedure("intention.source-residual-copy","IntentionProjectionResolver.sourceResidual",["Copy payload.canonicalEvent.manifold_analysis.topology.topology_state.residual_instability without recalibration."],{sourceCopyBehavior:["Preserve the exact source value and source provenance; do not infer calibration."]}),relatedMathematics:[],documentationAvailability:{status:"AVAILABLE"}}),
  entry({identity:"intention.resolve-aggregate-copy",displayName:"INTENTION Resolve aggregate copy",authorityClassification:AuthorityClassification.SOURCE_SUPPLIED,equationStatus:EquationStatus.SOURCE_COPY,characteristics:["ALGORITHMIC_PROCEDURE"],researchQuestion:"What Resolve aggregate was supplied to the INTENTION projection?",plainLanguageDefinition:"A lossless copy of the selected Resolve candidate aggregate, not an INTENTION probability or inference.",owner:"IntentionProjectionResolver",evaluatorIdentity:"IntentionProjectionResolver",evaluatorVersion:"1.0.0",deterministicProcedure:procedure("intention.resolve-aggregate-copy","IntentionProjectionResolver",["Copy explanation.aggregate.aggregateSimilarity from the authoritative selected Resolve candidate evaluation."],{sourceCopyBehavior:["Preserve the Resolve value and evaluation lineage without recomputation."]}),relatedMathematics:[related("resolve.aggregate-correspondence","Source computation")],documentationAvailability:{status:"AVAILABLE"}}),
  deferred("intention.theoretical-models-unavailable","INTENTION attractor, vector, and governing model","No authorized executable attractor definition, intention vector, or complete INTENTION governing model exists.","INTENTION contracts"),
  entry({identity:"evidence.source-confidence-boundary",displayName:"Evidence source-supplied confidence",authorityClassification:AuthorityClassification.SOURCE_SUPPLIED,equationStatus:EquationStatus.SOURCE_COPY,characteristics:[],researchQuestion:"What confidence value did the evidence source provide?",plainLanguageDefinition:"The value is source-supplied and is not calibrated, inferred, or endorsed by iSEES.",owner:"EvidenceWorkspaceProjection",evaluatorIdentity:"SOURCE_SUPPLIED",evaluatorVersion:"SOURCE_DEFINED",relatedMathematics:[],documentationAvailability:{status:"AVAILABLE"}}),
  deferred("timeline.categorical-mathematics-unavailable","Timeline categorical status","Timeline ordering and qualification fields do not currently have an authorized research-metric equation.","TimelineTemporalProjection"),
  deferred("studio.deterministic-research-metric-unavailable","Studio deterministic research metric","Studio currently supplies no authorized deterministic research metric for mathematical explanation.","Studio"),
];

export interface MetricMathematicsRegistry { readonly get: (identity:string)=>MetricMathematicsRegistryEntry|undefined; readonly list:()=>readonly MetricMathematicsRegistryEntry[]; }
export function createMetricMathematicsRegistry(values:readonly MetricMathematicsRegistryEntry[]):MetricMathematicsRegistry {
  const map=new Map<string,MetricMathematicsRegistryEntry>();
  for(const value of values){
    if(!value.identity.trim()||value.schemaVersion!==METRIC_MATHEMATICS_REGISTRY_SCHEMA_VERSION||!/^\d+\.\d+\.\d+$/.test(value.semanticVersion)) throw new Error(`Invalid mathematics registry identity/version: ${value.identity}.`);
    if(map.has(value.identity)) throw new Error(`Duplicate mathematics registry identity: ${value.identity}.`);
    assertValidAuthorityStatus(value.authorityClassification,value.equationStatus);
    if(value.equationStatus==="PROCEDURE_ONLY"&&!value.deterministicProcedure) throw new Error(`Procedure-only entry ${value.identity} lacks a deterministic procedure.`);
    if(value.equationStatus==="UNAVAILABLE"&&value.documentationAvailability.status!=="UNAVAILABLE") throw new Error(`Unavailable mathematics ${value.identity} must remain explicitly unavailable.`);
    if(value.equationStatus==="SOURCE_COPY"&&value.evaluatorIdentity!=="SOURCE_SUPPLIED"&&!value.deterministicProcedure) throw new Error(`Source-copy entry ${value.identity} must identify its copy procedure.`);
    if(value.authorityClassification==="CANON_AUTHORIZED"&&!new Set(["manifold.event-space-construction","manifold.evidence-conditioned-instantiation"]).has(value.identity)) throw new Error(`Unexpected Canon-authorized mathematics: ${value.identity}.`);
    map.set(value.identity,Object.freeze(value));
  }
  const ordered=Object.freeze([...map.values()].sort((a,b)=>a.identity.localeCompare(b.identity)));
  return Object.freeze({get:(identity:string)=>map.get(identity),list:()=>ordered});
}

export const METRIC_MATHEMATICS_REGISTRY=createMetricMathematicsRegistry(entries);
export const RESOLVE_DEFAULT_CONFIGURED_WEIGHTS=Object.freeze({...DEFAULT_CANONICAL_SIMILARITY_WEIGHTS});
