import { COMMAND_SCHEMA_VERSION, CONTENT_SCHEMA_VERSION, parseNativeCaseDraftContent } from "./NativeCaseDraftTypes.ts";
import type { FieldState, NativeCaseDraftContent, NativeCaseDraftCreateCommand, NativeCaseDraftProjection, NativeCaseDraftUpdateCommand, PrivacyClassification } from "./NativeCaseDraftTypes.ts";

export const NATIVE_CASE_DRAFT_FIELD_ORDER = ["workingTitle", "observationLocation", "localObservationDate", "localObservationTime", "timezone", "observationNarrative", "objectShape", "movementBehavior", "soundCharacteristics", "lightingVisibility", "observerContext", "witnessCount", "environmentalConditions", "approximateDuration", "researcherNotes", "sourceProvenanceStatement", "privacyClassification", "rightsPublicationRestriction"] as const;
export type NativeCaseDraftFieldName = typeof NATIVE_CASE_DRAFT_FIELD_ORDER[number];
export type NativeCaseDraftFormState = Readonly<Record<NativeCaseDraftFieldName, Readonly<{ state: FieldState; value?: string | number | PrivacyClassification | null }>>>;
export interface FieldValidationResult { readonly field: NativeCaseDraftFieldName; readonly valid: boolean; readonly message: string | null; }

const freeze = <T extends object>(value: T): Readonly<T> => Object.freeze(value);
const TEXT_FIELDS = new Set<NativeCaseDraftFieldName>(["workingTitle", "observationLocation", "observationNarrative", "objectShape", "movementBehavior", "soundCharacteristics", "lightingVisibility", "observerContext", "environmentalConditions", "researcherNotes", "sourceProvenanceStatement", "rightsPublicationRestriction"]);
export const omittedEnvelope = (): Readonly<{ state: "OMITTED" }> => freeze({ state: "OMITTED" });
export const unknownEnvelope = (): Readonly<{ state: "UNKNOWN" }> => freeze({ state: "UNKNOWN" });
export function suppliedEnvelope<T extends string | number>(value: T): Readonly<{ state: "SUPPLIED"; value: T }> { return freeze({ state: "SUPPLIED", value }); }
export function createBlankNativeCaseDraftContent(): NativeCaseDraftContent { return freeze({ schemaVersion: CONTENT_SCHEMA_VERSION, workingTitle: omittedEnvelope(), observationLocation: omittedEnvelope(), localObservationDate: omittedEnvelope(), localObservationTime: omittedEnvelope(), timezone: omittedEnvelope(), observationNarrative: omittedEnvelope(), objectShape: omittedEnvelope(), movementBehavior: omittedEnvelope(), soundCharacteristics: omittedEnvelope(), lightingVisibility: omittedEnvelope(), observerContext: omittedEnvelope(), witnessCount: omittedEnvelope(), environmentalConditions: omittedEnvelope(), approximateDuration: omittedEnvelope(), researcherNotes: omittedEnvelope(), sourceProvenanceStatement: omittedEnvelope(), privacyClassification: omittedEnvelope(), rightsPublicationRestriction: omittedEnvelope() }); }

function transportEnvelope(field: NativeCaseDraftFieldName, entry: NativeCaseDraftFormState[NativeCaseDraftFieldName]): object {
  if (entry.state !== "SUPPLIED") return freeze({ state: entry.state });
  if (field === "approximateDuration") return freeze({ state: "SUPPLIED", seconds: entry.value });
  return freeze({ state: "SUPPLIED", value: TEXT_FIELDS.has(field) && typeof entry.value === "string" ? normalizeSuppliedText(entry.value) : entry.value });
}
export function mapFormStateToContent(form: NativeCaseDraftFormState): NativeCaseDraftContent { const raw = Object.fromEntries(NATIVE_CASE_DRAFT_FIELD_ORDER.map(field => [field, transportEnvelope(field, form[field])])); return parseNativeCaseDraftContent({ schemaVersion: CONTENT_SCHEMA_VERSION, ...raw }); }
export function restoreNativeCaseDraftContent(content: NativeCaseDraftContent): NativeCaseDraftFormState { const restored = Object.fromEntries(NATIVE_CASE_DRAFT_FIELD_ORDER.map(field => { const envelope = content[field]; const value = field === "approximateDuration" ? content.approximateDuration.seconds : "value" in envelope ? envelope.value : undefined; return [field, freeze(value === undefined || value === null ? { state: envelope.state } : { state: envelope.state, value })]; })); return freeze(restored) as NativeCaseDraftFormState; }
export function restoreFormState(projection: NativeCaseDraftProjection): NativeCaseDraftFormState { return restoreNativeCaseDraftContent(projection.content); }
export function normalizeSuppliedText(value: string): string { return value.normalize("NFKC").trim(); }
export function validateNativeCaseDraftForm(form: NativeCaseDraftFormState): readonly FieldValidationResult[] { return Object.freeze(NATIVE_CASE_DRAFT_FIELD_ORDER.map(field => { try { mapFormStateToContent(freeze(Object.fromEntries(NATIVE_CASE_DRAFT_FIELD_ORDER.map(key => [key, key === field ? form[key] : omittedEnvelope()]))) as NativeCaseDraftFormState); return freeze({ field, valid: true, message: null }); } catch { return freeze({ field, valid: false, message: `Invalid value for ${field}.` }); } })); }
export function firstInvalidField(form: NativeCaseDraftFormState): FieldValidationResult | null { return validateNativeCaseDraftForm(form).find(result => !result.valid) ?? null; }
export function contentMatchesBaseline(local: NativeCaseDraftContent, baseline: NativeCaseDraftContent): boolean { return JSON.stringify(local) === JSON.stringify(baseline); }
export function applyCanonicalBaseline(projection: NativeCaseDraftProjection): NativeCaseDraftContent { return projection.content; }
const idempotency = (value: string): string => { const normalized = value.trim(); if (!normalized || normalized.length > 200) throw new Error("Idempotency key must contain 1 to 200 characters."); return normalized; };
const association = (value: string | null): string | null => { if (value === null) return null; const normalized = value.trim(); if (!normalized || normalized.length > 500) throw new Error("Investigation identity is invalid."); return normalized; };
export function createNativeCaseDraftCommand(form: NativeCaseDraftFormState, investigationId: string | null, idempotencyKey: string): NativeCaseDraftCreateCommand { return freeze({ schemaVersion: COMMAND_SCHEMA_VERSION, investigationId: association(investigationId), content: mapFormStateToContent(form), idempotencyKey: idempotency(idempotencyKey) }); }
export function updateNativeCaseDraftCommand(form: NativeCaseDraftFormState, investigationId: string | null, expectedRevision: number, idempotencyKey: string): NativeCaseDraftUpdateCommand { if (!Number.isSafeInteger(expectedRevision) || expectedRevision < 0) throw new Error("Expected revision is invalid."); return freeze({ schemaVersion: COMMAND_SCHEMA_VERSION, investigationId: association(investigationId), expectedRevision, content: mapFormStateToContent(form), idempotencyKey: idempotency(idempotencyKey) }); }
