import { resolveApiBaseUrl } from "../api/ApiOrigin.ts";
import { NativeCaseDraftClientError, NativeCaseDraftParseError, parseNativeCaseDraftList, parseNativeCaseDraftProjection, parseNativeCaseDraftReceipt, parseStructuredApiError } from "./NativeCaseDraftTypes.ts";
import type { NativeCaseDraftCreateCommand, NativeCaseDraftList, NativeCaseDraftProjection, NativeCaseDraftReceipt, NativeCaseDraftUpdateCommand, StructuredApiErrorEnvelope } from "./NativeCaseDraftTypes.ts";

export type NativeCaseDraftFetch = (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
export interface NativeCaseDraftApiOptions { readonly fetch?: NativeCaseDraftFetch; readonly apiBaseUrl?: string; readonly cookieSource?: () => string; }
function csrfCookie(source: () => string): string { const pair = source().split(";").map(part => part.trim()).find(part => part.startsWith("isees_csrf=")); if (!pair) throw new NativeCaseDraftClientError("CSRF", "The secure session could not be verified.", { status: 403, domainCode: "CSRF_TOKEN_MISSING" }); try { const value = decodeURIComponent(pair.slice("isees_csrf=".length)); if (!value) throw new Error(); return value; } catch { throw new NativeCaseDraftClientError("CSRF", "The secure session could not be verified.", { status: 403, domainCode: "CSRF_TOKEN_INVALID" }); } }
const errorKind = (status: number, code: string) => status === 401 ? "AUTHENTICATION" : status === 403 ? "CSRF" : status === 404 ? "NOT_FOUND" : status === 422 ? "VALIDATION" : status === 409 && code === "REVISION_CONFLICT" ? "REVISION_CONFLICT" : status === 409 && code === "IDEMPOTENCY_KEY_REUSE" ? "IDEMPOTENCY_CONFLICT" : "HTTP";
async function json(response: Response): Promise<unknown> { try { return await response.json(); } catch (cause) { throw new NativeCaseDraftParseError(`Native case draft response was not valid JSON${cause instanceof Error ? `: ${cause.message}` : "."}`); } }
export function createNativeCaseDraftApi(options: NativeCaseDraftApiOptions = {}) {
  const transport = options.fetch ?? fetch; const base = resolveApiBaseUrl(options.apiBaseUrl); const cookies = options.cookieSource ?? (() => document.cookie);
  async function request(path: string, init: RequestInit, parser: (raw: unknown) => NativeCaseDraftProjection | NativeCaseDraftReceipt | NativeCaseDraftList) {
    let response: Response; try { response = await transport(`${base}${path}`, { ...init, credentials: "include" }); } catch (cause) { if (init.signal?.aborted || cause instanceof DOMException && cause.name === "AbortError") throw new NativeCaseDraftClientError("ABORTED", "The native case draft request was cancelled.", { domainCode: "REQUEST_ABORTED", cause }); throw new NativeCaseDraftClientError("NETWORK", "The native case draft service could not be reached.", { domainCode: "NETWORK_FAILURE", cause }); }
    const body = await json(response); if (!response.ok) { let envelope: StructuredApiErrorEnvelope; try { envelope = parseStructuredApiError(body); } catch (cause) { throw new NativeCaseDraftClientError("MALFORMED_RESPONSE", "The native case draft error response was malformed.", { status: response.status, domainCode: "MALFORMED_ERROR_RESPONSE", cause }); } const detail = envelope.error; throw new NativeCaseDraftClientError(errorKind(response.status, detail.code), detail.message, { status: response.status, domainCode: detail.code, requestId: detail.requestId }); }
    return parser(body);
  }
  const mutation = (method: "POST" | "PUT", path: string, command: NativeCaseDraftCreateCommand | NativeCaseDraftUpdateCommand, signal?: AbortSignal) => request(path, { method, credentials: "include", headers: { "Content-Type": "application/json", "X-ISEES-CSRF": csrfCookie(cookies) }, body: JSON.stringify(command), signal }, parseNativeCaseDraftReceipt) as Promise<NativeCaseDraftReceipt>;
  return freezeApi({ create: (command: NativeCaseDraftCreateCommand, signal?: AbortSignal) => mutation("POST", "/api/v1/native-case-drafts", command, signal), list: (signal?: AbortSignal) => request("/api/v1/native-case-drafts", { method: "GET", credentials: "include", signal }, parseNativeCaseDraftList) as Promise<NativeCaseDraftList>, get: (candidateId: string, signal?: AbortSignal) => request(`/api/v1/native-case-drafts/${encodeURIComponent(candidateId)}`, { method: "GET", credentials: "include", signal }, parseNativeCaseDraftProjection) as Promise<NativeCaseDraftProjection>, update: (candidateId: string, command: NativeCaseDraftUpdateCommand, signal?: AbortSignal) => mutation("PUT", `/api/v1/native-case-drafts/${encodeURIComponent(candidateId)}`, command, signal) });
}
function freezeApi<T extends object>(api: T): Readonly<T> { return Object.freeze(api); }
export const nativeCaseDraftApi = createNativeCaseDraftApi();
