import { webcrypto } from "node:crypto";
import { act,cleanup,fireEvent,render,screen } from "@testing-library/react";
import { afterEach,beforeAll,describe,expect,it,vi } from "vitest";
const mocks=vi.hoisted(()=>({ensureSession:vi.fn(),search:vi.fn(),accountSearch:vi.fn(),capture:vi.fn()}));
const {ensureSession,search,accountSearch,capture}=mocks;
vi.mock("../../src/evidence/candidates/GuestWebDiscoveryApi.ts",()=>({guestWebDiscoveryApi:mocks,GuestWebDiscoveryError:class extends Error{status:number;code:string;constructor(status:number,code:string,message:string){super(message);this.status=status;this.code=code}}}));
vi.mock("../../src/evidence/candidates/WebDiscoveryApi.ts",()=>({webDiscoveryApi:{search:mocks.accountSearch,capture:mocks.capture},buildWebDiscoverySearchCommand:(value:unknown)=>value,buildWebDiscoveryCaptureCommand:(value:unknown)=>value,webDiscoveryAlreadyCaptured:()=>undefined}));
import WebDiscoveryWorkspace from "../../src/evidence/candidates/WebDiscoveryWorkspace.tsx";
import { workspaceRuntime } from "../../src/workspace/runtime/WorkspaceRuntime.ts";
const noop=async()=>{};
const result={resultId:"result-1",providerResultId:"provider-1",rank:1,title:"Primary source lead",providerReturnedUrl:"https://example.test/source",normalizedUrl:"https://example.test/source",displayUrl:"example.test/source",displayDomain:"example.test",snippet:"A metadata-only provider snippet.",mediaType:"text/html",attribution:"Tavily Basic Search",retentionRestrictions:[],providerMetadata:{sourceType:"web"}};
const outcome=(changes:Record<string,unknown>={})=>({schemaVersion:"guest-web-discovery-outcome/v1",operationId:"operation-1",operationState:"COMPLETED",status:"COMPLETED",normalizedQuery:"query",queryNormalizationVersion:"v1",runtimeStatus:"LIVE_WEB_DISCOVERY",adapterId:"tavily",adapterVersion:"v1",startedAt:"2026-09-28T00:00:00Z",completedAt:"2026-09-28T00:00:01Z",expiresAt:"2026-09-28T01:00:00Z",resultCount:1,results:[result],providerAttribution:"Tavily",restrictions:[],warnings:[],error:null,researcherCharge:"0.00",billingTriggered:false,providerCreditsConsumed:1,providerCreditUsage:"ACTUAL",effects:{candidateEvidence:"NONE",researchInbox:"NONE",candidateKnowledge:"NONE",canon:"NONE",graph:"NONE",manifold:"NONE",resolve:"NONE",rex:"NONE"},...changes});
function deferred<T>(){let resolve!:(value:T)=>void;const promise=new Promise<T>(done=>resolve=done);return{promise,resolve}}
async function run(){fireEvent.change(screen.getByLabelText("Web Discovery query"),{target:{value:"primary records"}});await act(async()=>fireEvent.click(screen.getByRole("button",{name:"Run Guest Basic Search"})))}
beforeAll(()=>Object.defineProperty(globalThis,"crypto",{value:webcrypto,configurable:true}));
afterEach(()=>{cleanup();workspaceRuntime.deactivate();ensureSession.mockReset();search.mockReset();accountSearch.mockReset();capture.mockReset()});
describe("Guest Web Discovery",()=>{
 it("runs the first signed-out search and exposes metadata without capture",async()=>{ensureSession.mockResolvedValue({status:"ACTIVE"});search.mockResolvedValue(outcome());render(<WebDiscoveryWorkspace authenticated={false} onCandidateCaptured={noop}/>);expect(screen.getByText("SEARCH · INSPECT · DISPOSABLE")).toBeTruthy();expect(screen.getByText("Guests can search and inspect disposable metadata leads but cannot capture Candidate Evidence.")).toBeTruthy();expect(screen.queryByText("SEARCH · REVIEW · CAPTURE")).toBeNull();await run();expect(ensureSession).toHaveBeenCalledOnce();expect(screen.getByText("Primary source lead")).toBeTruthy();expect(screen.getByText("A metadata-only provider snippet.")).toBeTruthy();expect(screen.getAllByText("Tavily").length).toBeGreaterThan(0);expect(screen.queryByText(/Add to Candidate Evidence|Add to Research Inbox/)).toBeNull()});
 it("preserves account capture wording",()=>{render(<WebDiscoveryWorkspace authenticated={true} scope={{investigationId:"i",principalId:"p"}} binding={{investigationAggregateRevision:1,manifoldRevisionId:"m"}} onCandidateCaptured={noop}/>);expect(screen.getByText("SEARCH · REVIEW · CAPTURE")).toBeTruthy();expect(screen.getByText("Search results are discovery references—not evidence. Capture only the results you want reviewed as Candidate Evidence.")).toBeTruthy();expect(screen.queryByText(/Guests can search and inspect/)).toBeNull()});
 it("shows expiry and restrained save language without claiming transfer",async()=>{ensureSession.mockResolvedValue({status:"ACTIVE"});search.mockResolvedValue(outcome());render(<WebDiscoveryWorkspace authenticated={false} onCandidateCaptured={noop}/>);await run();expect(screen.getByText(/expires/)).toBeTruthy();expect(screen.getByText("Save this investigation?")).toBeTruthy();expect(screen.getByText(/will not be transferred, copied, or saved/)).toBeTruthy()});
 it("discards confirmed leads and provisional effects on reset and sign-in",async()=>{ensureSession.mockResolvedValue({status:"ACTIVE"});search.mockResolvedValue(outcome());const view=render(<WebDiscoveryWorkspace authenticated={false} guestContextKey="guest:a" guestTargets={[{id:"event-1",label:"Event",type:"EVENT"}]} onCandidateCaptured={noop}/>);await run();fireEvent.click(screen.getByRole("button",{name:"Select for Guest Research Inbox"}));fireEvent.click(screen.getByRole("button",{name:"Confirm disposable lead"}));fireEvent.click(screen.getByRole("button",{name:"Reset Guest discovery"}));expect(screen.queryByLabelText("Guest Research Inbox")).toBeNull();expect(screen.queryByText("Primary source lead")).toBeNull();fireEvent.change(screen.getByLabelText("Web Discovery query"),{target:{value:"primary records"}});await act(async()=>fireEvent.click(screen.getByRole("button",{name:"Run Guest Basic Search"})));fireEvent.click(screen.getByRole("button",{name:"Select for Guest Research Inbox"}));fireEvent.click(screen.getByRole("button",{name:"Confirm disposable lead"}));view.rerender(<WebDiscoveryWorkspace authenticated={true} scope={{investigationId:"i",principalId:"p"}} binding={{investigationAggregateRevision:1,manifoldRevisionId:"m"}} guestContextKey="account:p" onCandidateCaptured={noop}/>);await act(async()=>{});expect(screen.queryByLabelText("Guest Research Inbox")).toBeNull();expect(screen.queryByLabelText("Guest event-space provisional preview")).toBeNull()});
 it("expires disposable leads without creating durable effects",async()=>{vi.useFakeTimers();try{ensureSession.mockResolvedValue({status:"ACTIVE"});search.mockResolvedValue(outcome({expiresAt:new Date(Date.now()+100).toISOString()}));render(<WebDiscoveryWorkspace authenticated={false} onCandidateCaptured={noop}/>);await run();fireEvent.click(screen.getByRole("button",{name:"Select for Guest Research Inbox"}));fireEvent.click(screen.getByRole("button",{name:"Confirm disposable lead"}));expect(screen.getByLabelText("Guest Research Inbox")).toBeTruthy();await act(async()=>vi.advanceTimersByTime(101));expect(screen.queryByLabelText("Guest Research Inbox")).toBeNull();expect(capture).not.toHaveBeenCalled()}finally{vi.useRealTimers()}});
 it.each([["GUEST_ALLOWANCE_EXHAUSTED","allowance"],["GUEST_GLOBAL_BUDGET_EXHAUSTED","shared operator-funded budget"],["GUEST_SEARCH_UNAVAILABLE","disabled or unavailable"]])("explains %s",async(code,copy)=>{ensureSession.mockResolvedValue({status:"ACTIVE"});search.mockRejectedValue(Object.assign(new Error("failure"),{code,status:503}));render(<WebDiscoveryWorkspace authenticated={false} onCandidateCaptured={noop}/>);await run();expect(screen.getByRole("alert").textContent).toContain(copy)});
 it("shows in-flight and UNKNOWN outcomes",async()=>{ensureSession.mockResolvedValue({status:"ACTIVE"});search.mockResolvedValueOnce(outcome({operationState:"DISPATCHING",status:"PENDING",resultCount:0,results:[],expiresAt:undefined}));const view=render(<WebDiscoveryWorkspace authenticated={false} onCandidateCaptured={noop}/>);await run();expect(screen.getByText(/already in flight/)).toBeTruthy();search.mockResolvedValueOnce(outcome({operationState:"UNKNOWN",status:"UNKNOWN",resultCount:0,results:[],expiresAt:undefined}));await run();expect(screen.getAllByText(/UNKNOWN/).length).toBeGreaterThan(0);view.unmount()});
 it("clears Guest results and query on account transition and ignores the late response",async()=>{ensureSession.mockResolvedValue({status:"ACTIVE"});const pending=deferred<ReturnType<typeof outcome>>();search.mockReturnValue(pending.promise);const view=render(<WebDiscoveryWorkspace authenticated={false} guestContextKey="guest:a" onCandidateCaptured={noop}/>);fireEvent.change(screen.getByLabelText("Web Discovery query"),{target:{value:"primary records"}});fireEvent.click(screen.getByRole("button",{name:"Run Guest Basic Search"}));view.rerender(<WebDiscoveryWorkspace authenticated={true} scope={{investigationId:"i",principalId:"p"}} binding={{investigationAggregateRevision:1,manifoldRevisionId:"m"}} guestContextKey="account:p" onCandidateCaptured={noop}/>);await act(async()=>pending.resolve(outcome()));expect(screen.queryByText("Primary source lead")).toBeNull();expect(screen.getByRole("button",{name:"Search Web"})).toBeTruthy();expect((screen.getByLabelText("Web Discovery query") as HTMLInputElement).value).toBe("");expect(screen.queryByText("Save this investigation?")).toBeNull()});
 it("clears account search input on transition to Guest",async()=>{const view=render(<WebDiscoveryWorkspace authenticated={true} scope={{investigationId:"i",principalId:"p"}} binding={{investigationAggregateRevision:1,manifoldRevisionId:"m"}} guestContextKey="account:p" onCandidateCaptured={noop}/>);fireEvent.change(screen.getByLabelText("Web Discovery query"),{target:{value:"account query"}});view.rerender(<WebDiscoveryWorkspace authenticated={false} guestContextKey="guest:b" onCandidateCaptured={noop}/>);await act(async()=>{});expect(screen.getByRole("button",{name:"Run Guest Basic Search"})).toBeTruthy();expect((screen.getByLabelText("Web Discovery query") as HTMLInputElement).value).toBe("")});
 it("cleans up its owned overlay on unmount without erasing a newer surface overlay",async()=>{workspaceRuntime.setActiveInvestigation({id:"guest-investigation"} as never);ensureSession.mockResolvedValue({status:"ACTIVE"});search.mockResolvedValue(outcome());const view=render(<WebDiscoveryWorkspace authenticated={false} guestInvestigationId="guest-investigation" guestTargets={[{id:"event-1",label:"Event",type:"EVENT"}]} onCandidateCaptured={noop}/>);await run();fireEvent.click(screen.getByRole("button",{name:"Select for Guest Research Inbox"}));fireEvent.click(screen.getByRole("button",{name:"Confirm disposable lead"}));fireEvent.change(screen.getByLabelText("Governed event or node for Primary source lead"),{target:{value:"event-1"}});fireEvent.click(screen.getByRole("button",{name:"Propose provisional connection"}));const owned=workspaceRuntime.getGuestDiscoveryOverlay()!;expect(owned).toBeTruthy();const newer={...owned,proposedBy:"guest:newer"};workspaceRuntime.setGuestDiscoveryOverlay(newer);view.unmount();expect(workspaceRuntime.getGuestDiscoveryOverlay()).toBe(newer)});
 it("clears the disposable overlay on the Guest-to-account identity transition",async()=>{workspaceRuntime.setActiveInvestigation({id:"guest-investigation"} as never);ensureSession.mockResolvedValue({status:"ACTIVE"});search.mockResolvedValue(outcome());const view=render(<WebDiscoveryWorkspace authenticated={false} guestContextKey="guest:identity" guestInvestigationId="guest-investigation" guestTargets={[{id:"event-1",label:"Event",type:"EVENT"}]} onCandidateCaptured={noop}/>);await run();fireEvent.click(screen.getByRole("button",{name:"Select for Guest Research Inbox"}));fireEvent.click(screen.getByRole("button",{name:"Confirm disposable lead"}));fireEvent.change(screen.getByLabelText("Governed event or node for Primary source lead"),{target:{value:"event-1"}});fireEvent.click(screen.getByRole("button",{name:"Propose provisional connection"}));expect(workspaceRuntime.getGuestDiscoveryOverlay()).toBeTruthy();view.rerender(<WebDiscoveryWorkspace authenticated={true} scope={{investigationId:"guest-investigation",principalId:"account:p"}} binding={{investigationAggregateRevision:1,manifoldRevisionId:"m"}} guestContextKey="guest-investigation:ACCOUNT:account:p" guestInvestigationId="guest-investigation" guestTargets={[{id:"event-1",label:"Event",type:"EVENT"}]} onCandidateCaptured={noop}/>);await act(async()=>{});expect(workspaceRuntime.getGuestDiscoveryOverlay()).toBeUndefined();expect(screen.queryByLabelText("Guest Research Inbox")).toBeNull();expect(screen.getByRole("button",{name:"Search Web"})).toBeTruthy()});
});
