import { useMemo, useState } from "react";
import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { describe, expect, it, vi } from "vitest";
import { readFileSync } from "node:fs";
import { StudioArtifactFamily } from "../../src/studio/components/StudioArtifactFamily.tsx";
import { StudioSaveActionContext, type StudioSaveActionContextValue } from "../../src/studio/runtime/StudioSaveActionContext.ts";
import type { ManifoldArtifactManifest } from "../../src/studio/contracts/StudioV1Contract.ts";
import type { StudioV1SaveState } from "../../src/studio/v1/runtime/StudioV1SaveOrchestrator.ts";

const manifest=JSON.parse(readFileSync("../contracts/studio-v1/fixtures/studio-v1-contract-fixtures.json","utf8")).manifoldArtifactManifest as ManifoldArtifactManifest;
const outputHash="sha256:fb09c4745288a006f106a6e7f1ff16b85d9c1d1992f5b40180d84787492bf90a";
const projection={projectionId:"projection-1",format:"MANIFOLD_ARTIFACT" as const,parentRevisionId:manifest.source.revisionId,state:"CURRENT" as const,failureCategory:null,outputHash};
const base:StudioV1SaveState={status:"SAVED",documentId:manifest.source.documentId,investigationId:manifest.source.investigationId,artifactId:manifest.source.artifactId,ownerPrincipalId:"principal-1",headRevisionId:manifest.source.revisionId,revisionNumber:1,contentHash:manifest.source.contentHash,message:"Saved",canSave:false,retryable:false,revisions:[],revisionPreviewStatus:"IDLE",projections:{artifactId:manifest.source.artifactId,revisionId:manifest.source.revisionId,items:[projection]},manifoldArtifact:{projectionId:projection.projectionId,artifactId:manifest.source.artifactId,revisionId:manifest.source.revisionId,revisionNumber:1,parentContentHash:manifest.source.contentHash,format:"MANIFOLD_ARTIFACT",state:"CURRENT",schemaVersion:"studio-manifold-artifact-manifest/v1",rendererVersion:"studio-v1-manifold-artifact/1",configurationIdentity:"manifold-artifact-default",configurationVersion:"1",configurationHash:"sha256:c09c4148dfafd4193cf3abad180990ab8ab4dc8a093262a7d3b4c9f9322d56e5",outputHash,mediaType:"application/vnd.isees.manifold-artifact+json",filename:"report.manifold-artifact.projection",byteLength:1,failureCategory:null,failureMessage:null,downloadAvailable:true}};

function Harness({materialize=vi.fn(async()=>{})}:{materialize?:()=>Promise<void>}){const [state,setState]=useState(base);const value=useMemo<StudioSaveActionContextValue>(()=>({state,admission:{authenticated:true,guest:false,eligible:true,investigationId:manifest.source.investigationId,operationalHeadId:"REV-0001",eligibleNodeIds:["knowledge-1"],pending:false,stale:false,message:""},save:async()=>{},retry:async()=>{},reloadHead:async()=>{},keepLocalDraft:()=>{},listRevisions:async()=>undefined,loadRevision:async()=>undefined,clearRevisionPreview:()=>{},inspectProjections:async()=>undefined,materializeManifoldArtifact:materialize,inspectManifoldArtifact:async()=>setState(value=>({...value,manifoldManifest:manifest})),downloadManifoldArtifact:async()=>undefined,closeManifoldInspector:()=>setState(value=>({...value,manifoldManifest:undefined})),admitManifoldArtifact:async()=>true,refreshAdmissionAuthority:async()=>{},viewAdmittedArtifact:()=>{}}),[materialize,state]);return <StudioSaveActionContext.Provider value={value}><StudioArtifactFamily state={state} dirty={true}/></StudioSaveActionContext.Provider>}

describe("Studio MANIFOLD_ARTIFACT card",()=>{
 it("keeps generation explicit and restores focus after keyboard dismissal",async()=>{const user=userEvent.setup(),materialize=vi.fn(async()=>{}),historyLength=history.length;render(<Harness materialize={materialize}/>);expect(screen.getAllByRole("article")).toHaveLength(4);expect(materialize).not.toHaveBeenCalled();expect(screen.getByText("Projected · Not admitted to Manifold.")).toBeTruthy();await user.click(screen.getByRole("button",{name:"CREATE MANIFOLD ARTIFACT"}));expect(materialize).toHaveBeenCalledTimes(1);const trigger=screen.getByRole("button",{name:"INSPECT MANIFEST"});await user.click(trigger);expect(document.activeElement).toBe(screen.getByRole("dialog",{name:"MANIFOLD ARTIFACT manifest"}));expect(screen.getAllByText("NONE").length).toBeGreaterThan(0);await user.keyboard("{Escape}");expect(screen.queryByRole("dialog")).toBeNull();expect(document.activeElement).toBe(trigger);expect(history.length).toBe(historyLength)});
});
