import assert from "node:assert/strict";
import { AuthorDocumentRuntime } from "../../src/author/runtime/AuthorDocumentRuntime.ts";
import type { ComputationalAuthorDocument } from "../../src/author/model/AuthorDocument.ts";
import { AuthorNodeTypes } from "../../src/author/model/AuthorNodeTypes.ts";
import type { StudioV1AuthorApiClient } from "../../src/studio/v1/api/StudioV1AuthorApiClient.ts";
import type { SaveAuthorRequest } from "../../src/studio/v1/api/StudioV1AuthorApiTypes.ts";
import { StudioV1AuthorClientError } from "../../src/studio/v1/api/StudioV1AuthorApiTypes.ts";
import { StudioV1SaveOrchestrator } from "../../src/studio/v1/runtime/StudioV1SaveOrchestrator.ts";
import { adaptAuthorDocument } from "../../src/studio/v1/runtime/StudioV1AuthorAdapter.ts";
import { readFileSync } from "node:fs";

let assertions=0;const check=(value:unknown,message:string)=>{assert.ok(value,message);assertions++};
const document=():ComputationalAuthorDocument=>({identity:{id:"author-document-1",createdAt:new Date("2026-09-10T12:00:00.000Z")},metadata:{title:"Investigation report",description:"",author:"",modifiedAt:new Date("2026-09-10T12:00:00.000Z"),version:1},type:"DOCUMENT",status:"NEW",nodes:[{id:"paragraph-1",type:AuthorNodeTypes.PARAGRAPH,text:"Researcher-authored finding.",section:"Analysis"}]});
type Deferred={resolve:(value:{artifactId:string;revisionId:string;revisionNumber:number;projectionIds:string[];replayed:boolean})=>void;promise:Promise<{artifactId:string;revisionId:string;revisionNumber:number;projectionIds:string[];replayed:boolean}>};
const deferred=():Deferred=>{let resolve!:Deferred["resolve"];const promise=new Promise<Parameters<Deferred["resolve"]>[0]>(r=>{resolve=r});return{resolve,promise}};
const requests:SaveAuthorRequest[]=[];let creates=0,saves=0,gets=0,lists=0,revisionGets=0,projectionGets=0;let pending:Deferred|undefined;let failure:StudioV1AuthorClientError|undefined;
const api:StudioV1AuthorApiClient={async createArtifact(_i,request){creates++;requests.push(request);if(failure)throw failure;if(pending)return pending.promise;return{artifactId:request.artifact.artifactId,revisionId:request.revision.revisionId,revisionNumber:request.revision.revisionNumber,projectionIds:[],replayed:false}},async saveRevision(_i,_a,request){saves++;requests.push(request);if(failure)throw failure;if(pending)return pending.promise;return{artifactId:request.artifact.artifactId,revisionId:request.revision.revisionId,revisionNumber:request.revision.revisionNumber,projectionIds:[],replayed:false}},async getArtifact(_i,a){gets++;return{artifactId:a,currentRevisionId:requests.at(-1)!.revision.revisionId,currentRevisionNumber:requests.at(-1)!.revision.revisionNumber,contentHash:requests.at(-1)!.revision.contentHash,savedAt:requests.at(-1)!.revision.createdAt}},async listRevisions(_i,a){lists++;return{artifactId:a,items:[...requests].reverse().map(r=>({revisionId:r.revision.revisionId,revisionNumber:r.revision.revisionNumber,parentRevisionId:r.revision.parentRevisionId??null,contentHash:r.revision.contentHash,savedAt:r.revision.createdAt,sourceSnapshots:r.revision.sourceSnapshots}))}},async getRevision(_i,a,r){revisionGets++;const request=requests.find(x=>x.revision.revisionId===r)!;return{artifactId:a,revision:{...request.revision,authorPrincipalId:"server-owned"}}},async listProjectionStatuses(_i,a,r){projectionGets++;return{artifactId:a,revisionId:r,items:[]}}};

const runtime=new AuthorDocumentRuntime();runtime.activateInvestigation("investigation-1");const owner=new StudioV1SaveOrchestrator(api,(()=>{let n=0;return()=>`id-${++n}`})(),()=>"2026-09-10T12:00:00.000Z");owner.observe(undefined,false,"investigation-1");check(creates===0,"mount/observe performs no request");runtime.setActiveDocument(document());owner.observe(runtime.getActiveDocument(),runtime.isDirty(),runtime.getActiveInvestigationId());check(creates===0,"New Document performs no request");check(owner.getState().status==="LOCAL_DRAFT","new document is local draft");await owner.save(runtime,false);check(creates===0,"guest save is transport-blocked");check(owner.getState().message==="Sign in to save this .author document.","guest guidance is explicit");check(Boolean(runtime.getActiveDocument()),"guest draft is preserved");
owner.observe(runtime.getActiveDocument(),runtime.isDirty(),runtime.getActiveInvestigationId());pending=deferred();const one=owner.save(runtime,true);const rapid=owner.save(runtime,true);check(one===rapid,"rapid saves share one mutation");check(creates===1,"initial save calls one POST");const first=requests[0]!;check(first.artifact.investigationId==="investigation-1","investigation is explicit");check(!("authorPrincipalId" in first.artifact)&&!("authorPrincipalId" in first.revision),"principal is absent");check(first.revision.revisionNumber===1&&!first.expectedHeadRevisionId,"initial revision contract");const firstKey=first.idempotencyKey,firstArtifact=first.artifact.artifactId,firstRevision=first.revision.revisionId;runtime.updateNodeText("paragraph-1","Edited while saving");pending.resolve({artifactId:firstArtifact,revisionId:firstRevision,revisionNumber:1,projectionIds:[],replayed:false});await one;pending=undefined;check(owner.getState().status==="DIRTY","edit during save remains dirty");check(owner.getState().headRevisionId===firstRevision,"success records head");check(owner.getState().revisionNumber===1,"success records revision number");
await owner.save(runtime,true);check(saves===1,"revision save calls saveRevision");const second=requests[1]!;check(second.artifact.artifactId===firstArtifact,"artifact identity is stable");check(second.expectedHeadRevisionId===firstRevision,"expected head supplied");check(second.revision.parentRevisionId===firstRevision,"parent revision supplied");check(second.revision.revisionId!==firstRevision,"new immutable revision identity");check(second.revision.revisionNumber===2,"revision increments");check(owner.getState().status==="SAVED","acknowledged exact draft is saved");check(owner.getState().message==="Saved — revision 2","revision visible");
runtime.updateNodeText("paragraph-1","Third revision");owner.observe(runtime.getActiveDocument(),true,"investigation-1");failure=new StudioV1AuthorClientError("NETWORK_FAILURE","offline","saveRevision");await owner.save(runtime,true);const failed=requests.at(-1)!;check(owner.getState().status==="UNAVAILABLE","unavailable state");check(owner.getState().headRevisionId===second.revision.revisionId,"failure does not advance head");failure=undefined;await owner.save(runtime,true);check(requests.at(-1)!.idempotencyKey===failed.idempotencyKey,"retry reuses idempotency key");check(owner.getState().revisionNumber===3,"retry advances once");
runtime.updateNodeText("paragraph-1","Conflict local");owner.observe(runtime.getActiveDocument(),true,"investigation-1");failure=new StudioV1AuthorClientError("EXPECTED_HEAD_CONFLICT","stale","saveRevision",{conflict:true});await owner.save(runtime,true);check(owner.getState().status==="CONFLICT","conflict explicit");check(runtime.getActiveDocument()!.nodes[0]&&"text" in runtime.getActiveDocument()!.nodes[0]&&runtime.getActiveDocument()!.nodes[0].text==="Conflict local","conflict preserves local draft");owner.keepLocalDraft();check(owner.getState().status==="DIRTY","keep-local is explicit");failure=undefined;
await owner.listRevisions();check(lists===1,"revision list read");check(owner.getState().revisions[0]!.revisionNumber>=owner.getState().revisions.at(-1)!.revisionNumber,"revision order deterministic");const history=await owner.loadRevision(firstRevision);check(revisionGets===1&&history?.revision.revisionId===firstRevision,"historical revision loads");check(owner.getState().historicalRevisionId===firstRevision&&!owner.getState().canSave,"historical revision is read-only");await owner.inspectProjections();check(projectionGets===1,"projection status is read-only");
const before=JSON.stringify(runtime.getActiveDocument());const a=adaptAuthorDocument(runtime.getActiveDocument()!,"investigation-1",{snapshotId:"snapshot-1",capturedAt:"2026-09-10T12:00:00.000Z"});const b=adaptAuthorDocument(runtime.getActiveDocument()!,"investigation-1",{snapshotId:"snapshot-1",capturedAt:"2026-09-10T12:00:00.000Z"});check(JSON.stringify(a)===JSON.stringify(b),"adaptation deterministic");check(JSON.stringify(runtime.getActiveDocument())===before,"adapter does not mutate input");check(a.semanticContent.citations.length===0&&a.snapshots.length===0,"no citation or snapshot fabricated");check(a.semanticContent.nodes[0]?.type==="PARAGRAPH","structured paragraph retained");check(first.revision.contentHash.startsWith("sha256:"),"shared canonical hash used");
const empty=document();empty.nodes=[];assert.throws(()=>adaptAuthorDocument(empty,"investigation-1",{snapshotId:"x",capturedAt:"2026-09-10T12:00:00.000Z"}),/at least one/);assertions++;check(gets===0,"no automatic head read");check(projectionGets===1,"save never calls projection workers");check(creates+saves===requests.length,"only declared save mutations occurred");check(firstKey!==second.idempotencyKey,"new logical revision gets new idempotency key");owner.dispose();check(Boolean(runtime.getActiveDocument()),"dispose preserves local document");
const inspector=readFileSync(new URL("../../src/studio/components/StudioArtifactInspector.tsx",import.meta.url),"utf8");check(/await saveAction\.save\(\)/.test(inspector),"Artifact Inspector Save Draft delegates to Studio V1");check(!/composeStudioVersionCommand/.test(inspector),"Artifact Inspector save does not compose a legacy version command");
console.log(`Studio V1 I8 orchestration verification passed (${assertions} assertions).`);
