import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { assembleTopologySimilarityBriefing, TOPOLOGY_SIMILARITY_DEFINITION, topologySimilaritySourceFromProjection } from "../../src/metric-intelligence/TopologySimilarityMetricIntelligence.ts";
import type { MetricIntelligenceSource } from "../../src/metric-intelligence/MetricIntelligenceTypes.ts";
import { collectMetricFinding, createMetricFindingResearchAnchor } from "../../src/metric-intelligence/MetricFindingResearchPublication.ts";
import { ResearchBridgeRuntime } from "../../src/research/ResearchBridgeRuntime.ts";
import { createGuestWorkspaceSessionSnapshot, isGuestWorkspaceSessionSnapshot } from "../../src/workspace/persistence/GuestWorkspaceSessionPersistence.ts";

let count=0; const pass=(message:string)=>{count++;console.log(`PASS ${count} — ${message}`);};
const component=(role:"CASE_A"|"CASE_B",id:string,name:string,value:number)=>({availability:"AVAILABLE",subjectKnowledgeObjectId:id,componentIdentity:`TOPOLOGY.${name}`,rawValue:value,lineage:{source:"KNOWLEDGE_PAYLOAD",sourceKnowledgeObjectIds:[id],sources:[{knowledgeObjectId:id,sourceIdentity:`source:${id}`,sourceVersion:"v1",sourceRevision:"1"}]}});
const names=["clusterFragmentation","contradictionDensity","entanglementScore","residualInstability"];
const endpoints=[{subjectRole:"CASE_A",subjectIdentity:"E-TICTAC-2004",knowledgeObjectId:"ko:tictac",endpointSnapshotId:"snapshot:a",components:names.map((name,index)=>component("CASE_A","ko:tictac",name,[.12,.22,.88,.71][index]!))},{subjectRole:"CASE_B",subjectIdentity:"E-RENDLESHAM-1980",knowledgeObjectId:"ko:rendlesham",endpointSnapshotId:"snapshot:b",components:names.map((name,index)=>component("CASE_B","ko:rendlesham",name,[.15,.27,.84,.69][index]!))}] as const;
const contribution={layerId:"EXPERIMENTAL:TOPOLOGY",classification:"CANONICAL",operationalMappingStatus:"MAPPED",canonicalDimension:"TOPOLOGY",evaluatorKey:"TOPOLOGY",evaluatorVersion:"canonical-similarity/v1",normalization:{normalizationKey:"CANONICAL_DIMENSION_SIMILARITY",normalizationVersion:"canonical-similarity/v1"},normalizedResult:.955,availability:"AVAILABLE",similarity:.955,canonicalWeight:.25,participatingWeight:1,weightedContribution:.955,sourceEvaluationId:"evaluation:1"};
const projection={kind:"LAYERS_EXPERIMENTAL_PAIR_PROJECTION",projectionId:"projection:1",investigationId:"investigation:1",executionId:"execution:1",pairId:"pair:1",candidateId:"candidate:1",evaluationId:"evaluation:1",evaluatorInput:{kind:"CANONICAL_LAYER_EVALUATOR_INPUT_PROJECTION",inputSchemaVersion:"layer-evaluator-input/v1",experimentSchemaVersion:"layers-experiment/v2",catalogVersion:"layers-catalog/v2",inputProjectionId:"input:1",investigationId:"investigation:1",pairId:"pair:1",candidateId:"candidate:1",evaluationId:"evaluation:1",executionId:"execution:1",endpoints,canonicalRepresentation:"immutable"},subjects:[],baseline:{relationship:{availability:"UNAVAILABLE"}},experimental:{relationship:{availability:"AVAILABLE",score:.955}},layerContributions:[contribution],unavailableInputs:[],delta:{state:"FORMED",experimentalScore:.955},provenance:{experimentSchemaVersion:"layers-experiment/v2",catalogVersion:"layers-catalog/v2",governingEquation:"M = g(L,T,S)",executionId:"execution:1",investigationId:"investigation:1",pairId:"pair:1",candidateId:"candidate:1",evaluationId:"evaluation:1",baselineLayerIds:[],experimentalLayerIds:["TOPOLOGY"],participatingLayerIds:["TOPOLOGY"],unavailableLayerIds:[],selectedLayerIds:["TOPOLOGY"],canonicalRepresentation:"immutable"},createsCanonicalKnowledgeRelationship:false} as unknown as Parameters<typeof topologySimilaritySourceFromProjection>[0];

const source=topologySimilaritySourceFromProjection(projection,{caseA:"Tic Tac",caseB:"Rendlesham"}); const first=assembleTopologySimilarityBriefing(source); const second=assembleTopologySimilarityBriefing(source);
assert.equal(JSON.stringify(first),JSON.stringify(second)); assert.equal(first.findingId,second.findingId); assert(Object.isFrozen(first)&&Object.isFrozen(first.source)&&Object.isFrozen(first.source.endpoints[0].components)); pass("identical immutable inputs produce byte-identical deeply frozen briefings and stable IDs");
for(const change of [{value:.954},{executionId:"execution:2"},{pairId:"pair:2"},{evaluator:{key:"TOPOLOGY",version:"canonical-similarity/v2"}},{normalization:{key:"CANONICAL_DIMENSION_SIMILARITY",version:"canonical-similarity/v2"}}]) { const changed={...source,...change} as MetricIntelligenceSource; if(change.evaluator||change.normalization) assert.throws(()=>assembleTopologySimilarityBriefing(changed)); else assert.notEqual(assembleTopologySimilarityBriefing(changed).findingId,first.findingId); } assert.throws(()=>assembleTopologySimilarityBriefing(source,{...TOPOLOGY_SIMILARITY_DEFINITION,briefingTemplateVersion:"v2"})); pass("score, execution, pair, evaluator, normalization, and template staleness change identity or fail closed");
assert.throws(()=>assembleTopologySimilarityBriefing({...source,executionId:""})); assert.throws(()=>topologySimilaritySourceFromProjection({...projection,layerContributions:[]})); assert.throws(()=>topologySimilaritySourceFromProjection({...projection,evaluatorInput:{...projection.evaluatorInput,executionId:"stale"}})); pass("incomplete, unsupported, and stale sources fail closed");
assert(first.microBriefing.length<90&&first.microBriefing.includes("95.5%")&&first.pairDisplay==="Tic Tac ↔ Rendlesham"); for(const token of ["does not mean there is a 95.5% chance","topology evaluator","Why do two distinct cases","Similarity is not probability","Similarity is not causation or proof","Topology similarity is not full-case similarity","not a canonical relationship","EXPERIMENTAL / DERIVED / NON-CANONICAL"]) assert(JSON.stringify(first).includes(token),token); pass("briefing is concise, conversational, and preserves all epistemic boundaries");
assert.deepEqual(source.endpoints[0].components.map(x=>x.value),[.12,.22,.88,.71]); assert.equal(source.canonicalConfiguredWeight,.25); assert.equal(source.participatingNormalizedWeight,1); pass("basis reads four frozen endpoint components and both weight meanings without recomputation");
const runtime=new ResearchBridgeRuntime(); const a=collectMetricFinding(first,runtime); const b=collectMetricFinding(first,runtime); assert.equal(a.anchorId,b.anchorId); assert.equal(runtime.getDesk().entries.length,1); assert.equal(a.kind,"METRIC_FINDING"); assert.equal(a.insertability.state,"INSPECTION_ONLY"); const newer=createMetricFindingResearchAnchor(assembleTopologySimilarityBriefing({...source,executionId:"execution:2"})); assert.notEqual(newer.anchorId,a.anchorId); pass("double/button-equivalent repeated collection deduplicates while a new execution is distinct");
const authorAt=new Date("2026-01-01T00:00:00.000Z"); const snapshot=createGuestWorkspaceSessionSnapshot({ownership:{kind:"GUEST",operatorId:"guest:metric-intelligence",establishedAt:authorAt.toISOString()},workspace:{operator:{activeMode:"OVERVIEW" as const,layoutMode:"NORMAL" as const},computational:{activeLayers:[]}},research:{desk:runtime.getDesk()},authoring:{activeDocument:{identity:{id:"author:metric-intelligence",createdAt:authorAt},metadata:{title:"Metric Intelligence",description:"Canonical persistence fixture",author:"guest:metric-intelligence",modifiedAt:authorAt,version:1},type:"DOCUMENT",status:"NEW",nodes:[]}}}); assert(isGuestWorkspaceSessionSnapshot(JSON.parse(JSON.stringify(snapshot)))); pass("metric finding survives existing Research guest persistence validation");
const trigger=readFileSync("src/metric-intelligence/MetricIntelligenceTrigger.tsx","utf8"); for(const token of ["role=\"tooltip\"","role=\"dialog\"","aria-modal=\"true\"","Enter","event.key === \" \"","Escape","trigger.current?.focus()","onDoubleClick","Add to Research Inbox","onPointerEnter","onFocus"]) assert(trigger.includes(token),token); assert(trigger.includes("210")&&trigger.includes("event.detail > 1")); pass("shared trigger exposes hover/focus, bounded click/double-click, keyboard, focus restoration, and explicit touch collection paths");
const assembler=readFileSync("src/metric-intelligence/TopologySimilarityMetricIntelligence.ts","utf8"); for(const forbidden of ["fetch(","XMLHttpRequest","axios","OpenAI","languageModel","Date.now","Math.random"]) assert(!assembler.includes(forbidden),forbidden); pass("assembler has no AI, drafting, clock, randomness, HTTP, or network dependency");
const layers=readFileSync("src/layers/components/LayersExperimentalIntelligence.tsx","utf8"); assert(layers.includes("MetricIntelligenceTrigger")&&layers.includes("Publish Experiment to Research")); assert.equal(projection.createsCanonicalKnowledgeRelationship,false); pass("metric trigger and separate complete-experiment publication coexist without canonical mutation");
console.log(`PASS VerifyMetricIntelligenceFoundation — ${count} groups verified`);
