import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

let passCount = 0;
const check = (value: unknown, message: string): void => { assert(value, message); passCount += 1; };
const includes = (source: string, value: string, message = value): void => check(source.includes(value), message);
const workspace = readFileSync("src/workspace/surfaces/EvidenceWorkspace.tsx", "utf8");
const component = readFileSync("src/evidence/candidates/WebDiscoveryWorkspace.tsx", "utf8");
const controller = readFileSync("src/evidence/candidates/WebDiscoveryWorkspaceController.ts", "utf8");
const css = readFileSync("src/workspace/surfaces/EvidenceWorkspace.css", "utf8");
const all = component + controller;

includes(workspace, "<WebDiscoveryWorkspace", "EVIDENCE composes the modular discovery surface");
includes(workspace, 'operator.identity?.kind === "ACCOUNT" ? apiScope : undefined', "only authenticated account identity creates Web Discovery scope");
includes(workspace, "const principalId = operator.identity?.operatorId", "existing Candidate Evidence scope remains intact");
includes(workspace, "candidateEvidenceApi.list(apiScope)", "existing Candidate Evidence owner performs refresh");
includes(workspace, "selectedCandidateId: candidateId", "created Candidate Evidence is selected after refresh");
includes(component, "Web Discovery query", "query has a visible associated label");
includes(component, 'onSubmit={submit}', "search requires explicit form submission");
includes(component, '!discovery.query.trim()', "empty and whitespace-only query disables search");
includes(controller, "const normalized = query.trim()", "controller independently rejects whitespace");
includes(controller, "expectedInvestigationRevision: binding.investigationAggregateRevision", "search and capture use authoritative aggregate revision");
includes(controller, "manifoldRevisionId: binding.manifoldRevisionId", "search and capture use authoritative Manifold revision");
includes(controller, "scope.principalId", "ephemeral state binding includes active principal");
includes(controller, "scope.investigationId", "commands and state bind active Investigation identity");
includes(component, "REVIEW · EPHEMERAL", "review state is visibly ephemeral");
includes(component, "No Candidate Evidence was created by search", "search visibly declares zero Candidate Evidence effect");
includes(component, "Capture as Candidate Evidence", "capture is an explicit per-result action");
includes(component, 'role="dialog"', "capture uses dialog semantics");
includes(component, "Confirm capture", "capture requires a second explicit confirmation");
includes(component, "Cancel", "confirmation can be cancelled");
includes(controller, "cancelCapture", "cancel has a no-transport controller path");
includes(controller, "if (!scope || !binding || !response || !confirmation || capturePending) return", "capture cannot occur before confirmation and duplicate pending clicks are blocked");
includes(controller, "searchSessionId: response.searchSessionId", "capture uses opaque session authority");
includes(controller, "resultId,", "capture targets one opaque result identity");
const captureCall = controller.match(/buildWebDiscoveryCaptureCommand\(\{([\s\S]*?)\}\)\)/)?.[1] ?? "";
for (const forbidden of ["title", "providerReturnedUrl", "normalizedUrl", "snippet", "attribution", "mediaType", "providerMetadata", "retentionRestrictions"]) check(!captureCall.includes(forbidden), `capture command excludes result ${forbidden}`);
includes(component, 'captured.disposition === "CREATED"', "created capture outcome has distinct feedback");
includes(component, "Already captured / replayed", "replayed capture outcome has distinct feedback");
includes(controller, "await onCandidateCaptured(outcome.candidateId)", "successful capture invokes only Candidate Evidence refresh callback");
includes(controller, "webDiscoveryAlreadyCaptured(caught)", "authoritative duplicate conflict is recognized as a governed replay");
includes(controller, "[resultId]: replayed", "duplicate replay visibly binds the stable Candidate Evidence identity to the result");
check((controller.match(/setConfirmation\(undefined\)/g) ?? []).length >= 4, "duplicate replay deterministically completes the confirmation modal");
includes(controller, "await onCandidateCaptured(replayed.candidateId)", "duplicate replay refreshes and selects the existing Candidate Evidence projection");
for (const forbidden of ["ResearchInbox", "ResearchBridge", "CuratedContext", "CandidateKnowledge", "Canon", "GraphRuntime", "ManifoldRuntime", "Resolve", "Studio", "Rex", "AI", "charge", "cost"]) check(!controller.includes(forbidden), `controller has no downstream ${forbidden} integration`);
includes(controller, "setResponse(undefined)", "authority binding changes clear ephemeral results");
for (const state of ["authenticated session has expired", "not available to the authenticated account", "revision changed", "discovery session expired"]) includes(controller, state, `recoverable ${state} message exists`);
includes(component, "server-authorized Web Discovery runtime", "search presentation preserves server provider authority");
includes(component, "Browser commands contain no provider choice or credential", "browser has no provider-selection authority");
for (const runtime of ["Live Tavily Web Discovery", "Explicit offline fixture · no live web access", "Web Discovery unavailable · server configuration disabled or invalid", "Live Tavily · bounded provider failure"]) includes(component, runtime, `runtime presentation includes ${runtime}`);
for (const status of ["OFFLINE_FIXTURE", "UNAVAILABLE", "RATE_LIMITED", "FAILED"]) includes(component, status, `runtime presentation handles ${status}`);
check(!controller.includes("adapterId") && !controller.includes("adapterVersion"), "browser search command contains no provider metadata");
includes(component, 'target="_blank" rel="noopener noreferrer"', "external sources use safe new-tab behavior");
includes(component, 'aria-live="polite"', "search state is announced");
includes(component, 'role="alert"', "structured errors are announced");
includes(component, "Researcher note (optional)", "authoritative optional note is exposed");
includes(component, "This creates one review-only Candidate Evidence item. It does not publish, add to Research Inbox, or alter the Manifold.", "confirmation states exact downstream boundary");
includes(controller, "commandIdentity(\"session\")", "each search gets a new session identity");
includes(controller, "commandIdentity(\"search-operation\")", "each search gets a distinct operation identity");
includes(controller, "commandIdentity(\"search-idempotency\")", "each search gets a distinct idempotency identity");
includes(controller, "commandIdentity(\"capture-operation\")", "confirmation receives a stable capture operation identity");
includes(controller, "commandIdentity(\"capture-idempotency\")", "confirmation receives a stable capture idempotency identity");
check((controller.match(/webDiscoveryApi\.capture/g) ?? []).length === 1, "exactly one capture transport boundary exists");
check((controller.match(/webDiscoveryApi\.search/g) ?? []).length === 1, "exactly one search transport boundary exists");
check(!all.includes("fetch("), "workspace creates no second fetch stack");
check(!all.includes("X-ISEES-CSRF"), "workspace creates no second CSRF implementation");
check(!all.includes("window.confirm"), "result selection does not implicitly confirm capture");
includes(css, ".web-discovery{min-width:0", "discovery surface prevents intrinsic horizontal overflow");
includes(css, "@media(max-width:720px)", "existing narrow-width boundary covers discovery composition");
includes(css, ".web-discovery__results{grid-template-columns:minmax(0,1fr)}", "result cards collapse to one bounded column");
includes(workspace, "Researcher-directed intake", "existing intake remains composed");
includes(workspace, "Direct media upload", "existing direct upload remains composed");
includes(workspace, "Investigation Evidence", "existing Investigation Evidence remains composed");
includes(workspace, "Curated Context", "existing Curated Context remains composed");

console.log(`PASS VerifyWebDiscoveryWorkspace — ${passCount} focused assertions passed`);
