import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { ResearchBridgeRuntime } from "../../src/research/ResearchBridgeRuntime.ts";
import { createRexApi, type RexCandidateBundle, type RexReceipt } from "../../src/rex/RexApi.ts";
import { createRexDiscoveryAnchors } from "../../src/rex/RexResearchInboxProjection.ts";

const H=`sha256:${"a".repeat(64)}`, H2=`sha256:${"b".repeat(64)}`, when="2026-09-17T14:19:36.649737Z";
const receipt:RexReceipt={executionId:"execution-1",jobId:"job-1",assignmentId:"assignment-1",assignmentRevisionId:"assignment-revision-1",manifoldRevisionId:"investigation-aggregate:1",manifoldRevisionHash:H,sourceAdapterIdentity:"rex-local-immutable-fixture",sourceAdapterVersion:"1.0.0",normalizerIdentity:"rex-fixture-claim-conserving-normalizer",normalizerVersion:"1.0.0",candidateBundleId:"bundle-1",candidateContentHash:H2,sourceContentHash:H,aiAssistanceStatus:"NONE",providerIdentity:"NONE",modelIdentity:"NONE",estimatedMicros:0,reservedMicros:0,actualMicros:0,chargedMicros:0,releasedMicros:0,terminalExecutionStatus:"COMPLETED",completedAt:when,contentHash:H2};
const bundle:RexCandidateBundle={candidateBundleId:"bundle-1",investigationId:"investigation-1",assignmentRevisionId:"assignment-revision-1",executionId:"execution-1",manifoldRevisionId:"investigation-aggregate:1",manifoldRevisionHash:H,sourceLocator:"rex-fixture://synthetic-observation/v1",sourceVersion:"1.0.0",sourceClassification:"LOCAL_FIXTURE",adapterIdentity:receipt.sourceAdapterIdentity,adapterVersion:receipt.sourceAdapterVersion,normalizerIdentity:receipt.normalizerIdentity,normalizerVersion:receipt.normalizerVersion,sourceContentHash:H,candidateContentHash:H2,candidateClassification:"CANDIDATE_KNOWLEDGE",reviewStatus:"RESEARCHER_REVIEW_REQUIRED",canonEffect:"NONE",aiAssistanceStatus:"NONE",providerIdentity:"NONE",modelIdentity:"NONE",modelClass:"NONE",nodes:[{candidateId:"candidate-node",kind:"OBSERVATION",label:"Reported blue indicator",claim:"A synthetic report.",candidateContentHash:H}],edges:[{candidateId:"candidate-edge",kind:"PROPOSED_RELATIONSHIP",label:"Possible relation",sourceCandidateId:"candidate-node",targetCandidateId:"selected-node",proposedRelationship:"MAY_RELATE_TO",candidateContentHash:H2}],fieldLineage:[{candidateId:"candidate-node",sourceLocator:"rex-fixture://synthetic-observation/v1",sourceVersion:"1.0.0",fields:[{candidateField:"label",sourceField:"candidate_label",exactValue:"Reported blue indicator",normalizationRule:"EXACT_STRUCTURED_FIELD/v1"}]},{candidateId:"candidate-edge",sourceLocator:"rex-fixture://synthetic-observation/v1",sourceVersion:"1.0.0",fields:[{candidateField:"relationship",sourceField:"relationship",exactValue:"MAY_RELATE_TO",normalizationRule:"EXACT_STRUCTURED_FIELD/v1"}]}]};
const input={investigationId:"investigation-1",selectedSource:{kind:"NODE" as const,identity:"selected-node"},assignmentId:"assignment-1",receipt,bundle};
const anchors=createRexDiscoveryAnchors(input);assert.equal(anchors.length,2);assert.equal(anchors[0]!.rexDiscovery.candidateKind,"NODE");assert.equal(anchors[1]!.rexDiscovery.candidateKind,"EDGE");assert.match(anchors[0]!.anchorId,/bundle-1.*candidate-node/);assert.deepEqual(anchors[0]!.rexDiscovery.fieldLineage,bundle.fieldLineage[0]!.fields);assert.equal(anchors[0]!.rexDiscovery.epistemicClassification,"CANDIDATE_KNOWLEDGE");assert.equal(anchors[0]!.rexDiscovery.reviewStatus,"RESEARCHER_REVIEW_REQUIRED");assert.equal(anchors[0]!.rexDiscovery.canonEffect,"NONE");assert.equal(anchors[0]!.rexDiscovery.aiAssistanceStatus,"NONE");assert.equal(anchors[0]!.insertability.state,"INSPECTION_ONLY");
const runtime=new ResearchBridgeRuntime();const before=JSON.stringify(runtime.getDesk());
assert.throws(()=>createRexDiscoveryAnchors({...input,bundle:{...bundle,fieldLineage:bundle.fieldLineage.slice(0,1)}}));assert.equal(JSON.stringify(runtime.getDesk()),before,"review projection must perform zero ResearchBridgeRuntime mutations");
const edgeAnchors=createRexDiscoveryAnchors({...input,selectedSource:{kind:"EDGE",identity:"selected-edge"}});assert.equal(edgeAnchors[0]!.rexDiscovery.selectedSource.kind,"EDGE");assert.equal(edgeAnchors[0]!.rexDiscovery.selectedSource.identity,"selected-edge");

const authoritativeAssignment={assignmentId:"rxa_a68644907809ab710381d4c695d170d973a0afae14d80350b49421ee5d31f007",investigationId:"investigation-1",targetId:"selected-node",targetKind:"NODE",lifecycle:"SLEEPING",currentRevisionId:"rxar_7b4a3898f4aa02729d35625f65aeca3131c6730e7d04bbb1a32eefef7426cd17",createdAt:when,updatedAt:when,idempotencyDisposition:"CREATED",manifoldRevisionId:"investigation-aggregate:1",manifoldRevisionHash:H};
const calls:{url:string;init:RequestInit}[]=[];const responses=[authoritativeAssignment,{executionId:"execution-1",jobId:"job-1",disposition:"EXECUTABLE",semanticDuplicateStatus:"UNIQUE",originalExecutionId:null,authorizationDisposition:"ALLOW",estimatedMicros:0,reservedMicros:0,executionStatus:"QUEUED"},{receipt,terminalStatus:"COMPLETED",receiptContentHash:H2},receipt,bundle,{discoveries:[{selectedSource:input.selectedSource,assignmentId:input.assignmentId,receipt,bundle}]}];let index=0;
const api=createRexApi({baseUrl:"https://isees.invalid",cookieSource:()=>"isees_csrf=token",fetch:async(input,init)=>{if(init===undefined)throw new Error("missing request init");calls.push({url:String(input),init});return new Response(JSON.stringify(responses[index++]),{status:index===1?201:200,headers:{"Content-Type":"application/json"}})}});const assignment=await api.createAssignment("investigation-1","selected-node","NODE");const prepared=await api.prepare("investigation-1",assignment);if(prepared.jobId===null)throw new Error("expected executable fixture job");const executed=await api.execute("investigation-1",prepared.jobId);await api.getReceipt("investigation-1",executed.executionId);await api.getBundle("investigation-1",executed.candidateBundleId);const restored=await api.listCompletedDiscoveries("investigation-1");assert.equal(restored.length,1);assert.equal(restored[0]?.selectedSource.identity,"selected-node");assert.equal(calls.filter(call=>call.url.endsWith("/execution-preparations")).length,1,"valid authoritative assignment prepares exactly once");assert.equal(calls.length,6);assert(calls.every(call=>call.url.startsWith("https://isees.invalid/api/v1/investigations/")));assert(calls.every(call=>call.init.credentials==="include"));assert(calls.slice(0,3).every(call=>new Headers(call.init.headers).get("X-ISEES-CSRF")==="token"));assert.equal(calls[5]?.init.method,"GET");assert.equal(JSON.parse(String(calls[0]?.init.body)).targetKind,"NODE");assert.equal(JSON.parse(String(calls[1]?.init.body)).manifoldRevisionHash,H,"preparation must reuse the server-issued aggregate hash rather than the local Selection Intelligence revision identity");
const malformedApi=createRexApi({baseUrl:"https://isees.invalid",cookieSource:()=>"isees_csrf=token",fetch:async()=>new Response(JSON.stringify({...authoritativeAssignment,manifoldRevisionHash:null}),{status:201,headers:{"Content-Type":"application/json"}})});await assert.rejects(()=>malformedApi.createAssignment("investigation-1","selected-node","NODE"),error=>error instanceof Error&&"code" in error&&error.code==="MALFORMED_RESPONSE","malformed authoritative assignments fail visibly");

const control=readFileSync(new URL("../../src/rex/RexExploreControl.tsx",import.meta.url),"utf8"), right=readFileSync(new URL("../../src/components/RightPanel.tsx",import.meta.url),"utf8"), inbox=readFileSync(new URL("../../src/manifold/components/ResearchInboxInstrument.tsx",import.meta.url),"utf8"), bridge=readFileSync(new URL("../../src/research/ResearchBridgeRuntime.ts",import.meta.url),"utf8");
assert(control.includes("Explore with REX"));assert(control.includes("REX discovery requires a saved researcher investigation."));assert(control.includes('setProgress("PREPARING")')&&control.includes('setProgress("EXECUTING")')&&control.includes('setProgress("COMPLETED")'));assert(right.includes("<RexExploreControl selectionBinding="));assert(inbox.includes('onExpandedChange(true)'));assert(!right.includes("createAssignment("),"selection rendering must not execute REX");
for(const forbidden of ["useResearchBridge","publishRexDiscoveriesAtomically","createAnchorsAtomically","ResearchBridgeRuntime"])assert(!control.includes(forbidden),`completion must not reach Research publication capability: ${forbidden}`);
for(const marker of ["REX-derived","Review only","Researcher review and explicit publication are required","Research Inbox is unchanged","HeldRexReviewResult","projectionFingerprint"])assert(control.includes(marker),`review hold must present and retain ${marker}`);
for(const marker of ["AbortController","controller.signal","requestGeneration","currentBindingKey","activeController.current?.abort()","requireCurrent()","bundle.manifoldRevisionId!==assignment.manifoldRevisionId","setProgress(\"FAILED\")"])assert(control.includes(marker),`request lifecycle must enforce ${marker}`);
assert(!control.includes("assignment.manifoldRevisionId!==capturedBinding.manifoldRevisionId"),"backend aggregate revision identity must not be compared to the local Selection Intelligence revision namespace");
assert.equal(control.match(/api\.prepare\(/g)?.length,1,"a valid assignment has exactly one preparation invocation site");assert(control.includes('const requireCurrent=()=>{if(!current())throw new RexClientError("STALE_SELECTION"'),"stale responses fail closed instead of returning from PREPARING");assert(control.includes("requestGeneration.current+=1;activeController.current?.abort();activeController.current=undefined;running.current=false"),"aborted selection generations safely reset their active request");
for(const field of ["investigationId","manifoldRevisionId","selectionKind","targetId","projectionFingerprint"])assert(control.includes(`binding.${field}`),`held identity key must include ${field}`);
assert(!control.includes("setInterval")&&!control.includes("setTimeout"),"REX must remain explicit and non-polling");assert(!control.match(/google|bing|openai|anthropic|api[_-]?key/i));
assert.equal(JSON.stringify(runtime.getDesk()),before,"successful API completion fixture leaves Research Inbox count unchanged");assert(bridge.includes("createAnchorsAtomically"),"ResearchBridgeRuntime remains the sole mutation owner");
console.log("P57-REX-SELECTION-I1F Research review-hold verification passed (zero automatic publication, exact binding, review presentation, cancellation, and stale-result boundaries).");
