import assert from "node:assert/strict";
import { AuthorDocumentRuntime } from "../../src/author/runtime/AuthorDocumentRuntime.ts";
import { createTypedResearchAnchor } from "../../src/research/ResearchAnchorContract.ts";
import { ResearchBridgeRuntime } from "../../src/research/ResearchBridgeRuntime.ts";
import { STUDIO_ARTIFACT_DESIGNS } from "../../src/studio/drafting/StudioArtifactDesigns.ts";
import { StudioDraftingRuntime, type StudioDraftingClient } from "../../src/studio/drafting/StudioDraftingRuntime.ts";
import { serializeStudioManifoldArtifact } from "../../src/studio/drafting/StudioManifoldArtifactProjection.ts";

const labels = STUDIO_ARTIFACT_DESIGNS.map(item => item.label);
assert.deepEqual(labels.slice(0, 4), ["Investigation Report", "Evidence Assessment", "Comparative Event Analysis", "Research Memorandum"]);
const design = STUDIO_ARTIFACT_DESIGNS.find(item => item.designId === "MANIFOLD_ARTIFACT")!;
assert.equal(design.label, "Manifold Artifact"); assert.match(design.purpose, /machine-readable.*event-space expansion.*not a prose report.*not automatically admitted/is);

const at = new Date("2026-09-25T12:00:00Z");
const research = new ResearchBridgeRuntime();
const source = createTypedResearchAnchor({ investigationId: "investigation:guest", kind: "EVIDENCE_RECORD", sourceWorkspace: "EVIDENCE", sourceIdentity: "evidence:exact", collectedAt: at, classification: "CANONICAL", display: { title: "Exact source", summary: "Captured summary" }, insertability: { state: "INSERTABLE", reason: "Governed source." }, capturedRepresentation: { schemaVersion: "evidence/v1", mediaType: "application/json", value: { confidence: 0.8, provenance: "exact" } } } as never);
research.createAnchor(source);
const author = new AuthorDocumentRuntime(); author.activateInvestigation("investigation:guest");
author.setActiveDocument({ identity: { id: "document:guest", createdAt: at }, metadata: { title: "Guest draft", description: "", author: "Guest researcher", modifiedAt: at, version: 1 }, type: "REPORT", status: "MODIFIED", nodes: [{ id: "note:assertion", type: "PARAGRAPH", text: "Researcher-authored statement." }, { id: "note:question", type: "PARAGRAPH", text: "What remains unresolved?" }] } as never);
let networkCalls = 0;
const client: StudioDraftingClient = { generateDraftProposal: async () => { networkCalls += 1; throw new Error("must not call drafting provider"); } };
const runtime = new StudioDraftingRuntime(client);
runtime.updateEnvironment({ scope: { investigationId: "investigation:guest", principalId: "guest:session" }, document: author.getActiveDocument(), documentRuntimeRevision: author.getRevision(), researchRevision: research.getRevision(), researchProjection: research.projectInvestigation({ investigationId: "investigation:guest" }) });
runtime.setDesign(design); runtime.setSourceSelected(source.anchorId, true); runtime.setNoteSelected("note:assertion", true); runtime.setNoteSelected("note:question", true); runtime.setDraftingInstruction("Project selected governed context."); await runtime.prepare();
const beforeDocument = JSON.stringify(author.getActiveDocument()), beforeResearch = JSON.stringify(research.getDesk()), beforeRevision = author.getRevision();
await runtime.generate(); const first = runtime.getState().manifoldArtifact!; await runtime.generate(); const second = runtime.getState().manifoldArtifact!;
assert.equal(networkCalls, 0, "local MANIFOLD_ARTIFACT generation requires no auth-gated or paid API");
assert.equal(first.outputHash, second.outputHash); assert.equal(serializeStudioManifoldArtifact(first), serializeStudioManifoldArtifact(second));
assert.equal(first.contextManifest.artifactDesign.designId, "MANIFOLD_ARTIFACT"); assert.equal(first.contextManifest.artifactDesign.designVersion, "1");
assert.equal(first.contextManifest.proposalEffect, "CREATES_UNAPPLIED_LOCAL_PROJECTION_ONLY"); assert.equal(first.contextManifest.sources[0]!.sourceIdentity, "evidence:exact");
assert.deepEqual(first.contextManifest.sources[0]!.capturedRepresentation, { confidence: 0.8, provenance: "exact" });
assert.deepEqual(first.contextManifest.researcherNotes.map(note => note.text), ["Researcher-authored statement.", "What remains unresolved?"]);
assert.deepEqual(first.projection.declarations, [], "prose notes must not be inferred into declarations");
assert.deepEqual(first.projection.evidenceReferences, [], "Research Inbox presence must not invent declaration references");
assert.equal(first.projection.normalizedProvenance[0]?.reference.kind, "SOURCE_SNAPSHOT");
assert.equal(first.projection.canonEffect, "NONE"); assert.equal(first.authorityState, "UNAPPLIED_LOCAL_PROJECTION");
assert.equal(JSON.stringify(author.getActiveDocument()), beforeDocument); assert.equal(JSON.stringify(research.getDesk()), beforeResearch); assert.equal(author.getRevision(), beforeRevision);
runtime.setSourceSelectionMode("ALL"); await runtime.prepare(); await runtime.generate(); assert.equal(runtime.getState().manifoldArtifact!.contextManifest.sourceSelectionMode, "ALL");
runtime.setDraftingInstruction("Changed artifact-defining instructions.");
assert.equal(runtime.getState().status, "STALE");
assert.equal(runtime.getState().manifoldArtifact, undefined, "artifact-defining input changes invalidate review eligibility");
await runtime.prepare(); await runtime.generate();
runtime.updateEnvironment({ scope: { investigationId: "investigation:guest", principalId: "guest:session" }, document: author.getActiveDocument(), documentRuntimeRevision: author.getRevision(), researchRevision: research.getRevision() + 1, researchProjection: research.projectInvestigation({ investigationId: "investigation:guest" }) });
assert.equal(runtime.getState().manifoldArtifact, undefined, "Research Inbox context revision changes invalidate review eligibility");
console.log("VerifyStudioDraftingManifoldArtifact: PASS");
