import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import type { RexReceipt } from "../../src/rex/RexApi.ts";
import { createRexCostProjection, formatOptionalUsdMicros, formatUsdMicros, projectFixtureRexCost, REX_BILLING_STATUS, REX_FEE_POLICY } from "../../src/rex/RexCostTransparency.ts";

const H=`sha256:${"a".repeat(64)}`;
const receipt:RexReceipt={executionId:"e",jobId:"j",assignmentId:"a",assignmentRevisionId:"ar",manifoldRevisionId:"mr",manifoldRevisionHash:H,sourceAdapterIdentity:"rex-local-immutable-fixture",sourceAdapterVersion:"1",normalizerIdentity:"local",normalizerVersion:"1",candidateBundleId:"b",candidateContentHash:H,sourceContentHash:H,aiAssistanceStatus:"NONE",providerIdentity:"NONE",modelIdentity:"NONE",estimatedMicros:0,reservedMicros:0,actualMicros:0,chargedMicros:0,releasedMicros:0,terminalExecutionStatus:"COMPLETED",completedAt:"2026-09-17T00:00:00Z",contentHash:H};
let passed=0;const prove=(test:()=>void)=>{test();passed+=1};
const projected=projectFixtureRexCost(receipt);
prove(()=>assert.deepEqual([projected.externalProviderCapMicros,projected.computeAndAiCapMicros,projected.iseesGovernanceFeeMicros,projected.contingencyReserveMicros,projected.maximumAuthorizedMicros,projected.finalChargeMicros,projected.releasedAuthorizationMicros],[0,0,0,0,0,0,0]));
prove(()=>assert.equal(projected.billingStatus,REX_BILLING_STATUS));
prove(()=>assert.equal(projected.feePolicy.state,REX_FEE_POLICY.state));
prove(()=>assert.deepEqual([0,1,9_999,10_000,10_001,1_230_000,1_234_567].map(formatUsdMicros),["$0.00","less than $0.01 ($0.000001 exact)","less than $0.01 ($0.009999 exact)","$0.01","$0.010001","$1.23","$1.234567"]));
prove(()=>assert.equal(formatUsdMicros(Number.MAX_SAFE_INTEGER),"$9,007,199,254.740991"));
prove(()=>assert.deepEqual([formatOptionalUsdMicros(undefined),formatOptionalUsdMicros(null)],["unavailable","unavailable"]));
prove(()=>assert.throws(()=>formatUsdMicros(-1),/non-negative integer/));
prove(()=>assert.throws(()=>formatUsdMicros(1.5),/non-negative integer/));
prove(()=>assert.throws(()=>formatUsdMicros(Number.MAX_SAFE_INTEGER+1),/non-negative integer/));
prove(()=>assert.equal(createRexCostProjection({externalProviderCapMicros:1,computeAndAiCapMicros:2,iseesGovernanceFeeMicros:3,contingencyReserveMicros:4},{finalChargeMicros:6,releasedAuthorizationMicros:4,expectedMaximumAuthorizedMicros:10},receipt).maximumAuthorizedMicros,10));
prove(()=>assert.throws(()=>createRexCostProjection({externalProviderCapMicros:1,computeAndAiCapMicros:0,iseesGovernanceFeeMicros:0,contingencyReserveMicros:0},{finalChargeMicros:2},receipt),/cannot exceed/));
prove(()=>assert.deepEqual([projected.providerIdentity,projected.modelIdentity,projected.aiAssistanceStatus],["NONE","NONE","NONE"]));
const control=readFileSync(new URL("../../src/rex/RexExploreControl.tsx",import.meta.url),"utf8");
prove(()=>{for(const marker of ["illustrative planning ranges, not quotes","illustrative planning only","Public-source scan: approximately $0.01 to $0.10","Standard REX discovery: approximately $0.10 to $0.50","Deep REX investigation: approximately $0.50 to $2.00","Specialized providers: priced before authorization"])assert(control.includes(marker),marker)});
prove(()=>assert(control.includes("no commercial percentage is active or final")&&control.includes("no authorization or payment control is active")));
prove(()=>{for(const marker of ["Frontier Agents · Coming Soon · Inactive","Light Frontier Agent watch: approximately $1 to $5 per month","Standard Frontier Agent watch: approximately $5 to $25 per month","Intensive or specialized monitoring: explicitly scoped and capped before activation","No Frontier Agent is active"])assert(control.includes(marker),marker)});
prove(()=>assert.equal(control.match(/No range is an active price, fee schedule, promise, or authorization\./g)?.length,2));
prove(()=>assert(control.includes("Current recurring Frontier Agent cost: $0.00")));
prove(()=>{for(const marker of ["cannot establish truth","modify canonical Knowledge","operational Manifold graph or active revision","publish to Research Inbox","authorize additional spending"])assert(control.includes(marker),marker)});
prove(()=>{for(const forbidden of ["useResearchBridge","publishRexDiscoveriesAtomically","createAnchorsAtomically","ResearchBridgeRuntime"])assert(!control.includes(forbidden),forbidden);assert(control.includes("Research Inbox is unchanged."))});
prove(()=>{for(const marker of ["AbortController","requestGeneration","currentBindingKey","activeController.current?.abort()","requireCurrent()","STALE_SELECTION"])assert(control.includes(marker),marker)});
console.log(`P57-REX-SELECTION-I1G cost-transparency verification passed (${passed}/20 proofs).`);
