import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { NATIVE_CASE_DRAFT_FIELD_ORDER, createBlankNativeCaseDraftContent, mapFormStateToContent, restoreNativeCaseDraftContent, suppliedEnvelope, unknownEnvelope, validateNativeCaseDraftForm } from "../../src/nativeCaseDraft/NativeCaseDraftFieldState.ts";
import { createGuestCandidateInvestigation, serializeGuestCandidateContent } from "../../src/workspace/guestCase/GuestCaseIntake.ts";

const root = resolve(import.meta.dirname, "../..");
const source = (path: string) => readFileSync(resolve(root, path), "utf8");
const identity = { status: "READY" as const, identity: { kind: "GUEST" as const, operatorId: "guest:verify", establishedAt: "2026-09-12T12:00:00.000Z" }, persistence: "SESSION" as const, revision: 1 };
const blank = restoreNativeCaseDraftContent(createBlankNativeCaseDraftContent());
assert.equal(NATIVE_CASE_DRAFT_FIELD_ORDER.length, 18);
assert.deepEqual(new Set(NATIVE_CASE_DRAFT_FIELD_ORDER.map(field => blank[field].state)), new Set(["OMITTED"]));
const form = Object.freeze({ ...blank, workingTitle: suppliedEnvelope("Harbor lights"), observationLocation: unknownEnvelope(), observationNarrative: suppliedEnvelope("Two lights above the water."), witnessCount: suppliedEnvelope(2), approximateDuration: suppliedEnvelope(75), privacyClassification: suppliedEnvelope("PRIVATE") });
assert.ok(validateNativeCaseDraftForm(form).every(result => result.valid), "canonical native validation must accept valid guest content");
assert.ok(validateNativeCaseDraftForm(Object.freeze({ ...form, localObservationDate: suppliedEnvelope("2026-02-30") })).some(result => result.field === "localObservationDate" && !result.valid));
assert.equal(createGuestCandidateInvestigation(blank, identity, "2026-09-12T12:00:00.000Z", "blank").status, "INVALID", "working title is guest-required");
const created = createGuestCandidateInvestigation(form, identity, "2026-09-12T12:00:00.000Z", "verification-session-id");
assert.equal(created.status, "CREATED");
if (created.status !== "CREATED") throw new Error("unreachable");
assert.deepEqual(created.candidate.content, mapFormStateToContent(form));
assert.equal(created.candidate.canonicalSerialization, serializeGuestCandidateContent(created.candidate.content));
assert.equal(created.candidate.candidateId, "guest-candidate:verification-session-id");
assert.ok(created.candidate.canonicalSerialization.includes("rightsPublicationRestriction"), "identity change material covers all canonical fields");
assert.deepEqual({ classification: created.candidate.knowledgeClassification, origin: created.candidate.origin, materialization: created.candidate.operationalMaterialization, canon: created.candidate.systemCanonIdentity }, { classification: "CANDIDATE_KNOWLEDGE", origin: "RESEARCHER_SUPPLIED", materialization: "NONE", canon: null });

const welcome = source("src/workspace/surfaces/GuestWelcomeOverview.tsx");
const intake = source("src/workspace/surfaces/GuestCaseIntake.tsx");
const model = source("src/workspace/guestCase/GuestCaseIntake.ts");
const compare = source("src/compare/components/CompareWorkspace.tsx");
const runtime = source("src/workspace/runtime/WorkspaceRuntime.ts");
const projection = source("src/compare/projection/GuestCandidateCompareProjection.ts");
const structuredForm = source("src/nativeCaseDraft/StructuredObservationForm.tsx");
assert.ok(welcome.indexOf("Bring Your Own Case") < welcome.indexOf("System Canon / Hydrated Records"), "enabled hero CTA precedes Canon cards");
assert.ok(source("src/identity/components/OperatorEntryScreen.tsx").includes("Bring your own case"));
assert.ok(intake.includes("Ready to compare your case?"), "guest completion heading exists");
assert.ok(intake.includes("Create this temporary case and choose a System Canon event for comparison."), "guest comparison explanation exists");
assert.ok(intake.includes("Your case remains only in this browser session and is not saved to an account or the server."), "guest retention reminder exists");
assert.ok(intake.includes("StructuredObservationForm") && intake.includes("onSubmit={onSubmit}") && intake.includes('submitLabel="Create Temporary Case"'), "guest primary action remains wired through StructuredObservationForm");
assert.equal((intake.match(/<StructuredObservationForm/g) ?? []).length, 1, "guest composes one structured form");
assert.equal((intake.match(/<form\b/g) ?? []).length, 0, "guest introduces no second form");
assert.equal((intake.match(/submitGuestCase\(/g) ?? []).length, 1, "guest retains one submission pathway");
assert.ok(structuredForm.includes('submitLabel = "Save Draft"'), "account default submit label remains Save Draft");
assert.ok(intake.includes("validateNativeCaseDraftForm") && model.includes("mapFormStateToContent"));
assert.ok(compare.includes('"Unknown"') && compare.includes('"Not answered"') && compare.includes('"Unavailable in Canon record"'));
assert.ok(runtime.includes("WorkspaceMode.COMPARE") && runtime.includes("activateGuestCandidateInvestigation"));
assert.ok(projection.includes('sourceType === "SYSTEM_CANON"') && projection.includes("fields: canonFields(object.payload)"));
assert.ok(source("src/workspace/persistence/GuestWorkspaceSessionPersistence.ts").includes("GuestWorkspaceSessionSnapshot"), "existing session restoration remains composed");
for (const forbidden of ["fetch(", "localStorage", "document.cookie", "NativeCaseDraftApi", "NativeCaseDraftCoordinator", "NativeCaseDraftEditor", "NativeCaseDraftWorkspace"]) assert.ok(!intake.includes(forbidden) && !model.includes(forbidden));
assert.ok(!model.includes("sourceUrl") && !model.includes("Math.imul"));
assert.ok(!compare.slice(compare.indexOf("function GuestCandidateWorkspace"), compare.indexOf("export default function CompareWorkspace")).match(/similarity score|confidence score|AI conclusion|relationship result|match result/i));
assert.ok(source("src/nativeCaseDraft/NativeCaseDraftWorkspace.tsx").includes('identity.identity?.kind === "ACCOUNT"'));
assert.ok(compare.includes("resolveComparePairProjection"), "existing canonical Compare flow remains composed");
assert.ok(source("src/account/GuestInvestigationAdoption.ts").includes("cannot cross the account adoption boundary"));
console.log("PASS VerifyGuestBringYourOwnCase: canonical guest form, validation, full content, session identity, restoration, Compare descriptions, boundaries, entry copy, adoption rejection, and Canon isolation verified.");
