import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { CANONICAL_EVENTS } from "../../src/canonical/runtimeCorpus.ts";
import { adaptSystemCanonToKnowledge } from "../../src/knowledge/ingestion/SystemCanonKnowledgeAdapter.ts";
import type { Investigation } from "../../src/investigation/investigationTypes.ts";
import { adaptFocusedEventTimelineSourceRecords } from "../../src/timeline/projection/TimelineSourceRecordAdapter.ts";
import { projectTimelineTemporal } from "../../src/timeline/projection/TimelineTemporalProjection.ts";
import { presentTimelinePrecision, presentTimelineTemporalValue } from "../../src/timeline/presentation/TimelineTemporalPresentation.ts";
import { TimelineCompositionKind, resolveTimelineComposition } from "../../src/timeline/presentation/TimelineComposition.ts";
import { ResearchAnchorType } from "../../src/research/researchBridgeTypes.ts";
import { buildInvestigationGraph } from "../../src/manifold/graphBuilder.ts";
import { SystemCanonAdapter } from "../../src/corpus/adapters/systemCanonAdapter.ts";

const surface = readFileSync("src/surfaces/WorkspaceSurface.tsx", "utf8");
const component = readFileSync("src/timeline/components/TimelineWorkspace.tsx", "utf8");
const css = readFileSync("src/timeline/components/TimelineWorkspace.css", "utf8");
const adapter = readFileSync("src/timeline/projection/TimelineSourceRecordAdapter.ts", "utf8");
const timelineContext = readFileSync("src/timeline/context/TimelineInspectionContext.tsx", "utf8");
const presentation = readFileSync("src/timeline/presentation/TimelineTemporalPresentation.ts", "utf8");
const combined = `${component}\n${adapter}\n${presentation}`;

assert.match(surface, /case WorkspaceMode\.TIMELINE:[\s\S]*?<TimelineWorkspace\s*\/>/);
assert.doesNotMatch(surface, /case WorkspaceMode\.TIMELINE:[\s\S]{0,160}<PlaceholderSurface/);
assert.match(surface, /from "\.\.\/timeline\/components\/TimelineWorkspace"/);
assert.doesNotMatch(combined, /Nimitz|TIC TAC|TICTAC|Rendlesham/i);
assert.match(timelineContext, /runtime\.getActiveInvestigation\(\)/);
assert.match(timelineContext, /investigation\?\.workspace\.focused_event_id/);
assert.match(component, /projectTimelineTemporal/);
assert.match(component, /projection\.focusedItems/);
for (const token of ["INSTANT", "DATE", "INTERVAL", "OPEN_INTERVAL", "DURATION", "SEQUENCE", "UNKNOWN", "Approximate", "Inferred", "Disputed", "Date only", "Sequence only"]) assert.ok(presentation.includes(token), `missing explicit presentation: ${token}`);
assert.match(component, /NO_TEMPORAL_RECORDS/);
assert.doesNotMatch(component, /1970-01-01/);
assert.doesNotMatch(adapter, /investigation\.createdAt|workspace\.created_at/);
assert.doesNotMatch(adapter, /artifact.*created_at|created_at.*artifact/i);
assert.doesNotMatch(adapter, /Date\.parse|match\([^)]*eventId|split\([^)]*eventId|substring\([^)]*eventId/);
assert.match(timelineContext, /setInspection\(undefined\)/);
assert.match(timelineContext, /\[investigation\?\.id, focusedEventId\]/);
assert.doesNotMatch(component, /setSelection|clearSelection/);
assert.doesNotMatch(component, /ResearchBridge|publish|createAnchor/);
assert.deepEqual(Object.keys(ResearchAnchorType).sort(), ["CANDIDATE", "EDGE", "EXPERIMENT", "NODE"]);
assert.doesNotMatch(surface, /activeMode ===\s*WorkspaceMode\.TIMELINE/);
assert.equal(resolveTimelineComposition(0), TimelineCompositionKind.FOCUSED_ONLY);
assert.equal(resolveTimelineComposition(1), TimelineCompositionKind.PAIRWISE);
assert.equal(resolveTimelineComposition(2), TimelineCompositionKind.MULTI_EVENT_OVERVIEW);
assert.equal(resolveTimelineComposition(3), TimelineCompositionKind.MULTI_EVENT_OVERVIEW);
for (const invalidCount of [-1, 0.5, Number.NaN, Number.POSITIVE_INFINITY, Number.MAX_SAFE_INTEGER + 1]) {
  assert.throws(() => resolveTimelineComposition(invalidCount));
}
assert.match(component, /qualifiedComparisonCount: timeline\.candidates\.length/);
assert.match(component, /resolveTimelineComposition/);
assert.doesNotMatch(component, /imported_events\.length/);
assert.doesNotMatch(component, /resolveCompareCandidateOptionProjection|resolveComparePairProjection|resolveCandidateIntelligenceCollection/);
assert.match(timelineContext, /resolveCompareCandidateOptionProjection/);
assert.match(css, /@media\(max-width:980px\).*grid-template-columns:minmax\(0,1fr\)/);
assert.match(component, /<button type="button" aria-pressed=\{selected\} onClick=\{onInspect\}>/);
assert.match(css, /button\[aria-pressed=true\]/);
assert.match(css, /button:focus-visible/);
assert.match(css, /@media\(prefers-reduced-motion:reduce\)/);

const eventId = "E-TICTAC-2004";
const knowledge = adaptSystemCanonToKnowledge(CANONICAL_EVENTS.filter(event => event.event_id === eventId));
const corpus = await new SystemCanonAdapter().importEvents();
const productionWorkspace = { id: "WS-I2", name: "", description: "", imported_events: [{ event_id: eventId, source: "SYSTEM_CANON" as const }], focused_event_id: eventId, investigations: [], artifacts: [], active_layers: [], created_at: "2026-01-01T00:00:00Z" };
const graph = buildInvestigationGraph(corpus, productionWorkspace);
const investigation: Investigation = { id: "INV-I2", name: "Dynamic Investigation", description: "", createdAt: "2026-01-01T00:00:00Z", updatedAt: "2026-01-01T00:00:00Z", createdBy: "verify", status: "ACTIVE", workspace: productionWorkspace, currentRevisionId: "REV-I2", revisions: [{ id: "REV-I2", revisionNumber: 1, timestamp: "2026-01-01T00:00:00Z", operator: "verify", branch: "MAIN", message: "", manifold: { id: "M-I2", timestamp: "2026-01-01T00:00:00Z", algorithmVersion: "1", activeLayers: [], graph } }] };
const records = adaptFocusedEventTimelineSourceRecords(investigation, knowledge);
assert.equal(records.length, 1);
assert.notEqual(knowledge[0]!.identity.id, graph.nodes.find(node => node.id === eventId)!.id);
assert.equal(records[0]!.subject?.id, graph.nodes.find(node => node.id === eventId)!.id);
assert.equal(records[0]!.temporal.kind, "DURATION");
assert.equal(records[0]!.semantic, "OCCURRENCE");
assert.equal(records[0]!.precision, "APPROXIMATE");
const projection = projectTimelineTemporal({ investigation, knowledgeObjects: knowledge, records });
assert.equal(projection.status, "READY");
if (projection.status === "READY") {
  assert.deepEqual(projection.focusedItems.map(item => item.itemId), records.map(item => item.itemId));
  assert.equal(presentTimelineTemporalValue(projection.focusedItems[0]!.temporal), "300 minutes");
  assert.equal(presentTimelinePrecision(projection.focusedItems[0]!), "Approximate");
  assert.notEqual(presentTimelineTemporalValue(projection.focusedItems[0]!.temporal), projection.focusedItems[0]!.orderKey);
  assert.equal(projection.focusedItems[0]!.subject.availability, "AVAILABLE");
}
const withoutSubjectGraph: Investigation = { ...investigation, revisions: [{ ...investigation.revisions[0]!, manifold: { ...investigation.revisions[0]!.manifold, graph: { ...graph, nodes: graph.nodes.filter(node => node.id !== eventId) } } }] };
const withoutSubjectRecords = adaptFocusedEventTimelineSourceRecords(withoutSubjectGraph, knowledge);
assert.equal(withoutSubjectRecords[0]!.subject, undefined);
const withoutSubjectProjection = projectTimelineTemporal({ investigation: withoutSubjectGraph, knowledgeObjects: knowledge, records: withoutSubjectRecords });
assert.equal(withoutSubjectProjection.status, "READY");
if (withoutSubjectProjection.status === "READY") assert.equal(withoutSubjectProjection.focusedItems[0]!.subject.availability, "UNAVAILABLE");
const duplicateEventNode = { ...graph.nodes.find(node => node.id === eventId)!, id: "alternate-event-node", metadata: { eventId } };
const ambiguousGraph: Investigation = { ...investigation, revisions: [{ ...investigation.revisions[0]!, manifold: { ...investigation.revisions[0]!.manifold, graph: { ...graph, nodes: [...graph.nodes, duplicateEventNode] } } }] };
const ambiguousFirst = adaptFocusedEventTimelineSourceRecords(ambiguousGraph, knowledge);
const ambiguousSecond = adaptFocusedEventTimelineSourceRecords(ambiguousGraph, knowledge);
assert.equal(ambiguousFirst[0]!.subject, undefined);
assert.deepEqual(ambiguousFirst, ambiguousSecond);
const falseClaim = [{ ...withoutSubjectRecords[0]!, subject: { type: "NODE" as const, id: "system:event:E-TICTAC-2004" } }];
assert.equal(projectTimelineTemporal({ investigation: withoutSubjectGraph, knowledgeObjects: knowledge, records: falseClaim }).status, "INVALID_SOURCE_TEMPORAL_RECORD");
const crossInvestigationClaim = [{ ...records[0]!, investigationId: "INV-OTHER" }];
assert.equal(projectTimelineTemporal({ investigation, knowledgeObjects: knowledge, records: crossInvestigationClaim }).status, "INVALID_SOURCE_TEMPORAL_RECORD");
assert.equal(JSON.stringify(projection).includes("resolved 0 times"), false);
assert.doesNotMatch(adapter, /E-TICTAC-2004|system:event:E-TICTAC-2004/);
assert.doesNotMatch(adapter, /label\s*===|\.label\s*===/);
const emptyKnowledge = knowledge.map(object => object.type === "EVENT" ? { ...object, payload: { source: "SYSTEM_CANON", sourceKind: "CANONICAL_REPLAY_EVENT", canonicalEvent: {} } } : object);
assert.equal(adaptFocusedEventTimelineSourceRecords(investigation, emptyKnowledge).length, 0);
assert.equal(projectTimelineTemporal({ investigation, knowledgeObjects: emptyKnowledge, records: [] }).status, "NO_TEMPORAL_RECORDS");
assert.equal(Object.isFrozen(records), true);
assert.equal(Object.isFrozen(records[0]), true);

console.log("PASS VerifyTimelineFocusedWorkspace — production focused TIMELINE ownership and presentation verified");
