import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
const read = (path: string) => readFileSync(path, "utf8");
const app = read("src/App.tsx");
const navigator = read("src/layers/components/LayersLaboratoryNavigator.tsx");
const intelligence = read("src/layers/components/LayersExperimentalIntelligence.tsx");
const selection = read("src/layers/components/LayersPresentationSelection.tsx");
const workspace = read("src/layers/components/LayersLaboratoryWorkspace.tsx");
const chamber = read("src/layers/components/LayersWireManifoldChamber.tsx");
const surface = read("src/surfaces/WorkspaceSurface.tsx");
const css = read("src/layers/components/LayersLaboratoryWorkspace.css") + read("src/layers/components/LayersSideInstruments.css");
assert(app.includes("ModeAwareLeftPanel") && app.includes("LayersLaboratoryNavigator"));
assert(app.includes("ModeAwareRightPanel") && app.includes("LayersExperimentalIntelligence"));
assert(app.includes("<InvestigationControl />") && app.includes("<RightPanel />"), "other modes retain established instruments");
assert(!selection.includes("setSelection") && !navigator.includes("setSelection") && !intelligence.includes("setSelection"));
assert(selection.includes("useState<LayersInspectionSelection>") && selection.includes('kind: "SUMMARY"'));
assert(navigator.includes("useLayersExperimentState") && intelligence.includes("experimentalManifoldSnapshot"));
assert(chamber.includes("Inspect Case A") && chamber.includes("Inspect baseline wire") && workspace.includes('kind:"CONTRIBUTION"'));
assert(chamber.includes("aria-pressed") && workspace.includes("aria-pressed") && css.includes(":focus-visible"));
assert(workspace.includes("<details>") && workspace.includes("Canonical Representation") && workspace.includes("canonicalRepresentation"));
assert(surface.includes("WorkspaceMode.LAYERS") && surface.includes("researchInboxExpanded"));
assert(css.includes("prefers-reduced-motion"));
console.log("PASS VerifyLayersSideInstruments");
