import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { CanonicalLayerCatalog, CanonicalLayerFamilies, CanonicalLayerOperationalStatus, CanonicalLayerProfileId, restoreCanonicalLayerProfile } from "../../src/layers/catalog/index.ts";
import { clearCatalogFamily, layerCatalogTotals, normalizeOperationalSelection, operationalSelectableLayerIds, projectLayerCatalogFamilies, selectCatalogFamily } from "../../src/layers/presentation/LayerCatalogMatrixProjection.ts";
import { LayersExperimentRuntime } from "../../src/layers/runtime/LayersExperimentRuntime.ts";

let passed = 0;
const verify = (name: string, condition: unknown) => { assert(condition, name); console.log(`PASS ${++passed} — ${name}`); };
const component = readFileSync("src/layers/components/LayerCatalogMatrix.tsx", "utf8");
const workspace = readFileSync("src/layers/components/LayersLaboratoryWorkspace.tsx", "utf8");
const css = readFileSync("src/layers/components/LayersLaboratoryWorkspace.css", "utf8");
const surface = readFileSync("src/surfaces/WorkspaceSurface.tsx", "utf8");
const intelligence = readFileSync("src/layers/components/LayersExperimentalIntelligence.tsx", "utf8");
const unfiltered = projectLayerCatalogFamilies("", []);
verify("empty filter renders all 16 families", unfiltered.length === 16);
verify("all 48 catalog layers project exactly once", unfiltered.flatMap(x => x.members).length === 48 && new Set(unfiltered.flatMap(x => x.members.map(y => y.id))).size === 48);
verify("all 16 families project in authoritative order", JSON.stringify(unfiltered.map(x => x.family.id)) === JSON.stringify(CanonicalLayerFamilies.map(x => x.id)));
verify("family membership and member order are authoritative", unfiltered.every(group => JSON.stringify(group.members.map(x => x.id)) === JSON.stringify(CanonicalLayerCatalog.filter(x => x.familyId === group.family.id).sort((a,b) => a.familyMemberOrder-b.familyMemberOrder).map(x => x.id))));
verify("display totals derive from catalog", layerCatalogTotals.total === CanonicalLayerCatalog.length && component.includes("layerCatalogTotals.total"));
verify("operational count is five", layerCatalogTotals.operational === 5);
verify("unavailable count is 43", layerCatalogTotals.unavailable === 43);
verify("browse semantics distinguish five INPUT REQUIRED from 43 UNAVAILABLE", component.includes("INPUT REQUIRED") && component.includes("UNAVAILABLE") && component.includes('experimentReady ? "Available" : "Input required"'));
verify("only operational researcher-selectable IDs normalize", normalizeOperationalSelection(CanonicalLayerCatalog.map(x => x.id)).length === 5);
verify("five operational layers toggle independently", operationalSelectableLayerIds.every(id => normalizeOperationalSelection([id]).includes(id)));
verify("select all includes exactly the five operational layers", JSON.stringify(operationalSelectableLayerIds) === JSON.stringify(["OBSERVABILITY","NARRATIVE","GEOGRAPHY","INFRASTRUCTURE","TOPOLOGY"]));
verify("clear all is an empty prepared selection", component.includes("onSelectionChange([])"));
verify("restore baseline consumes the versioned profile", component.includes("restoreProfile(CanonicalLayerProfileId.CANONICAL_BASELINE)") && JSON.stringify(restoreCanonicalLayerProfile(CanonicalLayerProfileId.CANONICAL_BASELINE)) === JSON.stringify(["OBSERVABILITY","NARRATIVE","TEMPORAL"]));
const geography = selectCatalogFamily(["NARRATIVE"], "GEOSPATIAL");
verify("family selection affects only its operational members", geography.includes("NARRATIVE") && geography.includes("GEOGRAPHY") && geography.length === 2);
verify("family clearing affects only its family", JSON.stringify(clearCatalogFamily(["OBSERVABILITY","NARRATIVE"], "NARRATIVE")) === JSON.stringify(["OBSERVABILITY"]));
verify("families without operational members cannot arm unavailable layers", selectCatalogFamily([], "SENSOR").length === 0 && component.includes("group.operationalCount === 0"));
const before = ["OBSERVABILITY"]; const beforeSnapshot = JSON.stringify(before); const radar = projectLayerCatalogFamilies("radar observation", before);
verify("filtering does not mutate selection", JSON.stringify(before) === JSON.stringify(["OBSERVABILITY"]));
const anxiety = projectLayerCatalogFamilies("anxiety", before);
verify("anxiety returns only Societal / Global Context and Global Anxiety Index", anxiety.length === 1 && anxiety[0].family.label === "Societal / Global Context" && JSON.stringify(anxiety[0].members.map(x=>x.id)) === JSON.stringify(["GLOBAL_ANXIETY_INDEX"]));
verify("no empty families survive a non-empty filter", [anxiety, radar].every(groups => groups.every(group => group.members.length > 0)));
verify("radar observation returns only its matching Sensor member", radar.length === 1 && radar[0].family.label === "Sensor" && JSON.stringify(radar[0].members.map(x=>x.id)) === JSON.stringify(["RADAR_OBSERVATION"]));
const sensor = projectLayerCatalogFamilies("sensor", []); const linguistic = projectLayerCatalogFamilies("LINGUISTIC", []);
verify("family matches expose every authoritative member", sensor.length === 1 && sensor[0].family.label === "Sensor" && sensor[0].members.length === CanonicalLayerCatalog.filter(x=>x.familyId===sensor[0].family.id).length && linguistic.length === 1 && linguistic[0].family.label === "Linguistic" && linguistic[0].members.length === CanonicalLayerCatalog.filter(x=>x.familyId===linguistic[0].family.id).length);
verify("matching is case-insensitive", JSON.stringify(projectLayerCatalogFamilies("ANXIETY", []).map(x=>x.members.map(y=>y.id))) === JSON.stringify(anxiety.map(x=>x.members.map(y=>y.id))));
verify("filter normalization is trimmed and locale-independent", JSON.stringify(projectLayerCatalogFamilies("  AnXiEtY  ", []).map(x=>x.members.map(y=>y.id))) === JSON.stringify(anxiety.map(x=>x.members.map(y=>y.id))));
verify("stable ID and description matching work", projectLayerCatalogFamilies("GLOBAL_ANXIETY_INDEX", []).flatMap(x=>x.members).length===1 && projectLayerCatalogFamilies("Sensor observations, witnesses", []).flatMap(x=>x.members).some(x=>x.id==="OBSERVABILITY"));
const unavailable = CanonicalLayerCatalog.find(x=>x.operationalStatus===CanonicalLayerOperationalStatus.UNAVAILABLE)!;
verify("unavailable reason and required input matching work", projectLayerCatalogFamilies(unavailable.unavailableReason!.slice(0,24), []).flatMap(x=>x.members).some(x=>x.id===unavailable.id) && projectLayerCatalogFamilies(unavailable.requiredCanonicalInputs[0], []).flatMap(x=>x.members).some(x=>x.id===unavailable.id));
verify("no-match query returns zero families", projectLayerCatalogFamilies("no-such-investigation-layer-xyz", []).length === 0);
verify("projection preserves caller inputs and is deterministic", JSON.stringify(before) === beforeSnapshot && JSON.stringify(projectLayerCatalogFamilies("anxiety", before)) === JSON.stringify(projectLayerCatalogFamilies("anxiety", before)));
verify("clearing filter restores 48 entries", projectLayerCatalogFamilies("", before).flatMap(x=>x.members).length === 48);
verify("component has one catalog-level no-match status and Clear filter action", (component.match(/role="status"/g) ?? []).length === 1 && component.includes("No investigation layers match the filter") && component.includes("Clear filter") && !component.includes("No layers in this family match"));
verify("unavailable cells expose reasons and required inputs", component.includes("layer.unavailableReason") && component.includes("layer.requiredCanonicalInputs.join"));
for (const id of ["GLOBAL_ANXIETY_INDEX","TEMPORAL"]) verify(`${id} is unavailable and non-selectable`, CanonicalLayerCatalog.find(x=>x.id===id)?.operationalStatus === CanonicalLayerOperationalStatus.UNAVAILABLE && !operationalSelectableLayerIds.includes(id));
verify("Resolve Topology State is operational and selectable", CanonicalLayerCatalog.find(x=>x.id==="TOPOLOGY")?.label === "Resolve Topology State" && operationalSelectableLayerIds.includes("TOPOLOGY"));
verify("TEMPORAL baseline association is distinguished from activity", component.includes("CANONICAL BASELINE MEMBER · NOT COMPUTATIONALLY ACTIVE"));
const runtime = new LayersExperimentRuntime(); runtime.establish({scope:{investigationId:"i",workspaceId:"w",focusedEventId:"a",comparisonEventId:"b",subjectIds:["s1","s2"],compareOrigin:{pairId:"p",candidateId:"c",evaluationId:"e"},resolveOrigin:{executionId:"r"}},baseline:{investigationId:"i",workspaceId:"w",subjectIds:["s1","s2"],canonicalStartingLayerIds:["TEMPORAL"],startingResolveExecutionId:"r",temporalContext:{},investigativeScale:{}},armedLayers:{layerIds:["TEMPORAL","TOPOLOGY","GLOBAL_ANXIETY_INDEX","OBSERVABILITY"]}});
verify("programmatic unavailable IDs fail closed while TOPOLOGY remains armed", JSON.stringify(runtime.getState().armedLayers.map(x=>x.id)) === JSON.stringify(["OBSERVABILITY","TOPOLOGY"]));
verify("selection changes do not execute automatically", workspace.includes("onSelectionChange={establish}") && workspace.includes("onClick={run}") && !component.includes("beginExecution"));
verify("prerequisite prose is concise and browse-first", !workspace.includes("Missing:") && !workspace.includes("before entering the laboratory") && workspace.includes("before running an experiment"));
verify("prerequisite actions are contextual", workspace.includes("resolveMissing && <button") && workspace.includes("comparisonMissing && <button") && workspace.includes("resolveMissing || comparisonMissing"));
verify("selection does not mutate Workspace active layers", !component.includes("workspaceRuntime") && !workspace.includes("active_layers ="));
verify("selection does not mutate canonical knowledge or publish Research", !component.match(/KnowledgeObjectRuntime|publishLayers|ResearchBridge/) && workspace.includes("Canonical knowledge is untouched"));
verify("Run / Recompute is the only execution control", (workspace.match(/Run \/ Recompute experiment/g) ?? []).length === 1);
verify("Run action rail is semantic and outside catalog scroller", workspace.includes('className="layers-lab__primary-action-rail" role="region"') && workspace.indexOf("<LayerCatalogMatrix") < workspace.indexOf("layers-lab__primary-action-rail") && !component.includes("Run / Recompute experiment"));
verify("Run action uses primary cyan styling", css.includes(".layers-lab__run-action") && css.includes("border:2px solid #67e8f9") && css.includes("background:#0891b2"));
verify("action rail wraps narrowly and preserves reduced motion", css.includes(".layers-lab__primary-action-rail{align-items:stretch}") && css.includes("prefers-reduced-motion:reduce") && css.includes("transform:none"));
verify("I1A publication gating remains intact", intelligence.includes("isLayersExperimentExecutionCurrent") && intelligence.includes("activeAuthority"));
verify("semantic keyboard controls and accessible states are present", component.includes("type=\"button\"") && component.includes("aria-pressed") && component.includes("type=\"search\"") && component.includes("<details") && component.includes("<summary"));
verify("focus and reduced-motion CSS are present", css.includes(":focus-visible") && css.includes("prefers-reduced-motion"));
verify("catalog prevents application-level horizontal overflow", css.includes("overflow-x:hidden") && css.includes("max-width:100%") && css.includes("min-width:0"));
verify("Research Inbox clearance remains owned by WorkspaceSurface", surface.includes("ResearchInboxInstrument") && !component.includes("ResearchInbox"));
verify("center workspace and side-panel ownership are unchanged", workspace.includes("<main className=\"layers-lab\"") && !component.match(/Navigator|ExperimentalIntelligence/));
console.log(`\nVerifyLayerCatalogMatrix: ${passed}/${passed} checks passed.`);
