import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

let passCount = 0;
const check = (value: unknown, message: string): void => { assert(value, message); passCount += 1; };
const includes = (source: string, value: string, message = value): void => check(source.includes(value), message);
const workspace = readFileSync("src/workspace/surfaces/EvidenceWorkspace.tsx", "utf8");
const component = readFileSync("src/evidence/candidates/WebDiscoveryWorkspace.tsx", "utf8");
const controller = readFileSync("src/evidence/candidates/WebDiscoveryWorkspaceController.ts", "utf8");
const css = readFileSync("src/workspace/surfaces/EvidenceWorkspace.css", "utf8");
const all = component + controller;

includes(workspace, "<WebDiscoveryWorkspace", "EVIDENCE composes the modular discovery surface");
includes(workspace, 'operator.identity?.kind === "ACCOUNT" ? apiScope : undefined', "only authenticated account identity creates Web Discovery scope");
includes(workspace, "const principalId = operator.identity?.operatorId", "existing Candidate Evidence scope remains intact");
includes(workspace, "candidateEvidenceApi.list(apiScope)", "existing Candidate Evidence owner performs refresh");
includes(workspace, "selectedCandidateId: candidateId", "created Candidate Evidence is selected after refresh");
includes(component, "Web Discovery query", "query has a visible associated label");
includes(component, 'onSubmit={submit}', "search requires explicit form submission");
includes(component, '!discovery.query.trim()', "empty and whitespace-only query disables search");
includes(controller, "const normalized = query.trim()", "controller independently rejects whitespace");
includes(controller, "expectedInvestigationRevision: binding.investigationAggregateRevision", "search and capture use authoritative aggregate revision");
includes(controller, "manifoldRevisionId: binding.manifoldRevisionId", "search and capture use authoritative Manifold revision");
includes(controller, "scope.principalId", "ephemeral state binding includes active principal");
includes(controller, "scope.investigationId", "commands and state bind active Investigation identity");
includes(component, "REVIEW · EPHEMERAL", "review state is visibly ephemeral");
includes(component, "No Candidate Evidence was created by search", "search visibly declares zero Candidate Evidence effect");
includes(component, '"Add to Research Inbox"', "available result action leads with Research Inbox terminology");
includes(component, 'role="dialog"', "capture uses dialog semantics");
includes(component, "Add “{discovery.confirmation.result.title}” to Research Inbox?", "dialog heading names the intended Research Inbox destination");
includes(component, "iSEES will preserve this discovery result as review-only Candidate Evidence and add it to your Research Inbox. It will not publish or alter the Manifold.", "dialog explains Candidate Evidence truth and downstream boundary");
includes(component, "Cancel", "confirmation can be cancelled");
includes(controller, "cancelCapture", "cancel has a no-transport controller path");
includes(controller, "if (!scope || !binding || !response || !confirmation || capturePending) return", "capture cannot occur before confirmation and duplicate pending clicks are blocked");
includes(controller, "searchSessionId: response.searchSessionId", "capture uses opaque session authority");
includes(controller, "resultId,", "capture targets one opaque result identity");
const captureCall = controller.match(/buildWebDiscoveryCaptureCommand\(\{([\s\S]*?)\}\)\)/)?.[1] ?? "";
for (const forbidden of ["title", "providerReturnedUrl", "normalizedUrl", "snippet", "attribution", "mediaType", "providerMetadata", "retentionRestrictions"]) check(!captureCall.includes(forbidden), `capture command excludes result ${forbidden}`);
includes(component, 'captured.disposition === "CREATED"', "created capture outcome has distinct feedback");
includes(component, "Already captured / replayed", "replayed capture outcome has distinct feedback");
includes(controller, "await onCandidateCaptured(outcome.candidateId)", "successful capture refreshes Candidate Evidence and the existing Research Inbox projection");
includes(controller, "webDiscoveryAlreadyCaptured(caught)", "authoritative duplicate conflict is recognized as a governed replay");
includes(controller, "[resultId]: replayed", "duplicate replay visibly binds the stable Candidate Evidence identity to the result");
check((controller.match(/setConfirmation\(undefined\)/g) ?? []).length >= 4, "duplicate replay deterministically completes the confirmation modal");
includes(controller, "await onCandidateCaptured(replayed.candidateId)", "duplicate replay refreshes and selects the existing Candidate Evidence projection");
for (const forbidden of ["ResearchBridge", "CuratedContext", "CandidateKnowledge", "Canon", "GraphRuntime", "ManifoldRuntime", "Resolve", "Studio", "Rex", "AI", "charge", "cost"]) check(!controller.includes(forbidden), `controller has no downstream ${forbidden} integration`);
includes(controller, "setResponse(undefined)", "authority binding changes clear ephemeral results");
for (const state of ["authenticated session has expired", "not available to the authenticated account", "revision changed", "discovery session expired"]) includes(controller, state, `recoverable ${state} message exists`);
includes(component, "server-authorized Web Discovery runtime", "search presentation preserves server provider authority");
includes(component, "Browser commands contain no provider choice or credential", "browser has no provider-selection authority");
for (const runtime of ["Live Tavily Web Discovery", "Explicit offline fixture · no live web access", "Web Discovery unavailable · server configuration disabled or invalid", "Live Tavily · bounded provider failure"]) includes(component, runtime, `runtime presentation includes ${runtime}`);
for (const status of ["OFFLINE_FIXTURE", "UNAVAILABLE", "RATE_LIMITED", "FAILED"]) includes(component, status, `runtime presentation handles ${status}`);
check(!controller.includes("adapterId") && !controller.includes("adapterVersion"), "browser search command contains no provider metadata");
includes(component, 'target="_blank" rel="noopener noreferrer"', "external sources use safe new-tab behavior");
includes(component, 'aria-live="polite"', "search state is announced");
includes(component, 'role="alert"', "structured errors are announced");
includes(component, "Researcher note (optional)", "authoritative optional note is exposed");
check((component.match(/type="radio"/g) ?? []).length === 2, "two explicit capture choices exist");
check((component.match(/name="web-capture-destination"/g) ?? []).length === 2, "capture choices are mutually exclusive radios");
includes(component, "Creates Candidate Evidence and adds its reference to the Inbox.", "Research Inbox choice explains its effect");
includes(component, "Keep as Candidate Evidence only", "Candidate Evidence-only choice is explicit");
includes(component, "Captures it for review without adding it to the Inbox.", "Candidate Evidence-only choice explains its effect");
includes(component, "checked={discovery.addToResearchInbox}", "Research Inbox choice reflects the selected default");
includes(component, "checked={!discovery.addToResearchInbox}", "Candidate Evidence-only choice reflects the alternate selection");
includes(controller, "useState(true)", "Research Inbox choice defaults selected");
includes(component, "setAddToResearchInbox(true)", "default choice serializes true");
includes(component, "setAddToResearchInbox(false)", "Candidate Evidence-only choice serializes false");
includes(controller, "addToResearchInbox,", "capture transmits the explicit Research Inbox choice");
for (const label of ["Add to Research Inbox", "Keep as Candidate Evidence", "Adding to Research Inbox…", "Keeping as Candidate Evidence…"]) includes(component, label, `selection-aware action includes ${label}`);
includes(component, 'addedToInbox ? "Added to Research Inbox" : "Kept as Candidate Evidence"', "completed feedback distinguishes both capture outcomes");
includes(component, '<fieldset className="web-discovery__capture-choices"', "choices use grouped fieldset semantics");
includes(component, '<legend className="sr-only">Choose capture destination</legend>', "capture choice group has an accessible name");
includes(component, '<div className="web-discovery__note"><label htmlFor="web-capture-note">', "researcher note is a separate labeled block");
includes(component, '<textarea id="web-capture-note"', "researcher note label remains associated with its textarea");
includes(css, ".web-discovery__note{display:grid;gap:6px;margin-top:20px}", "researcher note is visibly separated from choices");
includes(css, ":focus-visible", "dialog controls retain visible keyboard focus");
includes(workspace, "listCandidateEvidenceResearchAnchors", "successful capture reads durable Candidate Evidence anchors");
includes(workspace, "research.createAnchorsAtomically(inboxAnchors)", "durable anchors enter the established visible Research Inbox runtime");
includes(workspace, "listCandidateEvidenceResearchAnchors(webDiscoveryScope.investigationId", "owned Investigation activation restores durable Candidate Evidence anchors after reload");
includes(controller, "commandIdentity(\"session\")", "each search gets a new session identity");
includes(controller, "commandIdentity(\"search-operation\")", "each search gets a distinct operation identity");
includes(controller, "commandIdentity(\"search-idempotency\")", "each search gets a distinct idempotency identity");
includes(controller, "commandIdentity(\"capture-operation\")", "confirmation receives a stable capture operation identity");
includes(controller, "commandIdentity(\"capture-idempotency\")", "confirmation receives a stable capture idempotency identity");
check((controller.match(/webDiscoveryApi\.capture/g) ?? []).length === 1, "exactly one capture transport boundary exists");
check((controller.match(/webDiscoveryApi\.search/g) ?? []).length === 1, "exactly one search transport boundary exists");
check(!all.includes("fetch("), "workspace creates no second fetch stack");
check(!all.includes("X-ISEES-CSRF"), "workspace creates no second CSRF implementation");
check(!all.includes("window.confirm"), "result selection does not implicitly confirm capture");
includes(css, ".web-discovery{min-width:0", "discovery surface prevents intrinsic horizontal overflow");
includes(css, "@media(max-width:720px)", "existing narrow-width boundary covers discovery composition");
includes(css, ".web-discovery__results{grid-template-columns:minmax(0,1fr)}", "result cards collapse to one bounded column");
includes(workspace, "Researcher-directed intake", "existing intake remains composed");
includes(workspace, "Direct media upload", "existing direct upload remains composed");
includes(workspace, "Investigation Evidence", "existing Investigation Evidence remains composed");
includes(workspace, "Curated Context", "existing Curated Context remains composed");

console.log(`PASS VerifyWebDiscoveryWorkspace — ${passCount} focused assertions passed`);
