import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { AuthorDocumentRuntime } from "../../src/author/runtime/AuthorDocumentRuntime.ts";
import type { StudioV1AuthorApiClient } from "../../src/studio/v1/api/StudioV1AuthorApiClient.ts";
import { StudioV1AuthorClientError } from "../../src/studio/v1/api/StudioV1AuthorApiTypes.ts";
import { StudioV1SaveOrchestrator } from "../../src/studio/v1/runtime/StudioV1SaveOrchestrator.ts";
import { canonicalSha256 } from "../../src/studio/contracts/StudioCanonicalSerialization.ts";

const at="2026-09-11T01:14:35.365Z",ownerId="account-1",investigationId="investigation-1",artifactId="artifact-1",revisionId="artifact-1.r1";
const semantic={documentId:"author-1",schemaVersion:"studio-author-semantic/v1" as const,title:"Restored report",nodeOrder:["p1"],nodes:[{id:"p1",type:"PARAGRAPH" as const,text:"Saved content"}],citations:[],citationStyle:{style:"APA" as const,styleVersion:"studio-v1-apa/1",locale:"en-US"}};
const hash=canonicalSha256(semantic);
const item={artifactId,investigationId,ownerPrincipalId:ownerId,profile:"INVESTIGATION_REPORT",lifecycleClassification:"CANDIDATE_KNOWLEDGE",createdAt:at,currentRevisionId:revisionId,currentRevisionNumber:1,contentHash:hash,savedAt:at};
const detail={artifactId,revision:{artifactId,revisionId,revisionNumber:1,semanticContent:semantic,contentHash:hash,sourceSnapshots:[],profile:"INVESTIGATION_REPORT" as const,profileVersion:"investigation-report/v1",authorPrincipalId:ownerId,createdAt:at,immutableStatus:"IMMUTABLE_SAVED_REVISION" as const}};
const baseApi:StudioV1AuthorApiClient={async createArtifact(){throw Error("no save")},async saveRevision(){throw Error("no save")},async discoverArtifacts(){return{items:[item]}},async getArtifact(){return{artifactId,currentRevisionId:revisionId,currentRevisionNumber:1,contentHash:hash,savedAt:at}},async listRevisions(){return{artifactId,items:[]}},async getRevision(){return detail},async listProjectionStatuses(){return{artifactId,revisionId,items:[]}}};
const runtime=()=>{const value=new AuthorDocumentRuntime();value.activateInvestigation(investigationId);return value};

const emptyRuntime=runtime(),emptyOwner=new StudioV1SaveOrchestrator({...baseApi,async discoverArtifacts(){return{items:[]}}});await emptyOwner.discover(emptyRuntime,investigationId,ownerId);assert.equal(emptyRuntime.getActiveDocument(),undefined);assert.equal(emptyOwner.getState().status,"NO_DOCUMENT");
const restoredRuntime=runtime(),restoredOwner=new StudioV1SaveOrchestrator(baseApi,()=>"next",()=>at);await restoredOwner.discover(restoredRuntime,investigationId,ownerId);assert.equal(restoredRuntime.getActiveDocument()?.identity.id,"author-1");assert.equal(restoredRuntime.getActiveDocument()?.nodes[0]&&"text" in restoredRuntime.getActiveDocument()!.nodes[0]!?restoredRuntime.getActiveDocument()!.nodes[0].text:undefined,"Saved content");assert.equal(restoredRuntime.isDirty(),false);assert.deepEqual({artifactId:restoredOwner.getState().artifactId,revision:restoredOwner.getState().revisionNumber,head:restoredOwner.getState().headRevisionId,draft:restoredOwner.getState().status},{artifactId,revision:1,head:revisionId,draft:"SAVED"});
restoredRuntime.updateNodeText("p1","Unsaved content");restoredOwner.observe(restoredRuntime.getActiveDocument(),true,investigationId);assert.equal(restoredOwner.getState().status,"DIRTY");assert.equal(restoredOwner.getState().headRevisionId,revisionId);
let release!:()=>void;const delayed=new Promise<void>(resolve=>{release=resolve});const dirtyRuntime=runtime(),dirtyOwner=new StudioV1SaveOrchestrator({...baseApi,async discoverArtifacts(){await delayed;return{items:[item]}}});const pending=dirtyOwner.discover(dirtyRuntime,investigationId,ownerId);dirtyRuntime.setActiveDocument({identity:{id:"local",createdAt:new Date(at)},metadata:{title:"Local",description:"",author:"",modifiedAt:new Date(at),version:1},type:"DOCUMENT",status:"NEW",nodes:[{id:"local-p",type:"PARAGRAPH",text:"Keep me"}]});dirtyRuntime.markDirty();release();await pending;assert.equal(dirtyRuntime.getActiveDocument()?.identity.id,"local");assert.equal(dirtyOwner.getState().status,"CONFLICT");
let releaseSwitch!:()=>void;const switchedRuntime=runtime(),switchedOwner=new StudioV1SaveOrchestrator({...baseApi,async discoverArtifacts(){await new Promise<void>(resolve=>{releaseSwitch=resolve});return{items:[item]}}});const stale=switchedOwner.discover(switchedRuntime,investigationId,ownerId);while(!releaseSwitch)await Promise.resolve();switchedRuntime.activateInvestigation("investigation-2");releaseSwitch();await stale;assert.equal(switchedRuntime.getActiveDocument(),undefined);
const unavailableRuntime=runtime();unavailableRuntime.setActiveDocument({identity:{id:"local",createdAt:new Date(at)},metadata:{title:"Local",description:"",author:"",modifiedAt:new Date(at),version:1},type:"DOCUMENT",status:"NEW",nodes:[{id:"p",type:"PARAGRAPH",text:"Preserved"}]});const unavailableOwner=new StudioV1SaveOrchestrator({...baseApi,async discoverArtifacts(){throw new StudioV1AuthorClientError("NETWORK_FAILURE","offline","discoverArtifacts")}});await unavailableOwner.discover(unavailableRuntime,investigationId,ownerId);assert.equal(unavailableRuntime.getActiveDocument()?.identity.id,"local");assert.equal(unavailableOwner.getState().status,"UNAVAILABLE");
const inspector=readFileSync(new URL("../../src/studio/components/StudioArtifactInspector.tsx",import.meta.url),"utf8");assert.match(inspector,/saveAction\.state\.artifactId/);assert.match(inspector,/Legacy lifecycle\/artifact service \(secondary\)/);assert.doesNotMatch(inspector,/runtime\.restoreActiveDocument|runtime\.reconcileCanonicalState/);
console.log("PASS VerifyStudioV1DiscoveryRestoration — empty, exact revision-1 restoration, clean reconciliation, authoritative Inspector identity, dirty preservation, stale Investigation rejection, backend failure safety, and legacy separation verified.");
