import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { ResearchBridgeRuntime } from "../../src/research/ResearchBridgeRuntime.ts";
import { createRexDiscoveryAnchors } from "../../src/rex/RexResearchInboxProjection.ts";
import type { RexCandidateBundle, RexCompletedDiscovery, RexReceipt } from "../../src/rex/RexApi.ts";

const H=`sha256:${"1".repeat(64)}`, C=`sha256:${"2".repeat(64)}`, at="2026-09-15T19:00:00.000Z";
const receipt:RexReceipt={executionId:"execution-durable",jobId:"job-durable",assignmentId:"assignment-durable",assignmentRevisionId:"revision-durable",manifoldRevisionId:"investigation-aggregate:4",manifoldRevisionHash:H,sourceAdapterIdentity:"rex-local-immutable-fixture",sourceAdapterVersion:"1.0.0",normalizerIdentity:"rex-fixture-claim-conserving-normalizer",normalizerVersion:"1.0.0",candidateBundleId:"bundle-durable",candidateContentHash:C,sourceContentHash:H,aiAssistanceStatus:"NONE",providerIdentity:"NONE",modelIdentity:"NONE",estimatedMicros:0,reservedMicros:0,actualMicros:0,chargedMicros:0,releasedMicros:0,terminalExecutionStatus:"COMPLETED",completedAt:at,contentHash:C};
const bundle:RexCandidateBundle={candidateBundleId:"bundle-durable",investigationId:"owned-investigation",assignmentRevisionId:"revision-durable",executionId:"execution-durable",manifoldRevisionId:"investigation-aggregate:4",manifoldRevisionHash:H,sourceLocator:"rex-fixture://synthetic-observation/v1",sourceVersion:"1.0.0",sourceClassification:"LOCAL_FIXTURE",adapterIdentity:receipt.sourceAdapterIdentity,adapterVersion:receipt.sourceAdapterVersion,normalizerIdentity:receipt.normalizerIdentity,normalizerVersion:receipt.normalizerVersion,sourceContentHash:H,candidateContentHash:C,candidateClassification:"CANDIDATE_KNOWLEDGE",reviewStatus:"RESEARCHER_REVIEW_REQUIRED",canonEffect:"NONE",aiAssistanceStatus:"NONE",providerIdentity:"NONE",modelIdentity:"NONE",modelClass:"NONE",nodes:[{candidateId:"reported-blue-indicator",kind:"OBSERVATION",label:"Reported blue indicator",claim:"A synthetic report.",candidateContentHash:H}],edges:[],fieldLineage:[{candidateId:"reported-blue-indicator",sourceLocator:"rex-fixture://synthetic-observation/v1",sourceVersion:"1.0.0",fields:[{candidateField:"label",sourceField:"candidate_label",exactValue:"Reported blue indicator",normalizationRule:"EXACT_STRUCTURED_FIELD/v1"}]}]};
const discovery:RexCompletedDiscovery={selectedSource:{kind:"NODE",identity:"system:event:E-TICTAC-2004"},assignmentId:receipt.assignmentId,receipt,bundle};
const identity=createRexDiscoveryAnchors({investigationId:bundle.investigationId,...discovery})[0]!.anchorId;
const refreshed=new ResearchBridgeRuntime();const graphBefore={nodes:16,edges:13,events:1},canonBefore="immutable";
const before=JSON.stringify(refreshed.getDesk());
assert.equal(createRexDiscoveryAnchors({investigationId:bundle.investigationId,...discovery})[0]!.anchorId,identity,"durable result identity remains reproducible without publication");
assert.equal(JSON.stringify(refreshed.getDesk()),before,"restoration creates zero Research Anchors and performs zero ResearchBridgeRuntime mutations");assert.deepEqual(graphBefore,{nodes:16,edges:13,events:1});assert.equal(canonBefore,"immutable");
const previouslyPublished=createRexDiscoveryAnchors({investigationId:bundle.investigationId,...discovery})[0]!;refreshed.createAnchorsAtomically([previouslyPublished]);const storedBefore=JSON.stringify(refreshed.getDesk());assert.equal(refreshed.getDesk().entries.length,1);assert.equal(JSON.stringify(refreshed.getDesk()),storedBefore,"previously stored researcher work is preserved");
const hydrator=readFileSync(new URL("../../src/rex/RexResearchInboxHydrator.tsx",import.meta.url),"utf8"), control=readFileSync(new URL("../../src/rex/RexExploreControl.tsx",import.meta.url),"utf8");
for(const forbidden of ["listCompletedDiscoveries","useResearchBridge","publishRexDiscoveriesAtomically","createAnchorsAtomically","ResearchBridgeRuntime"])assert(!hydrator.includes(forbidden),`restoration must not invoke ${forbidden}`);assert(!hydrator.includes("createAssignment")&&!hydrator.includes(".prepare(")&&!hydrator.includes(".execute("));assert(control.includes("heldResult")&&!control.includes("restored"));
console.log("P57-REX-SELECTION-I1F durable history/nonpublishing restoration verification passed (11 boundaries).");
