import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import {
  CANONICAL_LAYER_CATALOG_VERSION, LAYERS_EXPERIMENT_SCHEMA_VERSION,
  CANONICAL_LAYER_DEFAULT_PROFILE_VERSION, CanonicalLayerCatalog, CanonicalLayerFamilies,
  CanonicalLayerAvailability, CanonicalLayerOperationalStatus, CanonicalLayerProfileId,
  decodeCanonicalLayerSelection, enumerateCanonicalLayers, getCanonicalLayerDefinition,
  isCanonicalLayerId, restoreCanonicalLayerProfile,
} from "../../src/layers/catalog/index.ts";
import { CanonicalLayerRegistry, SystemCanonLayers } from "../../src/manifold/layers/systemCanonLayers.ts";
import { LayersExperimentRuntime } from "../../src/layers/runtime/LayersExperimentRuntime.ts";

const pass = (n:number, text:string) => console.log(`PASS ${n} — ${text}`);
const expected = "OBSERVABILITY VISUAL_OBSERVATION RADAR_OBSERVATION INFRARED_OBSERVATION ACOUSTIC_OBSERVATION ELECTROMAGNETIC_OBSERVATION MULTISENSOR_CORROBORATION SENSOR_COVERAGE SENSOR_RELIABILITY NARRATIVE WITNESS_TESTIMONY MILITARY_REPORTING HISTORICAL_ACCOUNTS TERMINOLOGY SEMANTIC_DRIFT TRANSLATION_VARIANCE CONTEXT_PRESERVATION TEMPORAL DURATION SEQUENCE RECURRENCE SEASONALITY LONG_TERM_PERSISTENCE GEOGRAPHY SPATIAL_PROXIMITY TERRAIN BATHYMETRY FLIGHT_CORRIDORS STRATEGIC_LOCATION INFRASTRUCTURE MILITARY_INSTALLATIONS RADAR_SYSTEMS AIRPORTS POWER_GRIDS TRANSPORT_NETWORKS COMMUNICATIONS_INFRASTRUCTURE TOPOLOGY SOURCE_DIVERSITY EVIDENCE_DENSITY CONFIDENCE_PROFILE PROVENANCE_COMPLETENESS MYTHOLOGY FOLKLORE SYMBOLISM RELIGIOUS_INTERPRETATION TECHNOLOGICAL_CAPABILITY SOCIETAL_RESPONSE GLOBAL_ANXIETY_INDEX".split(" ");
assert.equal(CANONICAL_LAYER_CATALOG_VERSION,"layers-catalog/v1"); assert.equal(LAYERS_EXPERIMENT_SCHEMA_VERSION,"layers-experiment/v1"); assert.equal(CANONICAL_LAYER_DEFAULT_PROFILE_VERSION,"layers-default-profiles/v1"); pass(1,"catalog, experiment schema, and profile versions are explicit");
assert.equal(CanonicalLayerCatalog.length,48); assert.deepEqual(CanonicalLayerCatalog.map(x=>x.id),expected); assert.equal(new Set(expected).size,48); pass(2,"exact approved 48 identities occur once");
assert.equal(CanonicalLayerFamilies.length,16); assert.deepEqual(CanonicalLayerFamilies.map(x=>x.displayOrder),[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]); pass(3,"family identities and ordering are explicit");
const families=new Set(CanonicalLayerFamilies.map(x=>x.id)); assert(CanonicalLayerCatalog.every(x=>families.has(x.familyId))); pass(4,"every family reference is valid");
assert.deepEqual(CanonicalLayerCatalog.map(x=>x.displayOrder),Array.from({length:48},(_,i)=>i+1)); assert(CanonicalLayerCatalog.every(x=>x.familyMemberOrder>0)); pass(5,"display and member ordering are explicit");
assert(CanonicalLayerCatalog.every(x=>x.label.trim()&&x.description.trim())); pass(6,"labels and descriptions are non-empty");
assert(CanonicalLayerCatalog.every(x=>x.requiredCanonicalInputs.length>0)); pass(7,"required canonical inputs are declared");
assert(CanonicalLayerCatalog.every(x=>x.provenancePolicy.trim()&&x.missingDataBehavior.includes("UNAVAILABLE"))); pass(8,"provenance and missing-data behavior are explicit");
const operational=CanonicalLayerCatalog.filter(x=>x.operationalStatus===CanonicalLayerOperationalStatus.OPERATIONAL); assert(operational.every(x=>x.evaluatorKey&&x.evaluatorVersion)); assert.deepEqual(operational.map(x=>x.id),["OBSERVABILITY","NARRATIVE","GEOGRAPHY","INFRASTRUCTURE"]); pass(9,"only four proven layers are operational with evaluators");
const unavailable=CanonicalLayerCatalog.filter(x=>x.operationalStatus===CanonicalLayerOperationalStatus.UNAVAILABLE); assert.equal(unavailable.length,44); assert(unavailable.every(x=>x.unavailableReason?.trim()&&!x.evaluatorKey&&!x.evaluatorVersion)); pass(10,"all 44 unavailable layers have truthful reasons and no fake evaluators");
for(const id of ["TEMPORAL","TOPOLOGY","GLOBAL_ANXIETY_INDEX"]){const x=getCanonicalLayerDefinition(id)!;assert.equal(x.operationalStatus,"UNAVAILABLE");assert.equal(x.researcherSelectable,false);} pass(11,"Temporal, Topology, and Global Anxiety are visible and unavailable");
const anxiety=getCanonicalLayerDefinition("GLOBAL_ANXIETY_INDEX")!; for(const input of ["governed component definitions","declared population","declared time window","qualified input datasets","normalization rules","coverage and adequacy requirements","complete component ledger","versioned methodology","full provenance"]) assert(anxiety.requiredCanonicalInputs.includes(input)); pass(12,"Global Anxiety declares its complete governed-input contract without computation");
assert(isCanonicalLayerId("OBSERVABILITY")&&!isCanonicalLayerId("FUTURE_LAYER")&&!getCanonicalLayerDefinition("FUTURE_LAYER")); pass(13,"unknown identities never cast to canonical or operational");
const source=["TEMPORAL","OBSERVABILITY","TEMPORAL","FUTURE_LAYER","OLD_LAYER"] as const; const before=JSON.stringify(source); const decoded=decodeCanonicalLayerSelection(source,["OLD_LAYER"]); assert.deepEqual(decoded.known,["OBSERVABILITY","TEMPORAL"]); assert.deepEqual(decoded.unsupported,["FUTURE_LAYER","OLD_LAYER"]); assert.equal(JSON.stringify(source),before); pass(14,"duplicates normalize and unknown/retired identities are retained and diagnosed");
assert(decoded.diagnostics.some(x=>x.normalized==="FUTURE_LAYER"&&x.classification==="UNKNOWN")&&decoded.diagnostics.some(x=>x.normalized==="OLD_LAYER"&&x.classification==="RETIRED")); pass(15,"compatibility diagnostics distinguish unknown and retired identities");
assert.throws(()=>decodeCanonicalLayerSelection(["bad layer"]),/malformed/); assert.throws(()=>decodeCanonicalLayerSelection([7]),/strings/); pass(16,"invalid serialized identities are rejected");
assert.deepEqual(restoreCanonicalLayerProfile(CanonicalLayerProfileId.CANONICAL_BASELINE),["OBSERVABILITY","NARRATIVE","TEMPORAL"]); assert.deepEqual(restoreCanonicalLayerProfile(CanonicalLayerProfileId.EMPTY_EXPERIMENT),[]); assert.deepEqual(restoreCanonicalLayerProfile(CanonicalLayerProfileId.ALL_OPERATIONAL),["OBSERVABILITY","NARRATIVE","GEOGRAPHY","INFRASTRUCTURE"]); pass(17,"versioned profiles restore deterministically");
const legacyExpected={OBSERVABILITY:["Observability","Sensor observations, witnesses, instrumentation, and evidence.","OBSERVATION",true],NARRATIVE:["Narrative","Claims, reports, testimony, and descriptive accounts.","CONTEXT",true],TEMPORAL:["Temporal","Time relationships, chronology, sequencing, and recurrence.","CONTEXT",true],GEOGRAPHY:["Geography","Spatial relationships, location, terrain, and proximity.","PHYSICAL",false],INFRASTRUCTURE:["Infrastructure","Facilities, platforms, organizations, and supporting systems.","PHYSICAL",false]} as const;
assert.equal(CanonicalLayerRegistry.length,5); for(const [id,values] of Object.entries(legacyExpected)){const x=SystemCanonLayers[id as keyof typeof SystemCanonLayers];assert.deepEqual([x.name,x.description,x.group,x.enabledByDefault],values);} pass(18,"SystemCanonLayers exact five-layer compatibility metadata is derived and intact");
assert.deepEqual(enumerateCanonicalLayers().map(x=>x.id),enumerateCanonicalLayers().map(x=>x.id)); assert(Object.isFrozen(CanonicalLayerCatalog)&&Object.isFrozen(CanonicalLayerCatalog[0])&&Object.isFrozen(enumerateCanonicalLayers())); pass(19,"catalog enumeration and structures are stable and immutable");
const runtime=new LayersExperimentRuntime(); runtime.establish({scope:{investigationId:"i",workspaceId:"w",focusedEventId:"a",comparisonEventId:"b",subjectIds:["s1","s2"],compareOrigin:{pairId:"p",candidateId:"c",evaluationId:"e"},resolveOrigin:{executionId:"r"}},baseline:{investigationId:"i",workspaceId:"w",subjectIds:["s1","s2"],canonicalStartingLayerIds:[],startingResolveExecutionId:"r",temporalContext:{},investigativeScale:{}},armedLayers:{layerIds:["OBSERVABILITY","TEMPORAL","TOPOLOGY","FUTURE_LAYER"]}}); const armed=runtime.getState().armedLayers; assert.equal(armed.find(x=>x.id==="OBSERVABILITY")?.operational,true); assert(armed.filter(x=>x.id!=="OBSERVABILITY").every(x=>!x.operational)); pass(20,"runtime catalog membership cannot imply computational capability");
const workspaceBefore=readFileSync("src/workspace/defaultWorkspace.ts","utf8"); assert(workspaceBefore.includes('"OBSERVABILITY",')&&workspaceBefore.includes('"NARRATIVE",')&&workspaceBefore.includes('"TEMPORAL",')); assert(!workspaceBefore.includes("CanonicalLayerCatalog")); pass(21,"catalog does not own or mutate Workspace.active_layers defaults");
const projection=readFileSync("src/layers/projection/LayersExperimentalPairProjection.ts","utf8"); for(const token of ["DEFAULT_CANONICAL_SIMILARITY_WEIGHTS","weightedContribution","weightedSum / participatingWeight","scoreDelta"]) assert(projection.includes(token)); pass(22,"existing projection mathematics remains owned by the unchanged projection module");
const catalogSource=readFileSync("src/layers/catalog/CanonicalLayerCatalog.ts","utf8"); assert(!catalogSource.includes("function compute")&&!catalogSource.includes("placeholder")); pass(23,"catalog contains metadata only and no placeholder computation");
const lab=readFileSync("src/layers/components/LayersLaboratoryWorkspace.tsx","utf8"); assert(lab.includes("CanonicalLayerRegistry.map")); assert.equal(CanonicalLayerRegistry.length,5); pass(24,"no 48-layer visual grid or family controls were composed");
assert(unavailable.every(x=>x.availability!==CanonicalLayerAvailability.OPERATIONAL)); pass(25,"no unavailable layer has operational availability");
assert(CanonicalLayerCatalog.every(x=>x.catalogVersion===CANONICAL_LAYER_CATALOG_VERSION)); pass(26,"every entry carries the catalog version");
assert(CanonicalLayerCatalog.every(x=>x.outputKinds.length>0&&typeof x.researcherSelectable==="boolean")); pass(27,"outputs and researcher selectability are explicit");
assert.equal(JSON.stringify(source),before); pass(28,"decoder leaves caller inputs unmodified");
console.log("\nAll 28 Canonical Layer Catalog invariants passed.");
