import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { ResearchBridgeRuntime } from "../../src/research/ResearchBridgeRuntime.ts";
import { createRexApi, type RexCandidateBundle, type RexReceipt } from "../../src/rex/RexApi.ts";
import { createRexDiscoveryAnchors, publishRexDiscoveriesAtomically } from "../../src/rex/RexResearchInboxProjection.ts";

const H=`sha256:${"a".repeat(64)}`, H2=`sha256:${"b".repeat(64)}`, when="2026-09-15T12:00:00.000Z";
const receipt:RexReceipt={executionId:"execution-1",jobId:"job-1",assignmentId:"assignment-1",assignmentRevisionId:"assignment-revision-1",manifoldRevisionId:"investigation-aggregate:1",manifoldRevisionHash:H,sourceAdapterIdentity:"rex-local-immutable-fixture",sourceAdapterVersion:"1.0.0",normalizerIdentity:"rex-fixture-claim-conserving-normalizer",normalizerVersion:"1.0.0",candidateBundleId:"bundle-1",candidateContentHash:H2,sourceContentHash:H,aiAssistanceStatus:"NONE",providerIdentity:"NONE",modelIdentity:"NONE",estimatedMicros:0,reservedMicros:0,actualMicros:0,chargedMicros:0,releasedMicros:0,terminalExecutionStatus:"COMPLETED",completedAt:when,contentHash:H2};
const bundle:RexCandidateBundle={candidateBundleId:"bundle-1",investigationId:"investigation-1",assignmentRevisionId:"assignment-revision-1",executionId:"execution-1",manifoldRevisionId:"investigation-aggregate:1",manifoldRevisionHash:H,sourceLocator:"rex-fixture://synthetic-observation/v1",sourceVersion:"1.0.0",sourceClassification:"LOCAL_FIXTURE",adapterIdentity:receipt.sourceAdapterIdentity,adapterVersion:receipt.sourceAdapterVersion,normalizerIdentity:receipt.normalizerIdentity,normalizerVersion:receipt.normalizerVersion,sourceContentHash:H,candidateContentHash:H2,candidateClassification:"CANDIDATE_KNOWLEDGE",reviewStatus:"RESEARCHER_REVIEW_REQUIRED",canonEffect:"NONE",aiAssistanceStatus:"NONE",providerIdentity:"NONE",modelIdentity:"NONE",modelClass:"NONE",nodes:[{candidateId:"candidate-node",kind:"OBSERVATION",label:"Reported blue indicator",claim:"A synthetic report.",candidateContentHash:H}],edges:[{candidateId:"candidate-edge",kind:"PROPOSED_RELATIONSHIP",label:"Possible relation",sourceCandidateId:"candidate-node",targetCandidateId:"selected-node",proposedRelationship:"MAY_RELATE_TO",candidateContentHash:H2}],fieldLineage:[{candidateId:"candidate-node",sourceLocator:"rex-fixture://synthetic-observation/v1",sourceVersion:"1.0.0",fields:[{candidateField:"label",sourceField:"candidate_label",exactValue:"Reported blue indicator",normalizationRule:"EXACT_STRUCTURED_FIELD/v1"}]},{candidateId:"candidate-edge",sourceLocator:"rex-fixture://synthetic-observation/v1",sourceVersion:"1.0.0",fields:[{candidateField:"relationship",sourceField:"relationship",exactValue:"MAY_RELATE_TO",normalizationRule:"EXACT_STRUCTURED_FIELD/v1"}]}]};
const input={investigationId:"investigation-1",selectedSource:{kind:"NODE" as const,identity:"selected-node"},assignmentId:"assignment-1",receipt,bundle};
const anchors=createRexDiscoveryAnchors(input);assert.equal(anchors.length,2);assert.equal(anchors[0]!.rexDiscovery.candidateKind,"NODE");assert.equal(anchors[1]!.rexDiscovery.candidateKind,"EDGE");assert.match(anchors[0]!.anchorId,/bundle-1.*candidate-node/);assert.deepEqual(anchors[0]!.rexDiscovery.fieldLineage,bundle.fieldLineage[0]!.fields);assert.equal(anchors[0]!.rexDiscovery.epistemicClassification,"CANDIDATE_KNOWLEDGE");assert.equal(anchors[0]!.rexDiscovery.reviewStatus,"RESEARCHER_REVIEW_REQUIRED");assert.equal(anchors[0]!.rexDiscovery.canonEffect,"NONE");assert.equal(anchors[0]!.rexDiscovery.aiAssistanceStatus,"NONE");assert.equal(anchors[0]!.insertability.state,"INSPECTION_ONLY");
const runtime=new ResearchBridgeRuntime();const before=runtime.getDesk();const added=publishRexDiscoveriesAtomically(runtime,input);assert.equal(added.added,2);assert.equal(runtime.getDesk().entries.length,2);const repeated=publishRexDiscoveriesAtomically(runtime,input);assert.deepEqual({added:repeated.added,alreadyPresent:repeated.alreadyPresent},{added:0,alreadyPresent:2});assert.equal(runtime.getDesk().entries.length,2);assert.equal(before.entries.length,0);
assert.throws(()=>publishRexDiscoveriesAtomically(runtime,{...input,bundle:{...bundle,fieldLineage:bundle.fieldLineage.slice(0,1)}}));assert.equal(runtime.getDesk().entries.length,2,"failed projection must publish no partial entries");
const edgeAnchors=createRexDiscoveryAnchors({...input,selectedSource:{kind:"EDGE",identity:"selected-edge"}});assert.equal(edgeAnchors[0]!.rexDiscovery.selectedSource.kind,"EDGE");assert.equal(edgeAnchors[0]!.rexDiscovery.selectedSource.identity,"selected-edge");

const calls:{url:string;init:RequestInit}[]=[];const responses=[{assignmentId:"assignment-1",investigationId:"investigation-1",targetId:"selected-node",targetKind:"NODE",lifecycle:"SLEEPING",currentRevisionId:"ar-1",manifoldRevisionId:"investigation-aggregate:1",manifoldRevisionHash:H,createdAt:when,updatedAt:when,idempotencyDisposition:"CREATED"},{executionId:"execution-1",jobId:"job-1",disposition:"EXECUTABLE",semanticDuplicateStatus:"UNIQUE",originalExecutionId:null,authorizationDisposition:"ALLOW",estimatedMicros:0,reservedMicros:0,executionStatus:"QUEUED"},{receipt,terminalStatus:"COMPLETED",receiptContentHash:H2},receipt,bundle,{discoveries:[{selectedSource:input.selectedSource,assignmentId:input.assignmentId,receipt,bundle}]}];let index=0;
const api=createRexApi({baseUrl:"https://isees.invalid",cookieSource:()=>"isees_csrf=token",fetch:async(input,init)=>{calls.push({url:String(input),init:init!});return new Response(JSON.stringify(responses[index++]),{status:200,headers:{"Content-Type":"application/json"}})}});const assignment=await api.createAssignment("investigation-1","selected-node","NODE");const prepared=await api.prepare("investigation-1",assignment);const executed=await api.execute("investigation-1",prepared.jobId!);await api.getReceipt("investigation-1",executed.executionId);await api.getBundle("investigation-1",executed.candidateBundleId);const restored=await api.listCompletedDiscoveries("investigation-1");assert.equal(restored.length,1);assert.equal(restored[0]!.selectedSource.identity,"selected-node");assert.equal(calls.length,6);assert(calls.every(call=>call.url.startsWith("https://isees.invalid/api/v1/investigations/")));assert(calls.every(call=>call.init.credentials==="include"));assert(calls.slice(0,3).every(call=>(call.init.headers as Record<string,string>)["X-ISEES-CSRF"]==="token"));assert.equal(calls[5]!.init.method,"GET");assert.equal(JSON.parse(String(calls[0]!.init.body)).targetKind,"NODE");assert.equal(JSON.parse(String(calls[1]!.init.body)).manifoldRevisionHash,H,"preparation must reuse the server-issued hash");

const control=readFileSync(new URL("../../src/rex/RexExploreControl.tsx",import.meta.url),"utf8"), right=readFileSync(new URL("../../src/components/RightPanel.tsx",import.meta.url),"utf8"), inbox=readFileSync(new URL("../../src/manifold/components/ResearchInboxInstrument.tsx",import.meta.url),"utf8");assert(control.includes("Explore with REX"));assert(control.includes("REX discovery requires a saved researcher investigation."));assert(control.includes('setProgress("PREPARING")')&&control.includes('setProgress("EXECUTING")')&&control.includes('setProgress("COMPLETED")'));assert(right.includes("<RexExploreControl />"));assert(inbox.includes('onExpandedChange(true)'));assert(!right.includes("createAssignment("),"selection rendering must not execute REX");assert(!control.includes("useEffect")&&!control.includes("setInterval")&&!control.includes("setTimeout"),"REX must be explicit and non-polling");assert(!control.match(/google|bing|openai|anthropic|api[_-]?key/i));
console.log("P57-REX-A3.5 Research Inbox projection verification passed (37 contract checks grouped across API, workflow, atomicity, lineage, UI, and authority boundaries).");
