import { canonicalIntentionSerialize, type IntentionProjection } from "../../src/intention/projection";
import { createIntentionDerivationSelection, createIntentionLinkSelection, createIntentionNodeSelection, IntentionSelectionKind, NO_INTENTION_SELECTION, resolveIntentionSelection } from "../../src/intention/selection";
let count=0;const assert=(v:unknown,m:string)=>{if(!v)throw new Error(`VERIFY FAILED: ${m}`);count+=1;};
const projection={id:"P",executionId:"IX",availability:"AVAILABLE",epistemicClassification:"COMPUTATIONAL_PROJECTION",nodes:[{id:"N",owner:"INTENTION",sourceKnowledgeId:"K",canonicalEventId:"E",role:"FOCUSED_EVENT",metricDerivationIds:["D"]}],links:[{id:"L",owner:"INTENTION",sourceNodeId:"N",targetNodeId:"N",kind:"DESCRIPTIVE_RESOLVE_COMPARISON",metricDerivationIds:["D"]}],derivations:[{id:"D",metricId:"m",metricName:"Metric",symbol:"m",value:1,displayValue:"1",units:"unitless",availability:"AVAILABLE",epistemicClassification:"COMPUTATIONAL_PROJECTION",equationId:"intention:descriptor:resolve-aggregate-similarity:v1",inputs:[{id:"i",symbol:"i",value:1,sourcePath:"source",sourceKnowledgeIds:["K"],sourceRelationshipIds:[],availability:"AVAILABLE"}],assumptions:[],unavailableInputs:[],sourceKnowledgeIds:["K"],sourceRelationshipIds:[],investigationId:"I",operationalRevisionId:"R",resolveExecutionId:"RX",intentionExecutionId:"IX",modelId:"M",modelVersion:"V",configurationId:"C",projectedNodeId:"N"}],lineage:{investigationId:"I",operationalRevisionId:"R",focusedEventId:"E",resolveExecutionId:"RX",candidateId:"CA",evaluationId:"EV",sourceKnowledgeIds:["K"],sourceRelationshipIds:[],modelId:"M",modelVersion:"V",configurationId:"C"},hypotheses:[],validationStatus:"NOT_TESTED",canonicalRepresentation:"fixed"} as unknown as IntentionProjection;
const before=canonicalIntentionSerialize(projection);const node=createIntentionNodeSelection(projection,"N"),link=createIntentionLinkSelection(projection,"L"),derivation=createIntentionDerivationSelection(projection,"D");
assert(resolveIntentionSelection(NO_INTENTION_SELECTION,projection).kind===IntentionSelectionKind.NONE,"NONE resolves safely");assert(resolveIntentionSelection(node,projection).kind===IntentionSelectionKind.INTENTION_PROJECTED_NODE,"valid node resolves exactly");assert(resolveIntentionSelection(link,projection).kind===IntentionSelectionKind.INTENTION_PROJECTED_LINK,"valid link resolves exactly");assert(resolveIntentionSelection(derivation,projection).kind===IntentionSelectionKind.INTENTION_METRIC_DERIVATION,"valid derivation resolves exactly");
assert(canonicalIntentionSerialize(createIntentionNodeSelection(projection,"N"))===canonicalIntentionSerialize(createIntentionNodeSelection(projection,"N")),"2D and 3D IDs create identical locked selection");const beforeRendererModeBoundary={lockedSelection:node,resolvedSelection:resolveIntentionSelection(node,projection)};const afterRendererModeBoundary={lockedSelection:node,resolvedSelection:resolveIntentionSelection(node,projection)};assert(canonicalIntentionSerialize(beforeRendererModeBoundary)===canonicalIntentionSerialize(afterRendererModeBoundary),"renderer-mode boundary preserves locked selection kind, identity, lineage, and resolved projection entity");assert(resolveIntentionSelection(node,projection).kind!==IntentionSelectionKind.NONE,"locked node resolves to an existing projected identity");assert(NO_INTENTION_SELECTION.kind===IntentionSelectionKind.NONE,"hover creates no locked selection");
for(const [key,value] of [["investigationId","OTHER"],["operationalRevisionId","OTHER"],["intentionExecutionId","OTHER"],["projectionId","OTHER"],["modelId","OTHER"],["modelVersion","OTHER"],["configurationId","OTHER"],["resolveExecutionId","OTHER"],["candidateId","OTHER"],["evaluationId","OTHER"]] as const) assert(resolveIntentionSelection({...node,[key]:value},projection).kind===IntentionSelectionKind.NONE,`wrong ${key} fails closed`);
assert(resolveIntentionSelection({...node,projectedNodeId:"MISSING"},projection).kind===IntentionSelectionKind.NONE,"missing selected object fails closed");assert(resolveIntentionSelection(node,{...projection,id:"P2"}).kind===IntentionSelectionKind.NONE,"stale projection transition clears to NONE");assert(canonicalIntentionSerialize(projection)===before,"projection and source inputs remain unchanged");assert(!/storage|persist|localStorage|sessionStorage/i.test([createIntentionNodeSelection,resolveIntentionSelection].map(String).join("\n")),"no selection persistence occurs");console.log(`PASS VerifyIntentionSelectionCoherence — ${count} assertions verified`);
