import assert from "node:assert/strict";
import { CANONICAL_LAYER_EVALUATOR_INPUT_SCHEMA_VERSION, projectCanonicalLayerEvaluatorInput } from "../../src/layers/evaluators/CanonicalLayerEvaluatorInputProjection.ts";
import type { KnowledgeObject } from "../../src/knowledge/model/KnowledgeObject.ts";

let count=0; const pass=(message:string)=>console.log(`PASS ${++count} — ${message}`);
const fixed="2020-01-01T00:00:00.000Z";
function event(id:string, duration:number|undefined, contradiction=.1, revision=7):KnowledgeObject{return {identity:{id,createdAt:fixed},metadata:{title:id,version:"canon/v1"},lifecycle:{status:"KNOWLEDGE",revision:1},type:"EVENT",status:"KNOWLEDGE",confidence:{value:id.endsWith("a")?0:.75},provenance:{sourceId:`authority:${id}`,sourceType:"CANON",sourceRevision:revision,observedAt:fixed,createdAt:fixed,updatedAt:fixed},revision:{revision:1,timestamp:fixed},graph:[],relationships:[],tags:[],capabilities:{projectable:true,publishable:true,editable:false},payload:{source:"SYSTEM_CANON",sourceKind:"CANONICAL_REPLAY_EVENT",canonicalEvent:{core_event:{semantic_signature:{traits:["zeta","alpha"]},observability_profile:{...(duration===undefined?{}:{duration_minutes:duration})}},topology:{topology_state:{contradiction_density:contradiction,residual_instability:.2,entanglement_score:.3,cluster_fragmentation:.4}}},observabilityRegime:"multi_sensor"}};}
const base=[event("knowledge:b",undefined),event("knowledge:a",0)];
const request=(knowledgeObjects:readonly KnowledgeObject[],extra:Partial<Parameters<typeof projectCanonicalLayerEvaluatorInput>[0]>={})=>projectCanonicalLayerEvaluatorInput({investigationId:"investigation:1",pairId:"canonical-pair:knowledge:a:knowledge:b",candidateId:"similarity-candidate:knowledge:a:knowledge:b",evaluationId:"evaluation:similarity-candidate:knowledge:a:knowledge:b",executionId:"layers-execution:1",caseA:{subjectIdentity:"event:a",knowledgeObjectId:"knowledge:a"},caseB:{subjectIdentity:"event:b",knowledgeObjectId:"knowledge:b"},knowledgeObjects,...extra});

const first=request(base);
assert.equal(CANONICAL_LAYER_EVALUATOR_INPUT_SCHEMA_VERSION,"layer-evaluator-input/v1"); assert.equal(first.inputSchemaVersion,"layer-evaluator-input/v1"); pass("exact input schema version is explicit");
assert.equal(first.experimentSchemaVersion,"layers-experiment/v2"); assert.equal(first.catalogVersion,"layers-catalog/v1"); pass("experiment and catalog versions are linked");
assert.deepEqual([first.investigationId,first.pairId,first.candidateId,first.evaluationId,first.executionId],["investigation:1","canonical-pair:knowledge:a:knowledge:b","similarity-candidate:knowledge:a:knowledge:b","evaluation:similarity-candidate:knowledge:a:knowledge:b","layers-execution:1"]); pass("all ownership identities are preserved");
assert.deepEqual(first.endpoints.map(x=>[x.subjectRole,x.subjectIdentity,x.knowledgeObjectId]),[["CASE_A","event:a","knowledge:a"],["CASE_B","event:b","knowledge:b"]]); assert(first.endpoints.every(x=>x.endpointSnapshotId.startsWith("layer-endpoint-input:"))); pass("Case A/B and endpoint snapshot identities are frozen");
const zero=first.endpoints[0].components.find(x=>x.componentIdentity==="OBSERVABILITY.durationMinutes")!; assert.equal(zero.availability,"AVAILABLE"); if(zero.availability==="AVAILABLE") {assert.equal(zero.rawValue,0);assert.equal(zero.lineage.sources[0]?.sourceVersion,"canon/v1");assert.equal(zero.lineage.sources[0]?.sourceRevision,"7");} pass("AVAILABLE raw zero and authoritative lineage round-trip");
const missing=first.endpoints[1].components.find(x=>x.componentIdentity==="OBSERVABILITY.durationMinutes")!; assert.equal(missing.availability,"UNAVAILABLE"); assert.equal(missing.code,"CANONICAL_FEATURE_UNAVAILABLE"); assert(!("rawValue" in missing)); pass("UNAVAILABLE has structured identity/reason and no fabricated raw value");
assert(Object.isFrozen(first)&&Object.isFrozen(first.endpoints)&&Object.isFrozen(first.endpoints[0].components)&&Object.isFrozen(zero)&&Object.isFrozen(zero.availability==="AVAILABLE"?zero.lineage.sources:[])); pass("nested projection arrays and objects are immutable");
const source=event("knowledge:a",0); const captured=request([event("knowledge:b",undefined),source]); const before=captured.canonicalRepresentation; (source.payload as any).canonicalEvent.core_event.observability_profile.duration_minutes=99; assert.equal(captured.canonicalRepresentation,before); assert.equal((captured.endpoints[0].components.find(x=>x.componentIdentity==="OBSERVABILITY.durationMinutes") as any).rawValue,0); pass("source mutation after capture cannot change snapshot");
const reordered=request([...base].reverse()); assert.equal(reordered.inputProjectionId,first.inputProjectionId); assert.equal(reordered.canonicalRepresentation,first.canonicalRepresentation); pass("reordered equivalent input has identical identity and representation");
assert.notEqual(request([event("knowledge:b",undefined),event("knowledge:a",0,.9)]).inputProjectionId,first.inputProjectionId); pass("material raw component change changes identity");
assert.notEqual(request([event("knowledge:b",3),event("knowledge:a",0)]).inputProjectionId,first.inputProjectionId); pass("material missing-input change changes identity");
assert.notEqual(request([event("knowledge:b",undefined,undefined,8),event("knowledge:a",0)]).inputProjectionId,first.inputProjectionId); pass("material source revision change changes identity");
assert.throws(()=>request([event("knowledge:a",0)]),/CASE_B endpoint/); assert.throws(()=>request([event("knowledge:a",0),event("knowledge:a",0)]),/Duplicate Knowledge/); pass("missing and duplicate endpoint ownership reject");
for(const name of ["contradictionDensity","residualInstability","entanglementScore","clusterFragmentation"]){assert(first.endpoints.every(endpoint=>endpoint.components.some(component=>component.componentIdentity===`TOPOLOGY.${name}`)));} pass("future exact Resolve topology-state shape is captured without activation");
console.log(`\nAll ${count} Canonical Layer Evaluator Input Projection invariants passed.`);
