import { resolveApiBaseUrl } from "../../api/ApiOrigin.ts";
import type { WebDiscoverySearchResult, WebDiscoveryStableError } from "./WebDiscoveryApi.ts";

export type GuestOperationState = "RESERVED" | "DISPATCHING" | "COMPLETED" | "UNKNOWN";
export type GuestSearchStatus = "PENDING" | "COMPLETED" | "ZERO_RESULTS" | "CANCELLED" | "UNAVAILABLE" | "RATE_LIMITED" | "FAILED" | "UNKNOWN";
export interface GuestWebDiscoveryOutcome { readonly schemaVersion:"guest-web-discovery-outcome/v1";readonly operationId:string;readonly operationState:GuestOperationState;readonly status:GuestSearchStatus;readonly normalizedQuery?:string;readonly queryNormalizationVersion?:string;readonly runtimeStatus?:"LIVE_WEB_DISCOVERY"|"OFFLINE_FIXTURE"|"UNAVAILABLE";readonly adapterId?:string;readonly adapterVersion?:string;readonly startedAt?:string;readonly completedAt?:string;readonly expiresAt?:string;readonly resultCount:number;readonly results:readonly WebDiscoverySearchResult[];readonly providerAttribution?:string;readonly restrictions?:readonly string[];readonly warnings?:readonly string[];readonly error?:WebDiscoveryStableError|null;readonly researcherCharge:"0.00";readonly billingTriggered:false;readonly providerCreditsConsumed:0|1;readonly providerCreditUsage:"ZERO"|"ESTIMATED"|"ACTUAL"|"UNKNOWN";readonly effects:Readonly<Record<"candidateEvidence"|"researchInbox"|"candidateKnowledge"|"canon"|"graph"|"manifold"|"resolve"|"rex","NONE">> }
export class GuestWebDiscoveryError extends Error { readonly status:number;readonly code:string;constructor(status:number,code:string,message:string){super(message);this.status=status;this.code=code} }
type Transport=(input:string,init:RequestInit)=>Promise<Response>;
const csrf=(source:()=>string):string=>{const pair=source().split(";").map(value=>value.trim()).find(value=>value.startsWith("isees_csrf="));if(!pair)throw new GuestWebDiscoveryError(403,"CSRF_TOKEN_MISSING","The secure Guest session could not be verified.");try{const value=decodeURIComponent(pair.slice("isees_csrf=".length));if(!value)throw 0;return value}catch{throw new GuestWebDiscoveryError(403,"CSRF_TOKEN_INVALID","The secure Guest session could not be verified.")}};
const parse=async(response:Response):Promise<any>=>{try{return await response.json()}catch{throw new GuestWebDiscoveryError(response.status,"MALFORMED_RESPONSE","Guest Web Discovery returned an invalid response.")}};
const fail=(response:Response,value:any):never=>{const detail=value?.error;throw new GuestWebDiscoveryError(response.status,typeof detail?.code==="string"?detail.code:"GUEST_SEARCH_FAILED",typeof detail?.message==="string"?detail.message:"Guest Basic Search could not be completed.")};
export function createGuestWebDiscoveryApi(options:{readonly transport?:Transport;readonly cookieSource?:()=>string;readonly baseUrl?:string}={}){const transport=options.transport??fetch,cookies=options.cookieSource??(()=>typeof document==="undefined"?"":document.cookie),base=(options.baseUrl??resolveApiBaseUrl()).replace(/\/$/,"");const call=async(path:string,init:RequestInit)=>{const response=await transport(`${base}${path}`,{...init,credentials:"include",redirect:"error"}),value=await parse(response);return{response,value}};return Object.freeze({ensureSession:async(signal?:AbortSignal)=>{const restored=await call("/api/v1/auth/guest-session",{method:"GET",signal});if(restored.response.ok)return restored.value;if(restored.response.status!==401)fail(restored.response,restored.value);const created=await call("/api/v1/auth/guest-sessions",{method:"POST",signal});if(!created.response.ok)fail(created.response,created.value);return created.value},search:async(query:string,operationId:string,idempotencyKey:string,signal?:AbortSignal):Promise<GuestWebDiscoveryOutcome>=>{const outcome=await call("/api/v1/guest/web-discovery/searches",{method:"POST",headers:{"Content-Type":"application/json","X-ISEES-CSRF":csrf(cookies)},body:JSON.stringify({schemaVersion:"guest-web-discovery-search/v1",operationId,query,resultLimit:10,idempotencyKey,executionPolicy:{metadataOnly:true,aiAssistance:"NONE",rexExecution:"NONE",authorizedSpend:0}}),signal});if(!outcome.response.ok&&outcome.response.status!==202)fail(outcome.response,outcome.value);return outcome.value as GuestWebDiscoveryOutcome}})}
export const guestWebDiscoveryApi=createGuestWebDiscoveryApi();
