import type { FormEvent } from "react";
import { useEffect, useState } from "react";
import type { CandidateEvidenceApiScope } from "./CandidateEvidenceApi";
import { useWebDiscoveryWorkspaceController } from "./WebDiscoveryWorkspaceController";
import type { WebDiscoveryRevisionBinding } from "./WebDiscoveryWorkspaceController";
import { useGuestWebDiscoveryWorkspaceController } from "./GuestWebDiscoveryWorkspaceController";
import { workspaceRuntime } from "../../workspace/runtime/WorkspaceRuntime";

interface Props { readonly authenticated: boolean; readonly scope?: CandidateEvidenceApiScope; readonly binding?: WebDiscoveryRevisionBinding; readonly guestContextKey?: string; readonly guestInvestigationId?: string; readonly guestProposedBy?: string; readonly guestTargets?: readonly { readonly id: string; readonly label: string; readonly type: string }[]; readonly guestActiveLayerIds?: readonly string[]; readonly onCandidateCaptured: (candidateId: string) => Promise<void> }
const metadata = (value: Readonly<Record<string, string | undefined>>): string[] => Object.entries(value).filter((entry): entry is [string, string] => Boolean(entry[1])).map(([key, item]) => `${key}: ${item}`);
const runtimePresentation = (response: ReturnType<typeof useWebDiscoveryWorkspaceController>["response"]): string => {
  if (!response) return "Server-managed runtime";
  if (response.runtimeStatus === "OFFLINE_FIXTURE") return "Explicit offline fixture · no live web access";
  if (response.runtimeStatus === "UNAVAILABLE") return "Web Discovery unavailable · server configuration disabled or invalid";
  if (response.status === "UNAVAILABLE" || response.status === "RATE_LIMITED" || response.status === "FAILED") return "Live Tavily · bounded provider failure";
  return "Live Tavily Web Discovery";
};

export default function WebDiscoveryWorkspace({ authenticated, scope, binding, guestContextKey = "guest-workspace", guestInvestigationId = "", guestProposedBy = "Guest researcher", guestTargets = [], guestActiveLayerIds = [], onCandidateCaptured }: Props) {
  const discovery = useWebDiscoveryWorkspaceController(scope, binding, onCandidateCaptured);
  const guest = useGuestWebDiscoveryWorkspaceController(!authenticated, guestContextKey, guestInvestigationId, guestProposedBy, guestTargets, guestActiveLayerIds);
  const [targetId, setTargetId] = useState("");
  const [relationship, setRelationship] = useState<"REFERENCES" | "ASSOCIATED_WITH" | "SUPPORTS" | "CONTRADICTS">("REFERENCES");
  const active = authenticated ? discovery : guest;
  useEffect(() => {
    if (authenticated || !guest.preview) return;
    const ownedOverlay = guest.preview;
    workspaceRuntime.setGuestDiscoveryOverlay(ownedOverlay);
    return () => workspaceRuntime.clearGuestDiscoveryOverlay(ownedOverlay);
  }, [authenticated, guest.preview]);
  function submit(event: FormEvent) { event.preventDefault(); void active.search(); }
  const available = authenticated ? scope !== undefined && binding !== undefined : true;
  return <section className="web-discovery" aria-labelledby="web-discovery-title">
    <header className="web-discovery__header"><div><p className="evidence-eyebrow">{authenticated ? "SEARCH · REVIEW · CAPTURE" : "SEARCH · INSPECT · DISPOSABLE"}</p><h2 id="web-discovery-title">Web Discovery</h2></div><span className="web-discovery__runtime">{runtimePresentation(discovery.response)}</span></header>
    <p className="web-discovery__boundary">{authenticated ? "Search results are discovery references—not evidence. Capture only the results you want reviewed as Candidate Evidence." : "Guests can search and inspect disposable metadata leads but cannot capture Candidate Evidence."}</p>
    <p className="web-discovery__provider">The Web Discovery provider is selected and authenticated by the server. Browser commands contain no provider choice or credential.</p>
    <form className="web-discovery__search" onSubmit={submit}><label htmlFor="web-discovery-query">Web Discovery query</label><div><input id="web-discovery-query" type="search" value={active.query} onChange={(event) => active.setQuery(event.target.value)} disabled={!available || active.searching} placeholder="Enter a deliberate research query"/><button type="submit" disabled={!available || active.searching || (authenticated ? !discovery.query.trim() : !guest.query.trim())}>{active.searching ? "Searching…" : authenticated ? "Search Web" : "Run Guest Basic Search"}</button></div></form>
    <div className="web-discovery__state" aria-live="polite">{authenticated && !binding ? "Web Discovery unavailable while authoritative Investigation revisions are loading." : active.searching ? "Searching the server-authorized Web Discovery runtime…" : active.response ? `${active.response.resultCount} ephemeral discovery reference${active.response.resultCount === 1 ? "" : "s"}. No Candidate Evidence was created by search.` : authenticated ? "Ready for an explicit researcher-directed search." : "Guest Basic Search is available without an account. The server establishes or restores its secure Guest session before search."}</div>
    {active.error && <p className="evidence-api-error" role="alert">{active.error}</p>}
    {!authenticated && guest.response && <section className="web-discovery__review" aria-label="Ephemeral Guest Web Discovery results"><div className="web-discovery__review-heading"><div><span>GUEST · METADATA ONLY · DISPOSABLE</span><strong>{guest.response.providerAttribution ?? "Provider attribution unavailable"}</strong></div><p>Status: {guest.response.status}{guest.response.expiresAt ? ` · expires ${new Date(guest.response.expiresAt).toLocaleString()}` : ""}</p></div>{guest.response.status === "PENDING" && <div className="web-discovery__empty">This search is already in flight. No second provider request was started.</div>}{guest.response.operationState === "UNKNOWN" && <div className="web-discovery__empty">Provider outcome UNKNOWN. iSEES will not automatically retry potentially dispatched work.</div>}{guest.response.results.length === 0 && guest.response.status !== "PENDING" && guest.response.operationState !== "UNKNOWN" ? <div className="web-discovery__empty">No metadata-only discovery references were returned.</div> : <ol className="web-discovery__results">{guest.response.results.map(result => <li key={result.resultId}><span>Discovery reference {result.rank}</span><h3>{result.title}</h3><a href={result.providerReturnedUrl} target="_blank" rel="noopener noreferrer">{result.displayDomain} · {result.displayUrl}</a><p>{result.snippet}</p><dl><div><dt>Attribution</dt><dd>{result.attribution}</dd></div>{metadata(result.providerMetadata).map(item => <div key={item}><dt>Provider metadata</dt><dd>{item}</dd></div>)}</dl><button type="button" onClick={() => guest.requestAddLead(result)} disabled={guest.leads.some(lead => lead.result.resultId === result.resultId)}>{guest.leads.some(lead => lead.result.resultId === result.resultId) ? "Added to Guest Research Inbox" : "Select for Guest Research Inbox"}</button></li>)}</ol>}{guest.response.results.length > 0 && <aside className="web-discovery__warning"><strong>Save this investigation?</strong> Create or sign in to an account for future account-owned research. These Guest results will not be transferred, copied, or saved; leaving, expiry, reset, or sign-in discards them.</aside>}</section>}
    {!authenticated && guest.leads.length > 0 && <section className="web-discovery__guest-inbox" aria-label="Guest Research Inbox"><div className="web-discovery__review-heading"><div><span>GUEST RESEARCH INBOX · DISPOSABLE</span><strong>{guest.leads.length} metadata lead{guest.leads.length === 1 ? "" : "s"}</strong></div><button type="button" onClick={guest.reset}>Reset Guest discovery</button></div><p className="web-discovery__warning">Session-local preview input only. No page was acquired or inspected; no Candidate Evidence, canonical node, edge, fact, or account-owned record exists.</p>{guest.leads.map(lead => <article key={lead.leadId} className="web-discovery__guest-lead"><h3>{lead.result.title}</h3><a href={lead.result.providerReturnedUrl} target="_blank" rel="noopener noreferrer">{lead.result.providerReturnedUrl}</a><p>{lead.result.snippet}</p><dl><div><dt>Query</dt><dd>{lead.query}</dd></div><div><dt>Provider</dt><dd>{lead.provider} · {lead.result.attribution}</dd></div><div><dt>Status</dt><dd>METADATA ONLY · PAGE NOT ACQUIRED OR INSPECTED</dd></div></dl><div className="web-discovery__connection"><label>Governed event/node<select aria-label={`Governed event or node for ${lead.result.title}`} value={guest.connection?.leadId === lead.leadId ? guest.connection.targetId : targetId} onChange={event => setTargetId(event.target.value)}><option value="">Choose explicitly…</option>{guestTargets.map(target => <option value={target.id} key={target.id}>{target.label} · {target.type}</option>)}</select></label><label>Proposed connection<select aria-label={`Proposed connection for ${lead.result.title}`} value={relationship} onChange={event => setRelationship(event.target.value as typeof relationship)}><option value="REFERENCES">REFERENCES</option><option value="ASSOCIATED_WITH">ASSOCIATED WITH</option><option value="SUPPORTS">SUPPORTS</option><option value="CONTRADICTS">CONTRADICTS</option></select></label><button type="button" disabled={!targetId} onClick={() => guest.proposeConnection({ leadId: lead.leadId, targetId, relationship })}>Propose provisional connection</button><button type="button" onClick={() => guest.removeLead(lead.leadId)}>Remove disposable lead</button></div></article>)}</section>}
    {!authenticated && guest.preview && <section className="web-discovery__preview" aria-label="Guest event-space provisional preview"><p className="evidence-eyebrow">PROVISIONAL · GUEST EVENT-SPACE PREVIEW</p><h3>{guest.preview.relationship} → {guest.preview.target.label}</h3><p>Trace: lead <code>{guest.preview.leadId}</code> · chosen node <code>{guest.preview.target.id}</code> · projection <code>{guest.preview.projectionId}</code></p><div><strong>Manifold projection</strong><span>+1 disposable metadata-reference node · +1 provisional connection · governed mutation: NONE</span></div><div><strong>Layers visibility</strong><span>{guest.preview.layers.length ? guest.preview.layers.map(layer => `${layer.id}: ${layer.effect} · ${layer.evaluation}`).join(" · ") : "No active governed Layers; provisional input is unavailable."}</span></div><p className="web-discovery__warning">This deterministic projection is a disposable overlay only. It is excluded from operational Manifold serialization and Layers evaluation.</p></section>}
    {!authenticated && guest.pendingResult && <div className="web-discovery__dialog-backdrop"><section className="web-discovery__dialog" role="dialog" aria-modal="true" aria-labelledby="guest-lead-title"><p className="evidence-eyebrow">GUEST · EXPLICIT CONFIRMATION</p><h2 id="guest-lead-title">Add “{guest.pendingResult.title}” to the disposable Guest Research Inbox?</h2><p>This adds one metadata reference to temporary preview state only. The linked page will not be acquired or inspected, and Candidate Evidence and governed graph state remain unchanged.</p><div className="web-discovery__dialog-actions"><button type="button" onClick={guest.cancelAddLead}>Cancel</button><button type="button" onClick={guest.confirmAddLead}>Confirm disposable lead</button></div></section></div>}
    {authenticated && discovery.response && <section className="web-discovery__review" aria-label="Ephemeral Web Discovery results"><div className="web-discovery__review-heading"><div><span>REVIEW · EPHEMERAL</span><strong>{discovery.response.providerAttribution}</strong></div><p>Status: {discovery.response.status} · expires {new Date(discovery.response.expiresAt).toLocaleString()}</p></div>
      {discovery.response.restrictions.length > 0 && <p className="web-discovery__restrictions">Session restrictions: {discovery.response.restrictions.join(" · ")}</p>}{discovery.response.warnings.map((warning) => <p className="web-discovery__warning" key={warning}>{warning}</p>)}
      {discovery.response.results.length === 0 ? <div className="web-discovery__empty">No discovery references were returned. Nothing was captured.</div> : <ol className="web-discovery__results">{discovery.response.results.map((result) => { const captured = discovery.captured[result.resultId]; const pending = discovery.capturePending === result.resultId; const addedToInbox = captured?.researchInboxEffect !== undefined && captured.researchInboxEffect !== "NONE"; return <li key={result.resultId} className={captured ? "is-captured" : undefined}><div className="web-discovery__result-status"><span>Discovery reference {result.rank}</span>{captured && <strong role="status">{captured.disposition === "CREATED" ? "Created" : "Already captured / replayed"} · Candidate {captured.candidateId} · {addedToInbox ? "Added to Research Inbox" : "Kept as Candidate Evidence"}</strong>}</div><h3>{result.title}</h3><a href={result.providerReturnedUrl} target="_blank" rel="noopener noreferrer">{result.displayDomain} · {result.displayUrl}<span className="sr-only"> (opens in a new tab)</span></a><p>{result.snippet}</p><dl><div><dt>Attribution</dt><dd>{result.attribution}</dd></div>{result.mediaType && <div><dt>Media type</dt><dd>{result.mediaType}</dd></div>}{metadata(result.providerMetadata).map((item) => <div key={item}><dt>Provider metadata</dt><dd>{item}</dd></div>)}<div><dt>Retention / restrictions</dt><dd>{result.retentionRestrictions.length ? result.retentionRestrictions.join(" · ") : "None reported"}</dd></div></dl><button type="button" onClick={() => discovery.requestCapture(result)} disabled={Boolean(discovery.capturePending) || Boolean(captured)}>{pending ? discovery.addToResearchInbox ? "Adding to Research Inbox…" : "Keeping as Candidate Evidence…" : captured ? addedToInbox ? "Added to Research Inbox" : "Kept as Candidate Evidence" : "Add to Research Inbox"}</button></li>; })}</ol>}
    </section>}
    {discovery.confirmation && <div className="web-discovery__dialog-backdrop"><section className="web-discovery__dialog" role="dialog" aria-modal="true" aria-labelledby="web-capture-title" aria-describedby="web-capture-description"><p className="evidence-eyebrow">CAPTURE · EXPLICIT CONFIRMATION</p><h2 id="web-capture-title">Add “{discovery.confirmation.result.title}” to Research Inbox?</h2><p id="web-capture-description">iSEES will preserve this discovery result as review-only Candidate Evidence and add it to your Research Inbox. It will not publish or alter the Manifold.</p><fieldset className="web-discovery__capture-choices" disabled={Boolean(discovery.capturePending)}><legend className="sr-only">Choose capture destination</legend><label><input type="radio" name="web-capture-destination" checked={discovery.addToResearchInbox} onChange={() => discovery.setAddToResearchInbox(true)}/><span><strong>Add to Research Inbox</strong><small>Creates Candidate Evidence and adds its reference to the Inbox.</small></span></label><label><input type="radio" name="web-capture-destination" checked={!discovery.addToResearchInbox} onChange={() => discovery.setAddToResearchInbox(false)}/><span><strong>Keep as Candidate Evidence only</strong><small>Captures it for review without adding it to the Inbox.</small></span></label></fieldset><div className="web-discovery__note"><label htmlFor="web-capture-note">Researcher note (optional)</label><textarea id="web-capture-note" maxLength={20000} value={discovery.researcherNote} onChange={(event) => discovery.setResearcherNote(event.target.value)} disabled={Boolean(discovery.capturePending)}/></div><div className="web-discovery__dialog-actions"><button type="button" onClick={discovery.cancelCapture} disabled={Boolean(discovery.capturePending)}>Cancel</button><button type="button" onClick={() => void discovery.confirmCapture()} disabled={Boolean(discovery.capturePending)}>{discovery.capturePending ? discovery.addToResearchInbox ? "Adding to Research Inbox…" : "Keeping as Candidate Evidence…" : discovery.addToResearchInbox ? "Add to Research Inbox" : "Keep as Candidate Evidence"}</button></div></section></div>}
  </section>;
}
