import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { beginCandidateRequest, partitionCandidateEvidence, permittedReviewActions, reconcileCandidateTransition, reviewActionLabel, settleCandidateRequest } from "./src/evidence/candidates/CandidateEvidenceRuntime.ts";
import type { ApiCandidateRecord } from "./src/evidence/candidates/CandidateEvidenceApi.ts";

const record = (origin: ApiCandidateRecord["origin"], lifecycleState: ApiCandidateRecord["lifecycleState"], id: string): ApiCandidateRecord => ({ candidateId: id, investigationId: "investigation-a", revision: 0, origin, originIdentity: `origin-${id}`, lineage: {}, source: {}, lifecycleState, acquisitionState: "NOT_REQUESTED", archiveState: "NOT_REQUESTED", availability: "UNKNOWN", provenanceEvents: [], createdAt: "now", updatedAt: "now" });
const records = [record("CURATED_REPOSITORY", "REFERENCED", "curated"), record("SUBMISSION", "SUBMITTED", "submission"), record("DISCOVERY", "DISCOVERED", "discovery")];
const lanes = partitionCandidateEvidence(records);
assert.deepEqual(lanes.candidate.map((item) => item.candidateId), ["submission", "discovery"]);
assert.deepEqual(lanes.curated.map((item) => item.candidateId), ["curated"]);
assert.deepEqual(permittedReviewActions(records[1]!), ["REFERENCED"]);
assert.deepEqual(permittedReviewActions({ ...records[1]!, lifecycleState: "IN_REVIEW" }), ["DEFERRED", "EXCLUDED"]);
assert.deepEqual(permittedReviewActions({ ...records[1]!, lifecycleState: "DEFERRED" }), ["IN_REVIEW"]);
assert.equal(reviewActionLabel(records[1]!, "REFERENCED"), "Reference");
assert.equal(reviewActionLabel({ ...records[1]!, lifecycleState: "REFERENCED" }, "IN_REVIEW"), "Begin Review");
assert.equal(reviewActionLabel({ ...records[1]!, lifecycleState: "IN_REVIEW" }, "DEFERRED"), "Defer");
assert.equal(reviewActionLabel({ ...records[1]!, lifecycleState: "IN_REVIEW" }, "EXCLUDED"), "Exclude");
assert.equal(reviewActionLabel({ ...records[1]!, lifecycleState: "DEFERRED" }, "IN_REVIEW"), "Reopen Review");
const a = { principalId: "principal-a", investigationId: "investigation-a" };
const loading = { ...beginCandidateRequest(a), selectedCandidateId: "stale" };
assert.equal(beginCandidateRequest({ ...a, investigationId: "investigation-b" }).selectedCandidateId, undefined);
assert.equal(settleCandidateRequest(loading, { ...a, investigationId: "investigation-b" }, "READY", records), loading);
assert.equal(settleCandidateRequest(loading, { ...a, principalId: "principal-b" }, "READY", records), loading);
assert.equal(settleCandidateRequest(loading, a, "UNAVAILABLE").status, "UNAVAILABLE");
assert.equal(settleCandidateRequest(loading, a, "READY", []).records.length, 0);
const selected = { ...settleCandidateRequest(beginCandidateRequest(a), a, "READY", records), selectedCandidateId: "submission", error: "stale transition error" };
const updated = { ...records[1]!, revision: 1, lifecycleState: "REFERENCED" as const, updatedAt: "later" };
const reconciled = reconcileCandidateTransition(selected, a, updated);
assert.equal(reconciled.selectedCandidateId, "submission");
assert.equal(reconciled.records.find((item) => item.candidateId === "submission"), updated);
assert.equal(reconciled.error, undefined);
const refreshed = settleCandidateRequest(reconciled, a, "READY", [records[0]!, updated, records[2]!]);
assert.equal(refreshed.selectedCandidateId, "submission");
const staleRefresh = settleCandidateRequest(reconciled, a, "READY", records);
assert.equal(staleRefresh.records.find((item) => item.candidateId === "submission"), updated);
assert.equal(reconcileCandidateTransition(selected, { ...a, investigationId: "investigation-b" }, updated), selected);
const api = readFileSync("src/evidence/candidates/CandidateEvidenceApi.ts", "utf8");
const workspace = readFileSync("src/workspace/surfaces/EvidenceWorkspace.tsx", "utf8");
const projection = readFileSync("src/evidence/projection/EvidenceWorkspaceProjection.ts", "utf8");
assert(api.includes('"X-ISEES-Principal-Id": scope.principalId'));
assert(api.includes("encodeURIComponent(scope.investigationId)"));
assert(workspace.includes("API unavailable — count unknown, not zero"));
assert(workspace.includes("No ADMITTED or canonical-materialization controls"));
assert(workspace.indexOf("&& !reason)") < workspace.indexOf("candidateEvidenceApi.transition"));
assert.equal(workspace.match(/reviewDecision:/g)?.length, 1);
assert(workspace.includes("setCommandError(undefined); setCandidateRequest((current) => reconcileCandidateTransition"));
assert(projection.includes("investigation.workspace.artifacts"));
for (const mutation of ["addArtifact", "removeArtifact", "createEdge", "KnowledgeObjectRuntime"]) assert(!api.includes(mutation) && !workspace.includes(mutation));
console.log("PASS VerifyCandidateEvidenceRuntime — scoped three-lane runtime, review graph, offline semantics, and canonical isolation verified");
